#!/usr/bin/env perl
use 5.012;
use warnings;
use utf8::all;

# Struktur taget fra feminazi-pakken
#

while (my $text = <>) {
    $text =~ s/packet/pakke/ig;
    $text =~ s/packets/pakker/ig;
    print $text;
}
