#!/bin/sh

if [ "$EGGS_USER" = "$CONCIEGGS_NAME" ]; then
    exit
fi

. $CONCIEGGS_DIR/concieggs.conf

set -f

awk_getcmd='{ print tolower($1); }'
awk_getargs='{ print substr($0, index($0, $1)+length($1)+1, length($0)) }'

rawcmd=$(echo "$EGGS_BODY"|gawk "$awk_getcmd")
if [ "$rawcmd" ]; then
    args="$(echo "$EGGS_BODY"|gawk "$awk_getargs")"
    runcmd -a "$rawcmd" $args
    if [ "$rawcmd" = "maxima" ]; then
        echoToServer ":m $CONCIEGGS_DEFAULT_CHANNEL $EGGS_USER skriver måske farlige ting til mig privat!"
    fi
fi
