#!/bin/sh
#
# Try to pre-compile all compilable programs.  Report any failures.

set -e

failed=$(mktemp -d)

grep -E '^#!/usr/bin/env compile' --files-with-matches -R "$(dirname "$0")" | while read f; do
    f=$(basename $f)
    ./fakeconcieggs compile --do-not-run $f 2>$failed/$f || {
        echo $f >> $failed/log
    }
done

if [ -f $failed/log ]; then
    for f in $(cat $failed/log); do
        echo "Error for '$f'":
        echo ----------------------------------------
        cat $failed/$f
        echo ----------------------------------------
        echo
    done
    failure=1
else
    failure=0
fi

rm -rf $failed

exit $failure
