#!/bin/sh
pidfile="$(mktemp)"

trap 'kill $(cat "$pidfile") 2> /dev/null; rm $pidfile' INT QUIT TERM EXIT

/bin/sh -c -i "$(printf '/bin/sh '$(dirname $PWD)'/concieggsd &\necho $! > '"$pidfile"'\nfg')"
