#!/bin/sh

dir=$(dirname $0)
cfg=$dir/concieggs.conf
. $cfg

# Connect to Bitlbee.
ii -s localhost -i $irc_dir -n $irc_username -f $irc_realname &

# Wait for connection to stabilize...
sleep 2

# Enter the directory containing the Bitlbee stuff.
cd 'concieggs_irc/localhost/&bitlbee'

# Auth.
echo identify $irc_password > in

sleep 2

# Join channel.
echo join_chat 0 eggs@conference.jabber.dk > in
echo "$irc_username connected!"
