#!/bin/sh
#
# Original character DO NOT STEAL

set -e # Die on error
set -f # No globbing

setTrap() {
    # Kill all children when we quit, and cleanup after eggsmld.
    trap 'eggsmld_cleanup; exit' INT QUIT TERM
    trap 'eggsmld_cleanup; cleanup' EXIT
}

setTrap

eggsmld_cleanup() {
    # Try to remove its socket.
    rm -f $EGGS_DAEMON_SOCKET
}

cleanup() {
    kill 0
}

# Try to figure out where this executable resides.
dir=$(readlink -f $(dirname $0))

# Load the configuration file.
cfg=$dir/concieggs.conf
. $cfg

# Export some bot information.
export CONCIEGGS_DIR=$dir
export CONCIEGGS_IRC_DIR=$irc_dir
export CONCIEGGS_DB_DIR=$dir/db
export CONCIEGGS_LIB_DIR=$dir/eggspi
export CONCIEGGS_DEFAULT_NAME=$irc_username
export CONCIEGGS_DEFAULT_CHANNEL=$irc_channel
export CONCIEGGS_ERROR_CHANNEL=$irc_error_channel
export CONCIEGGS_HOME="$HOME"

# Export some lunch information.
export EGGS_DIR=$dir/..
export EGGS_LIB_DIR=$EGGS_DIR/eggslib

# Export where to find eggsmld (we'll start it real soon now).
export EGGS_DAEMON_SOCKET=$CONCIEGGS_DIR/eggsmld.socket

# Import the concieggs library.
export PATH=$CONCIEGGS_LIB_DIR:$PATH

# We also use Python!
export PYTHONPATH=$CONCIEGGS_LIB_DIR:$PYTHONPATH

# Hack for UTF-8 handling in GHC on OpenBSD
export HS_ENCODING=UTF-8

say "Interacting with concieggs_irc in $irc_dir."

# Let all eggsml users touch our stuff.
umask 002

ircloop () {
    while true; do
        # Connect to IRC.
        sic -h irc.freenode.net -n "$irc_username" || true
        say "IRC crashed - reconnecting in a few seconds." >&2
        # Sleep a few seconds before trying again.
        sleep 4
    done
}

eventprocessor () {
    while true; do
        # Run commands from lines.
        gawk -f $dir/irc_event_reader.awk || true
        # We might terminate gawk if we wish to restart the eventprocessor.
        say "gawk was terminated - reconnecting in a second." >&2
        # Sleep a second before trying again.
        sleep 1
    done
}

throttle() {
    gawk -f $dir/throttle.awk
}

outfile=$irc_dir/out

# Make sure the outfile exists.
touch "$outfile" || True

# Start eggsmld.
$EGGS_DIR/eggslib/eggsmld.py $EGGS_DIR/slashdotfrokost $EGGS_DAEMON_SOCKET &

# Tie the two loops together.
tail -f -n 0 "$outfile" | \
    eventprocessor | \
    tee /dev/stderr | \
    throttle | \
    ircloop >> "$outfile"
