#!/bin/sh

trap 'exit' INT QUIT TERM
trap 'cleanup' EXIT

cleanup() {
    jobsfile="$(mktemp)"
    jobs -p > "$jobsfile" #dash be silly
    pids="$(cat $jobsfile)"
    rm "$jobsfile"

    #echo "Jeg er $$. Dette er mine børn: $pids"
    [ -n "$pids" ] && kill $pids
    kill 0
}

dir=$(dirname $0)
cfg=$dir/concieggs.conf
. $cfg

irc () {
# Connect to Bitlbee.
    ii -s irc.freenode.net -i $irc_dir -n $irc_username -f $irc_realname &

# Wait for connection to stabilize...
    sleep 2

# Enter the directory containing the IRC stuff.
    cd $irc_dir'/irc.freenode.net'

    sleep 2

# Now join!
    echo "/j $irc_channel" > in
    echo "/j $irc_error_channel" > in
    echo "$irc_username connected!"

# Wait for ii to die.
    wait $!
}

while true; do irc; done
