#!/bin/sh
#
# Original character DO NOT STEAL

set -e # Die on error
set -f # No globbing

setTrap() {
    # Kill all children when we quit.
    trap 'exit' INT QUIT TERM
    trap 'cleanup' EXIT
}

setTrap

cleanup() {
    kill 0
}

# Try to figure out where this executable resides.
dir=$(readlink -f $(dirname $0))

# Load the configuration file.
cfg=$dir/concieggs.conf
. $cfg

# Export some bot information.
export CONCIEGGS_DIR=$dir
export CONCIEGGS_IRC_DIR=$irc_dir
export CONCIEGGS_DB_DIR=$dir/db
export CONCIEGGS_LIB_DIR=$dir/eggspi
export CONCIEGGS_NAME=$irc_username
export CONCIEGGS_DEFAULT_CHANNEL=$irc_channel
export CONCIEGGS_ERROR_CHANNEL=$irc_error_channel

# Export some lunch information.
export EGGS_DIR=$dir/..
export EGGS_LIB_DIR=$EGGS_DIR/eggslib

# Export where to find eggsmld (we'll start it real soon now).
export EGGS_DAEMON_SOCKET=$CONCIEGGS_DIR/eggsmld.socket

# Set our locale.
export LC_ALL=da_DK.UTF-8

# Some people are unethical programmers and like Python, and
# apparently they think this is necessary.
(echo $PYTHONPATH | grep -qv $CONCIEGGS_LIB_DIR) && export PYTHONPATH=$CONCIEGGS_LIB_DIR:$PYTHONPATH

echo "Interacting with concieggs_irc in $irc_dir."

# Let all eggsml users touch our stuff.
umask 002

# Import the concieggs library.
export PATH=$CONCIEGGS_LIB_DIR:$PATH

ircloop () {
    while true; do
        # Connect to IRC
        sic -h irc.freenode.net -n "$irc_username" || true
        echo "IRC crashed - reconnecting in a few seconds." >&2
        # Sleep a few seconds before trying again.
        sleep 4
    done
}

eventprocessor () {
    awk -f $dir/irc_event_reader.awk
}

filter_non_commands() {
    while read -r line; do
        (if echo "$line" | egrep -q '^:'; then
             echo "$line"
         else
             user="$(echo "$line" | sed -r 's/: .+//')"
             if (echo "$user" | grep -q ' '); then
                 user=''
             fi
             "$(dirname "$0")"/outfilter "$(basename "$PWD")" "$user" "$line"
         fi) || echo "$line"
    done
}

throttle() {
    awk '{print; fflush(); system("sleep 1")}'
}

outfile=$irc_dir/out

# Make sure the outfile exists.
touch "$outfile"

# The the two loops together.
tail -f -n 0 "$outfile" | \
    eventprocessor | \
    tee /dev/stderr | \
    filter_non_commands | \
    throttle | \
    ircloop >> "$outfile"
