#!/bin/sh

dir=$(dirname $0)
cfg=$dir/concieggs.conf
. $cfg

irc () {
# Connect to Bitlbee.
    ii -s irc.freenode.net -i $irc_dir -n $irc_username -f $irc_realname &

# Wait for connection to stabilize...
    sleep 2

# Enter the directory containing the IRC stuff.
    cd 'concieggs_irc/irc.freenode.net'

    sleep 2

# Now join!
    echo "/j $irc_channel" > in
    echo "$irc_username connected!"

# Wait for ii to die.
    wait $!
}

while true; do irc; done
