#!/bin/sh
#
# Simulate a concieggs environment.

cmd=$1

dir=$(readlink -f $(dirname $0))
cmddir=$dir/cmds/

. $dir/concieggs.conf

export CONCIEGGS_NAME=$irc_username
export CONCIEGGS_DIR=$dir
export CONCIEGGS_DB_DIR=$dir/db
export CONCIEGGS_LIB_DIR=$dir/eggspi
export CONCIEGGS_IRC_CHANNEL=$irc_channel
export CONCIEGGS_ERROR_CHANNEL=$irc_error_channel
export EGGS_DIR=$dir/..
export EGGS_LIB_DIR=$EGGS_DIR/eggslib
export LC_ALL=da_DK.UTF-8
export CONCIEGGS_DB_DIR=$CONCIEGGS_DIR/db
export EGGS_USER=${EGGS_USER:-$(whoami)}
export PATH=$CONCIEGGS_DIR/eggspi:$PATH
export PYTHONPATH=$CONCIEGGS_LIB_DIR:$PYTHONPATH
shift

$cmd "$@"
