#!/bin/sh
#
# Simulate a concieggs environment.

set -e

cmd=$1

if [ $(uname) = Darwin ]; then
    # Steve's sublimely elegant alternative to readlink.
    dir=$(dirname $0)
    dir=$( ( echo "$dir" | egrep -q 'ˆ/' ) && echo "$dir" || echo "$PWD/${dir#./}")
else
    dir=$(readlink -f $(dirname $0))
fi

. $dir/concieggs.conf

export CONCIEGGS_DEFAULT_NAME=$irc_username
export CONCIEGGS_NAME=${CONCIEGGS_NAME:-$CONCIEGGS_DEFAULT_NAME}
export CONCIEGGS_DIR=$dir
export CONCIEGGS_DB_DIR=$dir/db
export EGGS_DAEMON_SOCKET=$CONCIEGGS_DIR/eggsmld.socket
export CONCIEGGS_LIB_DIR=$dir/eggspi
export CONCIEGGS_DEFAULT_CHANNEL=$irc_channel
export CONCIEGGS_ERROR_CHANNEL=$irc_error_channel
export EGGS_DIR=$dir/..
export EGGS_LIB_DIR=$EGGS_DIR/eggslib
export LC_ALL=da_DK.UTF-8
export CONCIEGGS_DB_DIR=$CONCIEGGS_DIR/db
export EGGS_USER=${EGGS_USER:-$(whoami)}
export CONCIEGGS_IRC_DIR=$irc_dir
if [ $EGGS_USER = $CONCIEGGS_NAME ]; then
    export EGGS_USER=${CONCIEGGS_NAME}_helper
fi
export PATH=$CONCIEGGS_DIR/eggspi:$PATH
export PYTHONPATH=$CONCIEGGS_LIB_DIR:$PYTHONPATH
export PERL5LIB=$CONCIEGGS_LIB_DIR/perleggs:$PERL5LIB

if which emacs > /dev/null; then
    get_loadpath=$(mktemp)
    (echo "(princ (mapconcat 'identity load-path \":\"))"; echo "(kill-emacs 0)") > $get_loadpath
    export EMACSLOADPATH=$(emacs --quick --script $get_loadpath):$CONCIEGGS_LIB_DIR/emeggslisp
    rm $get_loadpath
fi

if [ ! "$CONCIEGGS_HOME" ]; then
    export CONCIEGGS_HOME="$HOME"
fi
shift
export EGGS_WHERE='#local_eggsml'
exec 3>&1
$cmd "$@"
