#!/bin/sh
#
# This script is run on all non-command output from the IRC bot.

set -e

channel=$1
destuser=$2 # empty if it's not a 'user: message' message.

translate_example() {
    # Example.
    translate da ja da
}

apply_db_filter() {
    read -r line
    cmd=''
    if [ $destuser ]; then
        cmd=$(dbRead outfilter_command_$destuser || echo -n '')
    fi
    if [ ! "$cmd" ]; then
        cmd=$(dbRead outfilter_command || echo -n '')
    fi
    if [ ! "$cmd" ]; then
        echo "$line"
        exit
    fi
    echo "$line" | $cmd
}

apply_db_filter

# translate_example

# cat
