#!/bin/sh
#
# This script is run on all non-command output from the IRC bot.

set -e

channel="$1"
destuser="$2" # empty if it's not a 'user: message' message.
line="$3"


translate_example() {
    echo "$line" | translate da ja da
}

apply_db_filter() {
    cmd=''
    if [ "$destuser" != '' ]; then
        cmd=$(echo -n $(dbRead outfilter_command_$destuser))
    elif [ "$channel" != '' ]; then
        cmd=$(echo -n $(dbRead outfilter_command_$channel))
    fi
    if [ '' = "$cmd" ]; then
        cmd=$(echo -n $(dbRead outfilter_command))
    fi
    if [ '' = "$cmd" ]; then
        echo "$line"
        exit
    fi
    echo "$line" | $cmd
}

apply_db_filter

# translate_example

# echo "$line"
