#!/bin/sh
#
# This script is run on all non-command output from the IRC bot.

set -e

translate_example() {
    # Example.
    translate da ja da
}

apply_db_filter() {
    # not done yet
    while read -r line; do
        cmd=$(dbRead outfilter_command) # command with args
        if [ "$cmd" ]; then
            echo "$line" | $cmd
        else
            echo "$line"
        fi
    done
}

#apply_db_filter

translate_example
