#!/usr/bin/env dash

set -f

eval "$(parseConcieggsCommand)"

if [ "$rawcmd" ]; then
    if [ "$rawcmd" == "fluen" ]; then
        runcmd "$rawcmd" $args
    else
        gtimeout 10s runcmd "$rawcmd" $args
fi
