#!/usr/bin/env dash

set -f

eval "$(parseConcieggsCommand)"

if [ "$rawcmd" ]; then
    if [ "$rawcmd" = fluen -o "$rawcmd" = duen -o "$rawcmd" = flaske ]; then
        runcmd "$rawcmd" $args
    else
        gtimeout 30s runcmd "$rawcmd" $args
    fi
fi
