#!/usr/bin/env dash

set -f

eval "$(parseConcieggsCommand)"

if [ "$rawcmd" ]; then
        gtimeout 300s runcmd "$rawcmd" $args  || (echo "Nu må i til at skrive noget ordentlig kode. En kommando bør ikke tage over fem minutter at afvikle!"; echo "Jeg døde næsten!!! Vil du mig livet?"; echo "Jeg stødte ind i et problem. I skal vist have jeres skolepenge tilbage."; echo "Min kode er lort. Elendige amatører! Måske skulle I finde noget andet at lave? Har I overvejet at blive skraldemænd?";) | randomLine
fi
