#!/bin/sh

shame() {
    annoyedBy "$EGGS_USER" 5 "hægtede til $1 (jeg har ikke en konto)"
}

if echo "$EGGS_BODY" | grep spotify.com -q; then
    NON_SPOTIFY_LINK="$(echo "$EGGS_BODY" | findSpotifyAlternative)"
    echo "Athas: Bare rolig! Du skal ikke føle dig udenfor. Du kan bruge følgende hægte i stedet: $NON_SPOTIFY_LINK"
fi
if echo "$EGGS_BODY" | grep www.linkedin.com -q; then
    shame LinkedIn
fi
