#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Lad Concieggs translitterere mellem traditionelle kinesiske tegn og
# utraditionelle kinesiske tegn, så vi ikke behøver at gøre det.

# Installer med `/usr/local/bin/python3.8 -m pip install opencc`
# og `pkg_add opencc`

import os
import opencc

mao_zedong = opencc.OpenCC('t2s.json')
chiang_kai_shek = opencc.OpenCC('s2t.json')

udgydelse = os.getenv('EGGS_BODY')

oversat = mao_zedong.convert(udgydelse)
if len(oversat) and oversat != udgydelse:
    print(f'Mao Zedong:  {oversat}')

oversat = chiang_kai_shek.convert(udgydelse)
if len(oversat) and oversat != udgydelse:
    print(f'Chiang Kai-shek:  {oversat}')
