#!/bin/sh

spor=`randomLine <<EOF
Ikke her i hvert fald!
/me snurrer nervøst med fødderne
/me kigger ned i gulvet
Skal vi ikke snakke om noget andet bots?
EOF`

t=$(echo "$EGGS_BODY" | grep -ciE "er der (mon )?en bot til ?stede\??")
if [ "$t" = "1" ]; then
  sleep 2
  echo "$spor"
fi
