#!/bin/sh

shuttingUp && exit
maybeGood .1 || exit

# Undlad at reagere på ting der er kommandoer, men som ikke gav noget uddata da
# 01runcmd kørte.
eval "$(parseConcieggsCommand)"
if [ "$rawcmd" ]; then
    exit
fi

if echo "$EGGS_BODY" | grep -qiE $CONCIEGGS_NAME; then
    if [ $(random 1 2) = 2 ]; then
        echo $(echo "$EGGS_BODY" | sed "s/$CONCIEGGS_NAME/$EGGS_USER/g")
    else
        randomLine <<EOF
Taler I om mig?
Ja, det er mig der er ${CONCIEGGS_NAME}!
Det er altså ikke særligt høfligt at tale om mig, men ikke at tale til mig.
Jeg er lige her.
EOF
    fi
fi
