#!/bin/sh

shuttingUp && exit
maybeGood .2 || exit

# Undlad at reagere på ting der er kommandoer, men som ikke gav noget uddata da
# 01runcmd kørte.
eval "$(parseConcieggsCommand)"
if [ "$rawcmd" ]; then
    exit
fi

if echo "$EGGS_BODY" | grep -qiE $CONCIEGGS_NAME; then
    if [ $(random 1 4) = 4 ]; then
        randomLine <<EOF
Taler I om mig?
Ja, det er mig der er ${CONCIEGGS_NAME}!
Det er altså ikke særligt høfligt at tale om mig, men ikke at tale til mig.
Jeg er lige her.
hejsa!
Når man taler om solen, så skinner jeg!
bøh ;-)
EOF
    else
        echo $(echo "$EGGS_BODY" | sed "s/$CONCIEGGS_NAME/$EGGS_USER/g")
    fi
fi
