#!/bin/sh

if [ "$EGGS_USER" = hej_fra_github ]; then
    if echo "$EGGS_BODY" | grep '^\[EggsML\]' | grep pushed | grep -v 'concieggs pushed' > /dev/null; then
        cd $EGGS_DIR
        git pull
        if [ $? == 0 ]; then
            echo 'Jeg har hentet de nyeste ændringer fra https://github.com/Athas/EggsML!' > '/home/concieggs/concieggs_irc/irc.freenode.net/#eggsml/in'
        else
            echo 'Noget gik galt da jeg lavede git pull.' > '/home/concieggs/concieggs_irc/irc.freenode.net/#eggsml/in'
        fi
    elif echo "$EGGS_BODY" | grep '^\[futhark\]' | egrep 'pushed|merged' > /dev/null; then
        # Concieggs - the HIPERFIT continuous integration server.
        ( cd /home/concieggs/futhark; tools/ci.sh .) >&2 &
    fi
fi
