#!/bin/sh

(shuttingUp || talkingToConcieggs) && exit

forpuledelort() {
    if [ $(uname) = "OpenBSD" ]; then
        iconv -f ISO-8859-1 -t UTF-8
    else
        cat
    fi
}

body="$(say "$EGGS_BODY" | makeDanish | forpuledelort)"

if [ "$body" != "$EGGS_BODY" ]; then
    prefix=`randomLine <<EOF
$EGGS_USER mener nok
/me foretrækker nu
$EGGS_USER, her på dansk
/me oversætter
Nejnej, på dansk
EOF`

    say "$prefix: $body"
fi
