#!/bin/sh

(shuttingUp || talkingToConcieggs) && exit

body="$(say "$EGGS_BODY" | makeDanish)"

if [ "$body" != "$EGGS_BODY" ]; then
    prefix=`randomLine <<EOF
$EGGS_USER mener nok
/me foretrækker nu
$EGGS_USER, her på dansk
/me oversætter
Nejnej, på dansk
EOF`

    say "$prefix: $body"
    annoyedBy "$EGGS_USER" 1
fi
