#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
import os
import re
import random

from eggsthon import *


os.system('maybeGood .5')

if os.system('shuttingUp') != 0:
    sys.exit()

user = os.getenv('EGGS_USER')
body = os.getenv('EGGS_BODY')

if user == 'hej_fra_github':
    sys.exit()

if body.startswith('concieggs:') or body.startswith('concieggs,'):
    sys.exit()

with open(CONCIEGGS_DB_DIR + '/ordbog-engelsk-dansk') as f:
    eng_dan = [map(eval, x.split()) for x in f.read().split('\n')]
with open(CONCIEGGS_DB_DIR + '/ordbog-engelsk-forkortelser') as f:
    eng_special = set(f.read().split('\n'))

def fix_casing(a, b):
    s = a.group(0)
    if s.isupper():
        return b.upper()
    elif s[0].isupper():
        return b[0].upper() + b[1:]
    else:
        return b

body1 = body
for a, b in eng_dan:
    if a in eng_special:
        a = '(?<!["\w])' + a + '(?!["\w])'
    else:
        a = '(?<!")' + a + '(?!")'
    body1 = re.sub(a, lambda a: fix_casing(a, b), body1, flags=re.I)

if body1 != body:
    x = random.choice([user + ' mener nok',
                       '/me foretrækker nu',
                       user + ', her på dansk',
                       '/me oversætter',
                       'Nejnej, på dansk'])
    print '%s: %s' % (x, body1)
