#!/usr/bin/env perl
use 5.012;
use warnings;

use utf8::all;
use Env qw/EGGS_USER CONCIEGGS_DB_DIR/;
use Encode qw/decode/;

my $EGGS_BODY = decode('utf-8', $ENV{EGGS_BODY});

system("notOnEggsChannel || shuttingUp");
exit if ($? >> 8) == 0;

exit if $EGGS_USER eq 'hej_fra_github';
exit if $EGGS_BODY =~ qr/^concieggs[,:]/;

my %daneng;
open(my $f, '<', "$CONCIEGGS_DB_DIR/ordbog-dansk-eggs");
while (my $line = <$f>) {
    my ($from, $to) = $line =~ qr/'([^']+)' '([^']+)'/;
    next unless $from;
    $daneng{$from} = $to;
}
close($f);

sub make_eggpun {
    my ($word) = @_;
    my $orig = $word;

    for my $from (keys %daneng) {
        $word =~ s/$from/$daneng{$from}/gi;
    }

    return $word eq $orig ? $orig : "\U$word\E";
}

my $body = $EGGS_BODY;
$body =~ s/(\S+)/make_eggpun($1)/ieg;

if ($body ne $EGGS_BODY) {
    my @prefix = (
        "$EGGS_USER: Du mener nok...",
        "$EGGS_USER: Mener du ikke...",
    );

    $body =~ s/[.!?:]*\s*$/!!!!/;

    print $prefix[rand @prefix] . " $body! HAHAHAHAHA!\n";
}
