#!/usr/bin/env perl
use 5.012;
use warnings;

use utf8::all;
use Env qw/EGGS_USER CONCIEGGS_DB_DIR/;
use Encode qw/decode/;

my $EGGS_BODY = decode('utf-8', $ENV{EGGS_BODY});

system("notOnEggsChannel || shuttingUp");
exit if ($? >> 8) == 0;

exit if $EGGS_USER eq 'hej_fra_github';
exit if $EGGS_BODY =~ qr/^concieggs[,:]/;

my %daneng;
open(my $f, '<', "$CONCIEGGS_DB_DIR/ordbog-dansk-eggs");
while (my $line = <$f>) {
    my ($from, $to) = $line =~ qr/'([^']+)' '([^']+)'/;
    next unless $from;
    $daneng{$from} = $to;
}
close($f);

sub match_casing {
    my ($a, $b) = @_;
    return $a if $a =~ qr/^".*"$/;
    return "\u$b" if $a =~ qr/^[[:upper:]]/;
    return $b;
}

my $body = $EGGS_BODY;
for my $from (keys %daneng) {
    $body =~ s/($from)/match_casing($1,$daneng{$from})/ieg;
}

if ($body ne $EGGS_BODY) {
    my @prefix = (
        "$EGGS_USER mener nok",
        "/me foretrækker nu",
        "/me er vittig",
        "Nejnej, $EGGS_USER, du mener",
    );

    print $prefix[rand @prefix] . ": $body\n";
}
