#!/usr/bin/env perl
use 5.026;
use strict;
use warnings;

use Env qw(EGGS_USER EGGS_BODY);
use EggsML::EggsPI list => [qw(lastmsgs)];

my ($who, $pattern, $replacement, $flags) =
  $EGGS_BODY =~ m!^(?:([^ ,:]): +)?s/([^/])*/([^/]*)(?:/([ig]+))?!
  or exit;

$who ||= $EGGS_USER;
my @lastmsgs = lastmsgs($who);

if (!@lastmsgs) {
    my $thou = $EGGS_USER eq $who ? 'du' : $EGGS_USER;
    say "$EGGS_USER: Men $thou har jo ikke sagt noget!"
    exit;
}

while (my $lastmsg = pop @lastmsgs) {
    if ($lastmsg =~ s/$pattern/$replacement/$flags) {
        say "Rettet: <$who> $lastmsg";
        last;
    }
}
