#!/bin/sh

set -f

if echo "$EGGS_BODY" | egrep '[^ :]*: ' > /dev/null; then
    who="$(echo "$EGGS_BODY" | cut -d ':' -f 1)"
    EGGS_BODY="$(echo "$EGGS_BODY" | cut -d ' ' -f 2-)"
else
    who="$EGGS_USER"
fi

if echo "$EGGS_BODY" | egrep -x '^ *s/[^/]*/[^/]*(/g?)? *' > /dev/null; then
    last=$(dbUserRead "$who" lastmsg)
    if echo "$EGGS_BODY" | egrep '/g?$' > /dev/null; then
        exp="$EGGS_BODY"
    else
        exp="$EGGS_BODY/"
    fi
    if [ "$last" ]; then
        exec > in
        echo "Rettet: <$who> $(echo "$last" | sed -r "$exp")"
    elif [ "$EGGS_USER" = "$who" ]; then
        echo "$EGGS_USER: Men du har jo ikke sagt noget!"
    else
        echo "$EGGS_USER: Men $who har jo ikke sagt noget!"
    fi
fi
