#!/bin/sh

set -f

. $CONCIEGGS_DIR/eggspi.lib

if echo "$EGGS_BODY" | egrep 's/[^/]*/[^/]*(/g?)?' > /dev/null; then
    last=$(dbUserRead "$EGGS_USER" lastmsg)
    if echo "$EGGS_BODY" | egrep '/$' > /dev/null; then
        exp="$EGGS_BODY"
    else
        exp="$EGGS_BODY/"
    fi
    if [ "$last" ]; then
        echo "Rettet: <$EGGS_USER> $(echo "$last" | sed "$exp")"
    else
        echo "$EGGS_USER: Men du har jo ikke sagt noget!"
    fi
fi