#!/usr/bin/env perl

use Encode qw/decode/;
my $EGGS_BODY = decode('utf-8', $ENV{EGGS_BODY});

if (my ($who, $from, $to) =
            $EGGS_BODY =~ qr{^(?:([^ :]+):)?\s*(?:tr|y)/([^/]+)/([^/]+)/?\s*$}) {
    eval "use utf8::all";
    my $EGGS_USER = $ENV{EGGS_USER};
    $who ||= $EGGS_USER;
    my $last = `dbUserRead "$who" lastmsg` || `dbRead "strangers/$who" lastmsg`;

    if ($last) {
        eval "\$last =~ tr/$from/$to/";
        print "Rettet: <$who> $last\n";
    } else {
        printf("$EGGS_USER: Men %s har jo ikke sagt noget!\n",
               (lc $who) eq (lc $EGGS_USER) ? "du" : $who);
    }
}
