#!/usr/bin/env perl

use Env qw(EGGS_USER);
use Encode qw/decode/;
use EggsML::EggsPI text => ['lastmsg'];

my $EGGS_BODY = decode('utf-8', $ENV{EGGS_BODY});

if (my ($who, $from, $to) =
            $EGGS_BODY =~ qr{^(?:([^ :]+):)?\s*(?:tr|y)/([^/]+)/([^/]+)/?\s*$}) {
    eval "use utf8::all";
    $who ||= $EGGS_USER;
    my $last = lastmsg($who);

    if ($last) {
        eval "\$last =~ tr/$from/$to/";
        print "Rettet: <$who> $last\n";
    } else {
        printf("$EGGS_USER: Men %s har jo ikke sagt noget!\n",
               (lc $who) eq (lc $EGGS_USER) ? "du" : $who);
    }
}
