#!/bin/sh

shuttingUp && exit
isTodayRoyal || exit
checkCooldown royal $((60*20)) || exit

event=$(royalsToday | randomLine)
randomLine <<EOF
Busserne flager!  Det er sikkert på grund af $event.
I dag er det $event.  Lad os alle flage.
Husk at flage for $event!
Hurra, $event!
EOF
