#!/bin/sh
#
# Grin højlydt.

(notOnEggsChannel || shuttingUp) && exit

maybeGood .4 || exit

ha=$(for i in $(seq 1 $(random 4 20)); do
    echo -n HA
    if [ $(random 0 5) = 0 ]; then
        echo -n HR
    fi
    done)

foranSjov=$(randomLine <<EOF
VILDT
ULTRA
ROFLENDE
MEGA
LOLLENDE 
EOF
)
    
sjov="$foranSjov $(randomLine <<EOF
GRINERN
SJOVT
MORSOMT
LOLZ
ROFLCOPTER
EOF
)"

new=$(echo "$EGGS_BODY" | sed -r -e "s/(h[aøe](h[aøe])+|[Hh]eh)/$ha/g" -e "s/(sjovt?|grinern?|morsomt?|skægt?)/$sjov/g")

if [ "$new" != "$EGGS_BODY" ]; then
    echo "$new"
    pleasedBy "$EGGS_USER" 5
fi
