#!/bin/sh
#
# Grin højlydt.

(notOnEggsChannel || shuttingUp) && exit

maybeGood .4 || exit

ha=$(for i in $(seq 1 $(random 4 20)); do
    echo -n HA
    if [ $(random 0 5) = 0 ]; then
        echo -n HR
    fi
    done)

foranSjov=$(randomElement <<EOF
VILDT
ULTRA
ROFLENDE
MEGA
LOLLENDE 
EOF
)
    
sjov="$foranSjov $(randomElement <<EOF
GRINERN
SJOVT
MORSOMT
LOLZ
ROFLCOPTER
EOF
)"

new=$(echo "$EGGS_BODY" | sed -r -e "s/(ha){2,}/$ha/i" -e "s/(sjovt?|grinern?|morsomt?|skægt?)/$sjov/i")

if [ "$new" != "$EGGS_BODY" ]; then
    echo "$new"
fi
