#!/usr/bin/env php-7.0
<?php

$user = getenv('EGGS_USER');
$body = getenv('EGGS_BODY');

$esc_user = escapeshellarg($user);

function whether($cmd) {
    exec($cmd, $output, $exit);
    return !$exit;
}

if (strlen($user) > 0 && stripos($body, "ACTION kysser concieggs") === 1) {

    if (whether("isInBadStanding $esc_user"))) {
        $insults = [
            "Glem det, fister!",
            "Et kys går to veje, og dét der gik ikke din vej!",
            "Bedre held næste gang.",
            "Som om.",
        ];

        printf("%s: %s", $user, $insults[mt_rand(0, count($insults) - 1)]);
        exit(0);
    }

    shell_exec("echo $esc_user | dbWrite kaereste");

    if (whether("shuttingUp")) { exit(0); }

    echo "Tihi! Så er vi vel kærester, $user!";
}
