#!/bin/sh
#
# Vær på tværs.

(notOnEggsChannel || shuttingUp) && exit

maybeGood .4 || exit

new=$(echo "$EGGS_BODY" | sed -r -e "s/at/ikke at/i" -e "s/ikke //i")

if [ "$new" != "$EGGS_BODY" ]; then
    echo "$new"
fi
