#!/bin/sh
#
# Vær på tværs.

shuttingUp && exit

maybeGood .03 || exit

prog=$(cat <<'EOF'
    { if (match($0, /(^|\. )[^ ]+ (var|er|kunne|har|tog) ([^!.,]*)/, m)) {
        print m[1] "Din mor", m[2], m[3];
      } else if (match($0, ", [^ ]+ (var|er|kunne|har|tog) ([^!.,]*)", m)) {
        print "din mor", m[1], m[2];
      } else {
        print;
      }
    }
EOF
)
new=$(say "$EGGS_BODY" | awk "$prog")

if [ "$new" != "$EGGS_BODY" ]; then
    new_without_ending=$(say "$new" | sed -E -e 's/\.$//')
    echo "$EGGS_USER: ${new_without_ending}!"
fi
