#!/bin/sh

charm=$(dbRead charmen)
fraction=$(awk 'BEGIN{printf "%.1f", 0.1 * (10 - $charm)}')

front=$(randomLine <<EOF
HEY ALLESAMMEN
WÅUW hvor smart
opdagede lige
Øøøøøh
EOF
)

back=$(randomLine <<EOF
WAH WAH WAH!
hahaha *pruuuuuut*
, øh, øh, øh.
EOF
)

shuttingUp && exit
maybeGood $fraction || exit


grimt=$(echo "$EGGS_BODY" | tr '[:upper:]' '[:lower:]')

echo \""$front" "$grimt" "$back"\"
echo '/me giver et trut i båthornet'
echo "Det er sådan du lyder!"
