#!/bin/sh

. $CONCIEGGS_DIR/eggspi.lib

aliases "$EGGS_USER" | while read -r alias; do
    for x in $(dbIterate "$alias/messages"); do
        echo "$EGGS_USER: Besked fra $(dbRead $x/from): $(dbRead $x/msg)"
        dbDelete "$x";
    done
done
