#!/bin/sh

set -f

regex="(?i)(^$CONCIEGGS_NAME[,:!] (?<rawcmd>[^ ]+)(?<args>.*)$|(?<rawcmd>[^ ]+)(?<args>.*), $CONCIEGGS_NAME[!.?]*)\$"

eval "$(echo "$EGGS_BODY" | parse "$regex")"

if [ "$rawcmd" ]; then
    runcmd "$rawcmd" $args
fi
