#!/usr/bin/env perl
use 5.012;
use warnings;
use Env qw/EGGS_BODY/;
use IPC::System::Simple qw/runx capturex EXIT_ANY/;

# We don't want operators to operate if talking to concieggs.
exit if runx(EXIT_ANY, "talkingToConcieggs") == 0;

my @cmd = split(/\s*:([^:\s]+):\s*/, $EGGS_BODY);

exit(0) unless @cmd > 1;

while (@cmd > 1) {
    my $arg1 = shift @cmd;
    my $op   = shift @cmd;
    my $arg2 = shift @cmd // '';

    my $result = capturex('runoperator', $op, $arg1, $arg2);
    chomp $result;
    exit(0) unless $result;
    unshift(@cmd, $result);
}

printf("%s\n", $cmd[0]);
