#!/bin/sh

set -f

awk_getcmd='/^ *'$CONCIEGGS_NAME'[:,!] / { print tolower($2); }'
awk_getargs='{ print substr($0, index($0, " "$2)+length($2)+2, length($0)) }'

rawcmd=$(echo "$EGGS_BODY"|tolower|awk --posix "$awk_getcmd")
if [ "$rawcmd" ]; then
    args="$(echo "$EGGS_BODY"|awk --posix "$awk_getargs")"
    runcmd "$rawcmd" $args || runcmd $(echo "$rawcmd"|englishToDanish|tolower) $args
fi
