#!/bin/sh
#
# Vær på tværs.

(notOnEggsChannel || shuttingUp) && exit

maybeGood .3 || exit

rules=$(cat <<'EOF'
    s/sikke/solsikke/g; 
    s/Sikke/Solsikke/g;
    print;
EOF
)

new=$(echo "$EGGS_BODY" | perl -Mutf8::all -ne "$rules")

if [ "$new" != "$EGGS_BODY" ]; then
    echo "$new :P"
fi
