#!/usr/bin/env perl
use 5.026;
use strict;
use warnings;
use utf8::all;
use Env qw(EGGS_BODY EGGS_USER);
use EggsML::EggsPI boolean => [qw(shuttingUp checkCooldown)];

my $cooldown = checkCooldown('bibliotekaren', 300);

print STDERR "bibliotekar cooldown: $cooldown\n";

exit if shuttingUp || !$cooldown;

my $yelling = $EGGS_BODY =~ /!|\?{3}/;
my $uppercase = 0; $uppercase++ while ($EGGS_BODY =~ /\p{Uppercase}/g);

# Nogen råber hvis de benytter !, ??? eller mere end 50% store bogstaver.
exit unless $yelling || $uppercase*2 > length $EGGS_BODY;

my @comment = split "\n", <<"END_OF_BIBLIOTEKAR";
/me stirrer indgående på $EGGS_USER.
$EGGS_USER: Vil du være sød at dæmpe dig lidt?
$EGGS_USER: Ssh!
/me kigger på $EGGS_USER og tysser.
$EGGS_USER: Vær sød ikke at råbe.
$EGGS_USER: Her holder vi altså et civilt toneleje.
$EGGS_USER: Skal du hjælpes over på en mere larmende kanal?
$EGGS_USER: Dæmp dig.
/me kigger på $EGGS_USER og rømmer sig højlydt.
/me rømmer sig.
END_OF_BIBLIOTEKAR

print $comment[rand @comment];
