#!/usr/bin/env perl
use 5.026;
use strict;
use warnings;
use utf8::all;
use Env qw(EGGS_BODY EGGS_USER);
use EggsML::EggsPI boolean => [qw(shuttingUp checkCooldown)];

exit if shuttingUp || !checkCooldown('bibliotekaren', 300);

my $yelling = $EGGS_BODY =~ /!/;
my $uppercase = 0; $uppercase++ while ($EGGS_BODY =~ /\p{Uppercase}/g);

print STDERR ("bibliotekar-debug: " . $uppercase . " " . (2*$uppercase) . " " . $EGGS_BODY . "\n");

exit unless $yelling || $uppercase*2 > length $EGGS_BODY;

my @comment = split "\n", <<"END_OF_BIBLIOTEKAR";
/me stirrer indgående på $EGGS_USER.
$EGGS_USER: Vil du være sød at dæmpe dig lidt?
$EGGS_USER: Ssh!
/me kigger på $EGGS_USER og tysser.
$EGGS_USER: Vær sød ikke at råbe.
$EGGS_USER: Her holder vi altså et civilt toneleje.
$EGGS_USER: Skal du hjælpes over på en mere larmende kanal?
$EGGS_USER: Dæmp dig.
/me kigger på $EGGS_USER og rømmer sig højlydt.
/me rømmer sig.
END_OF_BIBLIOTEKAR

print $comment[rand @comment];
