#!/usr/bin/env perl
use v5.20;
use warnings;
use utf8;

use Encode qw/decode/;
use utf8::all;
my $EGGS_BODY = decode('utf-8', $ENV{EGGS_BODY});

system("shuttingUp || talkingToConcieggs");
exit if ($? >> 8) == 0;

system("maybeGood", ".3");
exit if $? == 0;

# en + en = to
my @rules = (
    {
        en   => 'en',
        to   => 'to',
        uncle => [
            "den er go'",
            "værsgo'",
            "kan du tro",
            "prøv at glo",
        ],
    },
    {
        en   => 'to',
        to   => 'fire',
        uncle => [
            "det' det jeg siger",
            "pi'rne skriger",
        ],
    },
    {
        en => 'tre',
        to => 'seks',
        uncle => [
            "er du en heks",
            "også i hex",
            ]
    },
    {
        en => 'fire',
        to => 'otte',
        uncle => [
            "uden at måbe",
            "vær' ikk' en tåbe",
            "jeg går i kåbe"
        ]
    },
    {
        en => 'fem',
        to => 'ti',
        uncle => [
            "det kan vi li'",
            "ud'n at vi'",
            "I hør' mig si'",
            "uden pli"
        ]
    },
    {
        en => 'seks',
        to => 'tolv',
        uncle => [
            "betal din told",
            "brug ingen vold",
            "gå med en trold",
            "jeg siger lol"
        ]
    },
    {
        en   => 'ni',
        to   => 'atten',
        uncle => [
            "så for sat'n",
            "jeg løfter hatten",
            "her i chatten",
            "gå med katten",
        ],
    },
    {
        en   => 'ti',
        to   => 'tyve',
        uncle => [
            "uden at lyve",
        ],
    },
);

for my $rule (@rules) {
    my $left = $rule->{en} . '\s+' . $rule->{en};
    my $right = $rule->{to};

    my $body = $EGGS_BODY =~ s/$left/$right/gr;
    next if ($body eq $EGGS_BODY);

    my $pun = $rule->{uncle}->[rand @{$rule->{uncle}}];
    printf("%s og %s gi'r %s; %s: %s\n", ucfirst $rule->{en}, $rule->{en}, $rule->{to}, $pun, $body);
    exit(0);
}
