#!/bin/sh

(shuttingUp || talkingToConcieggs) && exit

body="$(say "$EGGS_BODY" | perl -pne 's/en en/to/g')"

onkel=$(randomLine <<EOF
den er go'
værsgo'
kan du tro
prøv at glo
EOF
     )

if [ "$body" != "$EGGS_BODY" ]; then
    say "En og en gi'r to; $onkel: $body"
fi
