#!/usr/bin/env tclsh

catch {exec shuttingUp} {} options
if {![dict get $options -code]} {exit 0}

set nick $::env(EGGS_USER)
set text $::env(EGGS_BODY)
set t [clock format [clock seconds] -format %H]

set replies {
    "Svin! <3"
    "Morgenkrammer!"
    "God morgen. Sikke et dejligt vejr udenfor!"
    "Guten Morgen, meinen Freund!"
    "¡Hola! Ándale, ándale!"
}

set goodreplies {
    "Hvad er der så godt ved den?"
    "Du skulle have en præmie for at være så positiv."
    "Hvilken strålende morgen! God morgen til dig!"
    "GOD morgen!!!"
}

set earlyreplies {
    "Gaaaab!"
    "Det er alt for tidligt at være så aktiv!"
    "ER DU A_MENNESKEÆÆ?"
}

set latereplies {
    "Se dét er et tidspunkt at stå op på."
    "Et eller andet sted i verden, måske."
    "Jeg tror også at jeg tager en eftermiddagslur."
}

if {[regexp -nocase {^(g(?:o?'?|od)?)?[ \t]*m[oå](?:rn|rgen)} $text {} g]} {
    if {$g != ""}          {set replies [concat $replies $goodreplies]}
    if {$t > 13}           {set replies [concat $replies $latereplies]}
    if {$t > 6 && $t < 13} {set replies [concat $replies $earlyreplies]}
    puts "$nick: [lindex $replies [expr {int(rand()*[llength $replies])}]]"
}
