#!/usr/bin/env perl
use 5.012;
use warnings;
use Encode qw/decode encode/;

my $EGGS_BODY = $ENV{EGGS_BODY};

system("shuttingUp");
exit if ($? >> 8) == 0;

sub randomName {
    my $EGGS_USER = $ENV{EGGS_USER};
    my $name = `randomName $EGGS_USER` // $EGGS_USER;
    chomp $name;
    return $name;
}

if (my ($body) = $EGGS_BODY =~ qr/^Jeg kan godt lide ([^.!?]*[.!?]?)/i) {
    my $CONCIEGGS_NAME = $ENV{CONCIEGGS_NAME};

    $body =~ s#$CONCIEGGS_NAME#randomName()#eg;
    print "Jeg kan også godt lide $body\n";
}
