#!/bin/sh
#
# concieggs er et komplekst individ med modstridende holdninger.

shuttingUp && exit
maybeGood .1 || exit
checkCooldown ideologi 300 || exit

if (echo "$EGGS_BODY" | grep -qEi '(^| |\,|;|:|\.)+su+( |\,|;|:|\.|\?|!|$)'); then
    echo 'SU? Er det ikke bedre at kode for kapitalen?'
else
    case "$EGGS_BODY" in
        *idé*) echo 'En idé?  Hvor uambitiøst.  Fortæl hellere verden om din *vision!*' ;;
        *penge*) echo 'Penge?  Lad os dog fordele produktionsmidlerne mere ordentligt!' ;;
        *pligt*) echo 'Pligter?  Overfor staten??' ;;
        *frihed*) echo 'Hvad med samfundet?' ;;
    esac
fi
