#!/bin/sh
#
# concieggs er et komplekst individ med modstridende holdninger.

shuttingUp && exit
maybeGood .1 || exit
checkCooldown ideologi 300 || exit

case "$EGGS_BODY" in
  *idé*) echo 'En idé?  Hvor uambitiøst.  Fortæl hellere verden om din *vision!*' ;;
  *penge*) echo 'Penge?  Lad os dog fordele produktionsmidlerne mere ordentligt!' ;;
esac

