#!/bin/sh

charmen=$(dbRead charmen)
num=$(awk "BEGIN{print 0.1 * $charmen.0}")
maybeGood $num || exit

support=$(dbUserRead "$EGGS_USER" "support")
if [ "$support" = "1" ]; then
   support "$EGGS_USER"
fi
