#!/bin/sh
#
# Vær på tværs.

(notOnEggsChannel || shuttingUp) && exit

maybeGood .3 || exit

rules=$(cat <<'EOF'
    s/\bjeg\b/JEG/ig;
    s/\bmin\b/MIN\ /ig;
    s/\bintet\b/a¥lt/ig;
    s/\balt\b/i¥ntet/ig;
    s/\sikke\s/ /ig;
    s/\sikke//ig;
    s/(at \w+)/\1 ikke/ig;
    s/(r\ \w+)/\1 ikke/ig;
    s/\baldrig\b/a¥ltid/ig;
    s/altid/a¥ldrig/ig;
    s/venner/f¥jender/ig;
    s/fjender/v¥enner/ig;
    s/¥//ig;
    print;
EOF
)

new=$(say "$EGGS_BODY" | perl -Mutf8::all -ne "$rules")

if [ "$new" != "$EGGS_BODY" ]; then
    echo "$new"
fi
