#!/bin/sh
#
# Brok over indtastning af kommandoer i IRC.  Rettet mod folk der bruger en
# kommandolinje-baseret IRC-klient.

shuttingUp && exit

error() {
    randomLine <<EOF
$EGGS_USER: Det ser ud til at du prøver at køre en kommando i din terminal, men dette er altså IRC!
$EGGS_USER, for fanden.  Det her er IRC, ikke din konsol!
Dette er en IRC-kanal og ikke en konsol, kære $EGGS_USER.
Kære $EGGS_USER.  Jeg har i længere tid været irriteret over at du bruger os som en konsol.
Nej...  Nej...  NEJ!  $EGGS_USER, du kan ikke køre konsol-kommandoer på IRC, ligesom!
EOF
}

command=$(echo "$EGGS_BODY" | cut -d' ' -f1)

if which "$command" 2> /dev/null 1> /dev/null; then
    error
fi
