#!/usr/bin/env tclsh
#
# Grin højlydt.

proc run cmd {
    catch [list exec {*}$cmd] output options
    return [list [expr {![dict get $options -code]}] $output]
}

proc myRand {} {
    expr {int(rand() * 10) + 1}
}

proc randindex xs {
    return [lindex $xs [expr {int(rand() * [llength $xs])}]]
}

proc sjov {} {
    set prefix {VILDT ULTRA ROFLENDE MEGA LOLLENDE}
    set suffix {GRINERN SJOV MORSOM LOLZ ROFLCOPTER HYL}
    return "[randindex $prefix] [randindex $suffix]"
}

proc roflcopter {} {
" ROFL:ROFL:ROFL:ROFL
         _^___
 L    __/   [] \
LOL===__        \
 L      \________]
         I   I
        --------/"
}

if {[lindex [run shuttingUp] 0]} {exit 0}

set active 0
set text $::env(EGGS_BODY)
incr active [regsub -all -nocase {sjov(?:e|t|ere|est|este)?|grinere?n|morsom(?:t|me|mere)?|skæg(?:t|ge|gest)?} $text [sjov] text]
incr active [regsub -all -nocase {[Hh][aeioø](?:(?:h[aeioø])+h?|h)} $text [lindex [run laughter] 1] text]

if {$active > 0} {
    puts stdout $text
    # FIXME
    # if { [myRand] > 0} { puts stdout [roflcopter] }
    run [list pleasedBy $::env(EGGS_USER) 5]
}
