#!/usr/bin/env tclsh
#
# Grin højlydt.

proc run cmd {
    catch [list exec {*}$cmd] output options
    return [list [expr {![dict get $options -code]}] $output]
}

proc randindex xs {
    return [lindex $xs [expr {int(rand() * [llength $xs])}]]
}

proc sjov {} {
    set prefix {VILDT ULTRA ROFLENDE MEGA LOLLENDE}
    set suffix {GRINERN SJOV MORSOM LOLZ ROFLCOPTER HYL}
    return "[randindex $prefix] [randindex $suffix]"
}

if {[lindex [run shuttingUp] 0]} {exit 0}

set active 0
set text $::env(EGGS_BODY)
incr active [regsub -all -nocase {([A-Z])OL} $text "LOL" text]
incr active [regsub -all -nocase {sjov[te]?|grinere?n|morsom(?:t|me)|skæg(?:t|ge)?} $text [sjov] text]
incr active [regsub -all -nocase {[Hh][aeioø](?:(?:h[aeioø])+h?|h)} $text [lindex [run laughter] 1] text]

if {$active > 0} {
    puts stdout $text
    run [list pleasedBy $::env(EGGS_USER) 5]
}
