#!/usr/bin/env tclsh
#
# Grin højlydt.

proc execp cmd {
    catch [list exec {*}$cmd] {} options
    return [expr {![dict get $options -code]}]
}

proc run cmd {
    catch [list exec {*}$cmd] output options
    set errorcode [dict get $options -code]
    if {$errorcode != 0} {
        set errmsg "Programmet $::argv0 fik en fejlkode $errorcode på '$cmd'"
        if {$output eq ""} {
            append errmsg ", men spyttede stadig noget ud på stdout."
        }
        puts stderr $errmsg
    }
    return $output
}

proc rand {min max} {
    return [expr {$min + int(rand() * ($max-$min))}]
}

proc randindex xs {
    return [lindex $xs [rand 0 [llength $xs]]]
}

proc sjov {} {
    set prefix {VILDT ULTRA ROFLENDE MEGA LOLLENDE}
    set suffix {GRINERN SJOV MORSOM LOLZ ROFLCOPTER}
    return "[randindex $prefix] [randindex $suffix]"
}

proc haha {} {
    return [run laughter]
}

if {[execp shuttingUp]} {exit 0}

set nick $::env(EGGS_USER)
set text $::env(EGGS_BODY)

set changes 0
incr changes [regsub -all -nocase {sjov[te]?|grinere?n|morsom(?:t|me)|skæg(?:t|ge)?} $text [sjov] text]
incr changes [regsub -all -nocase {[Hh][aeø](?:(?:h[aeø])+h?|h)} $text [haha] text]

if {$changes > 0} {
    puts stdout $text
    execp [list pleasedBy $nick 5]
}
