#!/bin/sh

shuttingUp && exit

tidspunkt=`randomElement <<EOF
1
2
3
4
5
6
7
8
9
10
60
EOF
`
echo "runcmd jul" | at now + $tidspunkt minutes
#echoToServer ":KICK $(ircChannel) Nikkel :Du skulle have passet bedre på!"

exit
