#!/usr/bin/env python

import sys, os, random, subprocess
from time import sleep

def fork_away():
    if os.fork():
        sys.exit()

def run_main(args):
    if (random.randint(0,3) == 0):
        subprocess.call(["runcmd jul"], shell=True)
    else:
        sys.exit(0)


if __name__ == '__main__':
    run_main(sys.argv)


