#!/bin/sh
#
# wow derudaf.

wow() {
    o=o
    O=O
    for i in $(seq 1 $(random 0 4)); do
        o=$o$o
        O=$O$O
    done
    randomLine <<EOF
Ja, hold da kæft!
Så for satan!
Ih du milde!
Hold da helt fest!
w${o}w
W${O}W
Død og kritte!
Z${O}MG
Milde makrel!
Helle dusse da!
Du store kineser!
Sikke en redelighed!
Så for Søren!
Nu har jeg da aldrig!
Hillemænd!
Torden og lynild!
EOF
}

if echo "$EGGS_BODY" | grep -qiE 'w[aeiouæøå]+w'; then
    wow
fi
