#!/bin/sh

usesFilter jpop || exit
shuttingUp && exit
maybeGood .2 || exit

selvsang() {
    jpopSong | sed -r 's/([aeiouy])$/\1\1\1\1\1\1~~~/'
}

vild_farve() {
    randomLine <<EOF
lilla
pang-rød
pink
vold-orange
EOF
}

kostume() {
    randomLine <<EOF
t magical-girl-kostume
ne katteører
n $(vild_farve) paryk
t maid-kostume
n selvlysende neglelak
EOF
}

randomLine <<EOF
$(selvsang)
/me tager si$(kostume) på og stemmer stemmen: $(selvsang)
/me synger med på tv'et: $(selvsang)
/me går ud på scenen: $(selvsang)
/me kommer med sin originale komposition: $(selvsang)
/me krammer sin kropspude og nynner til sig selv: $(selvsang)
EOF
