#!/bin/sh
#
# Varulv!  Måske.

shuttingUp && exit

if isFullMoon "$(dateTomorrow)"; then
    maybeGood .05 || exit
    line=$(randomLine <<EOF
Blodet strømmer stærkere igennem mig...
/me føler langsomt sine negle vokse hurtigere end normalt
Hvad sker der med min dunst?
EOF
        )
elif isFullMoon "$(dateToday)"; then
    maybeGood .1 || exit
    line=$(randomLine <<EOF
Awuuuuuu!
/me river tøjet af sig
/me føler hurtigt sine negle blive til kløer
Aaaarhuuuugggh...
Hjælp, jeg er en varulv!
Hvad... hvad sker der for mig?
/me flår sin nørdede tshirt af
Mit hår, det gror!
/me kan lugte BLOD.
Månen er fuld, og det er jeg også, hik.
/me kigger op på himlen og hyler.
/me hyler til de andre varulve i natten.
/me hyler længe og intensivt.
Nej, nej...  NEEEJ, aaauurghhhhhhhhh.
Så for søren, jeg er sgisme en VARulv!
/me skaber pinligt virak efter månen træder ind på himlen.
/me går helt agurk under fuldmånens skær.
Fuldmåne!  Åh nej!
IIIIIH, HVORFOR NU FULDMÅNE IGEN???
/me stirrer ud i natten mens tænderne bliver skarpere.
EOF
        )
elif isFullMoon "$(dateYesterday)"; then
    maybeGood .05 || exit
    line=$(randomLine <<EOF
I må altså virkelig undskylde det der i går.  Det sker bare hver måned...
/me spadserer pinligt og næsten nøgen ned ad gaden
EOF
        )
else
    # JEG ER BARE ET MENNESKE OKAY
    exit
fi

if [ "$(ircChannel)" = "#diku" ]; then
    echo "infoskaerm: breaking: $(echo $line | sed -r 's/^\/me/concieggs/')"
else
    echo "$line"
fi
