#!/bin/sh
#
# Varulv!  Måske.

if ! isFullMoon; then
    # JEG ER BARE ET MENNESKE OKAY
    exit
fi

maybeGood .1 || exit

randomLine <<EOF
Awuuuuuu!
/me føler sine negle blive til kløer
Blodet strømmer stærkere igennem mig.
/me river tøjet af sig
EOF
