#!/bin/sh
#
# Varulv!  Måske.

if ! isFullMoon; then
    # JEG ER BARE ET MENNESKE OKAY
    exit
fi

shuttingUp && exit
maybeGood .1 || exit

line=$(randomLine <<EOF
Awuuuuuu!
/me føler sine negle blive til kløer
Blodet strømmer stærkere igennem mig.
/me river tøjet af sig
Aaaarhuuuugggh...
Hjælp, jeg er en varulv!
Hvad... hvad sker der for mig?
/me flår sin nørdede tshirt af
Mit hår, det gror!
/me kan lugte BLOD.
Månen er fuld, og det er jeg også, hik.
/me kigger op på himlen og hyler.
/me hyler til de andre varulve i natten.
/me hyler længe og intensivt.
Nej, nej...  NEEEJ, aaauurghhhhhhhhh.
Så for søren, jeg er sgisme en VARulv!
/me skaber pinligt virak efter månen træder ind på himlen.
/me går helt agurk under fuldmånens skær.
Fuldmåne!  Åh nej!
IIIIIH, HVORFOR NU FULDMÅNE IGEN???
/me stirrer ud i natten mens mine tænder bliver skarpere.
EOF
)

if [ "$(ircChannel)" = "#diku" ]; then
    echo "infoskaerm: breaking: $(echo $line | sed -r 's/\/me/Jeg/')"
else
    echo "$line"
fi
