#!/bin/sh
#
# Velbelæste og velopdragne concieggs bidrager til samtalen til de pæne middagsselskaber, den inviteres til. 

shuttingUp && exit

if ! checkCooldown "HackerNewsHistorie" $((60*60*13)); then
    exit 0
fi

echo "$EGGS_USER: $($CONCIEGGS_DIR/cmds/hn)"
