#!/usr/bin/env bash
#
# Velbelæste og velopdragne concieggs bidrager til samtalen til de pæne middagsselskaber, den inviteres til. 

shuttingUp && exit

if ! checkCooldown "HackerNewsHistorie" $((60*60*13)); then
    exit 0
fi

curl --silent 'https://hn.algolia.com/api/v1/search_by_date?tags=story' | \
    jq --argjson i "$RANDOM" --raw-output \
        '.hits | map(select(.url != null))
               | .[$i % length]
               | "\(.title) på \(.url) lyder som en spændende artikel. Diskussion: https://news.ycombinator.com/item?id=\(.objectID)"'
