#!/usr/bin/env perl
use 5.026;
use strict;
use warnings;
use utf8::all;

use Env qw(EGGS_USER EGGS_BODY);
use EggsML::EggsPI list_stdin => [qw(lastmsgs dbUserWrite)];

my $keep_at_least = 5;
my @last = lastmsgs($EGGS_USER);
unshift @last unless scalar @last < $keep_at_least;
push @last, $EGGS_BODY;

dbUserWrite({ stdin => \@last }, $EGGS_USER, 'lastmsg');
