#!/bin/sh


doodle="$(echo "$EGGS_BODY" | egrep -o 'https?://(www\.)?(doodle\.com/(poll/)?[a-z0-9]+|dudle\.inf\.tu-dresden\.de/[a-zA-Z0-9]+)' | sed 's/www.//')"

alreadyHasDoodle() {
    dbRead doodles | cut -d' ' -f 1 | fgrep -x "$1" > /dev/null
}

titleOfDoodle() {
    curl -L "$1" | grep -o '<title>.*</title>' | sed -r 's,</?title>,,g'
}

if [ "$doodle" ]; then
    if ! alreadyHasDoodle "$doodle"; then
        title="$(titleOfDoodle "$doodle")"
        ((dbRead doodles | tail -n 3); echo "$doodle $title") | dbWrite doodles
    fi
fi
