#!/bin/sh

. $CONCIEGGS_DIR/eggspi.lib

doodle="$(echo "$EGGS_BODY" | egrep -o 'http://doodle\.com/[a-z0-9]+')"

alreadyHasDoodle() {
    dbRead doodles | cut -d' ' -f 1 | fgrep -x "$1" > /dev/null
}

titleOfDoodle() {
    curl "$1" | grep -o '<title>.*</title>' | sed -r 's,</?title>,,g'
}

if [ "$doodle" ]; then
    if ! alreadyHasDoodle "$doodle"; then
        title="$(titleOfDoodle "$doodle")"
        ((dbRead doodles | tail -n 3); echo "$doodle $title") | dbWrite doodles
    fi
fi
