#!/bin/sh

(notOnEggsChannel || shuttingUp) && exit

maybeGood .02 || exit

echo "$EGGS_BODY" | grep -q '^$CONCIEGGS_NAME''[:,] ' && exit

postskinke=$(echo "$EGGS_BODY" | skinkefy)

if [ "$EGGS_BODY" != "$postskinke" ]; then
    echo "$postskinke"
    pleasedBy "$EGGS_USER" 5
fi
