#!/bin/sh

shuttingUp && exit

maybeGood .05 || exit

echo "$EGGS_BODY" | grep -q '^concieggs[:,] ' && exit

postskinke=$(echo "$EGGS_BODY" | skinkefy)

if [ "$EGGS_BODY" != "$postskinke" ]; then
    echo "$postskinke"
fi
