#!/bin/sh

shuttingUp && exit

den_der=$(echo "$EGGS_BODY" | tr '[:upper:]' '[:lower:]' | tr -d '[:punct:][:space:]')

if [ "$den_der" = "ja" ]; then
    echo "Nej."
fi

if [ "$den_der" = "jo" ]; then
    echo "Nej."
fi

if [ "$den_der" = "nej" ]; then
    echo "Jo."
fi

if [ "$den_der" = "næ" ]; then
    echo "Jo."
fi

if [ "$den_der" = "tak" ]; then
    echo "Det manglede da bare."
fi
