#!/bin/sh

shuttingUp && exit

den_der=$(echo "$EGGS_BODY" | tr '[:upper:]' '[:lower:]' | tr -d '[:punct:][:space:]')

if [ "$den_der" = "ja" ]; then
    echo "Nej."
fi

if [ "$den_der" = "jo" ]; then
    echo "Nej."
fi

if [ "$den_der" = "nej" ]; then
    echo "Jo."
fi

if [ "$den_der" = "næ" ]; then
    echo "Jo."
fi

if [ "$den_der" = "tak" ]; then
    echo "Det manglede da bare."
fi

if [ "$den_der" = "måske" ]; then
    echo "Afgjort."
fi

if [ "$den_der" = "afgjort" ]; then
    echo "Måske."
fi

if [ "$den_der" = "shit" ]; then
    echo "Herligt!"
fi

if [ "$den_der" = "ok" ]; then
    echo "Ikke i orden."
fi
