#!/bin/sh

set -f

shuttingUp && exit

sviner() {
    when=$1
    who=$2
    echo "$who: JEG HADER DIG."
    echo "$who: Hvad sker der med $(titleEggs $when)?  Kom i sving!"
    echo "$who: Forventer du at jeg posteggser $(titleEggs $when) for dig?"
    echo "$who: Din mor spiser her ikke.  Du var med til $(titleEggs $when), så post den eggs!"
    echo "$who: Du er spild af Jordens sparsomme ilt.  Se så at få gjort noget ved $(titleEggs $when), den er stadigvæk ikke blevet postet."
    echo "$who: Følgende sjuskede svin spiste $(titleEggs $eggs): $(describeEggs $eggs).  Hvorfor fanden har I ikke postet?"
    echo "$who: Se så at få postet $(titleEggs $eggs)!  Du er den sygdom der inficerer frokostlogen."
    echo "$who: Selv et slamkodet shell script kan se at du ikke har styr på en skid!  Hvorfor har du ikke postet $(titleEggs $eggs)?!"
    echo "$who: SVIN!"
    echo "$who: Man skulle tro du var rus!"
    echo "$who: IDIOT!"
    echo "$who: Du har begået en frygtelig Ulrik!  Hvordan kan du leve med dig selv?"
    echo "$who: ANTIFROKOST!"
    echo "$who: Du har glemt at posteggse OG DIN MOR ER SIKKERT TYK!"
    echo "$who: Du er værre end den værste!"
    echo "$who: Jeg mangler ord til at beskrive MIT HAD over $(titleEggs $when)!"
    echo "$who: Jeg troede at vi var venner, men tydeligvis ikke efter $(titleEggs $when) :'("
    echo "$who: Du er et monster."
}

fuck() {
    ex="$(sviner $1 $2 | randomElement)"
    if [ "$ex" ]; then
        echo "$ex"
    fi
}

prevEggs | while read eggs; do
    if [ $(($(nowTime) - $eggs)) -gt 3600 ] && [ "$(isInEggs $eggs $EGGS_USER)" ]; then
        fuck $eggs $EGGS_USER
    fi
done
