#!/usr/bin/env python3
#
# Gør farlige ord sikre.

import sys
import re
import random

def censur_måske(t):
    if len(t) > 3 and random.random() < 0.3:
        return '*' * len(t)
    else:
        return t

for linje in sys.stdin:
    linje_bedre = re.sub(r'\w+', lambda m: censur_måske(m.group(0)), linje)
    print(linje_bedre, end='')
