#!/usr/bin/env python3
#
# Gør farlige ord sikre.

import sys
import re
import random

def sample_wr(population, k):
    n = len(population)
    _random, _int = random.random, int  # speed hack 
    result = [None] * k
    for i in range(k):
        j = _int(_random() * n)
        result[i] = population[j]
    return result

tegn = ['!' , '#' , '%', '*', '&', '$', '@']

def censur_måske(t):
    if len(t) > 3 and random.random() < 0.3:
        return ''.join(sample_wr(tegn, len(t)))
    else:
        return t

for linje in sys.stdin:
    linje_bedre = re.sub(r'\w+', lambda m: censur_måske(m.group(0)), linje)
    print(linje_bedre, end='')
