#!/bin/sh

# Det her skalerer helt sikkert.

sed -e 's/er/var/g' \
    -e 's/bliver/blev/g' \
    -e 's/kan/kunne/g' \
    -e 's/har/havde/g' \
    -e 's/mener/mente/g' \
    -e 's/synes/syntes/g' \
    -e 's/gør/gjorde/g'
