#!/usr/bin/env perl
use 5.042;
use utf8;

sub scratch {
  my $s = 's-' x rand 10;
  my $a = 'a' x rand 10;
  return "*${s}scr${a}atch!*";
}

while (<>) {
  chomp;
  say $_ . '  ' . scratch;
}

if (!int rand 10) {
  my $alfa = `whatsPlaying alfa`;
  chomp $alfa;
  say "/me sætter pladen med $alfa på!"
}
