#!/usr/bin/env perl
use 5.012;
use warnings;
use utf8::all;

# THIS IS WHAT FEMINISTS ACTUALLY BELIEVE[0]
#
# [0]: Ifølge /r/mensrights

my @ine = qw(ine ina); sub ine { $ine[rand @ine]; }

while (<>) {
    s/hans/hendes/ig;
    s/han/hun/ig;
    s/ham/hende/ig;
    s/manden/kvinden/ig;
    s/kongen/dronningen/ig;
    s/konge/dronning/ig;
    s/sværd/skjold/ig;
    s/mand/kvinde/ig;
    s/mænd/kvinder/ig;
    s/far/mor/ig;
    s/fader/moder/ig;
    s/penis/vagina/ig;
    s/pikken/kussen/ig;
    s/pik/kusse/ig;
    s/diller/fjams/ig;
    s/skæg\b/bryst/ig;
    s/\bde[nt]s\b/hendes/ig;
    s/drengene/pigerne/ig;
    s/drengen/pigen/ig;
    s/drenge\b/piger/ig;
    s/drenge?/pige/ig;
    s/knægtene/tøserne/ig;
    s/knægten/tøsen/ig;
    s/knægte/tøser/ig;
    s/knægt/tøs/ig;
    s/sønnens/datterens/ig;
    s/sønnen/datteren/ig;
    s/søn\b/datter/ig;
    s/bro(r|der)/søster/ig;
    s/brødre/søstre/ig;
    s/personer/kvinder/ig;
    s/person/kvinde/ig;
    s/woman/womyn/ig;
    s/\Bman/woman/ig;
    s/\bman\b/kvinde/ig;
    s/sir\b/lady/ig;
    s/Pind/Hul/g;
    s/pind/hul/g;
    s/\bhr\./fru/g;
    s/\bHr\./Fru/g;
    s/(?<=\bs)ir/øster/ig;
    s/\bLord\b/Lady/g;

    s/(?<=[Ss])øren/ørine/ig;
    s/(?<=[Jj])ørgen/ørgine/ig;
    s/(?<=[Gg])eorge/eorgine/ig;
    s/(?<=[Dd])onald/aisy/ig;
    s/(?<=[Tt])r(oe|u)lsa?/r\1lsina/ig;
    s/(?<=[Bb])ill/ella/ig;
    s/(?<=[Rr]onald)/ine/eig;
    s/(?<=[Ss]ebb)e/ine/eig;
    s/(?<=[Ss]ebast)ian/ine/eig;
    s/(?<=[Rr]asm)us/ina/eig;
    s/(?<=[Nn]ikkel)/ine/eig;
    s/(?<=[Nn]iels)/ine/eig;
    s/(?<=svip)/ine/eig;

    # Burde nok generaliseres.
    s/(?<=Athas)/ine/eig;
    s/(?<=oleks)/ine/eig;
    s/(?<=EricZ)ou/ine/eig;
    s/simon|s?shine/simone-tøzzen/ig;

    print;
}
