#!/usr/bin/env perl
use 5.012;
use warnings;
use utf8::all;

# THIS IS WHAT FEMINISTS ACTUALLY BELIEVE[0]
#
# [0]: Ifølge /r/mensrights

while (<>) {
    s/hans/hendes/ig;
    s/han/hun/ig;
    s/ham/hende/ig;
    s/manden/kvinden/ig;
    s/kongen/dronningen/ig;
    s/konge/dronning/ig;
    s/sværd/skjold/ig;
    s/mand/kvinde/ig;
    s/mænd/kvinder/ig;
    s/far/mor/ig;
    s/fader/moder/ig;
    s/penis/vagina/ig;
    s/pikken/kussen/ig;
    s/pik/kusse/ig;
    s/diller/fjams/ig;
    s/skæg\b/bryst/ig;
    s/\bde[nt]s\b/hendes/ig;
    s/drengene/pigerne/ig;
    s/drengen/pigen/ig;
    s/drenge\b/piger/ig;
    s/drenge?/pige/ig;
    s/knægtene/tøserne/ig;
    s/knægten/tøsen/ig;
    s/knægte/tøser/ig;
    s/knægt/tøs/ig;
    s/sønnens/datterens/ig;
    s/sønnen/datteren/ig;
    s/søn\b/datter/ig;
    s/bro(r|der)/søster/ig;
    s/brødre/søstre/ig;
    s/personer/kvinder/ig;
    s/person/kvinde/ig;
    s/woman/womyn/ig;
    s/\Bman/woman/ig;
    s/\bman\b/kvinde/ig;
    s/sir\b/lady/ig;
    s/Pind/Hul/g;
    s/pind/hul/g;
    s/Søren/Sørine/ig;

    print;
}
