#!/usr/bin/env sh

svin=$(randomLine <<EOF
For helvede,
Forbandede
Hop i havet,
Brænd dig på noget,
Dumme
Idioten
Fjolset
EOF
)

vrede=$(randomLine <<EOF
For helvede!
Hvor tit skal jeg sige det?
DNUR!
Og hold så kæft.
Er det så svært at fatte?
>:(
... er det til at fatte?
EOF
)

LINE=$(cat -)
echo $LINE | if $(echo $LINE | grep -q ':'); then
  sed -r -e "s/^/$svin /" -e "s/\$/  $vrede/"
else
  sed -r -e "s/^/$svin $EGGS_WHERE.  /" -e "s/\$/  $vrede/"
fi
