#!/usr/bin/env sh

svin=$(randomLine <<EOF
For helvede,
Forbandede
Hop i havet,
Brænd dig på noget,
Dumme
Idioten
Fjolset
EOF
)

vrede=$(randomLine <<EOF
For helvede!
Hvor tit skal jeg sige det?
DNUR!
Og hold så kæft.
Er det så svært at fatte?
>:(
... er det til at fatte?
EOF
)

sed -r -e "s/^(.+:)/$svin \1/" -e "s/^([^:]+)$/$svin $EGGS_WHERE.  \1/" -e "s/\$/  $vrede/"
