#!/usr/bin/env perl
use 5.012;
use warnings;
use strict;
use utf8::all;

my @start = qw(
    trå
    sjå
    lå
);

my @middle = qw(
    lå
    lååh
    -lå-
    å
);

my @end = qw(
    dååååh
    då
    lå
    lå
    låh
);

sub sing {
    my $syllables = shift;

    my $out = $start[rand @start];
    $out   .= $middle[rand @middle] for (2 .. $syllables-1);
    $out   .= $end[rand @end] if $syllables > 1;

    $out =~ s/-{2,}/-/g;

    return $out;
}

my $string = <>;
my @words  = split(' ', $string);

my @outarray = ();

for my $word (@words) {
    my ($punctuation) = $word =~ /([.?!])/;
    my $syllables = () = $word =~ /[aeiouyæåø]{1,2}/gi;
    push (@outarray, sing($syllables) . ($punctuation // ''));
}


my $song = join(" ", @outarray);
say uc($song) . "!";

