#!/usr/bin/env perl
#
# Fjern alle referencer til den trælse højtid i december

use 5.012;
use warnings;
use utf8::all;

my @bad_foods = qw(risengrød sylte flæskesteg sild eiskonfekt konfekt marcipan nougat blodpølse risalamande andesteg gås medisterpølse pebbernød pebbernødder);
my @bad_drinks = qw(snaps gløgg glögg likør rom portvin valnøddesnaps juleøl sne-bajer snebajer porsesnaps sprut vin);

my $ebenezer_scrooge_quote = "Bah! Humbug!";

while (my $line = <>) {

    # If sentence starts with the bad word, skip entire sentence. Nothing good can come from this.
    if ($line =~ qr/^ju+l\b/i){
        next;
    }

    # Nothing is worse than singing, also ban these sentences
    if ($line =~ qr/(\bsynge|\bsang|\bbjældeklang\bnr\..*hæfte)/i){
        next;
    }

    # The bad event has special greetings. Ban them!
    if ($line =~ qr/\bglædelig\b/i){
	say $ebenezer_scrooge_quote;
        next;
    }

    # Ban games!
    if ($line =~ qr/(rafle|pakkeleg)/){
        next;
    }

    $line =~ s/\bjulet\b/mørkt og koldt/gi;
    $line =~ s/[Ee]n gave/et stykke kul/gi;
    $line =~ s/\bgaver?\b/kul/gi;
    $line =~ s/juletræ/træ/gi;
    $line =~ s/juleaften/vintersolhverv/gi;
    $line =~ s/julen/september/gi;
    $line =~ s/jule-?//gi;
    $line =~ s/\bho(ho)+/haha/gi;
    $line =~ s/\bhøjtid(en)?/kulden og mørket/gi;
    $line =~ s/\bjuler\b/fryser/gi;
    $line =~ s/\bju+l\b/vinter/gi;
    $line =~ s/\bpakker\b/stykker kul/gi;
    $line =~ s/\bhygge\b/arbejde hårdt/gi;
    $line =~ s/hygge\b//gi;
    $line =~ s/familier/virksomheder/gi;
    $line =~ s/familie\b/virksomheds/gi;
    $line =~ s/stjerner/fugle/gi;
    $line =~ s/stjernen/fuglen/gi;
    $line =~ s/stjerne/fugl/gi;
    $line =~ s/engle/fugle/gi;
    $line =~ s/engel/fugl/gi;
    $line =~ s/familie/virksomhed/gi;
    $line =~ s/salmer?/kvad/gi;
    $line =~ s/kirke/politisk møde/gi;
    $line =~ s/et træ/en bregne/gi;
    $line =~ s/træet/bregnen/i;
    $line =~ s/træer/bregner/i;
    $line =~ s/træ/bregne/i;
    $line =~ s/Træet/Bregnen/i;
    $line =~ s/Træer/Bregner/i;
    $line =~ s/Træ/Bregne/g;
    $line =~ s/pynt/plakat/gi;
    $line =~ s/pynte/renovere/gi;
    $line =~ s/hyggelig/vild/gi;
    $line =~ s/hyggeligt/vildt/gi;
    $line =~ s/sne/solskin/gi;
    $line =~ s/vise mænd/personer/gi;
    $line =~ s/Jesusbarnet/Ole du ved/gi;
    $line =~ s/Jesus( Kristus)?/Ole du ved/gi;
    $line =~ s/slæden/bilen/gi;
    $line =~ s/slæde/bil/gi;
    $line =~ s/kanen/bilen/gi;
    $line =~ s/kane/bil/gi;
    $line =~ s/klejne/tvebakke/gi;
    $line =~ s/kager?/kiks/gi;
    $line =~ s/godter/havegrød/gi;
    $line =~ s/slik/havegrød/gi;
    $line =~ s/risengrød/havegrød/gi;
    $line =~ s/rensdyr/slaver/gi;
    $line =~ s/hall?eluja/helledusseda/gi;
    $line =~ s/Maria/Marlene/gi;
    $line =~ s/Josef/Jens/gi;
    $line =~ s/hyrde/fodermester/gi;
    $line =~ s/Beth?lehem/Slagelse/gi;
    $line =~ s/\blam/kalv/gi;
    $line =~ s/hjerte/lunge/gi;
    $line =~ s/\bløn/salær/gi;
    $line =~ s/\bfred/fordragelighed/gi;
    $line =~ s/\bbøn\b/begæring/gi;
    $line =~ s/glæde/fornøjelighed/gi;
    $line =~ s/kærligheden/følelsen/gi;
    $line =~ s/kærlighed/følelse/gi;
    $line =~ s/glæden/følelsen/gi;
    $line =~ s/glæde/følelser/gi;
    $line =~ s/\bhåb/aspiration/gi;
    $line =~ s/\bbarnet/personen/gi;
    $line =~ s/\bbarn/person/gi;
    $line =~ s/krybbe/hængekøje/gi;
    $line =~ s/\bblid/sensitiv/gi;
    $line =~ s/\bføde/søsætte/gi;
    $line =~ s/jord/planet/gi;

    # Ban bad foods
    my $food_pattern = '(\b' . join('\b|\b', @bad_foods) . '\b)';
    my $food_regex = qr/$food_pattern/i;
    my $drinks_pattern = '(\b' . join('\b|\b', @bad_drinks) . '\b)';
    my $drinks_regex = qr/$drinks_pattern/i;
    $line =~ s/$food_regex/lasagne/gi; # all banned foods are now lasagne, bitches
    $line =~ s/$drinks_regex/mælk/gi; # all banned drinks are now milk

    # Avoid printing empty lines or white space lines
    if ($line =~ /^\s*$/){
        next;
    }

    # Strip trailing whitespace
    $line =~s/\s+$//;

    say $line;
}
