#!/usr/bin/env perl
use strict;

my @vuf = qw(vuf vov );

sub vuf {
    my $vuf = $vuf[rand @vuf];
    return " *$vuf $vuf* ";
}

while (my $line = <>) {
    my $me = ($line =~ s!^/me !!);
    $line =~ s/^|(?<=[.!?])/vuf()/ge;
    print +($me ? "/me " : "") . $line;
}
