#!/bin/sh
#
# Wooooow!!!

Imponerende=$(randomLine <<EOF
Imponerende
Det må jeg nok sige
Wauw
Du er jo helt vild
Syyyygt nice
Hold da fest
Ser man det
Nu har jeg aldrig
Ih dog
Hillemænd
NOVRA
EOF
)

sed -r "s/^/$Imponerende.  /"
