#!/bin/sh
#
# Wooooow!!!

Imponerende=$(randomLine <<EOF
Nå nå, da
Imponerende
Det må jeg nok sige
Wauw
Du er jo helt vild
Syyyygt nice
Hold da fest
Hold da op
Ser man det
Nu har jeg aldrig
Ih dog
Jamen dog
Sikke en rumhelt
Hillemænd
Novra
Du store kineser
Nu har jeg da aldrig
Wow
Hvor vildt
Du godeste
Har man set magen
Gisp
Hvem ville have troet det
EOF
)

sed -r "s/^/$Imponerende.  /"
