#!/usr/bin/env python3
#
# Vær j-poppet, desu.

import random
import re
import subprocess
import sys


def jpopify(s):
    initial_exclamations = [
        'Ureshii',
        'Yaru',
        'Yasashii',
        'Sugoi',
        'Kawaii',
        'Zuttou',
        'Dattebayo',
    ]

    extra_words = [
        'darou',
        'desu',
        'ne',
        'deshou',
    ]

    silly_exclamations = [
        'uguu',
        'gyaa',
        'nyaa',
        'kyaa'
    ]

    dramatic_exclamations = [
        'Anata mou',
        'Kimi ga',
        'Kono setzubou',
        'Demou'
    ]

    honorifics = [
        'sama',
        'chan',
        'kun',
        'san',
    ]

    recently_active = subprocess.check_output(['recentlyActive'])
    recently_active = recently_active.decode('utf-8').strip()
    recently_active = recently_active.split('\n')

    def jpopify_word(word):
        if word in recently_active:
            return word + '-' + random.choice(honorifics)
        else:
            return word

    s = re.sub(r'\w+', lambda m: jpopify_word(m.group(0)), s)

    start = (random.choice(initial_exclamations) + ' ' +
             random.choice(extra_words) + '!  ')

    if random.randint(0, 1) == 0:
        s = s.rstrip('?!.,')
        end = (', ' + random.choice(silly_exclamations) +
               ('~' * random.randint(0, 5)))
    else:
        if not s[-1] in '?!.,':
            s += '.'
        end = '  ' + random.choice(dramatic_exclamations) + '...'

    s = start + s + end
    return s


def interact(fun):
    inp = sys.stdin.read().rstrip()
    out = fun(inp)
    sys.stdout.write(out)


def main():
    interact(jpopify)
    return 0

if __name__ == '__main__':
    sys.exit(main())
