#!/usr/bin/env python3
#
# Vær kapitalist

import sys
import re

def flatten(xss):
    return [ x for xs in xss for x in xs ]

upper = "𝔸𝔹ℂ𝔻𝔼𝔽𝔾ℍ𝕀𝕁𝕂𝕃𝕄ℕ𝕆ℙℚℝ𝕊𝕋𝕌𝕍𝕎𝕏𝕐ℤ"
lower = "𝕒𝕓𝕔𝕕𝕖𝕗𝕘𝕙𝕚𝕛𝕜𝕝𝕞𝕟𝕠𝕡𝕢𝕣𝕤𝕥𝕦𝕧𝕨𝕩𝕪𝕫"
table = dict(flatten([ [ (ord('a') + i, lower[i]),
                         (ord('A') + i, upper[i]) ]
                       for i in range(26) ]))

a = table[ord('a')]
e = table[ord('e')]
o = table[ord('o')]

table[ord('æ')] = a + e
table[ord('ø')] = o
table[ord('å')] = a + a

A = table[ord('A')]
E = table[ord('E')]
O = table[ord('O')]

table[ord('Æ')] = A + E
table[ord('Ø')] = O
table[ord('Å')] = A + A

if __name__ == "__main__":
    for line in sys.stdin:
        print(line.translate(table))
