#!/usr/bin/env perl
use 5.020;
use strict;
use warnings;
use utf8::all;

use EggsML::EggsPI list => ['cowsay'];

chomp (my @lines = <STDIN>);
@lines = cowsay({ stdin => \@lines }, "-n");
say $_ for @lines;
