#!/usr/bin/env perl
use 5.020;
use strict;
use warnings;

use EggsML::EggsPI raw => ['cowsay'];

chomp (my @lines = <STDIN>);
my @split_lines = ();
foreach ( @lines ) {
    push @split_lines, ( $_ =~ m/.{40}/g );
}

say cowsay({ stdin => \@split_lines }, "-n");
