#!/usr/bin/env perl
use 5.020;
use strict;
use warnings;

use EggsML::EggsPI raw => ['cowsay'];

chomp (my @lines = <STDIN>);
my @split_lines = ();
foreach ( @lines ) {
    push @split_lines, ( $_ =~ m/.{0,120}/g );
}

pop @split_lines if ($split_lines[-1] =~ /^\s*$/);
say cowsay({ stdin => \@split_lines }, "-n");
