#!/usr/bin/env perl
use 5.012;
use warnings;
use utf8::all;

my $red = "\cC04";
my %aliases = map { (lc($_) => 1) } split("\n", `allAliases`);

sub commify {
    my $word = shift;
    my $prefix = $aliases{lc $word} ? "kammerat " : "";

    if (rand() < 0.25) {
        $word = "█" x length $word;
    }

    return $prefix . $word;
}

while (my $line = <>) {
    chomp $line;

    my $me = ($line =~ m!^/me !);
    $line = substr $line, 4 if $me;

    $line =~ s/\b(\S*)\b/commify($1)/ge;

    my $meprefix = $me ? "/me " : "";
    say $meprefix . "$red☭ $line $red☭";
}
