#!/usr/bin/env perl
use 5.020;
use strict;
no warnings;
use utf8;
use Time::Piece;

if (0.2 > rand) {
    given (localtime->day_of_week) {
        when(0) { say "Åh nej, søndag!"; }
        when(1) { say "Åh nej, mandag!"; }
        when(2) { say "Åh nej, tirsdag!"; }
        when(3) { say "Åh nej, onsdag!"; }
        when(4) { say "Jubi, lille fredag!"; }
        when(5) { say "Jubii, fredag!"; }
        when(6) { say "Jubiii, lørdag!!"; }
    }
}

while (my $line = <STDIN>) {
    print $line;
}
