#!/usr/bin/env perl
use 5.020;
use strict;
no warnings;
use utf8;
use Time::Piece;
use EggsML::EggsPI boolean => [qw(shuttingUp)];

exit if shuttingUp;
exit unless 0.1 > rand;

given (localtime->day_of_week) {
    when(0) { print "Åh nej, søndag!"; }
    when(1) { print "Åh nej, mandag!"; }
    when(2) { print "Åh nej, tirsdag!"; }
    when(3) { print "Åh nej, onsdag!"; }
    when(4) { print "Jubi, lille fredag!"; }
    when(5) { print "Jubii, fredag!"; }
    when(6) { print "Jubiii, lørdag!!"; }
}
