#!/usr/bin/env perl
use 5.012;
use warnings;
use utf8::all;

# Et syntetisk skriftsprog opfundet af Ivar Aasen i midten af 1800-tallet
# i et forsøg på at undslippe det danske koloniale åg.

sub translate{
  my $source_lang = shift;
  my $target_lang = shift;
  my $text        = shift;
  open( my $fh, "|translate $source_lang $target_lang" );
  print $fh $text;
  local $/;
  my $res = <$fh>;
  close $fh;
  return $res;
}

my $vowel = "[aeiouyæøå]";
my $consonant = "[bcdfghjklmnpqrstvwxz]";

while (my $text = <>) {
    $text =~ s/jeg/eg/ig;
    $text =~ s/ikke/ikkje/ig;
    $text =~ s/meget/mykje/ig;
    $text =~ s/\bet\b/ett/ig;
    $text =~ s/\ben\b/ein/ig;
    $text =~ s/\Bdt\b/tt/ig;
    $text =~ s/æ/e/ig;
    $text =~ s/ved/veit/ig;
    $text =~ s/\Bo\B/u/ig;
    $text =~ s/(?<=${vowel})d(?=${vowel})/t/ig;
    $text =~ s/\Bvd/dd/ig;
    $text =~ s/hvorfor/kvifor/ig;
    $text =~ s/hvad/kva/ig;
    $text =~ s/\bhvor\b/kor/ig;
    $text =~ s/hvordan/korleis/ig;
    $text =~ s/\bvi\b/me/ig;
    $text =~ s/\bderes\b/dykk/ig;
    print translate( "da", "no", $text );
}
