#!/usr/bin/env perl
use 5.012;
use warnings;
use utf8::all;

# Et syntetisk skriftsprog opfundet af Ivar Aasen i midten af 1800-tallet
# i et forsøg på at undslippe det danske koloniale åg.

sub translate {
    my $source_lang = shift;
    my $target_lang = shift;
    my $source_text = shift;

    open( GOOGLE, "| translate $source_lang $target_lang" );
    print GOOGLE $source_text;
    close GOOGLE;
}

my $lande = join "|", qw(
  Danmark
  Norge
  Sverige
  Finland
  Tyskland
  USA
  Storbritannien
  Island
  Canada
  Mexico
  Brasilien
  Rusland
  Frankrig
  Spanien
  Italien
  Kina
  Indien
  Egypten
);

my @udraab = (
    "Ja da!",
    "Ikkje sant?",
    "Fy faen!",
    "Fy flate!",
    "Faen i helvete!",
    "Ja, vi elskar dette landet!",
    "Noreg er verdas beste land!",
    "Skriv nynorsk, tal dialekt!",
);

sub udraab {
    return rand() < 0.2 ? ' ' . $udraab[rand(@udraab)] . ' ' : '';
}

my $vowel = "[aeiouyæøå]";
my $consonant = "[bcdfghjklmnpqrstvwxz]";

while (my $text = <STDIN>) {
    $text =~ s/$lande/Noreg/ig;
    $text =~ s/\bjeg\b/eg/ig;
    $text =~ s/ikke/ikkje/ig;
    $text =~ s/meget/mykje/ig;
    $text =~ s/\bved\b/veit/ig;
    $text =~ s/\bvi\b/me/ig;
    $text =~ s/\bderes\b/dykk/ig;
    $text =~ s/navn/namn/ig;

    $text =~ s/hvorfor/kvifor/ig;
    $text =~ s/hvad/kva/ig;
    $text =~ s/\bhvor\b/kor/ig;
    $text =~ s/hvordan/korleis/ig;

    $text =~ s/\bet\b/eit/ig;
    $text =~ s/\ben\b/ein/ig;
    $text =~ s/(?<!n)o\B/u/ig;
    $text =~ s/(?<=${vowel})d(?=${vowel})/t/ig;

    # Tilfældige udråb
    $text =~ s/(?<=[.?!])/udraab()/ge;

    translate("da", "no", $text);
}
