#!/usr/bin/env perl
use 5.012;
use warnings;
use utf8::all;

sub ivrig {
    my $length = length shift;
    my $result = $_[0];
    $result .= $_[rand(@_)] for (1..$length+rand(3));
    return $result;
}

while (my $text = <>) {
    # Mindre kompleks grammatik
    $text =~ s/[.,;"-]/ /g;
    $text =~ s/(!+)/ivrig($1, '!', '1')/eg;
    $text =~ s/(\?+)/ivrig($1, '?', '+')/eg;

    # Stumme bogstaver, fonetisk stavning
    $text =~ s/gjort/gjordt/g;
    $text =~ s/\Ber\b/e/g;
    $text =~ s/nde/ne/g;
    $text =~ s/ind/in/g;
    $text =~ s/hv/v/g;
    $text =~ s/dt/t/g;
    $text =~ s/også/osse/g;
    $text =~ s/ige/ie/g;
    $text =~ s/åd/å/g;
    $text =~ s/ej/aj/g;
    $text =~ s/sk/sg/g if rand() < 0.5;
    $text =~ s/ege/aje/g;

    my $rd = rand() < 0.5 ? "r" : "rt";
    $text =~ s/rd/$rd/g;

    # Ord-endelser
    $text =~ s/et\b/ed/;
    $text =~ s/ede\b/et/g;
    $text =~ s/el\b/æl/g if rand() < 0.5;
    $text =~ s/å/or/g if rand() < 0.5;
    $text =~ s/en\b/æn/ if rand() < 0.5;

    my $ig = qw(i ej aj)[rand(3)];
    $text =~ s/ig\b/$ig/g;

    # Undgå dobbelt-konsonanter
    $text =~ s/([bcdfghjklmnpqrstvwxz])\1/$1/g;

    # nutids-r
    $text =~ s/rer /\@e\@ /g;
    $text =~ s/re /rer /g;
    $text =~ s/\@e\@ /re /g;
    $text =~ s/rer\./\@e\@\./g;
    $text =~ s/re\./rer\./g;
    $text =~ s/\@e\@\./re\./g;
    $text =~ s/rer,/\@e\@,/g;
    $text =~ s/re,/rer,/g;
    $text =~ s/\@e\@,/re,/g;

    print $text;
}
