#!/usr/bin/env perl
use 5.012;
use warnings;
use utf8::all;

my @facts = split '\n', <<'END_OF_PIND';
Søren Pind blev født den 20. november 1969 i Herning.
Søren Pind blev justitsminister (aka Sheriffen) den 28. juni 2015.
Søren Pind er søn af en tandlæge.
Søren Pind gik på Bornholms Amtsgymnasium.
Søren Pind blev cand.jur. fra Københavns Universitet i 1997.
Søren Pind var lektiehjælper i statsret ved Københavns Universitet fra 1999 til 2005.
Søren Pind er ridder af Dannebrogordenen.
Søren Pind er ridder af Æreslegionen.
Søren Pind blev i 1994 Danmarks yngste borgmester.
Søren Pind fik i 2001 flest personlige stemmer ved valget i Københavns Borgerrepræsentation.
Søren Pind har flere gange markeret sig som støtte for Ronald Reagan og USAs udenrigspolitik.
Søren Pind fik som etårig fjernet højre øje og har glasøje!
Søren Pind er i manges øjne tidernes mest attraktive danske minister.
Søren Pind har erhvervserfaring fra Waterfront Communications.
Søren Pind var med til at skrive de "ti liberale teser".
Søren Pind bliver i Den Korte Radioavis kald for "den enøjede justitshævner".
Søren Pind kaldte som udviklingsminister sit ministerium for "Frihedsministeriet".
Søren Pind og Søren Krarup har sammen skrevet bogen "Kære Søren - en brevveksling om det nye Danmarks kurs"
Silverfoxen Søren Pind var generalkonsul for KulturBornholm i 2002.
Søren Pind er en ven af skoven, da han i perioden 2002-2006 var bestyrelsesmedlem for Vestskovudvalget.
Søren Pinds valgplakat fra 2011 viste ham træde ud af et fly som en verdensmand.
Søren Pind er en hyppig gæst i P4s "Mads og Monopolet".
END_OF_PIND

while (my $line = <>) {
    chomp $line;

    if (rand() < 0.25) {
        my $fact = $facts[rand @facts];
        $line =~ s/(?<=[.?!])/ $fact /;
    }

    say $line;
}
