#!/usr/bin/env perl
use 5.042;
use warnings;
use utf8;
use Env qw/CONCIEGGS_LIB_DIR/;

my %aliases = map { (lc($_) => 1) } split("\n", `allAliases`);

sub preben {
    my $name = shift;

    return $name unless $aliases{lc($name)};

    my @names = qw/Preben Snefred Sigurd/;
    return $names[rand @names];
}

while (my $line = <>) {
    $line =~ s/\b(\S*)\b/preben($1)/ge;

    print $line;
}

