#!/usr/bin/env perl
use v5.14;
use warnings;

sub randpick {
    return $_[rand(@_)];
}

my @muligheder = (
    ', inshallah, ',
    ', alhamdullilah, ',
    ', alahhu akbar, ',
);

while (my $text = <>) {
    $text =~ s/\bt([aeiouyæøå])/tj$1/g;
    $text =~ s/(Jeg|Du)/Wolla \L$1/g;
    $text =~ s/, /rand() < 0.1 ? ' ' : randpick(@muligheder)/eg;
    print $text;
}


