#!/usr/bin/env perl
my @prutfis = ([qw(pr u t)], [qw(f i s)]);
my @skidegodt = split '\n', <<'END_OF_LORT';
Øj, det er godt nok svært at holde sig.
De herrer må have mig undskyldt.
Nu er det snart pølletid.
Har nogen set latrinen?
END_OF_LORT

sub luft {
    my $ekstra = shift;
    my $luft = `dbRead luft_i_maven`;
    chomp $luft;
    $luft += $ekstra;
    `echo $luft | dbWrite luft_i_maven`;
    return $luft;
}

# TODO: concieggs har ikke lært at skide.
sub prutfis {
    return "" if rand() < 0.75;

    my ($pr, $u, $t) = @{$prutfis[rand(@prutfis)]};
    my $luft = luft(5);

    return sprintf("\cC05*%s%s%s*\cC\cB\cB %s", $pr, $u x (1+rand(5)), $t, $luft > 50 ? $skidegodt[rand @skidegodt] . " " : " ");
}

while (<>) {
    s/(?<=[.!?] )/prutfis()/ge;
    print;
}
