#!/usr/bin/env perl
use 5.012;
use warnings;
use utf8::all;
use POSIX;
use List::MoreUtils qw/zip/;

my @rainbow = map { "\cC$_\cB\cB" } qw(04 07 08 09 11 06 13);

while (my $line = <>) {
    chomp $line;

    my $me = ($line =~ m!^/me !);
    $line = substr $line, 4 if $me;

    my $n = ceil(length($line) / @rainbow);
    my $d = length($line) - scalar(@rainbow) * ($n-1);
    my @lens = ( ($n+0) x $d , ($n-1) x (scalar(@rainbow) - $d) );

    my @msg;
    my $i = 0;
    for my $l (@lens) {
        push(@msg, substr($line, $i, $l));
        $i+=$l;
    }

    my $meprefix = $me ? "/me " : "";
    print $meprefix . join("", zip(@rainbow, @msg)) . "\cO\n";
}


