#!/usr/bin/env perl
use 5.042;
use warnings;
use utf8;
use Text::Roman qw(int2roman);

sub romersk {
    my $int = shift;
    return 'nul dut' if $int == 0;
    return int2roman($int) if $int > -4000 && $int < 4000;
    return '∞';

}

while (my $line = <>) {
    chomp $line;
    $line =~ s/(\d)[,.](\d)/$1 komma $2/;
    $line =~ s/(\d+)/romersk($1)/eg;
    $line =~ s/ae/æ/g;
    $line =~ s/u/v/g;
    $line =~ s/U/V/g;
    $line =~ s/([lgrsntd]i)e/$1um/g;
    say $line;
}
