#!/usr/bin/env perl
use 5.012;
use warnings;
use utf8::all;

sub preserve_case($$) {
    my ($old, $new) = @_;
    return $old if (lc($old) eq "skinken" || lc($old) eq "skinkende");
    my $mask = uc $old ^ $old;
    uc $new | $mask .
    substr($mask, 1) x ((length($new) - length($old)) > 0 ? length($new) - length($old) :  length($old) - length($new))
}

while (my $line = <>) {
    $line =~ s/(\w{8,})e[nt]/preserve_case($1, "skinken")/egi;
    $line =~ s/(\w{8,})ske/preserve_case($1, "skinkende")/egi;
    $line =~ s/(\w{9,})/preserve_case($1, "skinke")/egi;
    $line =~ s/\s+$//;
    $line =~ s/\s\s+/ /g;
    $line =~ s/\s+([.,!\?:;\-\"\'])/$1/g;
    say $line;
}
