#!/usr/bin/env perl
use 5.012;
use warnings;
use utf8::all;

sub randpick {
    return $_[rand(@_)];
}

my @categories = (
    [qw(ad af ak al am an at av bi bo by bæ da de dj du dy dø ed eg ej fæ få ha hi ja jo ko kø le li lo ly læ lå mø må ni nu ny næ nå og oh ok om op os pc på er et en ex ud æd æg æv åd åg ål)],
    [qw(jeg du man det han ham hende hun den disse hinanden mig dig mit dit)],
    );

my @symptoms = (
    "får en lammelse i benet",
    "kan ikke synke",
    "får en lammelse i højre side af ansigtet",
    "får det ildebefindende",
    "fråder om munden",
    "kan ikke løfte venstre arm",
    "mister besindelsen",
    "kan ikke længere formulere sætninger",
    );

while (my $line = <>) {
    foreach my $values (@categories) {
        my $pattern = join '|', map(quotemeta, @$values);
        $line =~ s/\b(?:$pattern)\b/randpick(@$values)/egi;
    }

    my @words = split / /, $line;
    my @newwords;
    my $collapse = 0;
    foreach my $word (@words) {
        if (rand(10) < 1) {
            push @newwords, $word;
        }
        if (rand(50) < 1) {
            push @newwords, "øøhhh ... ";
            $collapse = 1;
            last;
        }
        push @newwords, $word;
    }
    $line = join(" ", @newwords );
    if ($collapse)
    {
        say $line;
        say "/me " . randpick(@symptoms);
    } else {
        say $line;
    }
}
