#!/usr/bin/env perl
use 5.012;
use warnings;
use utf8::all;
use Env qw/CONCIEGGS_LIB_DIR/;

my %aliases = map { (lc($_) => 1) } split("\n", `allAliases`);

sub nuserfy {
    my $name = shift;

    return $name unless $aliases{lc($name)};

    my @options = (
        (map { "$name$_" } qw(
            -musen
            -snut
            kins
            pus
            -missen
            -nus
            -kis
            -trut
            .mus
            -skatten
            
        )),
        qw(
            pullernuller
            nullergøj
            skattebasse
            trut
            pillerpaller
            duller
            trunte
            tutternas
            tillernus
            misling
        ),
    );

    return $options[rand @options];
}

while (my $line = <>) {
    $line =~ s/\b(\S*)\b/nuserfy($1)/ge;

    print $line;
}

