#!/bin/sh

while read line; do
    for word in $line; do
        case $(random 0 4) in
            0) echo "$word" | translate dansk engelsk
               ;;
            *) echo "$word"
               ;;
        esac
    done
done
