#!/bin/sh

while read line; do
    for word in $line; do
        case $(random 0 4) in
            0) echo -n "$word" | translate dansk engelsk
               ;;
            *) echo -n "$word"
               ;;
        esac
    done
    echo
done
