#!/usr/bin/env perl
use 5.020;
use strict;
use warnings;
use utf8::all;

sub ej {
    my $word = shift;
    return $word =~ /^[A-ZÆØÅ]/ ? 'Ej ' . lcfirst $word : 'ej $word';
}

while (<>) {
    s/Ja/Nej/g;
    s/ja/nej/g;
    s/Jep/Niks/g;
    s/jep/niks/g;
    s/f(edt|jong)/uf$1/g;
    s/F(edt|jong)/Uf$1/g;

    s/SUCCESS/FAILURE/g;

    s/\ber\s+(jeg|du|vi)\b/er $1 ikke/g;
    s/\bsiger\s+(jeg|du|vi)\b/siger $1 ikke/g;

    s/\ber\b/er ikke/g;
    s/\bskal\b/skal ikke/g;
    s/\bhar\b/har ikke/g;

    s/\bgår\b/går ikke/g;
    s/\bfinder\b/finder ikke/g;
    s/\bslipper\b/slipper ikke/g;
    s/\bsummer\b/summer ikke/g;

    s/\bOK\b/ikke OK/ig;
    s/(forstået|accepteret|godtaget)/ej($1)/ige;
    print;
}
