#!/usr/bin/env perl

use v5.20;
use warnings;
use utf8;

use Encode qw/decode/;
use utf8::all;
my $EGGS_BODY = decode('utf-8', $ENV{EGGS_BODY});

$EGGS_BODY =~ s/(\.|\,)( |$)/punktummer()." "/ge;
print $EGGS_BODY;

sub punktummer {
    my $i = int(rand(2)) + 2;
    return "."x$i;
}

