#!/usr/bin/env perl
use 5.012;
use warnings;
use utf8::all;

# Categories

sub randpick {
    return $_[rand(@_)];
}

my @categories = (
    [qw(Danmark Sverige Finland)],
    [qw(København Roskilde Køge Farum Helsingør Dragør Ringsted Næstved Holdbøk Sorø)],
    [qw(Randers Holstebro Herning Hobro Aalborg Viborg Skagen)],
    [qw(Færøerne Island)],
    [qw(England Irland Skotland Storbritannien Commonwealth)],
    [qw(Hillary Donald Bill George Barack Ronald)],
    [qw(Trump Bush Clinton Reagan Obama)],
    [qw(Søren Jørgen George)],
    [qw(Troels Truls Athas trulsa)],
    [qw(højre venstre)],
    [qw(op ned)],
    [qw(nord syd øst vest)],
    [qw(svag let moderat kraftig)],
    [qw(regn sol overskyet dis syreregn hagl sne isslag)],
    [qw(vind orkan tyfon brise kuling storm stormflod cyklon tornado)],
    [qw(DIKU ITU SDU DTU AAU AU)],
    [qw(datalogi softwareudviking datamatiker)],
    [qw(.com .net .org .dk .co.uk .biz .aero .nu .xxx)],
    [qw(false true)],
    [qw(sandt falsk)],
    [qw(forkert rigtigt)],
    [qw(højre venstre)],
    [qw(første anden tredje fjerde femte sjette syvende ottende niende tiende)],
    [qw(↓ ↑ ← → ↙ ↖ ↘ ↗)],
    [qw(☁ ☀ ☾ ☔ ☁ ☃)],
    [('i dag', 'i morgen', 'i overmorgen', 'i går', 'i forgårs')],
);

# Numbers

sub max {
    my $x = shift;
    my $y = shift;
    return $x > $y ? $x : $y;
}

my $epsilon = 5;

sub cirka {
    my $number = shift;

    # random variation
    my $rand = int(rand() * 2 * $epsilon * 100) / 100;
    my $delta = ($number - int($number) ? $rand : int($rand));
    my $result = $number - $epsilon + $delta;

    # zero-padding
    if ($number =~ /^0/) {
        my $padding = length $number; $padding++ if $result < 0;
        $result = sprintf "%0${padding}d", $result;
    }

    return $result;
}

while (my $line = <>) {
    $line =~ s/(\d+(?:\.\d+)?)/cirka($1)/eg;

    foreach my $values (@categories) {
        my $pattern = join '|', map(quotemeta, @$values);
        $line =~ s/\b(?:$pattern)\b/randpick(@$values)/egi;
    }

    $line =~ s/kr(?:\b|\.|oner)/randpick('kr.', 'dollars', 'bobs')/egi;

    say $line;
}
