#!/usr/bin/env perl
use 5.012;
use warnings;
use utf8::all;

# Categories

sub randpick {
    return $_[rand(@_)];
}

my @categories = (
    [qw(Danmark Sverige Finland)],
    [qw(Færøerne Island)],
    [qw(England Irland Skotland Storbritannien Commonwealth)],
    [qw(Hillary Donald Bill George)],
    [qw(Trump Bush Clinton)],
    [qw(Søren Jørgen)],
);

# Numbers

sub max {
    my $x = shift;
    my $y = shift;
    return $x > $y ? $x : $y;
}

my $epsilon = 5;

sub cirka {
    my $number = shift;

    # random variation
    my $rand = int(rand() * 2 * $epsilon * 100) / 100;
    my $delta = ($number - int($number) ? $rand : int($rand));
    my $result = $number - $epsilon + $delta;

    # zero-padding
    if ($number =~ /^0/) {
        my $padding = length $number; $padding++ if $result < 0;
        $result = sprintf "%0${padding}d", $result;
    }

    return $result;
}

while (my $line = <>) {
    $line =~ s/(\d+(?:\.\d+)?)/cirka($1)/eg;

    foreach my $values (@categories) {
        my $pattern = join '|', map(quotemeta, @$values);
        $line =~ s/$pattern/randpick(@$values)/egi;
    }

    $line =~ s/kr(?:\b|\.|oner)/randpick('kr.', 'dollars', 'bobs')/egi;

    say $line;
}
