#!/usr/bin/env sh

hilsen=$(randomLine <<EOF
Min ven
Kære
Søde
EOF
)

smiley=$(randomLine <<EOF
:)
:-)
(:
(-:
:D
EOF
)

sed -r -e "s/^(.+:)/$hilsen \1/" -e "s/^([^:]+)$/$hilsen $EGGS_WHERE.  \1/" -e "s/\$/  $smiley/"
