#!/usr/bin/env sh

hilsen=$(randomLine <<EOF
Min ven
Kære
Søde
EOF
)

smiley=$(randomLine <<EOF
:)
:-)
(:
(-:
:D
EOF
)

LINE=$(cat -)
echo $LINE | if $(echo $LINE | grep -q ':'); then
  sed -r -e "s/^/$hilsen /" -e "s/\$/ $smiley/"
else
  sed -r -e "s/^/$hilsen $EGGS_WHERE.  /" -e "s/\$/  $smiley/"
fi
