#!/usr/bin/env python
#
# Udskift navneord med andre navneord af samme type.

import sys
import os
import re
import subprocess
from eggsthon import *
import eggsthon.shell as shell


ndir = os.path.join(CONCIEGGS_DB_DIR, 'navneord')
files = [os.path.join(ndir, f) for f in os.listdir(ndir)]

def member_of(w, f):
    try:
        subprocess.check_output(['grep', '-iq', '^' + w + '$', f])
        return True
    except subprocess.CalledProcessError as e:
        return False

def random_word(f):
    with open(f) as s:
        with open(os.devnull) as d:
            return subprocess.check_output(['randomLine'], stdin=s, stderr=d).rstrip().decode('utf-8')

def babble(w):
    for f in files:
        if member_of(w, f):
            w1 = random_word(f)
            if w.isupper():
                w1 = w1.upper()
            elif w[0].isupper():
                w1 = w1[0].upper() + w1[1:]
            return w1
    return w


i = sys.stdin.read().decode('utf-8')
o = re.sub(r'[\w]+', lambda m: babble(m.group(0)), i)
sys.stdout.write(o.encode('utf-8'))
