#!/usr/bin/env python
#
# Udskift navneord med andre navneord af samme type.

import sys
import os
import re
import subprocess
from eggsthon import *
import eggsthon.shell as shell


ndir = os.path.join(CONCIEGGS_DB_DIR, 'navneord')
files = [os.path.join(ndir, f) for f in os.listdir(ndir)]

def member_of(w, f):
    try:
        subprocess.check_output(['grep', '-q', '^' + w + '$', f])
        return True
    except subprocess.CalledProcessError as e:
        return False

def random_word(f):
    with open(f) as s:
        with open(os.devnull) as d:
            return subprocess.check_output(['randomLine'], stdin=s, stderr=d).rstrip()

def babble(w):
    for f in files:
        if member_of(w, f):
            return random_word(f).decode('utf-8')
    return w


i = sys.stdin.read().decode('utf-8')
o = re.sub(r'[\w-]+', lambda m: babble(m.group(0)), i)
sys.stdout.write(o.encode('utf-8'))
