#!/usr/bin/env python
#
# Udskift navneord med andre navneord af samme type.

import sys
import os
import subprocess
from eggsthon import *
import eggsthon.shell as shell


ndir = os.path.join(CONCIEGGS_DB_DIR, 'navneord')
files = [os.path.join(ndir, f) for f in os.listdir(ndir)]

def member_of(w, f):
    try:
        subprocess.check_output(['grep', '-q', '^' + w + '$', f])
        return True
    except subprocess.CalledProcessError as e:
        return False
    
def random_word(f):
    with open(f) as s:
        with open(os.devnull) as d:
            return subprocess.check_output(['randomElement'], stdin=s, stderr=d).rstrip()

def babble(w):
    for f in files:
        if member_of(w, f):
            return random_word(f)
    return w

sys.stdout.write(' '.join(babble(w) for w in sys.stdin.read().rstrip().split(' ')) + '\n')
