#!/usr/bin/env perl
#
# Før: tærte :>>=: \indhold -> ko indhold -- Nu: margrethe :<$>: nytårstale
use IPC::System::Simple qw/capturex/;

exit(1) unless @ARGV == 2;

# (<$>) :: (a -> b) -> m a -> m b
my ($f, $ma) = @ARGV;
print capturex('runoperator', ">>=", $ma, "\\lalalalala -> $f lalalalala");
