#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Crossfade kommandoer.

import sys
import itertools
import eggsthon.shell


# TǑDǑ: Gør lidt tilfældig.
def interleave(xs, ys):
    # har nu to lister af afsluttede sætninger.
    xss = list(itertools.chain(*map(lambda x: x.split(), xs)))
    yss = list(itertools.chain(*map(lambda x: x.split(), ys)))
    zippedsentences = zip(xss, yss)
    i = 0
    ts = []
    for element in zippedsentences:
        ts.append(element)
        i += 1
        i = (i % 2)

    return ' '.join(ts)

print interleave(*[eggsthon.shell.runcmd(*c.split()).split(". ")
                   for c in sys.argv[1:3]])
