#!/bin/sh
#
# Udfør dit sidste udsagn som kommando.

last=$(lastmsg)
set -- $last

if ! [ "$last" ]; then
    echo "$EGGS_USER: Du har ikke sagt noget, som jeg er villig til at afvikle."
elif [ "$1" == "^" ]; then
    echo "$EGGS_USER: A-ha! Den falder jeg ikke for... længere. :("
else
    dbUserDelete "$EGGS_USER" lastmsg
    echo "Udfører $last!"
    runcmd $last
fi
