#!/bin/sh

if [ $# -lt 1 ]; then
    echo "Brug: afeggs <tidspunkt>"
else
    alias=$(randomName $EGGS_USER)
    time=$(dateToTime $1)
    if [ "$time" != "" ]; then
        if [ "$alias" != "" ]; then
           gut=$(isInEggs "$1" "$alias")
            if [ "$gut" == "" ]; then
                echo "$alias spiser alligevel ikke med klokken $1!"
            elif rmFromEggs "$1" "$gut"; then
                echo "Javel! $alias spiser ikke længere med i dag klokken $1!"
            else
                exit 1
            fi
        else
            echo "Jeg kender dig ikke, $EGGS_USER!"
        fi
    else
        echo "Det tidspunkt giver ingen mening!"
    fi
fi
