#!/bin/sh
#
# Afhægt en af concieggs's kroge.

if [ $# -ne 1 ]; then
    echo "Brug: $0 <krog>"
else
    if ! [ "$(aliases "$EGGS_USER")" ]; then
        echo "$EGGS_USER: Beklager, denne kommando er kun for logemedlemmer."
        exit
    fi
    hook=$1
    if isHookDetached "$hook"; then
        echo "$EGGS_USER: $hook er skam allerede afhægtet."
    else
        if [ "$hook" = runcmd ]; then
            if isInBadStanding "$EGGS_USER"; then
                echo "$EGGS_USER: Det tror jeg ikke."
            else
                (echo "$EGGS_USER: ...virkelig?"
                 echo "$EGGS_USER: Du er en mesterlig komiker.  Jeg kan ikke forestille mig, at andre har tænkt på det før dig.  Bravo!"
                 echo "$EGGS_USER: Ja, det lyder som en virkelig god idé."
                 echo "$EGGS_USER: Dig først."
                ) | randomElement
                putInBadStanding "$EGGS_USER"
            fi
        else
            detachHook "$hook"
            echo "$(ack)  Jeg vil se bort fra de anvisninger der evt. måtte optræde under '$hook'."
        fi
    fi
fi
