#!/usr/bin/env python3

import sys
import types
import yfinance as yf


def get_price(ticker):
    """
    Return the last traded price of the asset as a float
    """
    if type(ticker.info['regularMarketPrice']) == type({}):
        return ticker.info['regularMarketPrice']['raw']
    else:
        return ticker.info['regularMarketPrice']
    
def get_quote_currency(ticker):
    """
    Return the currency in which this asset is listed
    """
    return ticker.info["currency"]

if len(sys.argv) < 2:
    exit("Brug: aktiepris <ticker>");

ticker = yf.Ticker(sys.argv[1])
if ticker is None:
    exit("Jeg kunne ikke finde %s" % sys.argv[1]);

print(ticker.info)
price = get_price(ticker)
currency = get_quote_currency(ticker)
print("%s handles til %.2f %s" % (sys.argv[1], price, currency))
