#!/usr/bin/env bash

set -eo pipefail

if [ "$1" == "" ]; then
    echo "Du gør det forkert"
    exit 1
fi

RES=$(curl -s https://query2.finance.yahoo.com/v7/finance/quote --get --data-urlencode "symbols=$1" | \
    jq -e '.quoteResponse.result[0]' | \
    jq -e -r '(.shortName + " koster " + (.regularMarketPrice | tostring) + " " + .currency)')

echo $RES
