#!/bin/bash
URL="http://netradio.radioalfa.dk"
SJOV="$(curl -s -H "Icy-MetaData: 1" ${URL} | head -c16300 | tail -c299 | grep -aho "StreamTitle='.*';" | cut -d "'" -f2)"
echo "Radio Alfa spiller '${SJOV}' lige nu"
