#!/bin/sh
KANAL="$*"
if ! [ "$KANAL" ]; then
    KANAL="Radio Alfa"
fi

SANG=$(whatsPlaying "$KANAL")
sang() {
    randomLine <<EOF
Ih, inde på $KANAL spiller de $SANG.
$KANAL spiller $SANG, lige nu!
Hvis du skulle få lyst, kan du høre $SANG på $KANAL.
Hov! $KANAL spiller jo min yndlingssang; $SANG.
EOF
}

echo "$(sang)"
