#!/usr/bin/env python3

from datetime import datetime
from dateutil import tz
import urllib.request as ur
import xml.etree.ElementTree as ET

from_zone = tz.tzutc()
to_zone = tz.tzlocal()
def date_convert(s):
    """Convert a datetime string from yr.no to datetime object."""
    return datetime.strptime(s, "%Y-%m-%dT%H:%M:%S").replace(tzinfo=from_zone).astimezone(from_zone).time()

with ur.urlopen('https://www.yr.no/place/Denmark/Capital/Copenhagen/forecast.xml') as f:
    tree = ET.parse(f)
root = tree.getroot()

sun = root.find('sun')

sunrise = date_convert(sun.attrib['rise'])
sunset = date_convert(sun.attrib['set'])

now = datetime.now().time()

if (sunrise > now):
    print("I dag står solen op kl. {0} og går ned kl. {1}".format(sunrise, sunset))
elif (sunset > now):
    print("I dag stod solen op kl. {0} og går ned kl. {1}".format(sunrise, sunset))
else:
    print("I dag stod solen op kl. {0} og gik ned kl. {1}".format(sunrise, sunset))
