#!/bin/sh
#
# Hvem er ansvarlig for en given kommando?

if [ $# != 1 ]; then
    echo "Brug: ansvar <kommando>"
fi

eval "$(echo "$@" | parse '^((?<cmd>[^/]+)|eggspi/(?<eggspi>[^/]+)|hooks/(?<hook>[^/]+/[^/]+)|compiled/(?<compiled>[^/]+))$')"

if [ "$cmd" ]; then
    file=$(findCommand $1)
elif [ "$eggspi" ] && [ -f "eggspi/$eggspi" ]; then
    file="$CONCIEGGS_DIR/eggspi/$eggspi"
elif [ "$hook" ] && [ -f "hooks/$hook" ]; then
    file="$CONCIEGGS_DIR/hooks/$hook"
elif [ "$compiled" ] && [ -f "compiled/$compiled" ]; then
    file="$CONCIEGGS_DIR/compiled/$compiled"
else
    echo "$EGGS_USER: Jeg kan ikke afgøre om '$@' overhovedet er et problem."
    annoyedBy "$EGGS_USER"
    exit
fi

if ! [ "$file" ]; then
    echo "$EGGS_USER: Jeg er ikke bekendt med nogen '$1'-kommando."
    exit
fi

guilty=$(git log --pretty=format:"%an" "$file")
first=$(echo "$guilty"|tail -n 1)
last=$(echo "$guilty"|head -n 1)

if ! [ "$guilty" ]; then
    echo "$EGGS_USER: Jeg er ikke i stand til at placere ansvaret nærmere, men jeg mistænker $(recentlyActive | randomElement)"
else
    if [ "$first" = "$last" ]; then
        echo "$EGGS_USER: Ansvaret kan placeres udelukkende hos $first."
    else
        echo "$EGGS_USER: $last har bevirket den sidste ændring, men $first stod bag første udgave."
    fi
fi
