#!/bin/sh
#
# Hvad var det nu deres slogan ikke var, eller ikke skulle være?

if [ $# = 0 ]; then
    echo "$EGGS_USER: Hvis ikke-slogan?"
    exit
fi

prompt=$($CONCIEGGS_DIR/cmds/autoviden "$@")

tries=10
for x in $tries; do
    stuff=$(gpt3 50 "$prompt.  $@s slogan er ikke: \"")
    slogan=$(echo $stuff | sed -n -E 's/[ ]*([^"]*").*/\1/p')
    if [ "$slogan" ]; then
        echo "$EGGS_USER: $@: \"$slogan"
        exit
    fi
done

echo "$EGGS_USER: Beklager, men jeg kan ikke umiddelbart komme på noget."
