#!/bin/sh
#
# Levér fantastisk Apina-link med en snedig og ustyrligt komisk
# kommentar!

kommentar=$(cat $CONCIEGGS_DB_DIR/fakta | sed 's/[.:!?].*//' | grep -v http | sort -R | head -n 1)

linkid() {
    if [ $1 -ne 0 ]; then
        id=$(random 10000 80000)
        if wget --load-cookies db/concieggs_cookies.txt -O /dev/stdout --quiet http://apina.biz/$id | grep -v 'Entry not found' > /dev/null; then
            echo $id
        fi
    fi
}

id=$(linkid 10)

if [ "$id" ]; then
    echo $kommentar: http://apina.biz/$id
else
    echo "Næh, ingen Apina til dig."
fi
