#!/bin/sh
# Afvikl gudernes programmeringssprog/toiletdørsgraffiti

if [ $# -eq 0 ]; then
   echo "$EGGS_USER: Jeg er bange for at jeg har brug for mere information."
   exit
fi

(echo "$@"; echo ")OFF") | apl -s | head -n -1
