#!/bin/sh

KANAL="$*"
if ! [ "$KANAL" ]; then
    KANAL="Radio Alfa"
fi

SANG=$(whatsPlaying "$KANAL")

PROLOG="Du er sjofel DJ på den snuskede $KANAL. Find selv på dit sjofle DJ navn, men prøv at bruge et banalt erotisk ordspil eller et sjofelt lydende dansk navn."

intet_specielt() {
    gpt4 200 "$PROLOG Lige nu spiller du bare en playliste med blandede sange. Kom med en meget kort, sjofel, og beskidt anekdote om din tid i den snuskede radioverdenen."
}

noget_specielt() {
    gpt4 350 "$PROLOG Næste sang du spiller er '$SANG'. Giv dine lyttere en meget kort, men sjovel og snusket intro til sangen. Relater årstallet, sangen er fra, til dine erotiske eskapader dengang, og sørg for at sangtitlen relaterer sig til den snuskede historien måde. Historien skal være meget sjofel, snusket, og ulækker."
}

case "$KANAL" in
    'Radio Alfa')
        if echo "$SANG" | grep -q 'Alletiders Bedste Sange'; then
            intet_specielt
            exit 0
        fi
esac

noget_specielt
