#!/bin/sh

KANAL="$*"
if ! [ "$KANAL" ]; then
    KANAL="Radio Alfa"
fi

SANG=$(whatsPlaying "$KANAL")

gpt4 200 "Du er DJ på $KANAL der skal introducere næste nummer, som er $SANG, og det fortjener da en kvik og lun, men kort, lille bemærkning."
