#!/bin/sh

KANAL="$*"
if ! [ "$KANAL" ]; then
    KANAL="Radio Alfa"
fi

SANG=$(whatsPlaying "$KANAL")

PROLOG="Du er DJ på $KANAL. Find selv på dit DJ navn, men prøv at bruge mellemgamle typiske danske navne."

intet_specielt() {
    gpt4 200 "$PROLOG Lige nu spiller du bare en playliste med blandede sange. Kom med en virkelig, virkelig kort anekdote om din tid i radioverdenen."
}

noget_specielt() {
    gpt4 300 "$PROLOG Næste sang du spiller er '$SANG'. Giv dine lyttere en kvik og lun, men kort, lille intro til sangen. Relater årstallet,sangen er fra, til hvad du lavede dengang."
}

case "$KANAL" in
    'Radio Alfa')
        if echo "$SANG" | grep -q 'Alletiders Bedste Sange'; then
            intet_specielt
            exit 0
        fi
esac

noget_specielt
