#!/bin/sh
#
# Et citat fra en stor personlighed.

if [ $# = 0 ]; then
    echo "$EGGS_USER: Et citat fra hvem?"
    exit
fi

prompt=$($CONCIEGGS_DIR/cmds/autoviden "$@")

tries=10
for x in $tries; do
    stuff=$(gpt3 100 "$prompt.  Et af de mest berømte citater fra $@ er: \"")
    quote=$(echo $stuff | sed -n -E 's/[ ]*([^"”«]*").*/\1/p')
    if [ "$quote" ]; then
        echo "$EGGS_USER: \"$quote - $@"
        exit
    fi
done

echo "$EGGS_USER: Beklager, men jeg kan ikke umiddelbart huske hvad $@ plejede at sige."
