#!/bin/sh
#
# Få concieggs's støtte.

eval "$(echo "$@" | parse '^(?<who>[^ ]+)( nu| så)?( lige)? op( på #(?<kanal>[^ ]+))?$')"

support_user() {
    user="$1"
    randomLine <<EOF
$user: Du har så ret!
$user: Enig!
$user har helt ret.
Fandeme godt sagt, $user!
Prædk det, $user!"
Lyt til $user, han ved hvad han taler om.
EOF
}

support_all() {
    randomLine <<EOF
I har så ret!
Enig!
Alle har helt ret.
Fandeme godt sagt!
Prædk det!
Ved I hvad, I er alle vildt intelligente!
EOF
}

if [ "$who" ]; then
    if [ "$who" = $CONCIEGGS_NAME ]; then
        echo "$EGGS_USER: Det er nu ikke nødvendigt."
        exit
    fi
    {
        if [ "$who" = mig ]; then
            support_user "$EGGS_USER"
        elif [ "who" = os ] || [ "$who" = alle ]; then
            support_all
        fi
    } | {
        if [ "$kanal" ]; then
            sayTo "#$kanal"
        fi
    }
else
    echo "$EGGS_USER: Brug: bak mig op [på #kanal]"
fi
