#!/bin/sh
#
# Få eller giv concieggs's støtte.

eval "$(echo "$@" | parse '^(?<follow>altid |ikke )?(?<who>[^ ]+)( nu| så)?( lige)? op( på #(?<kanal>[^ ]+))?$')"

name=$(randomName "$EGGS_USER")
canonical=$(aliases "$EGGS_USER" | head -n 1)
if [ "$who" ]; then
    if [ "$follow" = "altid" ]; then
        if [ "$name" ] && [ "$who" = "mig" ]; then
            echo "1" | dbUserWrite "$canonical" "support"
            echo "Det skal jeg nok, du er jo mega klog!"
            exit 0
        elif [ "$name" ]; then
            echo "1" | dbUserWrite "$canonical" "support"
            echo "Åhr ja, jeg har faktisk godt lagt mærke til, at $who siger nogle rimelig fornuftige ting."
            exit 0
        else
            echo "Det kender jeg altså ikke $who godt nok til."
            exit 0
        fi
   fi

   if [ "$follow" = "ikke" ]; then
       dbUserDelete "$canonical" "support"
       echo "Nej, du har ret. Jeg skal blive en stor bot, som tænker selvstændigt!"
       exit 0
   fi

   if  [ "$kanal" ]; then
       support "$who" "$kanal"
   else
       support "$who"
   fi
else
    echo "$EGGS_USER: Brug: bak mig op [på #kanal]"
fi
