#!/bin/sh
#
# Run the first argument as a Brainfuck program, with the remaining
# arguments as input.

if [ $# -lt 1 ]; then
    echo "Brug: bf <program>"
else
    prog="$1"
    shift
fi
echo "$prog" | $EGGS_LIB_DIR/eggsbf "$*" | cat -v
