#!/bin/sh
#
# Afvikl første argument som et Brainfuck-program, med de resterende
# argumenter som inddata.


if [ $# -lt 1 ]; then
    echo "Brug: bf <program>"
else
    prog="$1"
    shift
fi
progfile=$(mktemp) || exit 1
echo "$prog" > $progfile
echo $(echo "$@" | bf "$progfile" | cat -v)
rm -f $progfile
