#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Bed concieggs om at finde et potentielt grineren billede
# Ved flere argumenter, kan du søge på specifik sjov.
# Brug concieggs, billedmem <søgetermer> 

import sys
import os
from functools import partial
import itertools
import random
import urllib2
import re
from lxml import html

def run_main(args):

    if (len(args) > 1):
        if args[1] in ["med","omhandlende", "involverende", "om", "about"]:
        	args = args[2:]
        else:
        	args = args[1:]
        args = filter(lambda ord: ord != "og", args)
        specifik = True
        list = specifiktMem(args)
    else:
        specifik = False
        list = urllib2.urlopen("http://imgur.com/hot/viral/")

    content = list.read()
    tree = html.fromstring(content)

    if specifik:
        hits = tree.xpath("//div[@class='post']")
    else:
        hits = tree.xpath("//div[@class='post']")
#    try:
    pick = hits[random.randint(0, (len(hits) - 1))]
    (tekst, link) = behandlHit(pick, specifik)
    print "ha ha det her billede er bare " + kompliment() + " " + smiley()
    print "http:" + link.replace(".jpg","") + ' :  "' + tekst + '"'
#    except:
#	print "Der er ingen inden i imgur som har gidet at lave memer om " +         " og ".join(args)

def behandlHit(hit , Bool):
    if Bool:
        tekst = hit.xpath("./div[@class='hover']/p/text()")[0]
        link = hit.xpath("./a/img/@src")[0]
    else:
        tekst = hit.xpath("./div[@class='hover']/p/text()")[0]
        link = hit.xpath("./a/img/@src")[0]
    return (tekst, link)
def kompliment():
    komplimenter = ["nice" , 
                    "mega nice" , 
                    "super" , 
                    "top", 
                    "utroligt", 
                    "fantastisk", 
                    "kanon" , 
                    "dejligt" , 
                    "hyggeligt" ,
                    "sigende"]
    k = komplimenter[random.randint(0, (len(komplimenter) - 1))]
    return k


def smiley():
    smileyer = [":D" , 
                ":)" , 
                ":x" , 
                ":p" , 
                ":P" , 
                "D:" , 
                ":O" , 
                ";)" , 
                ";*"]
    sm = smileyer[random.randint(0, (len(smileyer) - 1))]
    return sm

def specifiktMem(args):
#skal det være en rigtig slager?

    query = ""
    for arg in args:
	query = query + "+" + arg
    query = query[1:]

    if (random.randint(0,2)):
        query = "http://imgur.com/search/score?q=" + query
    else:
        query = "http://imgur.com/search/relevance?q=" + query
    return urllib2.urlopen(query)


if __name__ == '__main__':
    run_main(sys.argv)
