#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Bed concieggs om at finde et muligvis grineren billede

import sys
import os
from functools import partial
import itertools
import random
import urllib2
import re


def run_main(args):
    list = urllib2.urlopen("http://imgur.com/hot/viral/")
    content = list.read()
    funnyPics = re.findall("i.imgur.com/\w+.jpg" , content)
    pic = funnyPics[random.randint(0, (len(funnyPics) - 1))]

    print "ha ha det her billede er bare " + kompliment() + " " + smiley() + " http://" + pic.replace(".jpg","")


def kompliment():
    komplimenter = ["nice" , 
                    "mega nice" , 
                    "super" , 
                    "top", 
                    "utroligt", 
                    "fantastisk", 
                    "kanon" , 
                    "dejligt" , 
                    "hyggeligt"]
    k = komplimenter[random.randint(0, (len(komplimenter) - 1))]
    return k


def smiley():
    smileyer = [":D" , 
                ":)" , 
                ":x" , 
                ":p" , 
                ":P" , 
                "D:" , 
                ":O" , 
                ";)" , 
                ";*"]
    sm = smileyer[random.randint(0, (len(smileyer) - 1))]
    return sm



if __name__ == '__main__':
    run_main(sys.argv)
