#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Bed concieggs om at finde et potentielt grineren billede
# Ved flere argumenter, kan du søge på specifik sjov.
# Brug concieggs, billedmem <søgetermer> 

import sys
import os
from functools import partial
import itertools
import random
import urllib2
import re
from lxml import html

def run_main(args):

    if (len(args) >= 2):
        specifik = True
        list = specifiktMem(args) 
    else:
        specifik = False
        list = urllib2.urlopen("http://imgur.com/hot/viral/")
    content = list.read()
       
    tree = html.fromstring(content)
    
    if specifik:
        hits = tree.xpath("//div[@class='post-details textbox']")
    else: 
        hits = tree.xpath("//div[@class='post']")

    pick = hits[random.randint(0, (len(hits) - 1))]
    (tekst, link) = behandlHit(pick, specifik)

    print "ha ha det her billede er bare " + kompliment() + " " + smiley()
    print "http:" + link.replace(".jpg","") + ' :  "' + tekst + '"'


def behandlHit(hit , Bool):
    if Bool:
        link = hit.xpath("./a/img/@src")[0]
        tekst = hit.xpath("./a/img/@alt")[0]
    else:
        tekst = hit.xpath("./div/p/text()")[0]
        link = hit.xpath("./a/img/@src")[0]
    return (tekst, link)
def kompliment():
    komplimenter = ["nice" , 
                    "mega nice" , 
                    "super" , 
                    "top", 
                    "utroligt", 
                    "fantastisk", 
                    "kanon" , 
                    "dejligt" , 
                    "hyggeligt" ,
                    "sigende"]
    k = komplimenter[random.randint(0, (len(komplimenter) - 1))]
    return k


def smiley():
    smileyer = [":D" , 
                ":)" , 
                ":x" , 
                ":p" , 
                ":P" , 
                "D:" , 
                ":O" , 
                ";)" , 
                ";*"]
    sm = smileyer[random.randint(0, (len(smileyer) - 1))]
    return sm

def specifiktMem(args):

#skal det være en rigtig slager?
    
    query = ""
    for arg in args[1:]:
        query = query + "+" + arg
    query = query[1:]

    if (random.randint(0,2)):
        query = "http://imgur.com/search/score?q=" + query
    else:
        query = "http://imgur.com/search/relevance?q=" + query
    return urllib2.urlopen(query)


if __name__ == '__main__':
    run_main(sys.argv)
