#!/usr/bin/env python3

import requests
import sys

url = "https://www.bitstamp.net/api/ticker/"
resp = requests.get(url=url)
data = resp.json()
price = data["last"]

print ("Prisen på 1 Bitcoin er " + price + " usd")
