#!/usr/bin/env bash

echo "Læs bare denne indsigtsfulde beretning fra datinglivets frontlinjer: https://www.version2.dk/blog/opraab-til-it-noerderne-smid-tennissokkerne-og-tal-saa-vi-kan-forstaa-det-254054"
