#!/usr/bin/env python3

import requests
import re

url = 'https://www.predictit.org/api/marketdata/markets/5429'

resp = requests.get(url=url)
data = resp.json()

price = data['contracts'][0]['lastTradePrice']

print("Under antagelse om ikke-arbitrage er sandsynligheden for Brexit inden 1/11-2019 {:4.0f} pct.".format(price * 100))
