#!/usr/bin/env python3

import requests
import csv

deathcsv = requests.get('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Deaths.csv')
deathreader = csv.reader(deathcsv.text.splitlines()[1:])
deaths = 0
for row in deathreader:
    deaths += int(row[-1])

confirmedcsv = requests.get('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv')
confirmedreader = csv.reader(confirmedcsv.text.splitlines()[1:])
confirmed = 0
for row in confirmedreader:
    confirmed += int(row[-1])

print('Coronastatus: %d smittede, %d døde' % (confirmed, deaths))
