#!/usr/bin/env python3

import requests
import csv
import random

deathcsv = requests.get('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Deaths.csv')
deathreader = csv.reader(deathcsv.text.splitlines()[1:])
deaths = 0
for row in deathreader:
    deaths += int(row[-1])

confirmedcsv = requests.get('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv')
confirmedreader = csv.reader(confirmedcsv.text.splitlines()[1:])
confirmed = 0
for row in confirmedreader:
    confirmed += int(row[-1])

countries = ['Kina', 'et krydstogskib', 'Sydkorea', 'Japan', 'Italien', 'Singapore', 'Hongkong', 'Iran', 'Amerikas forenede stater', 'Thailand', 'Taiwan', 'Australien', 'Malaysien', 'Tyskland', 'Vietname', 'de Forenede Arabiske Emirater', 'Frankrig', 'Macau', 'Canada', 'det Forenede Kongerige', 'Filippinerne', 'Indien', 'Rusland', 'Spanien', 'Irak', 'Israel', 'Lebanon', 'Sverige', 'Belgien', 'Cambodien', 'Ægypten', 'Finland', 'Nepal', 'Srilanka', 'Schweiz']

print('Coronavirussen har indtil videre slået %d mennesker ihjel og smittet %d. Det svarer til en succesrate på %.2f%%!' % (deaths, confirmed, deaths / confirmed * 100))
print('Du kan hjælpe ved at tage til %s og indånde folks hoste, og derefter hoste på andre mennesker.' % random.choice(countries))
