#!/bin/sh
#
# Byd concieggs op til dans!  Brug: dans

eval "$(echo "$@" | tolower | parse 'på (?<ting>.+)$|til (?<kanal>.+)$')"

if [ "$ting" = roser ]; then
    say "$EGGS_USER: Hrmpf!"
    exit
fi

if [ "$kanal" ]; then
    SANG=$(whatsPlaying "$kanal")
else
    SANG=$(whatsPlaying "alfa")
fi


DM() {
    randomLine <<EOF
DM
Danmarksmesterskabet
EM
Europamesterskabet
VM
Verdensmesterskabet
OL
De olympiske lege
Wimbledon
EOF
}

dans() {
    randomLine <<EOF
dans
danseri
dansning
dancing
tanz-tanz-tanz
danse-dusse-da
disko-gymnastik
livets dans
halbal
EOF
}

smukke() {
    randomLine <<EOF
smukke
elegante
uforståelige
fantastiske
dirtey
rytmiske
frække
EOF
}

trin() {
    randomLine <<EOF
trin
moves
bevægelser
dansetrin
hop
EOF
}

benet() {
    randomLine <<EOF
benet
armen
næsen
foden
fingrene
numsen
EOF
}

frem() {
    randomLine <<EOF
frem
tilbage
i cirkler
EOF
}

pirouette() {
    randomLine <<EOF
pirouette
salto
baglænder
dobbelt salto
dobbelt baglænder
360
EOF
}

tillaeg() {
    randomLine <<EOF

 så
 fint
 drastisk
 overraskende
 stille
EOF
}

abe() {
    randomLine <<EOF
abe
guerilla
giraf
zebra
pingvin
anakonda
okapi
EOF
}

danseart() {
    randomLine <<EOF
tango
salsa
zumba
vals
diskodasko
ballet
cha-cha
samba
foxtrot
quickstep
crowdsurfing
moshing
hiphop
EOF
}

offer() {
    recentlyActive | randomLine
}

svanen() {
    randomLine <<EOF
svanen
hejren
hjejlen
dodoen
pingvinen
EOF
}

robotten() {
    randomLine <<EOF
robotten
en moon walk
klovnen
EOF
}

danser() {
    randomLine <<EOF
flytter$(tillaeg) $(benet) $(frem)
udfolder kroppen i en $(pirouette)
hopper som en $(abe)
går frem, og tilbage, fra side, til side
giver $(offer) en lapdance i en stol
har den bedste tid i sit liv med $(offer)
laver en Swayze og råber "Ingen sætter $(offer) i hjørnet!"
improviserer et par $(danseart)-trin
viser sin $(danseart)-$(danseart)-fusionsdans frem
tager en maske på og laver $(svanen)
følger reglerne i $(danseart) til punkt og prikke
starter på $(danseart), men ender med $(robotten)
laver $(robotten)
EOF
}

Tada() {
    randomLine <<EOF
Tada!
Var det ikke bare flot?
Giv mig nu penge!
Fuld point!
Juhuuu!
Douze points.
Jeg elsker mine fans!
EOF
}

say "$(DM) i $(dans)!"
say "/me sætter et bånd med $SANG i afspilleren."
say "Nu kommer der $(smukke) $(trin)!"
for i in $(seq 1 $(random 5 10)); do
    say "/me $(danser)"
done
say "$(Tada)"
