#!/bin/sh
#
# Fortæl concieggs en anekdote.

randomElement <<EOF
Ja, man er vel ikke født i går!
Nånå, er det med den på?
Hvorledes?  Fortæl, fortæl!
Jo, mange tak da!
Ja, så er det klart man havner i suppedasen.
Ja, men det løste sig jo til syvende og sidst, ikke sandt?
Det tænker jeg også tit på.
Ligesom dengang med Dirch!
Man havde vel set det komme.
EOF
