#!/bin/sh
#
# Fortæl concieggs en anekdote.

randomElement <<EOF
Ja, man er vel ikke født i går!
Nånå, er det med den på?
Hvorledes?  Fortæl, fortæl!
Jo, mange tak da!
Ja, så er det klart man havner i suppedasen.
Ja, men det løste sig jo til syvende og sidst, ikke sandt?
Det tænker jeg også tit på.
Ligesom dengang med Dirch!
Man havde vel set det komme.
Undskyld mit toneleje, men har De dog ingen pli?
Jo, ligesom da efternøleren blev overladt til kogekonen!
Nånå, jeg tror godt at vi kan holde dette inden for disse fire vægge, ikke sandt?
Ja, det kan jo ske, men vi kan vel alle lide stegt flæsk med saucé.
EOF
