#!/usr/bin/env bash

betydninger=$(betydning $1)

if [ "$betydninger" ]; then
    echo "Jeg har fundet følgende definitioner for ordet $1:"
    while IFS= read -r line; do
        echo "  $line"
    done < <(printf '%s\n' "$betydninger")
else
    echo "Jeg kunne ikke finde definition for ordet \"$1.\""
fi
