#!/bin/sh
#
# Bed concieggs foretage et DNS opslag.
# concieggs: dig [@<server>] <name> <record type>

if echo "$1" | grep '^@'; then
    server=$1
    name=$2
    type=$3
else
    server=
    name=$1
    type=$2
fi


if [ ! "$name" ]; then
    echo "Du har ikke angivet hvilket navn jeg skal slå op."
    exit
fi

if [ ! "$type" ]; then
    echo "Du har ikke angivet typen af DNS records du er interesseret i."
    exit
fi

r=`/usr/bin/dig +short $server $name $type`
if [ "$r" ]; then
    echo $r
else
    echo "Den findes altså ikke."
fi
