#!/bin/sh
#
# Bed concieggs foretage et DNS opslag.
# concieggs: dig [@<server>] <name> <record type>

set -e

if echo "$1" | grep '^@'; then
    server=$1
    name=$2
    type=$3
else
    server=
    name=$1
    type=$2
fi


if [ ! "$name" ]; then
    echo "Du har ikke angivet hvilket navn jeg skal slå op."
    exit
fi

if [ ! "$type" ]; then
    echo "Du har ikke angivet typen af DNS records du er interesseret i."
    exit
fi

if [ "$type" == "ledighed" ]; then
    if /usr/sbin/dig $name | grep -q "AUTHORITY: 1"; then
        echo "Den er ledig! Køb køb køb!"
    else
        echo "Den er desværre optaget. Bedre held næste gang!"
    fi

    exit 0
fi

r=$(/usr/sbin/dig +short $server $name $type)
if [ "$r" ]; then
    echo $r
else
    echo "Den findes altså ikke."
fi
