#!/bin/sh
#
# Den er god den her - men du må sandsynligvis ikke bruge den.

if sejNok "$EGGS_USER" || aspirerendeTilAtVæreSejNok "$EGGS_USER"; then
    sh -c "$*"
else
    echo "$EGGS_USER: Beklager, men du er ikke stor nok endnu."
fi
