#!/bin/sh
#
# Dril nogen med de værst tænkelige ord.  Brug: dril <bruger>

user=$1
if ! [ "$user" ]; then
    user=$EGGS_USER
fi

tMonster() {
    randomLine <<EOF
t monster
t uhyre
n øksemorder
t kuglelyn
t gespenst
t genfærd
t spøgelse
n vejleder
EOF
}

farligt() {
    randomLine <<EOF
pejlevognen
Pawel
Cosmin
deadlinen
Andresen
EOF
}

pinligt() {
    randomLine <<EOF
glemt at lyne op
sovs på skjorten
spinat mellem tænderne
EOF
}

randomLine <<EOF
$user: Kig lige bag dig!  Der er e$(tMonster)!!!
Vend dig om, $user!  Jeg kan se e$(tMonster)!!!
Så for pokker, $user!  Nu kommer $(farligt)!!!
Ej $user, du har $(pinligt)!!
EOF

sleep 4

randomLine <<EOF
/me kan ikke holde masken
/me trækker på smilebåndet
/me holder et grin tilbage
EOF

sleep 1

randomLine <<EOF
... Det var bare GAS, $user!
... Det var bare FOR SJOV, $user!
... Jeg laver sjov med dig, $user!
... pwned, $user!
EOF

sleep 2

echo "$user: $(laughter)"
