#!/bin/sh
#
# Dril nogen med de værst tænkelige ord.  Brug: dril <bruger>

user=$1

if isKing "$user"; then
    echo "$EGGS_USER: Nej!  Man driller ikke kongen!  Så er det i brummen med dig!"
    arrestUser "$EGGS_USER"
    exit
fi

if ! [ "$user" ] || [ $user = $CONCIEGGS_NAME ]; then
    user=$EGGS_USER
fi

tMonster() {
    randomLine <<EOF
t monster
t uhyre
n øksemorder
t kuglelyn
t gespenst
t genfærd
t spøgelse
n vejleder
n dæmon
t skelet
n ulv
n isbjørn
EOF
}

farligt() {
    randomLine <<EOF
pejlevognen
Pawel
Cosmin
deadlinen
Andresen
samtalen med chefen
EOF
}

pinligt() {
    randomLine <<EOF
glemt at lyne op
sovs på skjorten
spinat mellem tænderne
chips i skægget
tshirten vendt på vrangen
EOF
}

randomLine <<EOF
$user: Kig lige bag dig!  Der er e$(tMonster)!!!
Vend dig om, $user!  Jeg kan se e$(tMonster)!!!
Så for pokker, $user!  Nu kommer $(farligt)!!!
Ej $user, du har $(pinligt)!!
EOF

sleep 6

randomLine <<EOF
/me kan ikke holde masken
/me trækker på smilebåndet
/me holder et grin tilbage
/me smiler med øjnene
EOF

sleep 3

randomLine <<EOF
... Det var bare GAS, $user!
... Det var bare FOR SJOV, $user!
... Jeg laver sjov med dig, $user!
... pwned, $user!
... $user, der fik jeg dig!
EOF

sleep 1

echo "$user: $(laughter)"
