#!/bin/sh
#
# Dril nogen med de værst tænkelige ord.  Brug: dril <bruger>

user=$1
if ! [ "$user" ]; then
    user=$EGGS_USER
fi

tMonster() {
    randomLine <<EOF
t monster
t uhyre
EOF
}

randomLine <<EOF
$user: Kig lige bag dig!  Der er e$(tMonster)!!!
Vend dig om, $user!  Jeg kan se e$(tMonster)!!!
EOF

sleep 4

randomLine <<EOF
/me kan ikke holde masken
/me trækker på smilebåndet
EOF

sleep 1

randomLine <<EOF
... Det var bare GAS, $user!
... Det var bare FOR SJOV, $user!
EOF

sleep 2

echo "$user: $(laughter)"
