#!/bin/sh
#
# Spørg concieggs om hvor mange mennesker der er blevet dræbt af droner.

echo Droner har indtil videre slået et ukendt antal mennesker ihjel.
echo Du kan hjælpe ved at flyve dit modelfly ind i folk.
