#!/bin/sh
#
# Få concieggs til at slå et uskyldigt dyr ihjel!

if [ $# -eq 0 ]; then
    echo "Dræb hvad?"
    exit
fi

echo -n "$(ack)  Jeg har dræbt "
echo "$@!" | sed -E 's/di([ntg])/Mi\1/g' | sed -E 's/mi([ntg])/di\1/g' \
    | sed -E 's/Mi([ntg])/mi\1/g'
