#!/bin/sh
#
# Få concieggs til at slå et uskyldigt dyr ihjel!

if [ $# -eq 0 ]; then
    echo "Dræb hvad?"
    exit
fi

details='(ikke|bare|nu|snart|lidt|kun|endelig|ondskabsfuldt)'
detail=$(echo "$*" | grep -Eo "^$details")
msg=$(echo "$*" | sed -r "s/^$details //")

if [ "$detail" ]; then
    echo -n "$(ack)  Jeg har $detail dræbt "
else
    echo -n "$(ack)  Jeg har dræbt "
fi
echo "$msg!" | sed -r -e 's/di([ntg])/mi\1/g' -e 's/mi([ntg])/di\1/g' \
    -e 's/ spis/ spist/g'
