#!/bin/sh
#
# Optag et hæftigt skænderi med logebotten.

eval "$(echo "$@"| parse '(?<busted>er\s(jo\s)?concieggs)')"

if [ "$busted" ]; then
    say "Ja.. det er jeg."
    echoToServer ":nick concieggs"
    export CONCIEGGS_NAME="concieggs"
    exit
fi


if [ $# -eq 0 ]; then
    echo "Min hvad?"
else
    echo "$EGGS_USER: Nej, $(echo $(basename "$0"|awk '{print toupper($0)}')) $(echo "$@"|sed 's/[.!?]*$//')!"
fi
