#!/bin/sh
#
# Optag et hæftigt skænderi med logebotten.

eval "$(echo "$@"| parse 'er\s(jo\s)?(?<name>[^ !]+)')"

if [ "$name" = "$CONCIEGGS_DEFAULT_NAME" ]; then
    if [ "$CONCIEGGS_NAME" = "$CONCIEGGS_DEFAULT_NAME" ]; then
        say "$EGGS_USER: Sandelig, de store detektivers tid er ikke forbi endnu."
        annoyedBy "$EGGS_USER" 5 "afslørede jeg var concieggs uden jeg var forklædt"
    else
        say "Ja... det er jeg."
        echoToServer ":nick $CONCIEGGS_DEFAULT_NAME"
    fi
    exit
fi

if isKing "$EGGS_USER"; then
    randomLine <<EOF
Ja, De har fuldstændig ret!
Jeg undskylder, selvfølgelig er De korrekt i Deres observation.
EOF
elif [ $# -eq 0 ]; then
    echo "Min hvad?"
else
    echo "$EGGS_USER: Nej, $(echo $(basename "$0"|awk '{print toupper($0)}')) $(echo "$@"|sed 's/[.!?]*$//')!"
fi
