#!/bin/sh
#
# Lad duen baske rundt.

"$(dirname "$0")"/fluen | while read line; do
    echo "$line" | sed -e 's/fluen/duen/g' \
                       -e 's/Fluen/Duen/g' \
                       -e 's/FLUEN/DUEN/g' \
                       -e 's/fluer/duer/g' \
                       -e 's/summer/basker/g' \
                       -e 's/bøtten/fugleburet/g' \
                       -e 's/krukken/fugleburet/g' \
                       -e 's/ryster/rører/g' \
                       -e 's/har fundet lorten, og/lægger en lort som/'
done
