#!/bin/sh
#
# Lad duen baske rundt.

tempfile="$(mktemp)"

trap 'rm $tempfile' INT QUIT TERM EXIT

sed -e 's/fluen/duen/g' \
    -e 's/Fluen/Duen/g' \
    -e 's/FLUEN/DUEN/g' \
    -e 's/fluer/duer/g' \
    -e 's/summer/basker/g' \
    -e 's/bøtten/fugleburet/g' \
    -e 's/krukken/fugleburet/g' \
    -e 's/ryster/rører/g' \
    -e 's/har fundet lorten, og/lægger en lort som/' \
    < "$(dirname "$0")"/fluen \
    > "$tempfile"

chmod +x "$tempfile"
"$tempfile"
