#!/bin/sh
#
# Meld dig til at spise med på et givent tidspunkt.  Tidspunktet er
# altid i fremtiden, og pt. aldrig mere end 24 timer fremme.  Således
# kan du derfor kun melde dig til spisning i dag eller i morgen.

source $CONCIEGGS_DIR/eggspi.lib

if [ $# -lt 1 ]; then
    echo "Brug: eggsml <tidspunkt> [navn]"
else
    if [ $# -ge 2 ]; then
        username=$2
    else
        username=$EGGS_USER
    fi
    alias=$(randomName $username)
    time=$(dateToTime $1)
    if [ "$time" != "" ]; then
        if [ "$alias" != "" ]; then
            if [ "$(isInEggs $1 $alias)" != "" ]; then
                echo "$alias spiser allerede med $(timeToDate $time)!"
            elif addToEggs "$1" "$alias"; then
                echo "Javel! $alias spiser med $(timeToDate $time)!"
            else
                exit 1
            fi
        else
            echo "Jeg kender ikke $username!"
        fi
    else
        echo "Det tidspunkt giver ingen mening!"
    fi
fi
