#!/bin/sh
#
# Det højeste antal eggs på stribe 

. $CONCIEGGS_DIR/eggspi.lib

if [ $# -eq 1 ]; then
    user="$1"
elif [ $# -eq 0 ]; then
    user="$EGGS_USER"
else
    echo "Brug: antaleggs [navn]"
    exit
fi

n="$($EGGS_LIB_DIR/eggstool.py $EGGS_DIR/slashdotfrokost consecutive "$user")"

if [ "$n" ]; then
    echo "$(randomName "$user") har $n eggs på stribe."
else
    echo "$user har mig bekendt aldrig spist med."
fi
