#!/bin/sh
#
# Meld dig til at spise med på et givent tidspunkt, der angives som et
# klokkeslet.  Tidspunktet kan aldrig være mere end 24 timer fremme
# eller tilbage.  Tidspunkter i fortiden angives ved at præfikse dem
# med en bindestreg.  Således kan du derfor kun melde dig til spisning
# i dag eller i morgen.

source $CONCIEGGS_DIR/eggspi.lib

subscribeToEggs() {
    time=$1
    name=$2
    if [ "$name" ]; then
        if [ $(dateSecs "$time" '+%u') == "1" ]; then
            echo "Det er en mandag!  Der er muligvis FF!"
        fi
        if [ "$(isInEggs $1 $name)" != "" ]; then
            echo "$name spiser allerede med $(timeToDate $time)!"
        elif addToEggs "$1" "$name"; then
            echo "Javel! $name spiser med $(timeToDate $time)!"
        else
            exit 1
        fi
}

checkNextEggs() {
    time=$(nextEggs | head -n 1)
    if [ ! "$time" ]; then
        echo "Ingen har tilmeldt sig Eggs - \
vil du være den første, så brug 'eggsml <tidspunkt>'."
        exit 0
    else
        echo $time
    fi
}

if [ $# -eq 0 ]; then
    time=$(checkNextEggs)
elif [ $# -ge 1 ]; then
    if [ "$(aliases $1)" ]; then
        time=$(checkNextEggs)
        username=$1
    else
        time=$(dateToTime $1)
    fi
fi
if [ ! $time ]; then
    echo "Tidspunktet '$giventime' giver ingen mening!"
    exit 0
fi
if [ $# -ge 2 ]; then
    name=$(randomName $2)
else
    name=$(randomName $EGGS_USER)
fi
if [ ! "$name" ]; then
    echo "Jeg kender ikke $username!"
    exit 0
fi
subscribeToEggs $time $username
