#!/bin/sh
#
# Det højeste antal eggs på stribe 


if [ $# -eq 1 ]; then
    user="$1"
elif [ $# -eq 0 ]; then
    user="$EGGS_USER"
else
    echo "Brug: antaleggs [navn]"
    exit
fi

n="$(eggstool consecutive "$user")"

echo TEST
echo "$n"
echo TEST

if [ "$n" ]; then
    echo "$(randomName "$user") har $n eggs på stribe."
else
    echo "$user har mig bekendt aldrig spist med."
fi
