#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Bed concieggs om at give dig en brugbar nyhed fra INTERNETTET.

import sys
import re
import random
import urllib

from eggsthon.decode_html_entities import decode_html_entities


data = urllib.urlopen('http://ekstrabladet.dk').read()

data = data.split('<div class="article-widget-body">', 1)[1]
data = data.split('<div class="m10px-rl m10px-b">', 1)[0]

boxes = [
    ('<h3>', '<div class="df-clearer"></div>'),
]

matches = []
for a, b in boxes:
    matches.extend(re.findall(a + r'(.+?)' + b, data,
                              re.MULTILINE | re.DOTALL))

def fix(m):
    m = re.sub(r'</?[^>]*>', ' ', m)
    m = m.replace('-\n', '').replace('\n', ' ')
    m = re.sub(r' +', ' ', m)
    m = m.strip()
    u = m.decode('utf-8', errors='ignore')
    t = decode_html_entities(u)
    s = t.encode('utf-8', errors='ignore')
    return s

matches = [fix(m) for m in matches]

if not (len(sys.argv) > 1 and sys.argv[1] == 'alle'):
    match = random.choice(matches)
    print match
else:
    for match in matches:
        print match
