#!/usr/bin/env perl
# -*- coding: utf-8 -*-
#
# Bed concieggs om at give dig en brugbar nyhed fra INTERNETTET.

use 5.020;
use warnings;

use EggsML::EggsPI
    list => [ qw( headlines ) ];

my @headlines = headlines();

if ($0 =~ m/eggstranyhed/) {
    my ($headline1, $headline2);
    my $i = 0;
    do {
        $headline1 = $headlines[rand() * @headlines] =~ s/\s*[:?–].*//r;
        die("Couldn't find headline1") if $i++ > 100;
    } until ($headline1);
    do {
        $headline2 = $headlines[rand() * @headlines] =~ s/.*[:?–]\s*//r;
        die("Couldn't find headline2") if $i++ > 100;
    } until ($headline2);
    say "$headline1: $headline2";
} elsif ($ARGV[0] eq 'alle') {
    say $_ for @headlines;
} else {
    say $headlines[rand() * @headlines];
}
