#!/usr/bin/env perl
use 5.020;
use strict;
use warnings;
use utf8::all;
use experimental qw/smartmatch/;
use IPC::System::Simple qw/systemx capturex EXIT_ANY/;

sub verdenssituationen {
    my $verdenssituationen = `dbRead verdenssituationen`;
    chomp $verdenssituationen;
    return $verdenssituationen;
}

my @tilstande = qw(fred koldkrig verdenskrig);
my $new = $ARGV[0];

if ($new && $new ~~ @tilstande) {
    my $previous = verdenssituationen();
    `echo $new | dbWrite verdenssituationen`;
    print `ack` . "Der var $previous.  Der er nu $new.";
} else {
    printf "Brug: erklær <%s>.", (join '/', @tilstande);
}
