#!/bin/sh

set -e

id="$(basename "$0")_$(ircChannel)"
program="$CONCIEGGS_DB_DIR/adventure"

if bgCmdIsRunning "$id"; then
    if [ "$*" = "DRÆB LORTET" ]; then
        bgCmdKill "$id"
    else
        bgCmdWrite "$id" "$*"
    fi
else
    bgCmdStart "$id" "$program"
fi
