#!/bin/sh

# 'adventure' skal være installeret.

set -e

echo "Munksgaard!  En dag får jeg ram på dig!"
putInBadStanding Munkgsaard
annoyedBy "$EGGS_USER"
echo "Aaargh!"

id="$(basename "$0")_$(ircChannel)"

if bgCmdIsRunning "$id"; then
    if [ "$*" = "DRÆB LORTET" ]; then
        bgCmdKill "$id"
    else
        bgCmdWrite "$id" "$*"
    fi
else
    bgCmdStart "$id" adventure
fi
