#!/bin/sh

# 'adventure' skal være installeret.

set -e

id="$(basename "$0")_$(ircChannel)"

if bgCmdIsRunning "$id"; then
    if [ "$*" = "DRÆB LORTET" ]; then
        bgCmdKill "$id"
    else
        bgCmdWrite "$id" "$*"
    fi
else
    bgCmdStart "$id" adventure
fi
