#!/bin/sh
#
# Hvad var det nu deres slogan var, eller skulle være?

if [ $# = 0 ]; then
    echo "$EGGS_USER: Hvilken film?"
    exit
fi

warm_up_text="Jeg var inde i biografen at se $@, og jeg vil nu \
dele mine tanker om $@ med jer. I kan se, hvad jeg synes om \
den, hvor mange stjerner den fortjener, og hvorfor jeg synes\
det. Jeg synes, at $@ er ";

tries=5
for x in $tries; do
    stuff=$(gpt3 150 "$warm_up_text")
    anmeldelse=$(echo $stuff | sed -E 's/(\s\s+|\.\.+)/ /g' | sed -E 's/(^\s+|\s+$)//g')
    if [ "$anmeldelse" ]; then
        echo $(echo "$EGGS_USER: $anmeldelse"| sed -E 's/\.\.+/./g')
        exit
    fi
done

echo "$EGGS_USER: Beklager, men den har jeg altså ikke set endnu."
