#!/bin/sh
#
# Hvad var det nu deres slogan var, eller skulle være?

if [ $# = 0 ]; then
    echo "$EGGS_USER: Hvilken film?"
    exit
fi

warm_up_text="Filmanmeldelse: Politiken bedømmer film: $@ er ";

tries=5
for x in $tries; do
    stuff=$(gpt3 150 "$warm_up_text")
    anmeldelse=$(echo $stuff | sed -E 's/(\s\s+|\.\.+)/ /g' | sed -E 's/(^\s+|\s+$)//g')
    if [ "$anmeldelse" ]; then
        echo $(echo "$EGGS_USER: $@ er $anmeldelse"| sed -E 's/\.\.+/./g')
        exit
    fi
done

echo "$EGGS_USER: Beklager, men den har jeg altså ikke set endnu."
