#!/bin/sh
# Lad concieggs, med assistance fra et par matriksmultiplikationer, forkorte en sætning."

if [ $# = 0 ]; then
    echo "$EGGS_USER: Men hvad skal jeg dog forkorte?"
    exit
fi

phrase="$@"

shortened="$phrase"

while true; do
    len=$(numchars "$shortened")
    out=$(gpt4 "$len" "Forkort følgende sætning: $shortened")

    if [ $(numchars "$out") -lt $len ]; then
	shortened="$out"
    else
	break
    fi
done

if [ "$shortened" != "$phrase" ]; then
    echo "$EGGS_USER: $shortened"
else
    echo "$EGGS_USER: Jeg kan desværre ikke finde på en kortere måde at udtrykke det på."
fi
