#!/bin/sh
#
# Gotta go fast!

pleasedBy "$EGGS_USER"

if [ $# = 0 ]; then
    (echo "Gotta go fast!";
     echo "Den ska' vær' travl!";
     echo "Det' kram!";
     echo "Macht schell!";
     echo "¡Más rápido!";
     echo "Enormi veloce!";
     echo "Arriba!  Arriba!  Andale!  Arriba!") | randomLine
elif [ $# = 1 -a "$1" = --version ]; then
    futhark --version
else
    file=$(mktemp)
    echo "fun main() = $@" > $file
    if futhark-c "$file" -o "$file.bin" 2>&1; then
        (timeout 10 "$file.bin" 2>&1 && pleasedBy "$EGGS_USER" 10) || echo "$EGGS_USER: Det gik galt."
    fi
    rm -f "$file" "$file.bin"
fi
