#!/bin/sh
#
# Gotta go fast!

pleasedBy "$EGGS_USER"

if [ $# = 0 ]; then
    (echo "Gotta go fast!"
     echo "Den ska' vær' travl!"
     echo "Det' kram!"
     echo "Asti-afsted!"
     echo "Fuld fart fremad!"
     echo "Sømmet i bund!"
     echo "Fuld gas!"
     echo "¡Vamos!"
     echo "Macht schnell!"
     echo "¡Más rápido!"
     echo "Enormi veloce!"
     echo "Arriba!  Arriba!  Andale!  Arriba!"
     echo "Slå turboen til!") | randomLine
elif [ $# = 1 -a "$1" = --version ]; then
    ssh napoleon.hiperfit.dk "futhark-c --version"
else
    if echo "$@" | egrep -q '^(entry|module|type|import|let)'; then
        code="$@"
    else
        code=$(printf 'let main =\n%s' "$*")
    fi

    allthatjazz=$(cat <<EOF
    file=\$(mktemp).fut
    cat > \$file
    futharki "\$file" 2>&1
    rm -f "\$file"
EOF
               )
    (echo "$code" | timeout 10 ssh napoleon.hiperfit.dk "$allthatjazz" && pleasedBy "$EGGS_USER" 10) || echo "$EGGS_USER: Det gik galt."
fi
