#!/bin/sh
#
# Gotta go fast!

pleasedBy "$EGGS_USER"

if [ $# = 0 ]; then
    (echo "Gotta go fast!"
     echo "Den ska' vær' travl!"
     echo "Det' kram!"
     echo "Asti-afsted!"
     echo "Fuld fart fremad!"
     echo "Sømmet i bund!"
     echo "Fuld gas!"
     echo "¡Vamos!"
     echo "Macht schnell!"
     echo "¡Más rápido!"
     echo "Enormi veloce!"
     echo "Arriba!  Arriba!  Andale!  Arriba!") | randomLine
elif [ $# = 1 -a "$1" = --version ]; then
    ssh napoleon.hiperfit.dk "futhark-c --version"
else
    if [ "$1" = -t ]; then
        flags="-t /dev/stdout"
        shift
    fi
    if echo "$@" | egrep -q '^(fun|entry|module|val|type|import|let)'; then
        code="$@"
    else
        code=$(printf 'import "/futlib/math" import "/futlib/array" let main() =\n%s' "$*")
    fi

    allthatjazz=$(cat <<EOF
    file=\$(mktemp).fut
    cat > \$file
    if futhark-c "\$file" -o "\$file.bin" 2>&1; then
        \$file.bin $flags 2>&1
    fi
    rm -f "\$file" "\$file.bin"
EOF
               )
    (echo "$code" | timeout 10 ssh napoleon.hiperfit.dk "$allthatjazz" && pleasedBy "$EGGS_USER" 10) || echo "$EGGS_USER: Det gik galt."
fi
