#!/bin/sh
#
# Informér logen om hvornår den angivne broder først blev indlemmet i
# frokostbroderskabet.

. $CONCIEGGS_DIR/eggspi.lib

if [ $# -eq 1 ]; then
    user=$1
elif [ $# -eq 0 ]; then
    user=$EGGS_USER
else
    echo "Brug: første [navn]"
    exit
fi

sidste=$($EGGS_LIB_DIR/eggstool.py $EGGS_DIR/slashdotfrokost lunches "$user" | last -n 1)

if [ "$sidste" ]; then
    echo $(randomName "$user") spiste første gang med $(timeToDate $sidste).
else
    echo $user har mig bekendt aldrig spist med.
fi
