#!/bin/sh
#
# Find en god Garfield-stribe.  Brug: garfield [emne]

topic="$1"

max_page=$(curl -s "https://www.gocomics.com/search/full_results?category=comic&short_name=garfield&sort=date_desc&terms=$topic" \
               | grep '<a rel="next" class="gc-pagination__item"' \
               | tail -n 1 \
               | cut -d '>' -f 2 \
               | cut -d '<' -f 1)
if ! [ "$max_page" ]; then
    max_page=1
fi
page=$(random 1 $max_page)
url=$(curl -s "https://www.gocomics.com/search/full_results?category=comic&short_name=garfield&sort=date_desc&terms=$topic&page=$page" \
          | egrep -o "<a itemprop='image' class=\"\" href=\"/garfield/[0-9]+/[0-9]+/[0-9]+\"" \
          | randomLine \
          | cut -d '"' -f 4)

if [ "$url" ]; then
    url=https://www.gocomics.com$url
    randomLine <<EOF
$EGGS_USER: Hvad med $url — den er ret skæg :)
$url er bare hygge, $EGGS_USER.
Jeg kan huske da jeg først så $url i det der album.
$url er vist noget for dig, $EGGS_USER.
Jeg kan da ikke benægte at jeg grinede en smule da jeg læste $url :p
EOF
else
    echo "$EGGS_USER: Jeg kunne ikke finde dét."
fi
