#!/bin/sh
#
# Spørg GitHub API'et om ting.
#
# https://docs.github.com/en/rest/reference/repos

case "$1" in
  sprog)
    echo -n "GitHub mener at jeg indtil videre, at jeg er skabt af følgende materialer: "
    curl -s -H "Accept: application/vnd.github.v3+json" \
      https://api.github.com/repos/Athas/EggsML/languages | \
      jq -r 'def percent: . * 10000 | floor / 100;
             add as $total
               | to_entries
               | map("\(.key): \(.value / $total | percent)%")
               | join(", ") + "."'
      ;;
  projekt)
    PROJECT=$2
    curl -s -H "Accept: application/vnd.github.v3+json" \
      "https://api.github.com/repos/$PROJECT/commits" | \
      jq -r \
         '(.[0:5] | map(.commit.author.name) | join(", ")) as $latest5 |
          (.[0] |
              {
                "date": .commit.author.date,
                "name": .commit.author.name,
                "login": .author.login,
                "message": .commit.message,
              })
            | (
                "Senest har \(.name) (\(.login)) lavet en tilføjelse \(.date) med beskeden: \(.message)",
                "Seneste 5 ændringer var foretaget af: \($latest5)"
              )'
    ;;
  *)
    echo "Det kan jeg ikke svare på."
    ;;
esac
