#!/bin/sh
#
# Giv noget til nogen.  Brug: giv TING til BRUGER

eval "$(echo "$@" | tolower | parse '(?<thing>[^ ]+) til (?<user>[^ ]+)|(?<person>[^ ]+) et billede')"

if [ "$person" ]; then
    if [ "$person" = "mig" ]; then
        person=$EGGS_USER
    fi

    img="$(randomImage || echo "Næh. Det vil jeg ikke, nå.")"

    echo "$person: $img"
elif [ "$user" ]; then
    echo "$user" | dbWrite "has_$thing"
    echo "$user har nu $thing!"
else
    echo "Brug: giv TING til BRUGER"
fi
