#!/bin/sh
# Hils pænt på concieggs.

greet=$(basename $0)
echo "Og $greet til dig, $EGGS_USER!"
pleasedBy "$EGGS_USER"

h=$(currentHour)

if checkCooldown "$greet_$EGGS_USER" $((3600*24)); then
    if [ "$greet" = godmorgen -a $h -lt 12 -a $h -gt 6 ]; then
        pleasedBy "$EGGS_USER" 25
    elif [ "$greet" = godaften -a $h -gt 18 -a $h -lt 22 ]; then
        pleasedBy "$EGGS_USER" 25
    elif [ "$greet" = godnat -a \( $h -gt 18 -o $h -lt 3 \) ]; then
        pleasedBy "$EGGS_USER" 25
    fi
fi
