#!/bin/sh
#
# Sig godmorgen til concieggs, agtigt.

randomLine <<EOF
En mår?  $(sayYes)
Mår til frokost?  $(sayNo)
Mår-tergranat, haha.  Hah.  $(tærteKommentar)
Er du måske mårmon?
Det her mårtte jo ske en dag.
Er det nu en god idé?  Mårske?
Er det Mårs dag i dag?
Sikken mårgengry!
Har i hørt at Mårs lov ikke holder længere?
Mår du ha' en go' dag!
EOF
