#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Foretag en søgning på Google.  Kan Google ej hjælpe dig (sker ofte),
# prøv da min 'forklar'-kommando.

import lxml.html
from lxml import etree
import urllib
import urllib2
import sys

results_per_page = 1
query = " ".join(sys.argv[1:])

# Create search URL
search_url = ("http://www.google.com/search?hl=da&ie=UTF-8&q="+urllib.quote(query)
     +"&num="+str(results_per_page)+"&as_qdr=all&safe=off")

# Query google
try:
    request = urllib2.Request(search_url)
    request.add_header("User-Agent", "Mozilla/5.0 (Windows; U; Windows NT "
                       "6.1; he; rv:1.9.2.8) Gecko/20100722 Firefox/3.6.8")
    request.add_header("Referer", "http://www.google.com")
    result = urllib2.urlopen(request)
except Exception as e:
    print "Problem ved forespørgsel til Google"
    sys.exit(-1)

# Parse HTML
try:
    parser = etree.HTMLParser()
    tree = lxml.etree.parse(result, parser)
except:
    print "Fejl underparsing af Googles HTML-kode"
    sys.exit(-1)

# Extract results
result_fields = tree.xpath('//li[@class="g"]')

if len(result_fields) <= 0:
    print "Ingen resultater"
    sys.exit(-1)
    

for field in result_fields:
    try:
        url = field.xpath('div/h3/a[@class="l"]')[0].get('href')
        title = ''.join(field.xpath('div/h3/a[@class="l"]/descendant-or-self::*/text()'))
        print title + " - " + url
    except:
        print "Problem ved udtrækning af søgeresultat fra HTML-parsetræ"
