#!/usr/bin/python

import urllib
import urllib2
import simplejson as json
import sys
import codecs

sys.stdout = codecs.getwriter('mbcs')(sys.stdout)

query = " ".join(sys.argv[1:])

results = 1
url = ('http://ajax.googleapis.com/ajax/services/search/web'
       '?v=1.0&start=0&rsz=' + str(results) + '&q=' + urllib.quote(query))

request = urllib2.Request(url, None, {'Referer': 'http://eggsml.dk'})
response = urllib2.urlopen(request)

results = json.load(response)

first_result = results["responseData"]["results"][0];

#print json.dumps(results, sort_keys=True, indent=4)

print first_result["titleNoFormatting"] + " (" + first_result["url"] + ")"


