#!/usr/bin/python

import urllib
import urllib2
import simplejson as json
import sys

query = " ".join(sys.argv[1:])

results = 1
url = (u'http://ajax.googleapis.com/ajax/services/search/web'
       u'?v=1.0&start=0&rsz=' + str(results) + u'&q=' + urllib.quote(query))

request = urllib2.Request(url, None, {'Referer': u'http://eggsml.dk'})
response = urllib2.urlopen(request)

results = json.load(response)

first_result = results["responseData"]["results"][0];

#print json.dumps(results, sort_keys=True, indent=4)

print unicode(first_result["titleNoFormatting"] + " (" + first_result["url"] + ")")


