#!/bin/sh
#
# Visualisér et stykke datamateriale, for derved at opnå bedre forståelse for dets struktur.

k=$#

if echo "$@" | egrep -vq '^([0-9]+ ?)+$'; then
    echo "$EGGS_USER: Brug: graf heltal1 heltal2 heltal3..."
    exit
fi

echo "$@" | histogram $k
