#!/bin/sh
#
#
# Anmod logebotten om at udtrykke sit velbehag ved en netop ytret morsomhed.

eval "$(echo "$@" | parse 'ad (?<person>[^ ]+)')"

funny=$(echo "$@"|wc -c)

haha="$(laughter $(($funny / 4 + 4)) $funny)"

if [ "$person" ]; then
   echo "$person: $haha"
else
   echo "$haha"
fi

echo

