#!/bin/sh
#
# Er concieggs rodet uklar med nogle suspekte typer?  Så kan det være
# en god idé at lade den gå undercover.


eval "$(echo "$@"| parse '(?<noget>undercover( som (?<navn>[a-zA-Z_]+))?)|(?<krig>i krig m[eo]d (?<alias>[a-zA-Z_]+))')"

if [ "$noget" ]; then
    if ! [ "$navn" ]; then
        navn=`randomLine <<EOF
gytta
verner
snefred
aase
ragnar
benny
svend
minnie
vinnie
christian
esther
arild
mitte
johannes
hanne
birger
bjarke
bjarne
finn
erik
rolf
sune
tage
tormod
edda
dagny
gerda
herdis
nanna
randi
sigurd
abelone
poul_emil
musling
magnhild
maude
ambrosius
bernhard
tordis
EOF`
    fi
    say "Hey, hvad er det derovre?!"
    bruger="$(recentlyActive | head -n 1)"
    if ! [ "$bruger" ]; then
        bruger=nogen
    fi
    echo "/me peger på $bruger."
    (sleep 4; echoToServer ":nick $navn")
elif [ "$krig" ]; then
    ond="$(randomName "$alias")"
    if [ "$ond" ]; then
        god="$(randomName "$EGGS_USER")"
        spilKrig "$god" "$ond"
    else
        echo "$EGGS_USER: Jeg tror ikke helt at $alias er indviet."
    fi
else
    say "Det kan jeg ikke endnu, men du må gerne implementere det."
fi
