#!/bin/sh
#
# Er concieggs rodet uklar med nogle suspekte typer?  Så kan det være
# en god idé at lade den gå undercover.


eval "$(echo "$@"| parse '(?<noget>.+)')"

if [ "$noget" = "undercover" ]; then
  navn=`randomElement <<EOF
gytta
verner
snefred
aase
ragnar
benny
svend
minnie
vinnie
christian
esther
arild
mitte
johannes
hanne
birger
bjarke
bjarne
finn
erik
rolf
sune
tage
tormod
edda
dagny
gerda
herdis
nanna
randi
EOF`
  say "Hey, hvad er det derovre?!"
  bruger="$(recentlyActive | head -n 1)"
  if ! [ "$bruger" ]; then
      bruger=nogen
  fi
  echo "/me peger på $bruger."
  echoToServer ":nick $navn"
fi


if ! [ "$noget" = "undercover" ]; then
    say "Det kan jeg ikke endnu, men du må gerne implementere det."

fi

exit
