#!/bin/sh
#
# Spørg om concieggs har et givent program installeret, eller om revyen
# nogensinde har skrevet en sang på en givet melodi.

if [ "$(ircChannel)" = "#dikurevy" ]; then
    eval "$(echo "$@" | parse '(?<tome>(?:vi|nogen)(?: nogensinde)? skrevet på (?<song>.*?)(?: endnu)?$)')"
    if [ "$song" ]; then
        checkRevueSong "$song"
        exit
    fi
fi

eval "$(echo "$@" | parse '(?<tome>du(?: +det(?: +der)?)? +(?<prog>[^/\s]+))|(?<revy>revyen (?:nogensinde )?skrevet på (?<song>.+?)(?: endnu)?)$')"

if [ "$prog" ]; then
    file=$(which "$(echo "$prog" | tolower)" 2>/dev/null)
    if [ "$file" ]; then
        (
            echo "Jep, det ligger trygt og godt i $file."
            echo "Ja, det ser ud til at være i $file."
            echo "Ja: $file."
            echo "Det ligner $file, så ja."
        )
    else
        (
            echo "Desværre, der må jeg skuffe."
            echo "Det ser ikke sådan ud."
            echo "Hmm... nope."
            echo "Ak, nej, $prog er ikke en del af min værktøjskasse."
            echo "Nej, men har du virkelig brug for det?"
            echo "$prog?  Lyder ubehageligt.  Jeg tror jeg holder mig fra det."
        )
    fi | randomLine
elif [ "$song" ]; then
    checkRevueSong "$song"
elif [ "$tome" ]; then
    echo "Har jeg hvad?  Brug 'har du <program> installeret'."
elif [ "$revy" ]; then
    echo "Har revyen hvad? Brug 'har revyen skrevet på <sang> endnu'."
else
    echo "Har hvem hvad?  Brug 'har du <program> installeret' eller 'har revyen skrevet på <sang> endnu'."
fi
