#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# lad concieggs beregne sha256-hashværdi.
# Du kan også bestemme en specifik hash-funktion som det første argument i dit kald.

import time
import sys
import os
from functools import partial
import itertools
import random
import xml.etree.ElementTree as ET
from lxml import html
import hashlib

def run_main(args):

    if len(args) < 2:
        print "Ork ja, det kunne være %s, hvis jeg var din %s, hva'? VED DIN MOR, AT DU ER KRIMINEL?!" % (nice() , pusher())
    else:
        method = getattr(hashlib, "sha256")
        if args[1] in ["sha1", "sha224", "sha256", "sha384", "sha512", "md5"]:
            method = getattr(hashlib, args[1])
            args = args[1:]

        print "Så lad gå."
        print "concieggs fyrer op..."
        time.sleep(3)
        streng =  " ".join(args[1:])
        m = method()
        m.update(streng)
        print "concieggs blæser røg%s..." % (roegting())
        time.sleep(3)
        print m.hexdigest()
        
def nice():
    grats = [
        "praktisk",
        "lækkert",
        "super cool",
        "belejligt",
        "sweet",
        "opperen",
        "anti-noiren",
        '"all that"',
        "bounce"]
    return grats[random.randint(0, len(grats)-1)]

def pusher():
    grats = [
        "pusher",
        "planteskaffer",
        "gartner",
        '"baker man"',
        '"forbindelse"',
        '"éen, som kender éen"',
        'Dr. Feelgood']

    return grats[random.randint(0, len(grats)-1)]


def roegting():
    grats = [
        "katte",
        "heste",
        "ringe",
        'dildoer',
        'matricer',
        'fugle',
        'drager',
        "blomster",
        "balloner",
        "skyer",
        "alarmer",
        "pikke",
        "signaler",
        "ede medistre",
        "ngentbilleder"]

    return grats[random.randint(0, len(grats)-1)]




def fejl():
    print "Brug 'valuta <beløb> <valutatype> <ord> <valutatype>.'"


if __name__ == '__main__':
    run_main(sys.argv)
