#!/bin/sh
#
# Hent de nyeste ændringer fra https://github.com/Athas/EggsML

cd /eggsml
if [ "$(git pull)" != 'Already up-to-date.' ]; then
    echo 'Jeg har hentet de nyeste ændringer fra https://github.com/Athas/EggsML!'
else
    echo 'Jeg blev bedt om at hente ændringer fra Git, men der var ingen!'
fi
