#!/bin/sh
#
# Få dokumentation til en given kommando (såfremt den dovne slubbert
# der har skrevet kommandoen har husket at dokumentere den).

doc () {
    s=$(cat $1 | docstring)
    if [ "$s" ]; then
        echo "$s"
    else
        w=$(echo $1 | sed 's|.*/cmds/||')
        echo "Kig her: https://github.com/Athas/EggsML/blob/master/concieggs/cmds/$w"
    fi
}

if [ $# -lt 1 ]; then
    if onEggsChannel; then
        echo "Brug 'eggsml' hvis du vil melde dig til spisning, 'neggst' og 'preggs' til at se hvem der spiser med. Forstår du ikke frokost? benyt 'hjælp frokost'"
    else
        echo "Dette er IRC.  Du kan skrive med folk på DIKU og hele verdenen rundt."
    fi
    echo "Vil du have hjælp til en specific kommando, brug da: hjælp <kommando>"
elif [ -f "$CONCIEGGS_DIR/cmds/$1" ]; then
    echo "$1: "
    doc $CONCIEGGS_DIR/cmds/$1
elif [ -f "$CONCIEGGS_DIR/cmds/$(ircChannel)/$1" ]; then
    echo "$1: "
    doc "$CONCIEGGS_DIR/cmds/$(ircChannel)/$1"
else
    echo "Der er ingen kommando ved navn $1.  Prøv eventuelt at skrive 'hjælp' uden nogen argumenter."
fi
