#!/bin/sh
#
# Få dokumentation til en given kommando (såfremt den dovne slubbert
# der har skrevet kommandoen har husket at dokumentere den).


if [ $# -lt 1 ]; then
    echo "Brug: hjælp <kommando>"
elif [ -f "$CONCIEGGS_DIR/cmds/$1" ]; then
    echo "$1: "
    cat $CONCIEGGS_DIR/cmds/$1 | docstring
else
    echo "Der er ingen kommando ved navn $1."
fi
