#!/bin/sh
#
# Få concieggs til at holde sin kæft i ti minutter.

eval "$(echo "$@" | tolower | parse '.*(?<shutUp>[kK][æÆ]+[fF][tT])[!.]*')"

if [ "$shutUp" ]; then
    count=$(echo "$@" |  sed 's/[^!æÆ]*//g' |wc -c)
    duration=$((60*10*$count))
    time=$(($(nowTime) + $duration))

    echo $time | dbWrite shutUpUntil

    echo "$(ack)  Jeg skal nok tie stille (indtil $(timeToDate $time))."
else
    echo "Hold min hvad?"
fi
