#!/bin/sh
#
# Få concieggs til at holde sin kæft i ti minutter.

eval "$(echo "$@" | tolower | parse '.* (?<shutUp>kæft)[!.]*')"

if [ "$shutUp" ]; then
    count=$(echo "$@" |  sed 's/[^!]*//g' |wc -c)
    duration=$((60*10*$count))

    echo $(($(nowTime) + $duration)) | dbWrite shutUpUntil

    echo "$(ack)  Jeg skal nok tie stille."
else
    echo "Hold min hvad?"
fi
