#!/bin/sh
#
# Find på bedre navn eller flet det her med hotburn.

domains="$CONCIEGGS_DB_DIR/DanNet/domain"

# Only use domains with at least three instances.
domain1="$(cut -d'<' -f2 $domains | sort | uniq -c | sort -n | grep -Ev ' [12] ' | sed -E 's/ *[0-9]+ //' | grep -i "$1" | randomLine)"
if ! [ "$domain1" ]; then
    echo Bøøøøøøvs.
    exit
fi
grep -E "<$domain1"'$' $domains | sort -R | head -n 3 | cut -d'<' -f1 | toupper | {
    domain1="$(echo "$domain1" | toupper)"
    read d1i1
    read d1i2
    read d1i3
    d2line="$(cat "$domains" | randomLine | toupper)"
    domain2="$(echo "$d2line" | cut -d'<' -f2)"
    d2i1="$(echo "$d2line" | cut -d'<' -f1)"

    echo "Så I kender godt $domain1, ikke?  Det er sådan $d1i1, $d1i2, $d1i3 — behøver jeg sige mere? ... Men $domain2, det er jo kun $d2i1!"
}
