#!/bin/sh
#
# Bed concieggs-komikeren lave en bait-and-switch-sammenlignings-vits
# der bare SMADRER xD

consonant() {
    echo BCDFGHJKLMNPQRSTVWXZ | cut -b $(random 1 20)
}

vowel() {
    echo AEIOUY | cut -b $(random 1 6)
}

total_fail() {
    echo "Hvad er forskellen på $(consonant)$(vowel) — ej, jeg gider ikke længere."
    randomLine <<EOF
/me smider mikrofonen i hovedet på $(randomName)
/me lægger sig til at sove på den fedtede scene
/me indser at livet ikke er at optræde i Casper Christensens nye natklub
/me kigger ud på publikum, der alle sidder og kigger ned i deres smartphones
/me synes at den akavede pause er vildt sjov
/me giver sig til at skrive vitser for Andreas Bo i stedet
/me tager tilløb til en omgang grænseoverskridende crowd work
/me fortryder at det er i dag han optager til DVD'en
/me laver en pludselig og meget spøjs posering
/me går over til scenetæppet og finder en guitar frem i stedet
/me checker lige sin insta
EOF
}

Fuck() {
    ting="$*"
    randomLine <<EOF
For søren, $ting!
Nej, nej, $ting, nej-nej-nej ...
Ha!
Ha!  Haaah.
$ting er bare _fjollet_.
$ting, alligevel ...
Det var sgu på tide nogen sagde det!
Har jeg ret eller hvad?
EOF
}

danNetEntries hyponymOf 2 "$1" | {
    eval $(readMany over under0 under1) || exit 1
    randomLine <<EOF
/me laver et hot burn!
/me laver standupper-fagter
Hey, nu skal nogen ned med nakken.
For. Satan.
HVA SÅ DANMARK
.. men så slog det mig:
Ej, I skal lige have en lille lun éen:
EOF
    echo "Hvad er forskellen på $under0 og $under1?  Det ene er $over — og det andet er $under0!  $(Fuck $under0)"
} || total_fail
