#!/bin/sh
#
# Spørg om din gæld til frokostkassen, eller få hjælp til diverse
# personlighedsfremmende gøremål.  Brug naturligt sprog.
eval "$(echo "$@" | parse \
'skylder (?<debtor>[^ ]+)$|'\
'har (?<debtor>[^ ]+) til gode$|'\
'spiller de( [^ ]+)? (på|hos|ved|i) (?<channel>.+)$|'\
'er balancen på ([Bb]itcoinadressen )?(?<btc>[^ \?]+)|'\
'er status på (?<txid>[^ \?]+)|'\
'(?<whatis>er (?<subject>.+))$|'\
'(?<missing>mangler jeg)$|'\
'(?<wtf>hulen)$|'\
'(?<status>så)$|'\
'(?<definition>betyder (?<word>[^ ]+))$|'\
'(?<meaning>mener (?<who>[^ ]+) med (?<what>[^ ]+)$)|'\
'hedder (?<githubname>[^ ]+) på GitHub|'\
'sker der i (?<kodeprojekt>[^ ]+)[ -]land|'\
'(?<version2>((?:hulen|satan) )?sker der (lige (nu )?)?(på|for) (det dersens )?([Vv]ersion2|v2)(\.dk)?)|'\
'(?<happening>(sker der( lige)?|mener du))|'\
'(?<kingname>hedder kongen)|'\
'(står (?<forkortelse>[^ ]+) for)|'\
'(?:lytter (?<listener>[^ ]+) til(?: lige nu)?)|'\
'(blev der af (?<fate>[^ ]+))')"

if [ "$whatis" ]; then
  eval "$(echo "$subject" | parse '(?<betalingsbalancen>betalingsbalancen)|(?<klokken>klokken)|(?<yourproblem>dit problem(?: med (?<problem>.+))?$)')"

  if [ "$betalingsbalancen" ]; then
    balance="$(lookupBalance)"
    if [ "$(echo "$balance" | grep "-")" ]; then
        echo "Uha, samlet set er der en gæld på $balance kroner."
    else
        echo "Spiser I slet ingen ting? EggsML har et samlet overskud på $balance kroner."
    fi
    exit

  elif [ "$klokken" ]; then
      if [ $(date +%H%M) = 1337 ]; then
          echo 'KLOKKEN ER LEET!!!'
      else
          echo "Den lille viser peger på $(talord $(($(date +%l) % 12))), den store på $(talord $(($(date +%M | tr 0 ' ')))), og den helt lille på $(talord $(($(date +%S | tr 0 ' '))))."
      fi
    exit
  elif [ "$yourproblem" ]; then
    githubIssue "$problem"
    exit
  else
    runcmd jeopardy "hvad er $subject"
    exit
  fi
fi

if [ "$channel" ]; then
    runcmd alfa "$channel"
    exit
fi

if [ "$debtor" ]; then
    if [ "$debtor" = "jeg" ]; then
        alias=$(randomName "$EGGS_USER")
    else
        alias=$(randomName "$debtor")
    fi
    if [ ! "$alias" ]; then
        echo "Jeg kender ikke $debtor."
        exit
    fi


    debt="$(lookupDebt "$alias")"

    if [ "$debt" ]; then
        if [ "$(echo "$debt" | grep "-")" ]; then
            echo "$alias har $(echo $debt | sed 's/-//') kr. til gode i frokostkassen!"
        else
            wish=$(eggstool wishes | randomLine)
            wish_str=""
            if [ "$wish" ]; then
                wish_str=" $(Du $alias Vedkommende) kunne overveje at købe $wish."
            fi
            echo "$(Du $alias) skylder $debt kr. til frokostkassen! $wish_str"
        fi
    else
        echo "Fejl ved beregning af gæld for $alias"
    fi
elif [ "$time" ]; then
    echo "Den lille viser peger på $(($(date +%l) % 12)), den store på $(($(date +%M))), og den helt lille på $(($(date +%S)))."
elif [ "$happening" ]; then
     echo -n "$EGGS_USER: "
     (echo "Ja, det må du nok sige."
      echo "Verden er af lave."
      echo "Det var aldrig sket førhen."
      echo "Og hvor er politikerne, må man spørge!"
      echo "Det hører ingen steder hjemme."
     ) | randomLine
elif [ "$status" ]; then
        reaktion
elif [ "$definition" ]; then
    description="$(betydning "$word")"
    if [ "$description" ]; then
        echo "$EGGS_USER: Det betyder blandt andet det her:"
        echo "$description" | randomLine
    else
        echo "$EGGS_USER: Jeg kunne ikke finde nogen betydning for det ord."
    fi
elif [ "$missing" ]; then
    echo "Du mangler $(randomLine < "$CONCIEGGS_DB_DIR/ordbog-dansk-navneord")!"
elif [ "$wtf" ]; then
    behaviour=$(dbRead filterchain)
    user_behaviour=$(dbRead "filterchain_$EGGS_USER")
    channel_behaviour=$(dbRead "filterchain_$(ircChannel)")
    if [ "$user_behaviour" = "$channel_behaviour" ]; then
        unset $channel_behaviour
    fi
    if [ "$behaviour" ]; then
        echo -n "Mit kulturelle islæt er $behaviour."
        if [ "$user_behaviour" ]; then
            echo " Men for din skyld er jeg også $user_behaviour."
        elif [ "$channel_behaviour" ]; then
            echo " Men i disse kamre forsøger jeg passe ind ved $channel_behaviour."
        else
            echo
        fi
    elif [ "$user_behaviour" ]; then
        echo "$EGGS_USER: Som forespurgt, så behandles du efter normerne for $user_behaviour."
    elif [ "$channel_behaviour" ]; then
        echo "$EGGS_USER: Skik følge eller land fly, og i dette land er normen $channel_behaviour."
    else
        echo "$EGGS_USER: Hvad er det helt præcist, der forvirrer dig?  Min adfærd er ganske konventionel."
    fi
    exit
elif [ "$meaning" ]; then
    if [ "$who" = du -o "$who" = "$irc_username" ]; then
        runcmd hjælp "$what"
    else
        if [ "$who" = jeg ]; then
            alias=$(randomName "$EGGS_USER")
        else
            alias=$(randomName "$who")
        fi
        if [ ! "$alias" ]; then
            echo "$EGGS_USER: '$who' er ikke at finde i logeprotokollen."
            exit
        fi
        cmdalias=$(cmdAlias "$alias" "$what")
        if [ "$cmdalias" ]; then
            if [ "$who" = jeg ]; then
                echo "$EGGS_USER: Med '$what', regner jeg naturligvis med at du mener '$cmdalias'."
            else
                echo "$EGGS_USER: Skulle $alias ytre '$what', så antager jeg naturligvis at han mener '$cmdalias'."
            fi
        else
            echo "$EGGS_USER: Ganske som det står skrevet."
        fi
    fi
elif [ "$githubname" ]; then
    if [ "$githubname" = jeg ]; then
        name=$(dbUserRead "$EGGS_USER" githubname)
        if [ "$name" ]; then
            echo "$EGGS_USER: $(Du "$EGGS_USER") hedder sørme '$name'!"
        else
            echo "$EGGS_USER: $(Du "$EGGS_USER") hedder da vist ikke noget.  Fortæl mig det med 'jeg hedder NAVN på GitHub'."
        fi
    else
        name=$(dbUserRead "$githubname" githubname)
        if [ "$name" ]; then
            echo "$EGGS_USER: $(randomName "$githubname") hedder sørme '$name'!"
        else
            echo "$EGGS_USER: $(randomName "$githubname") ser ikke ud til at hedde noget."
        fi
    fi
elif [ "$kingname" ]; then
    name="$(dbRead eggsking)"
    kingname="$(dbRead eggskingname)"

    if [ "$name" ] && [ "$kingname" ]; then
        echo "$EGGS_USER: Kongens royale navn er naturligvis H.M. ${kingname}, også kendt under det borgerlige navn $(randomName "$name")!"
    else
        echo "$EGGS_USER: Gisp! Det ser ikke ud til at Majestæten har noget royalt navn!"
    fi
elif [ "$forkortelse" ]; then
    ordene="$(falskForkortelse "$forkortelse")"
    randomLine <<EOF
$EGGS_USER: $forkortelse står da vist for $ordene.
$forkortelse, $EGGS_USER?  Det er helt sikkert $ordene!
Den er nem, $EGGS_USER, for $forkortelse er bare kort for $ordene.
EOF
elif [ "$kodeprojekt" ]; then
    latestGitNews "$kodeprojekt"
elif [ "$fate" ]; then
    eggstool fate "$fate"
elif [ "$listener" ]; then
    if [ "$listener" = "jeg" ]; then
        listener="$EGGS_USER"
    fi
    alias="$(randomName "$listener")"
    if [ ! "$alias" ]; then
        echo "Jeg kender ikke $listener."
        exit
    fi

    lastfm_username="$(dbUserRead "$listener" "lastfmname")"
    if [ ! "$lastfm_username" ]; then
        echo "$EGGS_USER: Jeg ved ikke hvad $listener hedder på last.fm."
        exit
    fi

    listening_to="$(currentlyScrobbling "$lastfm_username")"
    if [ ! "$listening_to" ]; then
        echo "$EGGS_USER: $alias lytter ikke til noget lige nu."
        exit
    fi

    echo "$EGGS_USER: $alias lytter til $listening_to lige nu."
    exit

elif [ "$btc" ]; then
    $(echo "$btc" | egrep -q '^tb1[0-9A-Za-z]+' || echo "$btc" | egrep -q '^[n|m|2][0-9A-Za-z]+' ) && json=$(curl -s "https://blockstream.info/testnet/api/address/$btc")
    $(echo "$btc" | egrep -q '^bc1[0-9A-Za-z]+' || echo "$btc" | egrep -q '^[1|3][0-9A-Za-z]+' ) && json=$(curl -s "https://blockstream.info/api/address/$btc")

    if [ "$json" ]; then
        btc_balance=$(echo "$json" | jq '.chain_stats | .funded_txo_sum - .spent_txo_sum')
    fi

    if echo $btc_balance | egrep -q '^[0-9]+$'; then
        echo "$EGGS_USER: Balancen på den adresse er $btc_balance satoshi."
        exit
    fi

    (echo "$EGGS_USER: Det kan jeg ikke svare dig på."
     echo "$EGGS_USER: Det må Bitcoin-vejrguderne vide."
     echo "$EGGS_USER: Den er vist steget 10.000% siden i morges!"
    ) | randomLine

elif [ "$txid" ]; then
    if echo "$txid" | egrep -q '[0-9a-fA-F]{64}'; then
        sc_mainnet=$(curl -s -o /dev/null -w "%{http_code}" --connect-timeout 1 "https://blockstream.info/api/tx/$txid")
        sc_testnet=$(curl -s -o /dev/null -w "%{http_code}" --connect-timeout 1 "https://blockstream.info/testnet/api/tx/$txid")
        [ $sc_mainnet -eq 200 ] && json=$(curl -s "https://blockstream.info/api/tx/$txid") && net="mainnet"
        [ $sc_testnet -eq 200 ] && json=$(curl -s "https://blockstream.info/testnet/api/tx/$txid") && net="testnet"
        if [ -z "$json" ]; then
            echo "Den transaktion kender jeg desværre ikke."
            exit 0
        fi
    else
        echo "Det transaktions-id ser ikke gyldigt ud"
        exit 1
    fi
    confirmed=$(echo "$json" | jq '.status.confirmed')
    if [ "$confirmed" = "true" ]; then
        block_number=$(echo "$json" | jq '.status.block_height')
        msg="Transaktionen er bekræftet i blok nummer $block_number på $net."
    else
        msg="Transaktionen er endnu ikke bekræftet, men ligger i mempool på $net."
    fi
    echo "$msg"

elif [ "$version2" ]; then
    version2Debat | {
        read author
        read title
        read summary_line
        read url
        HvadSoeren=$(randomLine <<EOF
Hvad søren
Vilde milde
Jeg ved ikke hvad jeg skal sige
Så for den da
Uha og lala
Ajajaij
EOF
                  )
        etDebatindlaeg=$(randomLine <<EOF
et debatindlæg
en rant
noget prut
noget tankevækkende
en kommentar
efterfølgeren til Magna Carta
sit livsværk
et sandt svendestykke
EOF
)
        echo "$EGGS_USER: $HvadSoeren, $author har skrevet $etDebatindlaeg med titlen \"$title\" på $url hvor der blandt andet står:"
        echo '"'"$summary_line"'"'
    }
else
    randomLine <<EOF
$EGGS_USER: Hmm, det er e$(tPattedyr).
$EGGS_USER: E$(tPattedyr) så vidt jeg ved.
Måske e$(tPattedyr), $EGGS_USER?
Den er svær, $EGGS_USER, men det minder mig om dengang med $(frase bestemt).
$EGGS_USER: Det er $(frase ubestemt).
EOF
    exit
fi
