#!/bin/sh
#
# Spørg om din gæld til frokostkassen


if [ $# -eq 2 -a "$1" = "skylder" -a '(' "$2" = "jeg" -o "$2" = "jeg?" ')' ]; then
    user=$EGGS_USER
elif [ $# -eq 2 -a "$1" = "skylder" ]; then
    user=$2
elif [ "$*" = "er klokken?" ]; then # påskeæg
    date +%H:%M:%S
    exit
else
    echo "Brug: hvad skylder [navn|jeg]"
    exit
fi

alias=$(randomName "$user")
if [ ! "$alias" ]; then
    echo "Jeg kender ikke $user"
    exit
fi

debt="$(lookupDebt "$user")"

if [ "$debt" ]; then
    if [ "$(echo "$debt" | grep "-")" ]; then
        echo "$alias har $(echo $debt | sed 's/-//') kr. til gode i frokostkassen!"
    else
        wish=$(eggstool wishes | randomElement)
        echo -n "$alias skylder $debt kr. til frokostkassen!  "
        if [ "$wish" ]; then
            if [ "$2" = jeg ]; then
                echo -n "Du "
            else
                echo -n "Vedkommende "
            fi
            echo "kunne overveje at købe $wish."
        else
            echo
        fi
    fi
else
    echo "Fejl ved beregning af gæld for $user"
fi
