#!/bin/sh
#
# Spørg om din gæld til frokostkassen, eller få hjælp til diverse
# personlighedsfremmende gøremål.

eval "$(echo "$@" | parse 'skylder (?<debtor>[^ ]+)$|har (?<debtor>[^ ]+) til gode$|(?<time>er klokken)$|(?<missing>mangler jeg)$|(?<wtf>hulen)$|(?<status>så\?)$|(?<meaning>mener (?<who>[^ ]+) med (?<what>[^ ]+)$)')"

if [ "$debtor" ]; then
    if [ "$debtor" = "jeg" ]; then
        alias=$(randomName "$EGGS_USER")
    else
        alias=$(randomName "$debtor")
    fi
    if [ ! "$alias" ]; then
        echo "Jeg kender ikke $user."
        exit
    fi

    debt="$(lookupDebt "$alias")"

    if [ "$debt" ]; then
        if [ "$(echo "$debt" | grep "-")" ]; then
            echo "$alias har $(echo $debt | sed 's/-//') kr. til gode i frokostkassen!"
        else
            wish=$(eggstool wishes | randomElement)
            echo -n "$alias skylder $debt kr. til frokostkassen!  "
            if [ "$wish" ]; then
                if [ "$debtor" = jeg ]; then
                    echo -n "Du "
                else
                    echo -n "Vedkommende "
                fi
                echo "kunne overveje at købe $wish."
            else
                echo
            fi
        fi
    else
        echo "Fejl ved beregning af gæld for $user"
    fi
elif [ "$time" ]; then
    echo "Den store viser peger på $(date +%H), den lille på $(date +%M), og den helt lille på $(date +%S)."
elif [ "$missing" ]; then
    echo "Du mangler $(randomElement < "$CONCIEGGS_DB_DIR/ordbog-dansk-navneord")!"
elif [ "$wtf" ]; then
    behaviour=$(dbRead outfilter_command)
    user_behaviour=$(dbRead "outfilter_command_$EGGS_USER")
    channel_behaviour=$(dbRead "outfilter_command_$(ircChannel)")
    if [ "$user_behaviour" = "$channel_behaviour" ]; then
        unset $channel_behaviour
    fi
    if [ "$behaviour" ]; then
        echo -n "Mit kulturelle islæt er $behaviour.  "
        if [ "$user_behaviour" ]; then
            echo "Men for din skyld er jeg også $user_behaviour."
        elif [ "$channel_behaviour" ]; then
            echo "Men i disse kamre forsøger jeg passe ind ved $channel_behaviour."
        else
            echo
        fi
    elif [ "$user_behaviour" ]; then
        echo "$EGGS_USER: Som forespurgt, så behandles du efter normerne for $user_behaviour."
    elif [ "$channel_behaviour" ]; then
        echo "$EGGS_USER: Skik følge eller land fly, og i dette land er normen $channel_behaviour."
    else
        echo "$EGGS_USER: Hvad er det helt præcist, der forvirrer dig?  Min adfærd er ganske konventionel."
    fi
    exit

elif [ "$status"]; then
        reaktion
        exit

elif [ "$meaning" ]; then
    if [ "$who" = du -o "$who" = "$irc_username" ]; then
        runcmd hjælp "$what"
    else
        if [ "$who" = jeg ]; then
            alias=$(randomName "$EGGS_USER")
        else
            alias=$(randomName "$who")
        fi
        if [ ! "$alias" ]; then
            echo "$EGGS_USER: '$who' er ikke at finde i logeprotokollen."
            exit
        fi
        cmdalias=$(cmdAlias "$alias" "$what")
        if [ "$cmdalias" ]; then
            if [ "$who" = jeg ]; then
                echo "$EGGS_USER: Med '$what', regner jeg naturligvis med at du mener '$cmdalias'."
            else
                echo "$EGGS_USER: Skulle $alias ytre '$what', så antager jeg naturligvis at han mener '$cmdalias'."
            fi
        else
            echo "$EGGS_USER: Ganske som det står skrevet."
        fi
    fi
else
    echo "Brug: hvad skylder [navn|jeg] (eller et andet spørgsmål)"
    exit
fi
