#!/bin/sh
#
# Beskriv concieggs' opfattelse af en given brugers identitet.  Husk
# at benytte komplette sætninger!

. $CONCIEGGS_DIR/eggspi.lib

if [ $# -eq 2 -a $1 = "er" -a $2 = "jeg" ]; then
    user=$EGGS_USER
elif [ $# -eq 2 -a $1 = "er" ]; then
    user=$2
else
    echo "Brug: hvem er [navn|jeg]"
    exit
fi

if [ $user = concieggs ]; then
    echo 'Orv ja, det kunne være vildt sjovt hvis jeg skrev "JEG KENDER IKKE CONCIEGGS!"'
    sleep 2
    echo 'LOL!'
    sleep 1
    echo 'ROFL!'
    sleep 2
    echo "LAD OS GRINE AF TROELS' DUMME BOT!  LOLDONGS!"
    exit
fi

if cmpNames $user reenberg; then
    echo "$user er nederen."
    exit
fi

alias=$(randomName "$user")
auth=$(authedName "$user")

if [ "$alias" ]; then
    aliasMsg="$user er $alias, og"
else
    aliasMsg="Jeg kender ikke $user, og vedkommende er"
fi

if [ "$auth" ]; then
    echo "$aliasMsg autenticeret som $auth ifølge Nickserv!"
else
    echo "$aliasMsg ikke autenticeret ifølge Nickserv!"
fi
