#!/bin/sh
#
# Hvem, hvad, hvor -- ingen ved det!

eval "$(echo "$@" | parse '(?<jeopardy>er .+)|'\
'(?<folkevalg>stemte|stemmer (?<bruger>[^ ]+) på)')"

if [ "$jeopardy" ]; then
    runcmd jeopardy "$0" "$@"
elif [ "$folkevalg" ]; then
    if [ "$bruger" = 'du' ]; then
        randomLine <<EOF
$EGGS_USER: På $(electee)!
$EGGS_USER: Jeg stemmer da på $(electee).
$(electee) er den eneste der kan lede nationen fremad, $EGGS_USER!
EOF
    else
        randomLine <<EOF
$EGGS_USER: $bruger stemmer sikkert på $(electee)!
$EGGS_USER: $bruger har nok set sig varm på $(electee).
$EGGS_USER: Jeg så $bruger stå i stemmeboksen og sætte kryds ud for $(electee).
Uha, det tør jeg ikke sige.  Men det var jo nok $(electee)...
EOF
    fi
else
    echo "Øhbøh."
fi
