#!/bin/sh
#
# Spørg hvor mange ...

factor=`randomLine <<EOF
millioner
tusinde
milliarder
tusindedele
hundrededele
EOF`

eval "$(echo "$@" | parse '^ *((?<gammel>(gammelt?|ungt?|lang tid|længe))|(?<lang>(langt?|kort|højt?|lavt?))|(?<charmerende>charmerende)|(?<tung>(tungt?|let))|(?<klog>(dumt?|klogt?|stupid))|(?<stor>(stort?|lille|meget))|(?<irriterende>(irriterende|udmattende|enerverende|trættende))|(?<grim>(grimt?|ulækkert?|monstrøst?|klamt?))).*')"

if [ "$gammel" ]; then
    unit=$(randomLine <<EOF
år
dage
sekunder
livstider
uger
måneder
EOF
)
elif [ "$lang" ]; then
    unit=$(randomLine <<EOF
centimeter
millimeter
kilometer
meter
Planck-distancer
kussehår
skægstubbe
fod
lysår
EOF
)
elif [ "$tung" ]; then
       unit=$(randomLine <<EOF
kilo
gram
ton
skæppepund
din mor
EOF
)
elif [ "$klog" ]; then
       unit=$(randomLine <<EOF
gange så klog som Brainfuck
gange så dum som John Strand
gange så klogdum som Troels
EOF
)
elif [ "$stor" ]; then
       unit=$(randomLine <<EOF
kubikmeter
brændestakke
kubikfod
rummeter
iPads
din mor
EOF
)
elif [ "$irriterende" ]; then
       unit=$(randomLine <<EOF
gange så irriterende som kode der fejler
gange så udmattende som din mor
EOF
)
elif [ "$grim" ]; then
       unit=$(randomLine <<EOF
gange grimmere end dig selv
gange pænere end fingermaling
EOF
)
elif [ "$charmerende" ]; then
  ppCharmen
  exit 0
fi

if [ "$unit" ]; then
    echo "$EGGS_USER: $(random 2 1337) $factor $unit!"
else
    evalIn() {
        read text
        eval "echo $text"
    }

    randEval() {
        randomLine | evalIn
    }

    her() {
        randEval <<"EOF"
ved siden af $(tingen)
ovenpå $(tingen)
EOF
    }

    tingen() {
        randEval <<"EOF"
DIKU
HCØ
Duniyas
Dilans
Oasen
Toves
Biocenteret
Rundetårn
Tivoli
Nørreport
den ting der er $(her)
de ting der ligner at de er $(her)
lige $(her)
præcist $(her)
måske $(her)
EOF
    }

    randEval <<EOF
$EGGS_USER: Det er selvfølgelig $(her)!
$EGGS_USER: Det er $(her), så er det besvaret.
Det er lige præcis $(her), $EGGS_USER!
EOF
fi
