#!/bin/sh
#
# Se hvordan vores lille by ser ud.

# TODO: Antag noget andet.

eval "$(echo "$@" | parse \
'(?<vejr>bliver vejret(\si\s(?<sted>.+))?\?)$')"

if [ "$vejr" ]; then
    if [ "$sted" ]; then
        echo -e $(vejrudsigt "$sted")
        exit
    fi
    echo -e $(vejrudsigt)
    exit
fi

dbRead hyggeby
