#!/bin/sh
#
# Spørg om essentielle datoer.

removeYear() {
    sed 's/^....-//'
}

eval "$(echo "$@" | parse \
'(?<birthday>har (?<birthday_kid>[^ ]+) fødselsdag)$|'\
'(?<halvening>(sker|kommer) the halvening)')"

who=$(randomName $EGGS_USER)
if ! [ "$who" ]; then
    echo "$EGGS_USER: Jeg kender dig slet, slet, slet ikke.  Hvad laver du her?"
    exit
fi

if [ "$birthday" ]; then
    if [ "$birthday_kid" != jeg ]; then
        who=$(randomName "$birthday_kid")
        if ! [ "$who" ]; then
            echo "$EGGS_USER: Hvem i alverden er denne '$birthday_kid'???"
            exit
        fi
        recp="$who"
    else
        recp="Du"
    fi
    date=$(dbUserRead $who birthday)
    if ! [ "$date" ]; then
        echo "$EGGS_USER: $recp har aldrig fødselsdag!"
    elif [ $(echo "$date" | removeYear) = $(dateToday | removeYear) ]; then
        echo "$EGGS_USER: $recp HAR FØDSELSDAG I DAG!  HURRRAAAAA!"
    else
        echo "$EGGS_USER: $recp har fødselsdag $(formatDate $date)!"
    fi
elif [ "$halvening" ]; then
    res=$(curl -s https://blockchain.info/q/getblockcount)
    missing_blocks=$((210000 - $res % 210000))
    estimated_missing_min=$(($missing_blocks * 10))
    estimated_halvening=$(date -d "+$estimated_missing_min min" '+%F %T')
    echo "Den næste halvering i Bitcoins inflation sker om $missing_blocks blokke og forventes $estimated_halvening CET"
else
    echo "Brug: hvornår har (jeg|<bruger>) fødselsdag? Eller: hvornår (kommer|sker) the halvening?"
fi
