#!/bin/sh
#
# Spørg hvor mange ...

factor=`randomElement <<EOF
millioner
tusinde
milliarder
tusindedele
hundrededele
EOF`

eval "$(echo "$@" | parse '^ *((?<gammel>(gammelt?|ungt?))|(?<lang>(langt?|kort|højt?))|(?<tung>(tungt?|let))|(?<klog>(dumt?|klogt?))|(?<stor>(stort?|lille))|(?<irriterende>(irriterende|udmattende|enerverende|trættende))).*')"

if [ "$gammel" ]; then
    unit=$(randomElement <<EOF
år
dage
sekunder
livstider
uger
måneder
EOF
)
elif [ "$lang" ]; then
    unit=$(randomElement <<EOF
centimeter
millimeter
kilometer
meter
Planck-distancer
kussehår
skægstubbe
fod
lysår
EOF
)
elif [ "$tung" ]; then
       unit=$(randomElement <<EOF
kilo
gram
ton
skæppepund
din mor
EOF
)
elif [ "$klog" ]; then
       unit=$(randomElement <<EOF
gange så klog som Brainfuck
gange så dum som John Strand
gange så klogdum som Troels
EOF
)
elif [ "$stor" ]; then
       unit=$(randomElement <<EOF
kubikmeter
brændestakke
kubikfod
rummeter
iPads
din mor
EOF
)
elif [ "$irriterende" ]; then
       unit=$(randomElement <<EOF
gange så irriterende som kode der fejler
gange så udmattende som din mor
EOF
)
fi

if [ "$unit" ]; then
    echo "$EGGS_USER: $(random 2 1337) $factor $unit!"
else
    prep=`randomElement <<EOF
På
I
Over
Under
EOF
`
    place=`randomElement <<EOF
Danmark
Sverige
Norge
Tyskland
Finland
Island
Polen
Frankrig
Italien
Portugal
Spanien
Egypten
Rusland
Hviderusland
Ukraine
Litauen
Letland
Estland
Grøndland
Færøerne
Bornholm
Skagen
EOF`
    echo "$EGGS_USER: $prep $place!"
fi
