#!/bin/sh
#
# Se hvordan vores lille by ser ud.

# TODO: Antag noget andet.

eval "$(echo "$@" | parse \
'(?<vejrudsigt>bliver vejret(\si\s(?<sted>.+))?(\?)*)$|'\
'(?<vejr>er vejret(\si\s(?<sted>.+))?(\?)*)$')";

if [ "$vejrudsigt" ]; then
    if [ "$sted" ]; then
        echo -e "$(vejrudsigt "$sted")"
        exit
    fi
    echo -e "$(vejrudsigt)"
    exit
fi
if [ "$vejr" ]; then
    if [ "$sted" ]; then
        echo "$(vejr "$sted")"
        exit
    fi
    echo "$(vejr)"
    exit
fi

dbRead hyggeby
