#!/bin/sh
#
# Spørg hvor mange ...

factor=`randomLine <<EOF
millioner
tusinde
milliarder
tusindedele
hundrededele
EOF`

eval "$(echo "$@" | parse '^ *((?<jul>julet er det(?: i procent)?)|((?<kongembede>længe har)|(?<antalkonge>mange gange har)) (?<hvilkenkonge>[^ ]+) været konge\??|mange har efternavnet (?<efternavn>.+)\??|mange har fornavnet (?<fornavn>.+)\??|mange (?:har navnet|hedder) (?<navne>.+?)(?: til (?<forefter>for|efter)navn)?\??$|(?<gammel>(gammelt?|ungt?|lang tid|længe))|(?<lang>(langt?|kort|højt?|lavt?))|(?<charmerende>charmerende)|(?<tung>(tungt?|let))|(?<klog>(dumt?|klogt?|stupid))|(?<mange>mange)|(?<stor>(stort?|lille|meget))|(?<irriterende>(irriterende|udmattende|enerverende|trættende))|(?<grim>(grimt?|ulækkert?|monstrøst?|klamt?))).*')"

if [ "$jul" ]; then
    charm="$(checkCharmen)"
    printf "Det er %.$(($charm + 2))f%% jul!  Det er %s julet!\n" "$(christmasLevel)" "$(christmasLevel -s)"
    exit
elif [ "$fornavn" ]; then
    navnestatistik "$fornavn" ''
    exit
elif [ "$efternavn" ]; then
    navnestatistik '' "$efternavn"
    exit
elif [ "$navne" ]; then
    if [ "$forefter" = "for" ]; then
        navnestatistik "$navne" ''
    elif [ "$forefter" = "efter" ]; then
        navnestatistik '' "$navne"
    else
        case $navne in
          *\ * ) navnestatistik $navne ;;
          * )    navnestatistik $navne $navne ;;
        esac
    fi
    exit
elif [ "$kongembede" ]; then
    tiltale=$EGGS_USER
    if [ "$hvilkenkonge" = "jeg" ]; then
        hvilkenkonge=$EGGS_USER
        tiltale="du"
    fi
    c=$(countRoyalReign "$hvilkenkonge")
    if [ $c = 0 ]; then
         echo "$EGGS_USER: Mig bekendt har $tiltale aldrig været konge."
         exit
    fi
    echo "$EGGS_USER: Så vidt jeg kan se, har $tiltale alt i alt været konge i $c."
    exit
elif [ "$antalkonge" ]; then
    tiltale=$EGGS_USER
    if [ "$hvilkenkonge" = "jeg" ]; then
        hvilkenkonge=$EGGS_USER
        tiltale="du"
    fi
    c=$(countRoyalReigns "$hvilkenkonge")
    if [ $c = 0 ]; then
         echo "$EGGS_USER: Mig bekendt har $tiltale aldrig været konge."
         exit
    fi
    echo "$EGGS_USER: Så vidt jeg kan se, har $tiltale alt i alt været konge $c gange."
    exit
elif [ "$gammel" ]; then
    unit=$(randomLine <<EOF
år
dage
sekunder
livstider
uger
måneder
EOF
)
elif [ "$lang" ]; then
    unit=$(randomLine <<EOF
centimeter
millimeter
kilometer
meter
Planck-distancer
kussehår
skægstubbe
fod
lysår
EOF
)
elif [ "$tung" ]; then
       unit=$(randomLine <<EOF
kilo
gram
ton
skæppepund
din mor
EOF
)
elif [ "$klog" ]; then
       unit=$(randomLine <<EOF
gange så klog som Brainfuck
gange så dum som John Strand
gange så klogdum som Troels
EOF
)
elif [ "$mange" ]; then
       unit=$(randomLine <<EOF
enheder
ting
dimsedutter
EOF
)
elif [ "$stor" ]; then
       unit=$(randomLine <<EOF
kubikmeter
brændestakke
kubikfod
rummeter
iPads
din mor
EOF
)
elif [ "$irriterende" ]; then
       unit=$(randomLine <<EOF
gange så irriterende som kode der fejler
gange så udmattende som din mor
EOF
)
elif [ "$grim" ]; then
       unit=$(randomLine <<EOF
gange grimmere end dig selv
gange pænere end fingermaling
EOF
)
elif [ "$charmerende" ]; then
  ppCharmen
  exit 0
fi

if [ "$unit" ]; then
    echo "$EGGS_USER: $(random 2 1337) $factor $unit!"
else
    evalIn() {
        read text
        eval "echo $text"
    }

    randEval() {
        randomLine | evalIn
    }

    her() {
        randEval <<"EOF"
ved siden af $(tingen)
ovenpå $(tingen)
EOF
    }

    tingen() {
        randEval <<"EOF"
DIKU
HCØ
Duniyas
Dilans
Oasen
Toves
Biocenteret
Rundetårn
Tivoli
Nørreport
den ting der er $(her)
de ting der ligner at de er $(her)
lige $(her)
præcist $(her)
måske $(her)
EOF
    }

    randEval <<EOF
$EGGS_USER: Det er selvfølgelig $(her)!
$EGGS_USER: Det er $(her), så er det besvaret.
Det er lige præcis $(her), $EGGS_USER!
EOF
fi
