#!/bin/sh
#
# Spørg concieggs om verdens spørgsmål.
eval "$(echo "$@" | parse 'kan du ikke lide (?<who>[^ ]+)')"

if [ "$who" = mig ]; then
    who=$EGGS_USER
fi

if [ "$who" ]; then
    reasons=$(annoyances "$who")

    if [ "$reasons" ]; then
        if cmpNames "$who" "$EGGS_USER"; then
            who=du
        fi
        echo "$EGGS_USER: Fordi $who $reasons."
    else
        s="$(annoyanceAt "$who") > 0"
        if isInBadStanding "$who" || [ $(echo "$s" | bc) = 1 ]; then
            if cmpNames "$who" "$EGGS_USER"; then
                who=dig
            fi
            echo "$EGGS_USER: Jeg ved ikke hvorfor, men der er noget afskyeligt ved $who."
        else
            echo "$EGGS_USER: Det kan jeg nu også godt."
        fi
    fi
else
    echo "Fordi `hjuleneDrejer`."
fi
