#!/bin/sh
#
# Grundlæggende afprøvningsfunktion for at se om concieggs fungerer
# nogenlunde.

echo "Hej $EGGS_USER!"
echo "Parametrene var $@."
echo "Den fulde linje var $EGGS_LINE."
echo "PATH er $PATH"
echo "Jeg hedder $CONCIEGGS_NAME"
echo "CONCIEGGS_DIR $CONCIEGGS_DIR"
