#!/bin/sh
#
# Hvem er hægtekongen? Brug: hægtekongen [del af hægte].

N=5

if [ $# -eq 0 ]
then
  TOP_N=$(cat db/links|cut -d' ' -f3|sort|grep -v hej_fra_github|uniq -c|sort -r|head -n $N)
  echo "Top $N hægtere:"
else
  TOP_N=$(grep -F "$@" db/links|cut -d' ' -f3|sort|grep -v hej_fra_github|uniq -c|sort -r|head -n $N)

  if [ -z $TOP_N ]
  then
    echo "Top $N hægtere for den dybe ende af Internettet er endnu ikke afgjort."
  else
    echo "Top $N hægtere =~ m/$regex/:"
  fi
  echo -e "$TOP_N"
fi
