#!/bin/sh
#
# Få dig et tilfældigt job!
#
# Brug: job [EMNE (standard: IT)]

s="${1:-IT}"

q="v0.1|SO:date desc|PS:50|CR:Freetext:$s|v0.1"

p="queryfilter:"

ENCRYPT() {
    python -c "import base64; print base64.b64encode('$1')"
}

url="http://www.ofir.dk/Resultat.aspx?soegeord=$s&query=$(ENCRYPT "$q")&params=$(ENCRYPT "$p")"

curl --silent "$url" \
    | grep '<div class="Teaser">' \
    | sed -r -e 's/ *<div class="Teaser">//' \
          -e 's/(<br \/>|<\/p>).*//' \
          -e 's/<[^>]+>//g' \
          -e 's/^ +//' \
          -e 's/&amp;/&/g' \
          -e 's/&ndash;/--/g' \
          -e "s/ [^. ]+\.\.\./ e$(tPattedyr)./" \
    | grep -E '.{30,}' \
    | randomElement
