#!/usr/bin/env python

import sys

bil = [ ' ___/_|_____ '
      , '[_,_______,_]'
      , '  "       "  '
      ]

trailer = [ '          '
          , '-|_______|'
          , '     O    '
          ]

def jyde(trailere):
    result = bil
    for i in range(trailere):
        result = map(lambda x: x[0] + x[1], zip(result, trailer))

    for s in result:
        print s

try:
    trailere = int(sys.argv[1])
    if trailere < 0:
        print("For lidt jyde")
        sys.exit()
    elif trailere > 4:
        print("For meget jyde")
        sys.exit()
except IndexError:
    trailere = 1
except Exception:
    print("hmmmmmm.")
    sys.exit()

jyde(trailere)
