#!/usr/bin/env python

import sys

bil = [ ' ___/_|_____ '
      , '[_,_______,_]'
      , '  0       0  '
      ]

trailer = [ '          '
          , '-|_______|'
          , '     O    '
          ]

def jyde(trailere):
    result = bil
    for i in range(int(trailere)):
        result = map(lambda x: x[0] + x[1], zip(result, trailer))

    fractional = int( (trailere % 1) * len(trailer[0]) )
    if fractional:
        result = map(lambda x: x[0] + x[1][:fractional-1], zip(result, trailer))

    for s in result:
        print s

try:
    trailere = float(sys.argv[1])
    if trailere < 0:
        print("For lidt jyde")
        sys.exit()
    elif trailere > 8:
        print("For meget jyde")
        sys.exit()
except IndexError:
    trailere = 1
except Exception:
    print("hmmmmmm.")
    sys.exit()

jyde(trailere)
