#!/bin/sh
#
# Find ud af om concieggs kan lide nogen.

eval "$(echo "$@" | parse '(du|De) (derimod |mon |så )?lide (?<user>[^ ]+)')"
if [ "$user" ]; then
    if [ "$user" = "mig" ]; then
        alias=$EGGS_USER
        user=$(du $alias)
    elif [ "$user" = "concieggs" ]; then
        echo "Ha ha, det er fandme sjovt at du spørger, om jeg kan lide mig selv. Ha ha ha, ikke også?"
        annoyedBy "$EGGS_USER" 25
        exit
    else
        alias=$user
    fi
    if cmpNames "$alias" reenberg; then
        echo "Nej, $user er nederen."
        exit
    fi
    s="$(annoyanceAt "$alias") > 0"
    if isInBadStanding "$alias" || [ $(echo "$s" | bc) = 1 ]; then
        echo "Nej, $user er et dumt svin."
    fi
    s="$(annoyanceAt "$alias") < 0"
    if [ $(echo "$s" | bc) = 1 ]; then
        echo "Ja, $user er god nok."
    fi
    if [ $(annoyanceAt "$alias") = 0 ]; then
        if [ "$user" = "du" ]; then
            echo "Jeg kender dig ikke godt nok."
        else
            echo "Jeg kender ikke $user godt nok."
        fi
    fi
else
    echo "$EGGS_USER: Kan hvem hvad hvornår?  Jeg kan bedst lide at svare på om jeg kan lide folk."
fi
