#!/bin/sh
#
# Find ud af om concieggs kan lide nogen.

eval "$(echo "$@" | parse '(du|De) (derimod |mon |så )?(godt )?lide (?<user>[^ ]+)')"

if [ "$user" ]; then
    if [ "$user" = "mig" ]; then
        alias=$EGGS_USER
        user=$(du $alias)
    elif [ "$user" = "concieggs" -o "$user" = "dig" ]; then
        echo "Ha ha, det er fandme sjovt at du spørger, om jeg kan lide mig selv. Ha ha ha, ikke også?"
        annoyedBy "$EGGS_USER" 25 "spurgte om jeg kunne lide mig selv"
        exit
    elif echo "$user" | grep -qi OpenBSD; then
        echo "$EGGS_USER: Naturligvis - det er det tænkende individs styresystem."
        exit
    else
        alias=$user
    fi
    if cmpNames "$alias" reenberg; then
        echo "Nej, $user er nederen."
        exit
    fi
    s="$(annoyanceAt "$alias") > 0"
    reasons=$(annoyances "$alias")
    if isInBadStanding "$alias" || [ $(echo "$s" | bc) = 1 ]; then
        if isKing "$alias"; then
            echo "Selvfølgelig kan jeg lide $alias, det er jo kongen..."
            removeFromBadStanding "$alias"
            pleasedBy "$alias" 25
        else
            if [ -n "$reasons" ]; then
                echo "Nej, $user er et dumt svin, da $user $reasons."
            else
                echo "Nej, $user er et dumt svin."
            fi
        fi
        exit
    fi
    s="$(annoyanceAt "$alias") < 0"
    if [ $(echo "$s" | bc) = 1 ]; then
        if isKing "$alias"; then
            echo "Selvfølgelig, det er jo vores alles konge."
        else
            if [ -n "$reasons" ]; then
                echo "Ja, $user er god nok, omend $user $reasons."
            else
                echo "Ja, $user er god nok."
            fi
        fi
        exit
    fi
    if [ $(annoyanceAt "$alias") = 0 ]; then
        if [ "$user" = "du" ]; then
            echo "Jeg kender dig ikke godt nok."
        else
            echo "Jeg kender ikke $user godt nok."
        fi
    fi
else
    echo "$EGGS_USER: Kan hvem hvad hvornår?  Jeg kan bedst lide at svare på om jeg kan lide folk."
fi
