#!/bin/sh
#
# Tag noget og kast det ad helvede til!  Eller andre ting.

eval "$(echo "$@" | parse '((?<thing>[^ ]+) ad helvede til)|(?<op>op)')"

if [ "$thing" ]; then
    who="$(dbRead has_$thing)"
    if [ "$who" ]; then
        echo "$(ack)  Du skal ikke bekymre dig mere om $thing, omend $who måske bliver skuffet."
        dbDelete "has_$thing"
    else
        echo "Ingen har $thing, så det er nemt gjort."
    fi
elif [ "$op" ]; then
    n() {
        t=''
        e=$(random 5 9)
        for i in $(seq 1 $e); do
            t="$t$1"
        done
        echo "$t"
    }

    echo "/me får det lidt dårligt..."
    echo "Bw$(n a)$(n d)$(n r)b$(n l)$(n u)$(n r)$(n h)$(n !)"
    echo "$EGGS_USER: Lige i fjæset!"
else
    echo "$EGGS_USER: Kast hvad, hvorledes og hvorfor?  Brug 'kast <ting> ad helvede til'"
fi
