#!/bin/sh
#
# Lad charmekatten vise noget skind.

length="$1"
if ! [ "$length" ]; then
    length=$(expr $(checkCharmen) '*' 3)
fi

if [ "$length" -gt 200 ] || [ "$length" -lt 0 ]
then
    say "$EGGS_USER: Det ville være MIS-handling."
    annoyedBy "$EGGS_USER" 1 "forsøg på mishandling"
    exit
fi

for i in $(seq $length); do
    echo -n $(catte)
done
catte
