#!/bin/sh
#
# Udskriv kataloget over mulige ønsker.  Der kan kun ønskes ting fra
# denne liste.  Brug 'indfør' til at tilføje nye muligheder, og
# 'bandlys' til at fjerne dem.


echo -n "Der eksisterer følgende indkøbsmuligheder: "
dbIterate katalog | while read -r item; do
    dbRead "$item"
done | grep -i "$*" | commasize | sed 's/$/./'
