#!/bin/sh
#
# Få concieggs til at klappe hesten.

eval "$(echo "$@" | tolower | parse '.*(?<ting>(karry|kaje|i|hesten|geden))!*')"

if [ ! "$ting" ]; then
    echo "$EGGS_USER: Du er dum!"
else
    echo "$EGGS_USER: Klap selv $ting!"
fi
