#!/usr/bin/env perl
#
# Kaster til "cowsay".
# for parametre se:
# https://en.wikipedia.org/wiki/Cowsay


use 5.020;
use warnings;
use Encode qw/decode/;

my $flag = 'd';
$flag = shift @ARGV if @ARGV > 0 && $ARGV[0] =~ /^[bdgpstwy]$/;

my $cmd = (rand() < 0.5) ? "cowsay" : "cowthink";
my $message = join(" ", @ARGV);
unless ($message) {
    $cmd = "cowthink";
    $message = <<'END_OF_COW';
\|/          (__)
     `\------(oo)
       ||    (__)
       ||w--||     \|/
   \|/
END_OF_COW
}

open(COWSAY, "|$cmd -$flag -n");
print COWSAY $message;
close(COWSAY);
