#!/usr/bin/env perl
#
# Kaster til "cowsay".
# for parametre se:
# https://en.wikipedia.org/wiki/Cowsay


use 5.020;
use warnings;
use Encode qw/decode/;

my $flag = 'd';
$flag = shift @ARGV if @ARGV > 0 && $ARGV[0] =~ /^[bdgpstwy]$/;

my $message = join(" ", @ARGV);
unless ($message) {
    my $user = decode('utf-8', $ENV{EGGS_USER});
    $message = "$user kan ikke finde ud af koen.";
}

my @args = ("-$flag",  $message);

system('cowsay', @args);
