#!/usr/bin/env perl
#
# Kaster til "cowsay".
# for parametre se:
# https://en.wikipedia.org/wiki/Cowsay

use 5.012;
#use warnings;

if ($ARGV[0] =~ /^[bdgpstwy]$/) {
    system('cowsay', ('-'.$ARGV[0]), @ARGV[1..@ARGV])
} else {
    system('cowsay', "-d", @ARGV);
}
