#!/bin/sh
#
# Lær noget fattigt om kongehuset.

if [ $# -ne 1 ]; then
    mere="Tilføj også noget om $*."
else
    mere=""
fi

gpt4 400 "Følgende tekst er af formen '[emne: beskrivelse]' og handler om det danske kongehus. Skriv et nyt, kort stykke tekst (uden at tage højde for den gamle form) der præsenterer nogenlunde samme fakta, men omdigtet til en fiktiv virkelighed hvor kongehuset er utroligt fattigt og socialt dysfunktionelt, f.ek.s ved at det lever af en ussel kontanthjælp og bor i en lejlighed på den københavnske vestegn eller i en døende landsby på Lolland. Det skal ikke nødvendigvis indeholde specielt meget patos eller medlidenhed, men derimod være beskrivende, og måske endda en smule kritisk. $mere Tekst: [$($CONCIEGGS_DB_DIR/kongehuset/get_kongehuset_fact.py)]"
