#!/bin/sh
#
# Lær noget forkert om kongehuset.

if [ $# -ne 1 ]; then
    mere="Tilføj også noget om $*."
else
    mere=""
fi

gpt4 400 "Følgende tekst er af formen '[emne: beskrivelse]' og handler om det danske kongehus. Skriv et nyt, kort stykke tekst (uden at tage højde for den gamle form) der præsenterer det modsatte af hvad der er fakta, men formuleret som om det er fakta. $mere Tekst: [$($CONCIEGGS_DB_DIR/kongehuset/get_kongehuset_fact.py)]"
