#!/bin/sh
#
# Lær noget objektivt om kongehuset.

gpt4 400 "Følgende tekst er af formen '[emne: beskrivelse]' og handler om det danske kongehus. Skriv et nyt, kort stykke tekst (uden at tage højde for den gamle form) der præsenterer den samme fakta, men ekstremt negativt ladet. Tekst: [$($CONCIEGGS_DB_DIR/kongehuset/get_kongehuset_fact.py)]"
