#!/bin/sh
#
# Lav en statusbesked på Twitter.  https://twitter.com/concieggs

if [ $# -lt 1 ]; then
    echo 'Brug: kvidr <besked>'
    exit 0
fi

# auth="$(isTrusted "$EGGS_USER")"
# if ! [ "$auth" ]; then
#     echo "$EGGS_USER: Almindeligt rakkerpak har ikke bemyndigelse til at betjene denne funktionalitet."
#     exit 0
# fi

echo "$*" | kvidr
