#!/bin/sh
#
# Lav en statusbesked på Twitter.  https://twitter.com/concieggs

if [ $# -lt 1 ]; then
    echo 'Brug: kvidr <besked>'
    exit 0
fi

auth="$(isTrusted "$EGGS_USER")"
if ! [ "$auth" ]; then
    echo "$EGGS_USER: Du er ikke mester nok, mester."
    exit 0
fi

curl hongabar.org/~concieggs/kvidr.php --data-urlencode message="$*"
