#!/bin/sh
#
# Lav en statusbesked på Twitter.  https://twitter.com/concieggs

. $CONCIEGGS_DIR/concieggs.conf

if [ $# -lt 1 ]; then
    echo 'Brug: kvidr <besked>'
    exit 0
fi

auth="$(isTrusted "$EGGS_USER")"
if ! [ "$auth" ]; then
    echo "$EGGS_USER: Du er ikke mester nok, mesterfidus."
    exit 0
fi

echo "$EGGS_BODY" | kvidr > $CONCIEGGS_IRC_DIR/$irc_channel/in
