#!/usr/bin/env perl
#
# Kør en kommando om lidt.

use 5.012;
use warnings;

my $args = join(" ", @ARGV);

use Env qw/EGGS_USER/;

if ($EGGS_USER ne 'Sebbe') {
    print "Work in progress! Ikke røre!\n"
    exit;
}

if ($args =~ qr/
                (?<command>.*)\s+
                om\s+
                (?<when>\d+\s+(?:sekunder|minutter|timer|dage))
                [\.!\s]*$
              /x) {
    my $command = $+{"command"};
    my $when = $+{"when"};
    my $realWhen = `parseHumanTime "$when"`;
    if ($realWhen) {
        print "Kører '$command' om $when!\n";
        fork and exit;
        sleep $realWhen;
        my ($cmd, @args) = split (/ /, $command);
        exec('runcmd', $cmd, join(' ', @args));
    } else {
        print "$EGGS_USER: Det synes jeg lyder som en dum idé.\n";
        `annoyedBy $EGGS_USER`;
    }
} else {
    print "$EGGS_USER: Kør hvad, og hvornår? Brug 'kør <kommando> om <interval>'.\n";
}

