#!/bin/sh
#
# Få et forslag til en lækker snack.

producents() {
    randomLine <<EOF
Dr. Oetkers
Karen Volfs
Kelloggs'
Maren Malkepiges
Duniyas'
Jensen's Bøfhus'
Dilans'
Toves
EOF
}

gode() {
    randomLine <<EOF
nye
fantastiske
billige
tilbudsramte
luksuriøse
frosne
anderledes
vitaminfyldte
fedtfattige
opfriskende
mineralpåfyldte
EOF
}

ret() {
    ting=$(randomLine <<EOF
burger
pizza
pomfritter
sushi
småkager
grillkylling
løgringe
durumrulle
nuggets
blæksprutteefterligning
milkshake
pitabrød
snøfler
bønner
EOF
)
    bogstav=$(echo $ting | sed -r 's/^(.).*$/\1/')
    echo $(grep "^$bogstav" "$CONCIEGGS_DB_DIR/ordbog-dansk-navneord-gode" | randomLine)-$ting
}

echo Du kunne spise $(producents) $(gode) $(ret).
