#!/bin/sh
#
# Optræd som en sand gentleman.

if [ $# -eq 1 ]; then
    from=$EGGS_USER
    to=$1
    if [ "$to" = "$CONCIEGGS_NAME" ]; then
        echo "$EGGS_USER: Tag et bad."
        annoyedBy "$EGGS_USER" 10 "er en neckbeard"
    else
        (
            echo "$to: Hvorfor vil du ikke have en sød fyr, som $EGGS_USER, der behandler dig som den prinsesse du er?"
            echo "$to: Hvorfor vil du kun have røvhuller og ikke f.eks. $from?"
            echo "$to: Drop de jocks og prøv en sød fyr, som $EGGS_USER, der værdsætter dig for hvem du er!"
        ) | randomLine
    fi
else
    echo "/me tips fedora."
fi
