#!/bin/sh
# Savner du en tingsbroders indsigtfulde kommentarer?  Lad concieggs syntetisere et bidrag.

if [ $# -ne 1 -a $# -ne 2 ]; then
    echo "Brug: $0 <hvem> [n]"
    exit
fi

if [ $# -eq 2 ]; then
    n=$2
else
    n=10
fi

grep "<$1>" "$CONCIEGGS_IRC_DIR/#eggsml/out" | \
cut -d'>' -f 2- | grep -v http | grep -v 'concieggs:' | \
sed -r -e 's/^ *//' -e 's/^[^ ]*://' | sort -R | $EGGS_DIR/concieggs_markov $n
