#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import random

truck = r'''
             _______ 
 GODDAW DO' / _____ |
           / /(__) ||
  ________/ / |OO| ||
 |         |-------||
(|         |     -.||
 |  ____   \       ||
/| / __ \   |______||
\|| /  \ |___________
   | () |            
    \__/             
'''.split('\n')[1:-1]

baghjul = r'''






_______________________ 
     / __ \   / __ \   |
____| /  \ |_| /  \ |__|
     | () |   | () |    
      \__/     \__/     
'''.split('\n')[1:-1]

def fuse(blocks, sep=""):
    return map(lambda parts: sep.join(parts), zip(*blocks))

for line in fuse([truck] + [baghjul] * random.randint(1, 4)):
    print(line)
