#!/bin/sh
#
# Bed concieggs om at være på en bestemt led mens du kører en kommando.

eval "$(echo "$@" | parse 'du er (?<what>.+?): (?<command>.+)$')"

if [ "$what" ] && [ "$command" ]; then
    echo "$what" | "filterchain_overwrite"
    runcmd $command
    dbDelete "filterchain_overwrite"
else
    echo "Brug: mens du er <væremåde>: <kommando>"
fi
