#!/bin/sh
#
# Mind en bruger om noget ved næste ytring.


if ! [ "$2" = "om" -a "$3" = "at" -a "$4" ]; then
    echo "Brug: mind <person> om at <besked...>"
    exit
fi

if [ "$1" = mig ]; then
    shift; shift; shift;
    echo "Okay: Husk at $@"
    exit
fi

to="$(randomName "$1")"
if ! [ "$to" ]; then
    to="$1"
fi
from="$(randomName "$EGGS_USER")"
if ! [ "$from" ]; then
    from="$EGGS_USER"
fi

shift; shift; shift;

msg="$@"

msgnode=$(dbUserInsertNode "$to" "messages")

fiksStedord() {
    sed -e 's/han/du/g' -e 's/hun/du/g' -e 's/hans/din/g' -e 's/hendes/din/g' \
        -e 's/ham/dig/g' -e 's/hende/dig/g'
}

echo "$msg" | fiksStedord | dbWrite "$msgnode/message"
echo "$from" | dbWrite "$msgnode/from"

echo "$(ack)  Næste gang $to blander sig i samtalen, vil jeg minde $(vedkommende "$to") om at $msg"
