#!/bin/sh
source $CONCIEGGS_DIR/eggspi.lib

next=$(nextEggs)
if [ "$next" != "" ]; then
    echo "Der er eggs klokken $(timeToDate $next), med "
    cat $CONCIEGGS_DB_DIR/eggs/$next | while read who; do
        echo $(randomName "$who")
    done
    echo "tilmeldt."
else
    echo "Ingen har tilmeldt sig eggs!"
fi
