#!/bin/sh
#
# Fortæl concieggs at han/hun tager fejl.

(cat | randomise | head -n 1) <<EOF
Jo.
Nå.
Som om.
Det sagde hun også i går.
Okay så.
Jooh, mon ikke?
Den er god med dig.
Sagde du noget?
Jojo.
Det kan vi vel tale om.
EOF
