#!/usr/bin/env perl
use 5.012;
use warnings;

use DateTime::Format::ISO8601;
use Facebook::Graph;
use YAML::Tiny;
use experimental qw(smartmatch autoderef);
use Try::Tiny;

my $configuration_file = '/home/concieggs/credentials/facebook.yaml';
my $ext_token_script = '/home/concieggs/credentials/facebook_ext_token.pl';

my $yaml = YAML::Tiny->read($configuration_file);
my $config = $yaml->[0];

my $fb;
try {
    $fb = Facebook::Graph->new(
        app_id       => $config->{app_id},
        app_secret   => $config->{app_secret},
        access_token => $config->{access_token},
    );
} catch {
    print "Mine Facebook credentials er udløbet. :(\n";
    print STDERR "En eller anden log ind som concieggs på fjæseren, gå ind på https://developers.facebook.com/tools/explorer/702475036512546/ og tryk 'Get Access Token' i toppen.\n";
    print STDERR "Kør så følgende fra en commandline: $ext_token_script <token>";
    exit();
};
$config->{seen_memes} //= [];

my $cnt = 0;
my $group_feed = $fb->fetch('1676857065872315/feed')->{data};
for my $elm (@$group_feed) {
    my $created = $elm->{created_time};
    $created =~ s/\+(\d{2})(\d{2})/+$1:$2/;
    $created = DateTime::Format::ISO8601->parse_datetime( $created )->epoch();

    if (time() - $created < 60 * 60 * 3 && not ($elm->{id} ~~ @{$config->{seen_memes}}) ) {
        printf("%s (af %s) - %s\n",
               $elm->{message} // "Ingen titel",
               $elm->{from}->{name},
               $elm->{actions}->[0]->{link},
        );
        push($config->{seen_memes}, $elm->{id});
        $cnt += 1;
    }
}

if ($cnt == 0) {
    print "Der er ingen nye mem i Facebook-gruppen. Slackers.\n";
}

$yaml->write($configuration_file);

