#!/usr/bin/env python
# vim: set fileencoding=utf-8 :
# En ny trunte er spottet!

import simplejson as json
from os import environ, path
from sys import exit
import sys


def main():
    if len(sys.argv) < 2:
        print "Du skal give trunten et navn. Ex: nytrunte redhead Hende den rødhårede"
        exit(0)

    trunte = sys.argv[1]
    truntel = trunte.lower()

    datafile = path.join(environ['CONCIEGGS_DB_DIR'], 'truntestats')

    if not path.exists(datafile):
        f = open(datafile, 'w+')
        f.write('{}')
        f.close()

    dbfile = open(datafile, 'r')
    db = json.load(dbfile)
    dbfile.close()

    if truntel in db:
        print "Vi har allerede den trunte liggende!"
        exit(0)

    db[truntel] = {
        'kortNavn': trunte,
        'fuldtNavn': trunte,
        'beskrivelse': 'Ingen info.',
        'vurderinger': {},
        'gennemsnit': 0,
        'billeder': {}
    }

    dbfile = open(datafile, 'w')
    json.dump(db, dbfile)
    dbfile.close()
    print "Javel! %s er nu oprettet i TrunteRegisteret." % trunte
    dbfile.close()

if __name__ == '__main__':
    main()
