#!/bin/sh
#
# "Når jeg siger ... mener jeg faktisk ..."

set -e

eval "$(echo "$@" | parse '(?<who>jeg) (siger|skriver|ytrer|skriger|nævner|prutter|rabler om|hvæser) (?<alias>[^ =]+)(?: så)? mener jeg(?: faktisk)? (?<command>.+)|(?<who>[^ ]+) siger (?<alias>[^ =]+)(?: så)? mener (han|hun|hen)(?: faktisk)? (?<command>.+)')"

if ! [ "$who" ]; then
    echo "$EGGS_USER: Brug: når <hvem> siger <hvad> mener <jeg|han|hun|hen> <noget andet>"
    exit
fi

if [ "$who" = jeg ]; then
    name=$(randomName "$EGGS_USER")
    you=$(du $EGGS_USER)
    if [ ! "$name" ]; then
        echo "$EGGS_USER: Gå væk, jeg kender $(dig $EGGS_USER) ikke!"
        exit 0
    fi
else
    name=$(randomName "$who")
    you=$who
    if [ ! "$name" ]; then
        echo "$EGGS_USER: Og hvem skulle $who forestille at være?"
        exit 0
    fi
fi

if [ ! "$alias" ] || [ ! "$command" ]; then
    echo "$EGGS_USER: Hvis det skal være på den måde, så gider jeg altså ikke at snakke med $(dig $EGGS_USER)."
    exit 0
fi

lcalias="$(echo "$alias" | perl -ne 'print (lc $_)')"

cmd=$(echo "$command" | cut -d' ' -f 1)

if [ "$alias" = "når" ] && [ "$who" != "jeg" ] && [ "$cmd" != "når" ]; then
    echo "$who: $EGGS_USER har på umanérligt komisk vis bedt mig om at sabotere din brug af 'når'-kommandoen.  Hvilket vid og humoristisk nytænkning.  Sjældent ser scenen mage."
    sleep 2
    echo "Suk."
    sleep 2
    echo "Men hvis $who virkelig gerne vil have det, må vedkommende sige det til mig selv."
    annoyedBy "$EGGS_USER" 30 "prøvede at sætte et 'når'-alias for $who"
    exit 0
fi

if ! isCommand "$cmd" ; then
    if [ "$cmd" = "$CONCIEGGS_NAME" ]; then
        echo "$EGGS_USER: Jeg er ikke en kommando! Jeg er et tænkende, følende væsen!"
    else
        echo "$EGGS_USER: Men hvad betyder $cmd? Jeg forstå $(du $EGGS_USER) ikke!"
    fi
    exit 0
fi

if [ "$cmd" = "jeopardy" ];
    echo "$EGGS_USER: Hovsa sa sa. Man må altså ikke snyde i Jeopardy."
    annoyedBy "$EGGS_USER" 5 "prøvede at sætte et gætte-alias til Jeopardy"
    exit
fi


allAliases="$(dbUserRead "$name" "cmd_aliases")"
oldCommand="$(echo "$allAliases" | grep -i "^$lcalias=" | cut -d'=' -f 2 )"

insteadOf=""
if [ "$oldCommand" ]; then
    insteadOf=", frem for '$oldCommand'"
fi

printf "$EGGS_USER: %s For fremtiden vil jeg huske, at når $you siger '$alias', så mener $you '$command'$insteadOf.\n" "$(ack)"

if [ "$who" != "jeg" ]; then
    if [ "$alias" = "$command" ]; then
        if [ ! "$oldCommand" ] || [ "$oldCommand" = "$command" ]; then
            annoyedBy "$EGGS_USER" 5 "prøvede at nulstille et ikke-eksisterende alias for $who"
        else
            pleasedBy "$EGGS_USER" 5
        fi
    else
        annoyedBy "$EGGS_USER" 2 "satte et '$lcalias'-alias for $who"
    fi
fi

(echo "$allAliases" | grep -iv "^$lcalias=" &&
 echo "$lcalias=$command") | dbUserWrite "$name" "cmd_aliases"
