#!/bin/sh
#
# "Når jeg siger ... mener jeg faktisk ..."

eval "$(echo "$@" | parse '(?<who>jeg) siger (?<alias>[^ =]+)(?: så)? mener jeg(?: faktisk)? (?<command>.+)|(?<who>[^ ]+) siger (?<alias>[^ =]+)(?: så)? mener (han|hun)(?: faktisk)? (?<command>.+)')"

if [ "$who" = jeg ]; then
    name=$(randomName "$EGGS_USER")
    you=$(saysDu $EGGS_USER)
    if [ ! "$name" ]; then
        echo "$EGGS_USER: Gå væk, jeg kender $(saysDig $EGGS_USER) ikke!"
        exit 0
    fi
else
    name=$(randomName "$who")
    you=$who
    if [ ! "$name" ]; then
        echo "$EGGS_USER: Og hvem skulle $who forestille at være?"
        exit 0
    fi
fi

if [ ! "$alias" ] || [ ! "$command" ]; then
    echo "$EGGS_USER: Hvis det skal være på den måde, så gider jeg altså ikke at snakke med $(saysDig $EGGS_USER)."
    exit 0
fi

lcalias="$(echo "$alias" | perl -ne 'print (lc $_)')"

cmd=$(echo "$command" | cut -d' ' -f 1)

if ! isCommand "$cmd" ; then
    if [ "$cmd" = "$CONCIEGGS_NAME" ]; then
        echo "$EGGS_USER: Jeg er ikke en kommando! Jeg er et tænkende, følende væsen!"
    else
        echo "$EGGS_USER: Men hvad betyder $cmd? Jeg forstår $(saysDu $EGGS_USER) ikke!"
    fi
    exit 0
fi

allAliases="$(dbUserRead "$name" "cmd_aliases")"
oldCommand="$(echo "$allAliases" | grep -Pi "^$lcalias=" | cut -d'=' -f 2 )"

insteadOf=""
if [ "$oldCommand" ]; then
    insteadOf=", frem for '$oldCommand'"
fi

printf "$EGGS_USER: %s For fremtiden vil jeg huske, at når $you siger '$alias', så mener $you '$command'$insteadOf.\n" "$(ack)"

(echo "$allAliases" | grep -Piv "^$lcalias=" &&
 echo "$lcalias=$command") | dbUserWrite "$name" "cmd_aliases"
