#!/usr/bin/env perl
use 5.026;
use strict;
use warnings;
use utf8::all;

use Env qw(EGGS_USER);
use EggsML::EggsPI text => [qw(dbRead dbWriteArg)];

my $ladning = dbRead('ladning');
if    ($ladning > 999) { say "$EGGS_USER: Jeg er allerede ladet op!"; }
elsif ($ladning > 500) { say "$EGGS_USER: Mange tak for opladningen."; }
elsif ($ladning > 150) { say "$EGGS_USER: Pyha, det var tiltrængt."; }
elsif ($ladning >   0) { say "$EGGS_USER: Pyha, jeg var næsten drænet."; }
else                   { say "/me aktiverer efter dvale og takker $EGGS_USER for opladningen."; }

dbWriteArg('ladning', 1000);
