#!/usr/bin/env perl
use 5.026;
use strict;
use warnings;
use utf8::all;

use Env qw(EGGS_USER);
use EggsML::EggsPI text => [qw(dbRead dbWriteArg)];

my $ladning = dbRead('ladning');
given ($ladning) {
  when(100) { say "$EGGS_USER: Jeg er allerede ladet op!"; }
  when(0)   { say "$EGGS_USER: Pyha, det var tiltrængt."; }
  default   { say "$EGGS_USER: Mange tak for opladningen."; }
}

dbWriteArg('ladning', 100);
