#!/bin/sh
#
# Oplys alle!  Promovér kritisk forbrug af medierne!  Giv demokratiets midler
# tilbage til folket!  Forhindr demagogers spredning i verdenssamfundet!
# Forbedr den offentlige debat!  Muliggør kreative løsninger til fremtidens
# flaskehalse!

# Tilføj gerne kontroversielle feeds.
url=$(randomFeedLink <<EOF
http://politiken.dk/rss/senestenyt.rss
http://www.dr.dk/nyheder/service/feeds/allenyheder
http://www.politico.com/rss/politicopicks.xml
http://www.bt.dk/bt/seneste/rss
https://www.information.dk/feed
http://www.kristeligt-dagblad.dk/rss/nyheder
http://www.socialister.dk/nyheder/rss.asp
http://gribskov.lokalavisen.dk/section/senestenytrss
https://www.jv.dk/rss/nyheder
https://www.frederiksbergbladet.dk/feed/
https://www.lokalavisen-frb.dk/feed/
https://ugeavisen.dk/rss/kolding
EOF
)

udbryd=$(randomLine <<EOF
Nu går det da helt galt for Kongeriget Danmark
Wow, nu har jeg aldrig
Hvad pape
Jeg ved ikke om jeg skal grine eller græde
Det her kan jeg ikke hamle op med
Giv mig jeres holdninger
Nu igen
FOR SATAN I HELVEDE
Pokkers
Det er vel egentlig meget godt
Rimelig fornuftigt alligevel
Kudos herfra
Læs det her
Jeg havde slet ikke tænkt over det her
Hmm, tjoo
Nu går det ned
Jamen altså
Ffffffff
Det her gav mig stof til eftertanke
Jamen dog
Det her bør du fandeme læse
Nej, det kan IKKE VÆRE SANDT
Det her vil de ikke fortælle dig på Christiansborg
Shiiiiiiit
Ih altså
Det er det jeg altid har sagt
Gør det her dig sur eller glad?  Læs
For syv sytten satan i sileme sulan
I må lige kigge på bogstaverne i denne artikel
EOF
)

besked="$udbryd: $url"

bruger="$1"

if ! [ "$bruger" ]; then
    echo "$besked"
else
    echo "$bruger: $besked"
fi
