#!/usr/bin/env python3
#
# Spørg oraklet om sandsynlighedsfordelinger for et givent emne. Sammenligning med 24 timer gamle sandsynligheder vises også.

import requests
import random
import sys
import subprocess

url = 'https://www.predictit.org/api/marketdata/all/'

resp = requests.get(url=url)
data = resp.json()

markets = data['markets']

matches = list(x for x in markets if ( any(list(map(lambda y: sys.argv[1] in y['longName'], x['contracts'] )))))

if not matches:
    matches = list(x for x in markets if ( any(list(map(lambda y: sys.argv[1].lower() in y['longName'].lower(), x['contracts'] )))))
    if not matches:
        print(random.choice([
            "Ingen kender det, end ikke jeg selv. Kun Faderen ved det.",
            "Der må jeg være svar skyldig. Måske du allerede selv har en idé?",
        ]))
        exit(0)

match = random.choice(matches)
contracts = match['contracts']

translate_input = "\n".join(map(lambda x: x['longName'], contracts))
process = subprocess.run(['translate', 'en', 'da'], stdout=subprocess.PIPE, input=translate_input.encode('utf-8'))
translate_output = process.stdout.decode('utf-8').rstrip()
contract_names_dk = translate_output.split('\n')
#contract_names_dk = translate_input.split('\n') # for local debuggin if translate is not in $PATH

i = 0
for contract in contracts:
    # if contract is new or price is unchanged
    if (contract['lastClosePrice'] == None or contract['lastClosePrice'] == contract['lastTradePrice'] ):
        symbol = "\u2013" # ndash
        diff   = "+ 0.0"
    # If contract price is up
    elif (contract['lastClosePrice'] < contract['lastTradePrice']):
        symbol = "\x0309\u2191\x03" # green up arrow
        diff   = "\x0309+{:4.1f}\x03".format(100*(contract['lastTradePrice'] - contract['lastClosePrice']))
    # If contract price is down
    else:
        symbol = "\x0304\u2193\x03" # red down arrow
        diff   = "\x0304-{:4.1f}\x03".format(100*(contract['lastClosePrice'] - contract['lastTradePrice']))

    print (contract_names_dk[i].rstrip() + " {:4.1f} pct. ".format(100 * contract['lastTradePrice']) + symbol +  " ({0})".format(diff))
    i += 1
