#!/usr/bin/env python3

import requests
import re
import sys
import subprocess

url = 'https://www.predictit.org/api/marketdata/all/'

resp = requests.get(url=url)
data = resp.json()

markets = data['Markets']

match = next( (x for x in markets if ( any(list(map(lambda y: sys.argv[1] in y['LongName'], x['Contracts'] ))))), None)

if match is None:
    print("Ingen kender det, end ikke jeg selv. Kun Faderen ved det.")
    exit(0)

contracts = match['Contracts']

for contract in contracts:
    navn = subprocess.run(['translate', 'en', 'da'], stdout=subprocess.PIPE, input=contract['LongName'].encode('utf-8'))
    print (navn.stdout.decode('utf-8') + " {:4.1f} pct.".format(100 * contract['LastTradePrice']))
