#!/bin/sh
#
# Oversæt fra et sprog til et andet.  Brug: oversæt fra SPROG til SPROG: TEKST

eval "$(echo "$@" | parse 'fra (?<fra>[^ ]+) til (?<til>[^ ]+): (?<tekst>.+)|(?<sep>[\'"]?)(?<tekst>.+)\g{sep} fra (?<fra>[^ ]+) til (?<til>[^ ]+)\\W*\$')"

if [ $fra ] && [ $til ] && [ "$tekst" ]; then
    fra=$(langcode $fra)
    if [ $? != 0 ]; then
        echo "Sproget $fra findes ikke!"
        exit
    fi
    til=$(langcode $til)
    if [ $? != 0 ]; then
        echo "Sproget $til findes ikke!"
        exit
    fi
    echo $(echo "$tekst" | translate $fra $til)
else
    echo "Fejl ved parsningen, læs dog dokumentationen!"
fi
