#!/usr/bin/env perl
use 5.024;
use warnings;
use utf8;

use List::Util qw/shuffle/;

my @phpinfo = split(/\n/, `echo "<?php phpinfo(); ?>" | php-7.0`);
@phpinfo = shuffle( grep { $_ !~ /^\s+$/ } @phpinfo );

say "Udvalgte linjer fra phpinfo:";
say $_ for @phpinfo[0..4];

