#!/usr/bin/env perl
use 5.042;
use warnings;
use utf8;

my @phpinfo = grep { $_ } split(/\n/, `echo "<?php phpinfo(); ?>" | php`);

my $length = @phpinfo;

say "Udvalgte linjer fra phpinfo:";
say $phpinfo[$_] for map { int(rand($length)) } (0..4);

