#!/bin/sh
#
# Ping en station med fire pakker. Angiv station som argument.

if [ ! "$1" ]; then
  echo "$EGGS_USER: Pong."
  exit
fi

case "$1" in
  *:*:* ) ping6 -c 4 $1 ;;
  *     ) ping  -c 4 $1 ;;
esac
