#!/bin/sh

prev=$(prevEggs)
if [ "$prev" != "" ]; then
    echo $prev | while read eggs; do
        echo "Der var Eggs klokken $(timeToDate $eggs), med "
        cat $CONCIEGGS_DB_DIR/eggs/$prev | while read who; do
            echo $(randomName "$who")
        done
        echo "tilmeldt."
    done
else
    echo "Alle Eggs er blevet bogført!"
fi
