#!/bin/sh
#
# Udskriv alle overståede Eggs der endnu ikke er blevet bogført.

prev=$(prevEggs)
if [ "$prev" != "" ]; then
    prevEggs | while read eggs; do
        echo "Der var $(countEggsers $eggs) tilmeldt til Eggs $(timeToDate $eggs): $(describeEggs $eggs)."
    done
else
    echo "Alle Eggs er blevet bogført!"
fi
