#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Årets Spil 2014 - klappet og klart til julehandlen. 
# Prik til concieggs mellem en og fem gange! - 
# Men vær forsigtig. Pludselig eksploderer concieggs!
# Vinderen er den, som har prikket mest til concieggs, uden at udløse et raserianfald!
# SJOVT FOR ALLE MENNESKER I HELE VERDEN!

import subprocess
import sys
import os, time

from functools import partial
import itertools
import random
import re
import json
import operator

#ordbogens design:   {'forrigePrikker': <navn> , 'prikTilbage': <tal>, 'pointtavle': {navn:point}}


def run_main(args):
    antalPrik = parseArgs(args)
    try:
        oldDict = subprocess.check_output(["dbRead", "prikkeleg"])
    except:
        dict = {'forrigePrikker': 'concieggs' , 'prikTilbage' : random.randint(15, 30), 'pointtavle':{}}
        subprocess.call(["echo \'" + json.dumps(dict, ensure_ascii=False) + "\' | dbWrite prikkeleg"], shell=True)
        sys.exit(0)
    Dict = json.loads(oldDict.decode('utf-8'))

    user = os.getenv("EGGS_USER")
    if Dict['forrigePrikker'] == user:
        print("%s! %s, du prikkede mig også sidst. Dit træk er ugyldigt!" % (svin(), user))
        sys.exit(0)

    sys.stdout.flush()
    time.sleep(1)
    status = Dict['prikTilbage'] - antalPrik
    Dict['forrigePrikker'] = user
    if status <= 0:
        slutsekvens(user, Dict)
    Dict['prikTilbage'] = status
    try:
        Dict['pointtavle'][user] += antalPrik
    except KeyError:
        Dict['pointtavle'][user] = antalPrik
    subprocess.call(["echo \'" + json.dumps(Dict, ensure_ascii=False) + "\' | dbWrite prikkeleg"], shell=True)
    hvemFoerer(Dict['pointtavle'], False)



def slutsekvens(taber, dict):
    dict['pointtavle'].pop(taber)
    print("%s, %s! Du prikkede det forkerte sted på det forkerte tidspunkt, og har dermed tabt!" % (svin(), taber))
    sys.stdout.flush()
    time.sleep(1)
    hvemFoerer(dict['pointtavle'], True)


def hvemFoerer(dictionary, Vindersekvens=False):
    sorted_dict = sorted(dictionary.items(), key=operator.itemgetter(1))
    if sorted_dict == []:
        sorted_dict = [('concieggs', 'concieggs')]
    if Vindersekvens:
        vinder = sorted_dict[-1][0]
        print ("%s %s! Du har lige vundet i prikkeleg!! %s er den nye konge af #eggsml!" % (congrats() , vinder, vinder))
        subprocess.call(["randomName \'" + inner + "\' | dbWrite eggsking"], shell=True)
        dict = {'forrigePrikker': 'concieggs' , 'prikTilbage' : random.randint(15, 30), 'pointtavle':{}}
        subprocess.call(["echo \'" + json.dumps(dict, ensure_ascii=False) + "\' | dbWrite prikkeleg"], shell=True)
        subprocess.call(["runcmd topic " + vinder + " er kongen"], shell=True)
        sys.exit(0)
    else:
        print("%s er i spidsen - %s, %s! Du kan sagtens nå det!" % (sorted_dict[-1][0], heppe(), sorted_dict[0][0]))

def svin():
    grats = [
        "Så så man lige dig, hva'",
        "Pak sammen",
        "Lortesvin",
        "Du gør mig bare trist",
        "DNUR",
        "FØJ",
        "Dit skodøje",
        "Røvlort",
        "Dit fuckhoved",
        "Hvad bilder du dig ind?",
        "Din bøf"
    ]
    return grats[random.randint(0, len(grats)-1)]


def congrats():
    grats = [
        "Tillykke",
        "Novra",
        "Vildt,",
        "Sikke noget,",
        "Godt gået,",
        "Tjullahop,",
        "Super fedest,"
    ]
    return grats[random.randint(0, len(grats)-1)]

def heppe():
    grats = [
        "Heja",
        "Fremad",
        "Kom igen",
        "Op med modet",
        "Frem med humøret",
        "Nu gælder det",
        "Nu handler det om at se fremad",
        "Bare rolig"
    ]
    return grats[random.randint(0, len(grats)-1)]

def parseArgs(args):
    antalPrik = 0
    for arg in args:
        if arg.lower() in ["prikke", "prik"]:
            antalPrik += 1
    try:
        assert antalPrik < 6 and antalPrik > 0

    except:
        print("Du må da ikke prikke mere end fem gange! Eller mindre end éen gang.")
        sys.exit(0)
    return antalPrik

if __name__ == '__main__':
    run_main(sys.argv)
