#!/bin/sh
#
# Rejs en problematik.

if [ $# = 0 ]; then
    hvem=$(randomLine <<EOF
indvandrerne
svenskerne
bilisterne
jyderne
læsere af Weekendavisen
EOF
        )
else
    hvem="$@"
fi

lov=$(cat $CONCIEGGS_DB_DIR/danske-love | randomLine)

gpt4 400 "De nyeste statistikker viser at $hvem er overrepræsenterede i statistikkerne omkring brud på $lov. Giv en polemisk og patosfyldt og kortfattet analyse af hvorfor det kan være problemet. Husk at nævne både $hvem og $lov."
