#!/usr/bin/env python3

import requests

url = 'https://www.predictit.org/api/marketdata/markets/3698'
resp = requests.get(url=url)
data = resp.json()
candidates = data['contracts']

output = "Sandsynlighed for sejr ved præsidentvalget 3. november 2020:\n"
for candidate in candidates:
    
    # Skip the candidate that have less than 2 % chance to prevent spamming the channel
    if (candidate['lastClosePrice'] < 0.02):
        continue
    
    # if contract is new or price is unchanged
    if (candidate['lastClosePrice'] == None or candidate['lastClosePrice'] == candidate['lastTradePrice'] ):
        symbol = "\u2013" # ndash
        diff   = "+ 0.0"
    
    # If contract price is up
    elif (candidate['lastClosePrice'] < candidate['lastTradePrice']):
        symbol = "\x0309\u2191\x03" # green up arrow
        diff   = "\x0309+{:4.1f}\x03".format(100*(candidate['lastTradePrice'] - candidate['lastClosePrice']))
    
    # If contract price is down
    else:
        symbol = "\x0304\u2193\x03" # red down arrow
        diff   = "\x0304-{:4.1f}\x03".format(100*(candidate['lastClosePrice'] - candidate['lastTradePrice']))
    
    output += candidate['name'] + " {:4.1f} pct. ".format(100 * candidate['lastTradePrice']) + symbol +  " ({0})\n".format(diff)

print(output)
