#!/bin/sh
#
# Påhægt en af concieggs's kroge.

if [ $# -ne 1 ]; then
    echo "Brug: $0 <krog>"
else
    if ! [ "$(aliases "$EGGS_USER")" ]; then
        echo "$EGGS_USER: Beklager, denne kommando er kun for logemedlemmer."
        exit
    fi
    hook=$1
    if [ "$hook" = "alting" -o "$hook" = "alt" ]; then
        hooks=$(detachedHooks)
        if [ "$hooks" ]; then
            for hook in $hooks; do
                undetachHook "$hook"
            done
            echo "$(ack)  Jeg vil igen følge de anvisninger der evt. måtte optræde under $(echo $hooks | enumerate -n).  Fest i gaden!"
        else
            echo "$EGGS_USER: Alt synes allerede at være tilkoblet."
        fi
    else
        if isHookDetached "$hook"; then
            undetachHook "$hook"
            echo "$(ack)  Jeg vil igen følge de anvisninger der evt. måtte optræde under '$(echo "$hook" | enumerate -n)'."
        else
            echo "$EGGS_USER: $hook er skam allerede påhægtet."
        fi
    fi
fi
