#!/bin/sh
#
# Sig pøls' til concieggs. Ligesom i folkeskolen!

if maybeGood 0.2; then
    echo "$EGGS_USER: leverpostej!"
    pleasedBy "$EGGS_USER" 25
else
    echo "$EGGS_USER: Synes du selv du er sjov?"
    annoyedBy "$EGGS_USER"
fi
