#!/bin/sh
#
# Bed concieggs om at rette din opgave.

startkommentar() {
    opgave="$1"
    randomElement <<EOF
Hmm, $opgave er ikke helt i orden.
$opgave?  Hvad fanden er det for noget lort??
Nuvel, nuvel...
Du koder jo skinke.
Nu skal jeg fortælle dig hvad du gør forkert i $opgave.
Hip, hip, hurra, du skal til genaflevering, HAHA.
I $opgave koder du dårligere end min mor.
ÅH NEJ DU HAR AFLEVERET DIN AFFØRING.  Nånej, det er bare din aflevering, tihi.
Husk at fjerne debug prints. :)
EOF
}

operation() {
    randomElement <<EOF
addition
subtraktion
multiplikation
division
eksponentiation
EOF
}

navn() {
    randomElement <<EOF
foo
bar
compileExp
checkExp
t
x
syscall_halt
TLB
EOF
}

ting() {
    randomElement <<EOF
n startparantes
t gullaschtegn
n $(operation)soperator
n '$(navn)'-funktion
n '$(navn)'-variabel
n TLB
t filsystem
t systemkald
n concatMap
EOF
}

funktion() {
    randomElement <<EOF
map
foldl
foldr
concatMap
mapM
liftM2
EOF
}

snedigtTrick() {
    randomElement <<EOF
punktfri notation
fixpunktsiteration
monader
monadisk parsing
implicitte semikoloner
partiel evaluering
let-bindinger
EOF
}

linjenummer() {
    random 54 933
}

kommentarsaetning() {
    ting="$(ting)"
    randomElement <<EOF
Du mangler e$ting i din '$(navn)' på linje $(linjenummer).
Di$ting skal i stedet være e$(ting).
Husk endeligt at e$ting ikke må distribueres over *hele* funktionskroppen!
Di$ting kan ikke hedde '$(navn)'!
Du korrumperer di$ting i $(navn).
Din $(navn) kan forenkles ved brug af $(funktion).
Når du laver e$ting skal den altid efterfølges af e$(ting)!
Du kan med fordel gøre mere brug af $(snedigtTrick) når du skriver di$ting.
EOF
}

opgavekommentar() {
    nummer="$1"
    echo -n "Opgave $nummer: $(kommentarsaetning)"
    for _ in $(seq 1 $(random 1 3)); do
        echo -n "  $(kommentarsaetning)"
    done
    echo
}

opgave="$*"

startkommentar "$opgave"
for n in $(seq 1 $(random 1 3)); do
    opgavekommentar $n
done
