#!/bin/sh
#
# Injicér resultat i concieggs-monaden.

if checkCooldown "return" $((3600 * 24)); then
    echo "ConcieggsLint: Du kunne også bruge 'pure', ej at forveksle med 'puré' jf. Funktor-Applikativ-Monade-forslaget."
fi

echo -e "$@"
