#!/bin/sh
#
# Gør op med al dette fjollede monarki.

if [ "$1" = af ] && dbRead robespierre; then
    if dbRead dawkins; then
    	randomLine <<EOF
$EGGS_USER: Uden guddommelighed, hvordan kan kongen så få magten?
$EGGS_USER: Måske du skal tale med Hr. Dawkins om hvordan man bliver konge?
$EGGS_USER: Hvis magten ikke kommer fra folket?  Hvorfra så?!
$EGGS_USER: Nej!  Vi tror kun på Det Almægtige Væsen!
EOF
        exit
    fi
    if ! checkCooldown "robespierre" $((3600 * 24)); then
        echo "$EGGS_USER: Giv lige republikken en chance!"
        exit
    fi
    randomLine <<EOF
Længe leve kongen!
Ned med republikken, det var kun kaos!
Tæller Kejserriget som et Kongerige?  Men hvor om alting er har vi nu faktisk en Konge.
Wienerkongressen gav os kongen tilbage!
Bourbonerne er tilbage!
Giv Louis XVIII nøglerne til tronen!
EOF
# TODO: Lav en Wienerkongres-funktion, som udvælger en konge.
    sleep 1
	echo "Men øøøøh... hvem skal nu være konge?"
    dbDelete robespierre
else
    if dbRead robespierre; then
        echo "$EGGS_USER: Robespierre har altså taget sig af det tidligere kongerige.  Så han har nok også mistet hovedet."
        exit
    fi
    if ! checkCooldown "robespierre" $((3600 * 24)); then
        echo "$EGGS_USER: Giv lige Robespierre en chance, vi skal lige putte hovedet tilbage på ham først!"
        exit
    fi
    echo "$(ack)  Robespierre-tilstand aktiveret!"
    sleep 1
    if dbRead eggsking; then
        king=$(dbRead eggsking)
        randomLine <<EOF
Vive la revolution !
¡Viva la revolutión!
Kong ${king}s hoved røg i svinget!
Guillotinen fik ramt på $king.
Ingen Gud kan give nogen magten!  Kong $king er afsat, og det er tronen også!
Al magt kommer fra folket, ikke Gud!
Hvis blot King ${king} ikke havde været så skide ufleksibel.  Men hvor om alting er, er han og kongeriget dødt!
Kongen er død, længe leve republikken!
EOF
    fi
    dbDelete underArrest
    dbDelete vilvæltekongen
    revolution
    echo | dbWrite robespierre
fi
