#!/bin/sh
#
# Slå en terning... i cyberspace!

if [ $# -eq 0 ]; then
    echo "Nej, $EGGS_USER, sådan her: rul [N]dM"
else
    echo -n "/me ryster og slår "
    for d in "$@"; do
        echo $d
    done | gawk -F d 'BEGIN{srand()} /^([0-9]+)?d[0-9]+$/{ if ($1=="") { $1=1 } ;\
for (i=1; i<=$1; i++) { print int(rand()*$2)+1; } }' | enumerate
fi
