#!/bin/sh

set -f

awk_getargs='{ print substr($0, index($0, " "$2)+length($2)+2, length($0)) }'

eval "$(echo "$@" | parse '(?<rawcmd>.+)( til (?<addr>.+@.+))')"

cmd=$(echo "$rawcmd" | cut -d' ' -f 1)
args="$(echo "$rawcmd"|awk --posix "$awk_getargs")"

echo Send $cmd med $args til $addr

runcmd "$cmd" $args | mailx -s "Afvikling af $cmd $args" "$addr" -- -r concieggs@eggsml.dk
