#!/bin/sh
#
# Udfør en kommando og send resultatet via elektropost til den givne
# adresse.

set -f

eval "$(echo "$@" | parse '(?<rawcmd>.+)( til (?<addr>.+@.+|(?<twitter>(?:twitter|inter)?(?:nettet|tubes|webben)?)|spiltirsdag))')"

if [ "$rawcmd" ]; then
    if [ "$addr" = "spiltirsdag" ]; then
        addr="concieggs@spiltirsdag.dk"
    fi

    cmd=$(echo "$rawcmd" | cut -d' ' -f 1)
    args=$(echo "$rawcmd"| sed 's/[^ ]* *//')
    runcmd "$cmd" $args | \
        if [ "$twitter" != "" ]; then
            kvidr
        else
            echo "Sender $rawcmd til $addr!"
            sed s/\n/\r\n/g | mailx -r concieggs@eggsml.dk \
                                    -s "Afvikling af $rawcmd, anmodet af $EGGS_USER" "$addr"
        fi
else
    echo 'Brug: send <kommando> til <hvem@hvor>|hvad'
fi
