#!/bin/sh
#
# Informér logen om hvornår den angivne broder sidst har spist med, ud
# fra hvilket man kan udlede en vægtning af hans bidrag til debatten.


if [ $# -eq 1 ]; then
    user="$1"
elif [ $# -eq 0 ]; then
    user="$EGGS_USER"
else
    echo "Brug: sidste [navn]"
    exit
fi

sidste="$(eggstool lunches "$user" | head -n 1)"

if [ "$sidste" ]; then
    echo "$(randomName "$user") spiste sidst med for $(daysSince $sidste) siden."
else
    echo "$user har mig bekendt aldrig spist med."
fi
