#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Bed concieggs om hjælp til at sige det du føler.
# Brug sig <ting> til <person>
import sys
import os
from functools import partial
import itertools
import random

from eggsthon.url_open import request
from eggsthon.mediawiki import get_page_urls, get_paragraphs, get_sentences

def forklarSig():
    print "Brug kommandoen korrekt:"
    print "sig <ting> til <person>"


def run_main(args):
    user = os.getenv("EGGS_USER")
    args = map(lambda a: a.decode('utf-8', 'ignore'), args)
    me = os.getenv("CONCIEGGS_NAME")

    if len(args) != 4 or args[2] != "til":
        forklarSig()
    elif args[3] == me:
        print user + ": Hvis du vil mig noget, så sig det direkte."
    else:
        string = args[3] + ": " + user + " ville gerne sige " + args[1] + " " + args[2] + " dig."
        print string.encode('utf-8')

if __name__ == '__main__':
    run_main(sys.argv)
