#!/usr/bin/env python
# -*- coding: utf-8 -*-
#

import sys
import os
from functools import partial
import itertools
import random

from eggsthon.url_open import request
from eggsthon.mediawiki import get_page_urls, get_paragraphs, get_sentences

def forklarSig():
    print "Brug kommandoen korrekt:"
    print "sig <ting> <forholdsord> <person>"


def run_main(args):
    user = os.getenv("EGGS_USER")
    args = map(lambda a: a.decode('utf-8', 'ignore'), args)

    if len(args) != 4:
        forklarSig()
    else:
        string = args[2] + ": " + user + "ville gerne sige " + args[0] + " " + args[1] + " dig."
        print string.encode('utf-8')

if __name__ == '__main__':
    run_main(sys.argv)
