#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Bed concieggs om hjælp til at sige det du føler.
# Brug sig <ting> til <person>
import sys
import os
from functools import partial
import itertools
import random
from time import sleep

def fork_away():
    if os.fork():
        sys.exit()

def forklarSig():
    print "Brug kommandoen korrekt:"
    print "sig <ting> til <person>"


def run_main(args):
    user = os.getenv("EGGS_USER")
    args = map(lambda a: a.decode('utf-8', 'ignore'), args)
    me = os.getenv("CONCIEGGS_NAME")

    if len(args) < 2:
        print "NAL!"
    elif args[-2] != "til":
        forklarSig()
    elif args[3] == me:
        print user + ": Hvis du vil mig noget, så sig det direkte."
    else:
        sentence = " ".join(args[1:-2])
        string = args[-1] + ": " + sentence
        if random.randint(0,5):
            print string.encode('utf-8')
        else:
            fork_away()
            sleep(random.randint(20,40))
            print string.upper().encode('utf-8')
            print "AAAAAAAAAAAAAAAAAAAAAAAARGH!"
            sleep(random.randint(0,4))
            print "undskyld " + user.encode('utf-8') + ", jeg ved ikke lige hvad der gik af mig der."


if __name__ == '__main__':
    run_main(sys.argv)
