#!/bin/sh
#
# Bedre alt

random=`date '+%s'`
random=$((($random % 2) + 1))
args=""
if [ "$1" ]; then
    shift
    args=" $@"
fi
case $random in
    2)
        org=`$CONCIEGGS_DIR/cmds/autoviden$args`
        ;;
    *)
        org=`$CONCIEGGS_DIR/cmds/visdom$args`
        ;;
esac
if [ "$org" ]; then
    new=$org
    i=0
    while [ "$new" = "$org" ]; do
        new=$(echo "$org" | skinkefy)
        i=$(($i+1))
        if [ $i -gt 4 ]; then
            break
        fi
    done
    echo "$new"
else
    echo "Hm, tjah... næh."
fi
