#!/bin/sh
#
# Bedre visdom

random=`date '+%s'`
random=$((($random % 2) + 1))
#org="$(cat $CONCIEGGS_DB_DIR/fakta | grep -i ".*$1" | randomElement)"
#org=""
case $random in
    2)
        org=`./$CONCIEGGS_DIR/autoviden`
        ;;
    *)
        org=`./$CONCIEGGS_DIR/visdom`
        ;;
esac
#org=$(visdom)
if [ "$org" ]; then
    new=$org
    i=0
    while [ "$new" = "$org" ]; do
        new=$(echo "$org" | skinkefy)
        i=$(($i+1))
        if [ $i -gt 4 ]; then
            break
        fi
    done
    echo "$new"
else
    echo "Hm, tjah... næh."
fi
