#!/usr/bin/env perl
#
#

my $arg_string = join(" ", @ARGV);
print $arg_string, "\n";



#ting jeg vil have 
#(op|ned) for charmen = charmen(++|--)
#helt (op|ned) for charmen = charmen = 0|10
#skru charmen op på n = fejl hvis charmen >= n, ellers charmen n
#skru charmen ned på n = fejl hvis charmen <= n, ellers charmen n
