#!/usr/bin/env perl
#
#

use warnings;
use utf8::all;
use 5.012;

my $currentCharm = `checkCharmen`;
chomp($currentCharm);
my $arg_string = join(" ", @ARGV);
#if ($arg_string =~ /\s?charmen\s(op|ned)\spå\s(\d\d?)/)
#  {
#  SpecificCharme($currentCharm, $2, $1);
#  }

  given($arg_string)
    {
    when ( /helt\sop\sfor\scharmen/ ){ setCharm(10);}
    when (/helt\sned\sfor\scharmen/){ setCharm(0);}
    when (/op\sfor\scharmen/) { setCharm($currentCharm + 1) unless $currentCharm == 10;}
    when (/ned\sfor\scharmen/) { setCharm($currentCharm - 1) unless $currentCharm == 0;}
    when (/charmen\s(op|ned)\spå\s(\d\d?)/) {SpecificCharme($currentCharm, $2, $1);}
    default {exit(0);}
    }


sub SpecificCharme {
  my ($gammel, $ny, $op) = @_;
  if($ny > 10){
    printf("Søde ven. Jeg kan altså kun være charmende på en nul-til-ti-skala.");
    exit(0);
  }

  elsif ($op eq "op"){
    if ($gammel < $ny){
      setCharm($ny);}
    else{
      printf("Lige nu er jeg ${gammel} charmerende. Skal jeg forklare dig forskellen på \"op\" og \"ned\"?");
      }
    }
  else {
    if ($gammel > $ny){
        setCharm($ny);}
    else {
      printf("Lige nu er jeg ${gammel} charmerende. Skal jeg forklare dig forskellen på \"op\" og \"ned\"?");
      }
    }
}

sub setCharm{
    my $newVal = $_[0];
    system("setCharmen", $newVal);
    system("ppCharmen");
}
