#!/bin/sh
# Bring offentlig skam til de som nasser på deres logebrødre!

debtors () {
    $EGGS_LIB_DIR/eggstool.py $EGGS_DIR/slashdotfrokost balances \
        | sort -n | head -n 5 | awk '$1 < 0 { print $0, abs($1) "kr" }' \
        | cut -d' ' -f 2- | commasize
}

echo "Følgende misdædere er de største skyldnere til den ærede frokostloge: $(debtors)."
