#!/bin/sh
#
# Et forslag til næste film i Marvel-universet.

char1=$(random_marvel_character | toupper)
char2=$(random_marvel_character | toupper)
char3=$(random_marvel_character | toupper)

hyps="$CONCIEGGS_DB_DIR/dannet-utils/hyponyms"

# Only use hyperonyms with at least two hyponyms.
over="$(cut -d'<' -f2 $hyps | sort | uniq -c | sort -n | grep -v ' 1 ' | sed -E 's/ *[0-9]+ //' | grep -i "$1" | randomLine)"

if [ $# = 1 ]; then
    wanted_raw=$(grep -i $1 $hyps | randomLine)
else
    wanted_raw=$(randomLine < $hyps)
fi
wanted=$(echo "$wanted_raw" | cut -d'<' -f1 | toupper)
wanted_category_raw=$(echo "$wanted_raw" | cut -d'<' -f2)
wanted_category=$(echo "$wanted_category_raw" | toupper)
got=$(cat $hyps | fgrep "$wanted_category_raw" | randomLine | cut -d'<' -f1 | toupper)

randomLine <<EOF
$char1 og $char2 dyster om hvorvidt $wanted_category er $wanted eller $got!
Et fjendskab opstår mellem $char1 og $char2 når $char1 stjæler $wanted fra $char2, som så må nøjes med $got!
Det umage par $char1 og $char2 forenes i kampen mod at forhindre $wanted i at blive klassificeret som $wanted_category!
$char1 affyrer en stråle af energi mod $char2, men strålen rammer $wanted som forvandles til $got!
$char1 indleder forblændet et forhold med $char2 i håbet om at $char2 er $wanted, men så viser det sig at $char2 hele tiden var $got.
$char1 bryder med $char2 over uenigheder i etikken ved at bruge $got i stedet for $wanted når der skal bruges $wanted_category.
Konflikten spænder til når $char1 havde fået lovning på $wanted fra $char2, men $char2 så dukker op med $got!
Er $wanted virkelig $wanted_category?  $char1 og $char2 er ikke enige, men danner fælles front da $char3 ankommer med $got.
EOF
