#!/bin/sh
#
# Et forslag til næste film i Marvel-universet.

char1=$(random_marvel_character | toupper)
char2=$(random_marvel_character | toupper)
char3=$(random_marvel_character | toupper)

hyps="$CONCIEGGS_DB_DIR/dannet-utils/hyponyms"

# Only use hyperonyms with at least two hyponyms.
over="$(cut -d'<' -f2 $hyps | sort | uniq -c | sort -n | grep -v ' 1 ' | sed -E 's/ *[0-9]+ //' | grep -i "$1" | randomLine)"

if [ $# = 1 ]; then
    wanted_raw=$(grep -i $1 $hyps | randomLine)
else
    wanted_raw=$(randomLine < $hyps)
fi
wanted=$(echo "$wanted_raw" | cut -d'<' -f1 | toupper)
wanted_category_raw=$(echo "$wanted_raw" | cut -d'<' -f2)
wanted_category=$(echo "$wanted_category_raw" | toupper)
got=$(cat $hyps | fgrep "$wanted_category_raw" | randomLine | cut -d'<' -f1 | toupper)

randomLine <<EOF
$char1 og $char2 dyster om hvorvidt $wanted_category er $wanted eller $got!
Et fjendskab opstår mellem $char1 og $char2 når $char1 stjæler $wanted fra $char2, som så må nøjes med $got!
Det umage par $char1 og $char2 forenes i kampen mod at forhindre $wanted i at blive klassificeret som $wanted_category!
$char1 affyrer en stråle af energi mod $char2, men strålen rammer $wanted som forvandles til $got!
$char1 indleder forblændet et forhold med $char2 i håbet om at $char2 er $wanted, men så viser det sig at $char2 hele tiden var $got.
$char1 bryder med $char2 over uenigheder i etikken ved at bruge $got i stedet for $wanted når der skal bruges $wanted_category.
Konflikten spænder til når $char1 havde fået lovning på $wanted fra $char2, men $char2 så dukker op med $got!
Er $wanted virkelig $wanted_category?  $char1 og $char2 er ikke enige, men danner fælles front da $char3 ankommer med $got.
$wanted eller $got?  Dette er netop spørgsmålet i en voldsom konflikt der opstår mellem $char1 og $char2.
$char1 med $wanted møder $got's forkæmper $char2 i en episk konflikt der skal komme til at afgøre fremtiden for $wanted_category.
$char1 forklædt som $wanted infiltrerer en hemmelig organisation der spreder $wanted_category, men $char2 gennemskuer forklædningen!  Skulle $char1 have valgt $got i stedet?
Efter mange års konflikt mellem $char1 og $char2 indgås kompromis om at $wanted er lige så godt som $got.  Lige indtil $char3 blander sig...
$char1 og $char2 slapper af efter deres fælles bekæmpelse af $expected.  MEN UD AF DET BLÅ KOMMER SÅ $got!!!
$char1 har i årevis bevogtet statens dyrebare beholdning af $wanted, men i kulissen pønser $char2 på at stjæle alt $wanted, og erstatte det med det langt billigere $got.
$char1 cirkelsparker $char2, som smadrer ind i en lagerbygning fyldt med $wanted_category. $char2 ligger kvæstet mellem $wanted og $got, men får så en snedig idé...
For at stoppe $char1, rejser $char2 tilbage i tiden for at forhindre mødet mellem $char1 og $wanted. Men da $char2 kommer tilbage, er verden helt uden $wanted_category.
En udmattet $char1 ligger brak efter at have reddet byen fra $wanted, men ud af ingenting dukker $char2 pludselig op med $got.
EOF
