#!/bin/sh
# Afvikl SML-kode i gudernes SML-fortolker

if [ $# -eq 0 ]; then
   echo "$EGGS_USER: Jeg er bange for at jeg har brug for mere information."
   exit
fi

echo "$@" | cat "$CONCIEGGS_DIR/misc/sandbox.sml" - | timeout -s HUP 5s mosml -P full | tail -n +78 | head -n -1 | head -n 10
