#!/bin/sh
#
# Spild noget.  Jeg kan spilde penge, tid og ikke så meget andet lige nu.

run() {
    case $1 in
        tid)
            randomLine <<EOF
Jeg spilder hermed tid.
Okay, du bad om det.
/me sover lidt.
SNOOOOORK.
ZzzzZZZzzzzz
EOF
            sleep 5
            ;;
        *)
            randomLine <<EOF
Den må du selv lige fikse sammen, min ven. :)
Hmm, dét kan jeg ikke spilde, men måske kan du. ;-)
Jeg ved snart ikke...
EOF
    esac
}

run "$@"
