#!/bin/sh
#
# Den sjove stak!

nemklods() {
    randomLine <<EOF
\cC04rød klods
\cC12blå klods
\cC09grøn klods
EOF
}

middelklods() {
    randomLine <<EOF
\cC08gul klods
EOF
}

svarklods() {
    randomLine <<EOF
\cC01sort klods
EOF
}

point() {
    randomLine<<EOF
dejlig pære
rødt kirsebær
diskette
Mars-bar
EOF
}

generator() {
    randomLine <<EOF
$(nemklods)
$(nemklods)
$(nemklods)
$(nemklods)
$(nemklods)
$(middelklods)
$(middelklods)
$(middelklods)
$(svarklods)
$(svarklods)
\cC00$(point)
EOF
}


generateSomeBlocks() {
    numBlocks=$1
    output=""
    for i in $(seq 1 $numBlocks)
    do
        klods=$(generator)
        output="$output$klods\n"
    done
    echo $output
}

arg=$1
if [ "$arg" = "forfra" ]; then
    dbDelete stakken
    echo "Aye aye, $EGGS_USER! Jeg har ryddet stakken."
    exit
fi

stak=$(dbRead stakken)
if [ "$stak" ]; then
    echo "$stak"
else
    nyStak=$(generateSomeBlocks 20)
    echo "$nyStak" | dbWrite stakken
    echo "$nyStak"
fi

