#!/bin/sh
#
# Den sjove stak!

nemklods() {
    randomLine <<EOF
\000304rød klods
\000312blå klods
\000309grøn klods
EOF
}

middelklods() {
    randomLine <<EOF
\000308gul klods
EOF
}

svarklods() {
    randomLine <<EOF
\000301sort klods
EOF
}

point() {
    randomLine<<EOF
dejlig pære
rødt kirsebær
diskette
Mars-bar
EOF
}

generator() {
    randomLine <<EOF
$(nemklods)
$(nemklods)
$(nemklods)
$(nemklods)
$(nemklods)
$(middelklods)
$(middelklods)
$(middelklods)
$(svarklods)
$(svarklods)
\u000300$(point)
EOF
}


generateSomeBlocks() {
    numBlocks=$1
    output=""
    for i in $(seq 1 $numBlocks)
    do
        klods=$(generator)
        output="$output$klods\n"
    done
    echo $output
}



stak=$(dbRead stakken)
if [ "$stak" ]; then
    echo "foo"
    echo "$stak"
else
    echo "bar"
    nyStak=$(generateSomeBlocks 20)
    echo "$nyStak" | dbWrite stakken
    echo "$nyStak"
fi

