#!/bin/sh

sc0=$(curl -s -o /dev/null -w "%{http_code}" --connect-timeout 1 $1)
echo "$sc0"
case $sc0 in 3*)
    sc_follow=$(curl -L -s -o /dev/null -w "%{http_code}" --connect-timeout 1 $1)
    echo "Følger jeg denne, får jeg $sc_follow."
esac
exit 0;
