#!/usr/bin/env perl
#
# Lav stavekontrol på din foregående besked.

use 5.012;

use utf8::all;
use EggsML::Spellcheck;

use Env qw/EGGS_USER/;
use EggsML::EggsPI text => ['lastmsg'];

my $quiet = $ARGV[0] && $ARGV[0] eq "-q";

chomp(my $last = lastmsg());

if ($last) {
    my $result = EggsML::Spellcheck::spellcheck($last);

    if ($result ne $last) {
        printf("Rettet: <%s> %s\n", $EGGS_USER, $result);
    } else {
        print "$EGGS_USER: Det ser da fint ud.\n" unless $quiet;
    }
} else {
    print "$EGGS_USER: Men du har jo ikke sagt noget!\n" unless $quiet;
}
