#!/bin/sh
#
# Den er god den her - men du må sandsynligvis ikke bruge den.

auth=$(authedName)

if [ "$auth" = Athas ]; then
    sh -c "$*"
else
    echo "$EGGS_USER: Beklager, men du er ikke stor nok endnu."
fi
