#!/bin/sh
#
# CINEMATIC UNIver-na-na-na-na-BATMa...STAR WARS

# Udvid det her:

character=$(marvel characters limit=1 offset=$(random 0 1490) \
                | egrep -o '"name":"[^"]+"' | head -n 1 | cut -d '"' -f 4)

echo "$EGGS_USER: Min favorit fra MARVEL er selvfølgelig $character!"
