#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Lav mem af alting.  Brug: supermem TEKST...

import sys
import random
import eggsthon.shell as sheggs


alt = ' '.join(sys.argv[1:])

start = random.choice([
    'Se her',
    'Wow, kig',
    'Waaaaat',
    'Vildt nok',
    'Wupwup'
])

print '%s: %s' % (start, sheggs.makeMeme(alt)),
