#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Lav mem af alting.  Brug: supermem TEKST...

import sys
import eggsthon.shell as sheggs


alt = ' '.join(sys.argv[1:])

print 'Se her: %s' % sheggs.makeMeme(alt),
