#!/bin/sh
#
# Brug concieggs' tid på at svine folk til.
#
# Opfylder EggsML-standard #3331.  Standarden, defineret her, siger følgende:
#
#   Kommandoer ved navn 'svin' skal svine deres modtager(e).
#
# Prut!

. $CONCIEGGS_DIR/concieggs.conf

ass=$EGGS_USER

if [ $# -gt 0 ]; then
    swine="$1"
else
    echo "Brug: svin <navn> [til]"
    exit
fi

if [ "$swine" = "$irc_username" -o "$swine" = "dig" ]; then
    echo "$ass: Nej."
    annoyedBy "$EGGS_USER" 10 "tilsvinede mig"
    exit
fi

if [ "$2" = "sofistikeret" ]; then
    sviner() {
        echo "$swine: Eders moder."
    }
else
    sviner() {
        echo "$swine: Din mor!"
    }
fi

if isKing "$swine"; then
    echo "$EGGS_USER: Under ingen omstændigheder!  Det ville være majestætsfornærmelse."
else
    if ircChannel | grep -q '^#'; then
        sviner
    else
        sviner | sayTo "$CONCIEGGS_DEFAULT_CHANNEL"
    fi
fi
