#!/bin/sh
#
# Tag den store bog ned fra hylden og besku menneskehedens forfald.

any=''
for who in $(dbIterate "users" | sed 's!users/!!'); do
    reasons=$(annoyances "$who")
    if [ "$reasons" ]; then
        echo "$(randomName $who) $reasons."
        any=yes
    fi
done

if ! [ "$any" ]; then
    echo "$EGGS_USER: Ingen er skyldige i mine øjne."
fi
