#!/bin/sh
#
# Tag den store bog ned fra hylden og besku menneskehedens forfald.

any=''
for who in $(dbIterate "users" | sed 's!users/!!'); do
    name=$(randomName "$who")
    if ! [ "$name" ]; then
        name="$who"
    fi
    reasons=$(annoyances "$who")
    if [ "$reasons" ]; then
        echo "$name $reasons."
        any=yes
    fi
done

if ! [ "$any" ]; then
    echo "$EGGS_USER: Ingen er skyldige i mine øjne."
fi
