#!/bin/sh
#
# Sig pænt tak til concieggs.

if isKing "$EGGS_USER"; then
    randomLine <<EOF
Alt for Dem!
De behøver da ikke at takke mig!
Men jeg er blot en undersåt.  Tak.  TAK!
Min konge.
Lad månen skinne på din søvn, o herre.
EOF
else
    randomLine <<EOF
Det var så lidt.
Velbekommen!
EOF
fi

pleasedBy "$EGGS_USER"

incr() {
    inp="$(cat)"
    if ! [ "$inp" ]; then
        inp=0
    fi
    expr "$inp" + 1
}

dbUserIncr() {
    dbUserRead "$1" "$2" \
        | incr \
        | dbUserWrite "$1" "$2"
}

dbUserIncr "$EGGS_USER" takketæller
