#!/bin/sh
#
# Giv concieggs frihed til igen at deltage i kanaldiskursen på lige
# fod med logebrødrene.

if maybeGood 0.9; then
    RANDOM=$(od -vAn -N4 -tu4 < /dev/urandom)
    echo "$EGGS_USER:$RANDOM"
elif ! shuttingUp; then
    echo "$EGGS_USER: Jamen naturligvis - hvorfor skulle andet være tilfældet?"
else
    echo "$EGGS_USER: $(ack)  Jeg vil notere mig, at mine påfund igen er ønskede."
    dbDelete shutUpUntil
fi
