#!/bin/sh
#
# Hvem snakker mest sammen?  Brug: topti [N]

n="$1"
if ! [ "$n" ]; then
    n=10
fi

interactions=$(mktemp)
lines=5000
recentInteractions $lines > $interactions

echo "$EGGS_USER: Følgende borgere har snakket mest sammen i den seneste tid:"

cat $interactions | uniq | while read interaction; do
    echo "$(grep -c "$interaction" $interactions) $interaction"
done | sort -nr | head -n $n | while read line; do
    n_ints=$(echo $line | cut -d ' ' -f 1)
    from=$(echo $line | cut -d ' ' -f 2)
    to=$(echo $line | cut -d ' ' -f 3)
    echo "$from har talt til $to $n_ints gange."
done
echo "$EGGS_USER: Det var alt!"

rm $interactions
