#!/bin/sh
#
# Hvem snakker mest sammen?  Brug: topti [N_BACKLOGLINJER]

lines="$1"
if ! [ "$lines" ]; then
    lines=2000
fi
n=10

interactions=$(mktemp)
recentInteractions $lines > $interactions

echo "$EGGS_USER: Følgende borgere har snakket mest sammen på de sidste $lines linjer:"

cat $interactions | uniq | while read interaction; do
    echo "$(grep -c "$interaction" $interactions) $interaction"
done | sort -nr | head -n $n | while read line; do
    n_ints=$(echo $line | cut -d ' ' -f 1)
    from=$(echo $line | cut -d ' ' -f 2)
    to=$(echo $line | cut -d ' ' -f 3)
    echo "$from har talt til $to $n_ints gange."
done
echo "$EGGS_USER: Det var alt!"

rm $interactions
