#!/usr/bin/env ruby
# Encoding: UTF-8
# Foretag en søgning på Urban Dictionary.
# Er sidste tegn et heltal vil dette blive brugt til at bestemme antal resultater

require 'open-uri'
require 'uri'

class String
  def is_i?
    !!(self =~ /^[-+]?[0-9]+$/)
  end
end

if ARGV.length < 1
  puts "Jeg ved ikke hvad jeg skal søge på"
  exit(-1)
end

max_output = ARGV.pop.to_i if ARGV[-1].is_i?
max_output ||= 3

term = ARGV.join(" ")
page = URI.parse(URI.encode("http://www.urbandictionary.com/define.php?term=#{term}"))

results = []

begin
  doc     = page.read
  results = doc.scan(/div class=["']meaning["']>(.*?)<\/div/m).flatten!
rescue RuntimeError => e
  puts "Fejl ved forespørgsel til Urban Dictionary"
  $stderr.puts "Fejl: #{e}"
  exit(-1)
end

if results.empty?
  puts "Fandt ingenting..."
else
  begin
    results.take(max_output).each do |result|
      result.gsub!(/&quot;/, '"')
      result.gsub!(/\r/, '')
      result.gsub!(/<[^>]*>/, '') # Erstat html-tags med ingenting

      puts result.chomp
      sleep 1
    end
  rescue RuntimeError => e
    puts "Fejl ved udskrivelse af resultat"
    $stderr.puts "Fejl: #{e}"
    exit(-1)
  end
end
