#!/bin/sh
#
# Udskriv indkøbslisten i pænt format på den givne printer.  Gives
# intet argument bruges m1b.  Givet et argument der indeholder et @
# vil PDFen blive sendt som email til den givne adresse.


wishes=$(eggstool wishes)

if [ "$1" ]; then
    printer=$1
else
    printer=m1b
fi

if echo "$printer" | fgrep '@' > /dev/null; then
    mail="$printer"
elif echo "$printer" | egrep -v '^[a-z][0-9][a-z]$' > /dev/null; then
    echo "$printer?  Er det virkelig en printer?"
    exit
fi

formatWishes() {
eggstool wishes \
    | sort \
    | uniq -c \
    | sed -e 's/ *1 //' -e 's/ *//' -e "$(printf 's/^/.TP\\\n.B */')"
}

doc=$(cat <<EOF
.TH EGGSML 7 indkøbliste\-$(date +'%d/%m %Y')
.SH NAME
Indkøbsliste $(date +'%d/%m %Y')
.SH SYNOPSIS
.nh
EggsML < Netto
.SH DESCRIPTION
.SS Overview
Denne liste indeholder alt hvad der skal købes ind.  Som udgangspunkt
kan det forventes at alt på listen kan købes i Netto på Jagtvej.  Husk
at købe fornuftigt.
.SS Ønsker
.TP
$(formatWishes)
.SH BUGS
Nu og da er der udsolgt af visse varer.  Som workaround bør du efter
indkøb genindtaste de manglende varer på ønskelisten.
.SH SEE ALSO
.BR dnur (1)
EOF
)

process() {
    if [ "$mail" ]; then
        (   echo 'Find indkøbslisten vedhæftet.'
            uuencode indkøbsliste.pdf
        ) | mailx -r concieggs@eggsml.dk -s "Indkøbsliste til EggsML" "$mail"
        echo "Sender til $mail!"
    else
        ssh athas@brok.diku.dk 'lpr -P'"$printer"
        echo "Udskriver på $printer!"
    fi
}

if [ "$wishes" ]; then
    echo "$doc" \
    | groff -m mandoc -D utf8 -T pdf \
    | process
else
    echo "Nægter at udskrive: Der er ingen indkøbsønsker!"
fi
