#!/bin/sh
#
# Udskriv information om hvad der skal gøres hvis jeg er gået i udu.

echo "Hvis jeg er gået i udu, så må $(du $EGGS_USER) reparere mig.  \
Minimum Troels, Niels og Sebastian har adgang til at logge \
ind på min konto (concieggs) på eggsml.dk via deres SSH-nøgler."
echo "Der kan de køre 'tmux attach' for at få adgang til mig og se om \
jeg har skrevet nogle fejlmeddelelser, og evt. genstarte mig \
(tjek kommandohistorien for at se hvordan)."
echo "Det er også en god idé at gå ind på #eggsml-maskinrum, da det er \
der jeg skriver min standard error.  Hvis jeg ikke er på #eggsml-maskinrum, \
så er der mange kommandoer der ikke virker."
echo "Bemærk at jeg skal genstartes hvis min grundkode (concieggs-filen) \
ændres - kommandoer kræver dog ej en genstart."
