#!/bin/sh
#
# Udskriv information om hvad der skal gøres hvis jeg er gået i udu.

echo "Hvis jeg er gået i udu, så må du reparere mig.  \
Minimum Troels, Dybber og Lindbo har adgang til at logge \
ind på min konto (concieggs) på eggsml.dk via deres SSH-nøgler."
echo "Der kan de køre 'screen -r' for at få adgang til mig og se om \
jeg har skrevet nogle fejlmeddelelser, og evt. genstarte mig \
(tjek kommandohistorien for at se hvordan)."
echo "Bemærk at jeg skal genstartes hvis min grundkode (concieggs-filen) \
ændres - kommandoer kræver dog ej en genstart."
