#!/bin/sh
#
# Giv noget Markov-kædet grundlov.  Brug: ugrundlov [ANTAL ORD]

antal_ord="$1"

if ! [ "$antal_ord" ]; then
    antal_ord=40;
fi

if [ "$antal_ord" -gt 979 ]; then
    echo "$EGGS_USER: Jamen, det er jo et højt tal!"
    exit
elif [ "$antal_ord" -lt 1 ]; then
    echo "$EGGS_USER: $antal_ord ord?  Det er jo retsstridigt!"
    exit
fi

echo -n "§$(random 1 89), stk. $(random 1 5). "
markov "$antal_ord" grundlov "$CONCIEGGS_DB_DIR/grundloven/grundlov-markov-ready" | withSpaces
