#!/bin/sh
#
# Vi kender det alle: Vi har gjort nogen ked af det, og vi kan ikke
# finde ud af at sige undskyld.  Brug denne kommando til at få
# concieggs til at fungere som mellemmand for dine dybfølte
# undskyldninger.

from=$EGGS_USER

if [ $# -eq 1 ]; then
    to="$1"
else
    to="concieggs"
fi

if [ "$to" = "concieggs" ]; then
    if isInBadStanding "$EGGS_USER"; then
        if maybeGood .20; then
            pleasedBy "$EGGS_USER" 25
            removeFromBadStanding "$EGGS_USER"
            echo "$EGGS_USER: Så lad gå.  Men lad det ikke gentage sig!"
        else
            echo "NEJ!  Jeg er stadig pisse vred."
        fi
    else
        echo "Aldrig i livet.  Jeg vil aldrig tilgive dig for hvad $(du $EGGS_USER) har gjort!"
        maybeGood .1 && sleep 3 && echo "... Ahr, okay så, $(du $EGGS_USER) er tilgivet!" && pleasedBy "$EGGS_USER" 25
    fi
    exit 0
fi

undskyldninger() {
    echo "Kære $to... $from ved ikke hvordan han skal få det sagt, men har det virkelig dårligt med sin hidtidige opførsel, og håber at $(du $to) kan finde tilgivelse i dit hjerte."
    echo "$to, kender $(du $to) det når man har en følelse i sit hjerte der gør så ondt, men man ikke kan finde ord til at formulere den, så den kan komme ud?  Sådan har $from det med sin opførsel over for dig."
    echo "$to, $from har det skidt med sin opførsel, og vil gøre hvad som helst for at gøre det godt igen - f.eks. lave dine HCI-afleveringer."
    echo "$to, $from ved godt at han har lavet en Nederen-Jesper, men håber at $(du $to) kan lave en Dybber og vise tilgivelse."
    echo "$from føler sig som en der har valgt at lave machine learning-øvelser i C, $to, og beder fra hjertet om tilgivelse og forståelse, selvom han godt ved at han ikke fortjener det."
    echo "$to, jeg har en besked fra $from... han har det som en bamse der er kommet til at spise al honningen, men vil virkelig gerne være ven igen."
}

u="$(undskyldninger $1 $2 | randomElement)"
if [ "$u" ]; then
    echo "$u"
fi
