#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Bedre program end google.

import subprocess
import sys
import os
from functools import partial
import itertools
import random
import urllib2
import re
import xml.etree.ElementTree as ET
from lxml import html

def run_main(args):

    (maengde, fraValuta, tilValuta) =  parseArgs(args)
    tilPrEenFra = skafPris(fraValuta, tilValuta)
    beloeb = maengde * tilPrEenFra

    user = os.getenv("EGGS_USER")
    if user is None:
        user = "min ven"
    print "Tillykke %s, du kan købe %.*f %s for %s %s" %  (user, 2,  beloeb, tilValuta.upper(), re.sub("\.0*$","",dine(maengde)), fraValuta.upper())

def dine(nummer):
    if nummer == 1:
        return "din ene"
    else:
        return "dine " + str(nummer)

#Hej Svip!


def parseArgs(args):
    args = args[1:]
    try:
        maengde   = float(args[0])
        fraValuta = args[1].lower()
        tilValuta = args[3].lower()
        assert (args[2] in ["i", "til", "blev", "bliver", "som"])
    except:
        fejl()
        sys.exit(0)
    return (maengde, fraValuta, tilValuta)

def fejl():
    print "Brug 'valuta <beløb> <valutatype> <ord> <valutatype>.'"

def skafPris(fraValuta, tilValuta):
    opener = urllib2.build_opener()
    opener.addheaders = [('User-agent', 'Mozilla/5.0')]
    list = opener.open("http://finance.yahoo.com/q?s=" + fraValuta + tilValuta +  "=X")
    content = list.read()

    try:

        tilPrEenFra = content.split('<span id="yfs_l10_' + fraValuta + tilValuta + '=x">')[1].split('<')[0]
        tilPrEenFra = tilPrEenFra.replace(",",".")
        points = tilPrEenFra.count(".")
        if points > 1:
            tilPrEenFra = tilPrEenFra.replace(".","", 1)
        return float(tilPrEenFra)
    except:
        print "Det ser ud til, at du har forsøgt at regne i valutaer, som IKKE EKSISTERER!"
        sys.exit(0)
if __name__ == '__main__':
    run_main(sys.argv)
