#!/bin/sh
#
# Uddel et enkelt kvantum af den opsamlede visdom.


visdom="$(cat $CONCIEGGS_DB_DIR/fakta | grep -i ".*$1" | sort -R | head -n 1)"
if [ "$visdom" ]; then
    echo $visdom
else
    echo "Hm, tjah... næh."
fi
