#!/bin/sh
#
# Gør et emne sjovere.

emne="$1"

uppercase() {
    # TODO: Make nice.
    $CONCIEGGS_LIB_DIR/filters/grel
}

unwords() {
    python -c 'import sys; sys.stdout.write("\n".join(sys.stdin.read().split()))'
}

words() {
    read word
    echo -n $word
    while read word; do
        echo -n " $word"
    done
}

m() {
    for i in $(seq 0 $(random 0 7)); do
        echo -n $1
    done
}

druk() {
    randomElement <<EOF
HiK
br$(m æ)rk
L$(m O)$(m o)rt
T$(m I)h$(m i)h$(m i)
skinke$(m n)
EOF
}

runcmd autoviden $emne | unwords | head -n 10 | {
    while read word; do
        rand=$(python -c 'import random; print random.randint(0, 2)')
        case $(expr $rand % 4) in
            0)
                echo $word;;
            1)
                druk;;
            2)
                echo $word | uppercase;;
        esac
    done
    randomElement <<EOF
Bl$(m u)r$(m R)CH!
Wr$(m ou)eh.
EOF
} | words
