#!/bin/sh
#
# Vælt kongen hvis I er nok!

if [ "$#" = 0 ]; then
    echo "$EGGS_USER: Vælt hvad?  Et glas vand?  Læsset?  På dansegulvet?  Richard Stallman?  ...Kongen?"
    exit
elif [ "$1" != "kongen" ]; then
    echo "$EGGS_USER: $(ack)  Vi siger bare at $@ er væltet."
    exit
fi

if isArrested "$EGGS_USER"; then
    echo "$EGGS_USER: Du prøver at vælte kongen, men indser at du sidder i kachotten."
    exit
fi

if dbRead robespierre; then
	echo "$EGGS_USER: Jeg ved ikke om du har hørt, men der er altså republik nu.  Og bare rolig, der kommer ingen Første Borger, Fyrstebeskytter eller Kejser i stedet..."
	exit
fi

kingname="$(dbRead eggsking)"
if [ -z "$kingname" ]; then
    echo "$EGGS_USER: Uagtet dit ønske om at gøre oprør mod 'manden', så er tronen allerede ganske tom."
    exit
fi

rebel="$(randomName "$EGGS_USER")"

if ! [ "$rebel" ]; then
    echo "$EGGS_USER: Ingen udefrakommende indblanding i intern logepolitik, tak."
    exit
fi

if isKing "$rebel"; then
    echo "Ærede majestæt, det ville være upassende hvis De skulle begå attentat mod eget embede.  Hvad vil folket ikke tænke?"
    exit
fi

if vilVælteKongen "$rebel"; then
    echo "$EGGS_USER: Du har allerede meldt dig under tricoloren.  Det kan anbefales at dirigere al denne energi mod at hverve medsammensvorne."
    exit
fi

if harStøttet "$rebel"; then
    echo "$EGGS_USER: Du beslutter dig for at forræde Kongen!"
    fjernStøtte "$rebel"
    sleep 2
    if $(random 1 4) = 4; then
        echo "Kongen er skuffet.  Du var smartere end ham denne gang, men ikke næste gang."
    else
        echo "... Tænk at du troede at det kunne lykkedes.  Du er arresteret."
        arrestUser "$rebel"
        exit
    fi
fi

echo "$rebel" | dbWriteAppend vilvæltekongen

v="$(dbRead vilvæltekongen | wc -l | sed 's/ //g')"
s="$(dbRead vilstøttekongen | wc -l | sed 's/ //g')"

if [ $(expr "$v" - "$s") -gt $(random 3 5) ]; then

    newKing=$(dbRead vilvæltekongen | randomLine)

    revolution

    randomLine <<EOF
KONGEN ER VÆLTET!
Kongen er død!  Længe leve anarkiet!
Kongen er smidt på porten!  Knap en bajer op!  Knap to bajere op!
¡Viva la revolución!
"Manden" er nu på SPANDEN!  Byd anarkiet velkomment!
EOF

    if [ "$newking" -a $(random 1 4) = 4 ] && isTrusted "$newking"; then
        sleep 2
        echo "Men hvad er nu dette?  $newking griber magten!  Længe leve den nye konge!"
        makeKing "$newking"
    fi
else
    revolutionærHandlingMedAI
    echo "Kun $v har meldt sig under den revolutionære fane!  I skal være flere!"
fi
