#!/bin/sh
#
# Vælt kongen hvis I er nok!

if isArrested "$EGGS_USER"; then
    echo "$EGGS_USER: Du prøver at vælte kongen, men indser at du sidder i kachotten."
    exit
fi

if [ "$#" = 0 ]; then
    echo "$EGGS_USER: Vælt hvad?  Et glas vand?  Læsset?  På dansegulvet?  Richard Stallman?  ...Kongen?"
    exit
elif [ "$1" != "kongen" ]; then
    echo "$EGGS_USER: $(ack)  Vi siger bare at $@ er væltet."
    exit
fi

kingname="$(dbRead eggsking)"
if [ -z "$kingname" ]; then
    echo "$EGGS_USER: Uagtet dit ønske om at gøre oprør mod 'manden', så er tronen allerede ganske tom."
    exit
fi

rebel="$(randomName "$EGGS_USER")"

if ! [ "$rebel" ]; then
    echo "$EGGS_USER: Ingen udefrakommende indblanding i intern logepolitik, tak."
    exit
fi

if isKing "$rebel"; then
    echo "Ærede majestæt, det ville være upassende hvis De skulle begå attentat mod eget embede.  Hvad vil folket ikke tænke?"
    exit
fi

harVaeltet() {
    dbRead vilvæltekongen | {
        while read user; do
            if cmpNames $rebel $user; then
                exit 0
            fi
        done
        exit 1
    }
}

if harVaeltet; then
    echo "$EGGS_USER: Du har allerede meldt dig under tricoloren.  Det kan anbefales at dirigere al denne energi mod at hverve medsammensvorne."
    exit
fi
echo "$rebel" | dbWriteAppend vilvæltekongen

v="$(dbRead vilvæltekongen | wc -l | sed 's/ //g')"

if [ "$v" -gt $(random 3 5) ]; then

    newKing=$(dbRead vilvæltekongen | randomLine)

    revolution
    dbDelete vilvæltekongen

    randomLine <<EOF
KONGEN ER VÆLTET!
Kongen er død!  Længe leve anarkiet!
Kongen er smidt på porten!  Knap en bajer op!  Knap to bajere op!
¡Viva la revolución!
"Manden" er nu på SPANDEN!  Byd anarkiet velkomment!
EOF

    if [ "$newking" -a $(random 1 4) = 4 ] && isTrusted "$newking"; then
        sleep 2
        echo "Men hvad er nu dette?  $newking griber magten!  Længe leve den nye konge!"
        makeKing "$newking"
    fi
else
    navn="$(randomLine <<EOF
Frederik
Knud
Niels
EOF
)"

    god_attribut="$(randomLine <<EOF
Gode
Barmhjertige
Glædelige
EOF
)"

    randomLine <<EOF
Du ser en gammel film.
Du bagtaler Kongen på en bar.
Du planlægger en retningsbestemt slotseksplosion.
Du lægger dit hoved i blød.
Du drømmer dig langt væk.
Du tager dit sværd ud af kisten.
Du læser en bog skrevet af en gut i fængsel.
Du skriver et langt digt.
Du går rundt og råber bandeord i en hel time.
Du putter rottegift i slotsvinen.
Du sender et brev om hjælp til en nærliggende republiks præsident.
Du øver dig i at ride på hest.
Du bestiller en guillotine fra et postordrekatalog.
Du tænker søde tanker om din familie i den frie naborepublik.
Du griner ad regentens nytårstale.
Du lytter til kontra-revolutionær musik på den lokale smugkro.
Du lyver i din selvangivelse.
Du tegner overskæg på et portræt af kongen.
Du hvisker »det svin« om Kongen til dig selv, mens Hans parade går forbi.
Du dukker ikke op til Kongens fødselsdagsparade.
Du tisser op ad slotsmuren.
Du polerer dine støvler.
Du prutter i retning ad slotsbygningen.
Du hænger et billede op af Kongen på dit toilet.
Du vender hjem fra et studieophold i en fjern republik.
Du spytter dristigt på skiltet af en hofleverandør af hvidtøl.
Ved Hendes Majestæts dronningens officielle helligdag prutter du højlydt på et offentligt toilet.
Du spiser en af prinsessens kælekaniner til aftensmad.
På dit arbejde hos den lokale smed imprægnerer du en slap tissemand på prinsens nye sværd.
Ved pudsning af en royals lædersko smører du med friskt snot i stedet for skosværte.
Du lytter til din farfars gamle historier om kong ${navn} den ${god_attribut}.
Du står med oprejst pande og ser en særligt satirisk dukketeaterforestilling.
Dagen før kongens jagt fodrer du hestene med din onkels ufiltrerede whisky.
Du graver den metaforiske stridsøkse op.
Du slagter en ged, lægger gedehovedet ved slottets indgang, og bruger gedeblodet til at male et uflatterende maleri af kongens voksne søn.
Du placerer en bombe under en af kongerigets mange royale stenbroer og sætter dig til at vente.
Du navngiver dit nye æsel efter Dronningen.
Ved din aftenbøn beder du Gud om at slagte Kongen.
Du tisser i voldgraven.
Du polerer kronprinsens nye skjold med snot.
Du drikker dig fuld på Kongerigets mindst hygiejniske bar og kaster op på et lovkravsmaleri af Kongen på hest.
Du starter en industriel revolution og håber på det bedste.
Du forfatter en uafhængighedserklæring for din nye republik med hovedsæde lige uden for slottet.
Du betaler ikke nok i skat.
Du deltager i det månedlige revolutionsmøde i kloakken.
Du opfinder journalisthvervet og opretter en kongekritisk avis.
Du brænder dit hus ned.  Nu er der ikke længere nogen bånd til din tidligere tilværelse som trællebonde.  Nu kan du fuldt ud vie dit liv til at omdanne dit elskede land til en ægte republik.
Ved betaling af skat konstruerer du en hul guldbarre med en lort indeni.
Du sender ukritisk breve til samtlige andre nationers overhoveder og spørger om de vil hjælpe til med en blodig revolution.
Du kigger i en tyk bog og bliver sur fordi du ikke har fået skoling og er analfabet.
Du smadrer et butiksvindue så du bliver fængslet i slotskælderen, hvorefter du prøver at overbevise fængselsvagterne om fordelene ved din demokratiske ideologi.
Du smækker hårdt med døren efter du har klippet prinsessens hår.
Du går på strejke, velvidende at det giver dødsstraf.
Du laver en tegneserie hvori Kongen dør af at have spist for meget god mad.
Du kigger dig selv i dit stjålne messingspejl og øver hårde grimasser.
Du introducerer en fatal bygningsfejl i Kongens nybestilte voldgravsbroløftesystem.
Du flytter i eksil og får nogen andre til at vælte Kongen.  Det her gider du sgu ikke at ofre dit liv på.
EOF
    echo "Kun $v har meldt sig under den revolutionære fane!  I skal være flere!"
fi
