#!/bin/sh
#
# Bed concieggs om at være på en bestemt led.  Brug: 'vær MÅDE' eller 'vær mod
# BRUGER MÅDE'.  Der er mange MÅDER.

if [ ! "$1" ]; then
    echo "Du mangler en væremåde."
    exit
fi

if [ "$1" = mod ]; then
    file=outfilter_command_$2
    shift 2
else
    file=outfilter_command
fi

case "$*" in
    normal)
        exit
        ;;
    "ultra grinern")
        echo 'filter grinern';;
    *)
        s='translate da'
        while [ "$1" ]; do
            lc=$(langcode "$1")
            if [ $? == 0 ]; then
                s="$s $lc"
            else
                echo "$lc er ikke et sprog!"
                exit
            fi
            shift
        done
        echo "$s"
esac | dbWrite $file
