#!/bin/sh
#
# Bed concieggs om at være på en bestemt led.  Brug: 'vær MÅDE' eller
# 'vær MÅDE mod BRUGER' eller 'vær MÅDE på KANAL'.  Der er mange MÅDER.

eval "$(echo "$@" | parse '^(?<additive>også )?(?<what>.+?)(?: (?:mod|på) (?<specific>#?[^\s/]+))?$')"

if [ ! "$what" ]; then
    echo "Du mangler en væremåde."
    exit
fi

if [ "$specific" ]; then
    if [ "$specific" = "mig" ]; then
      specific=$EGGS_USER
    fi
    file=outfilter_command_$specific
else
    file=outfilter_command
fi

save() {
    echo "$1" | dbWrite $file
    echo "$(ack)  Væremåden er sat!"
}

case "$what" in
    # Gå tilbage til normal kedsomhed.
    normal)
        save '';;

    # Specielle ord.
    "ultra grinern")
        save 'filter grinern';;
    1337)
        save 'filter leet';;
    "på bodega")
        save 'filter bodega';;
    "min")
        echo "Måske senere...";;
    "dig selv")
        echo "Bare rolig, jeg ignorerer gruppepres.";;

    # Sprog el.lign.
    *)
        if [ "$additive" ]
            then s="$(dbRead $file)"
                 s="${s:-translate da}"
            else s='translate da'
        fi


        for lang in $what
        do
            lc=$(langcode "$lang")
            if [ "$lc" != '' ]; then
                s="$s $lc"
            else
                echo "$lang er ikke et sprog!"
                exit
            fi
        done
        save "$s"
esac
