#!/bin/sh
#
# Bed concieggs om at være på en bestemt led.  Brug: 'vær MÅDE' eller
# 'vær MÅDE mod BRUGER' eller 'vær MÅDE på KANAL'.  Der er mange MÅDER.

eval "$(echo "$@" | parse '^(?:(?<additive>også)|(?<prepend>først)|(?<negate>ikke) )?(?<what>.+?)(?: (?:mod|på) (?<specific>#?[^\s/]+))?$')"

if [ ! "$what" ]; then
    echo "Du mangler en væremåde."
    exit
fi

if [ "$specific" ]; then
    if [ "$specific" = "mig" ]; then
      specific=$EGGS_USER
    fi
    file=filterchain_$specific
else
    file=filterchain
fi

save() {
    new="$*"
    while read forbidden; do
        is_forbidden=1
        for lang in $forbidden; do
            if ! echo "$new" | egrep -q "\<$lang\>"; then
                is_forbidden=''
                break
            fi
        done
        if [ "$is_forbidden" ]; then
            break
        fi
    done <<EOF
fraktur vildere
EOF
    if [ "$is_forbidden" ]; then
        echo "Nej tak, den kombination bringer kun ulykke."
    else
        s="$(dbRead $file)"
        if [ "$new" = "$s" ]; then
            if [ "$new" = '' ]; then
                new=normal
            fi
            echo "Jamen jeg er jo allerede $new!"
            annoyedBy "$EGGS_USER" 2 "bad mig være på en måde jeg allerede var"
        else
            echo "$new" | dbWrite $file
            echo "$(ack)  Væremåden er sat!"
        fi
    fi
}

if [ "$negate" ]; then
    for lang in $what; do
        s="$(echo $s | sed "s/\<$lang\>//g")"
    done
    save $s
    exit
fi

case "$what" in
    # Gå tilbage til normal kedsomhed.
    normal)
        save '';;

    # Specielle ord.
    "min")
        echo "Måske senere...";;
    "dig selv")
        echo "Bare rolig, jeg ignorerer gruppepres.";;

    # Sprog el.lign.
    *)
        if [ ! isChristmas ] && echo "$what" | grep -qi "grinch"; then
            echo "Det kan jeg kun finde ud af i nogle uger omkring vintersolhverv :("
            exit
        fi

        if echo "$what" | grep -q '?'; then
          what=$(echo "$what" | perl -pe 'use EggsML::EggsPI text => [qw(randomFilter)]; s/(^| )\?(?= |$)/"$1".randomFilter/eg')
        fi

        if [ "$additive" ]; then
            s="$(dbRead $file)"
        else
            s=''
        fi

        for lang in $what
        do
            if isFilter $lang; then
                s="$s $lang"
            else
                echo "$lang er bare overhovedet ikke en væremåde eller et sprog!"
                tilbyde=$(randomLine <<EOF
tilbyde
foreslå
EOF
                       )
                adjektiv=$(randomLine <<EOF
gode
dejlige
pæne
flotte
velbrugte
EOF
                        )
                echo "Jeg kan i stedet $tilbyde den $adjektiv væremåde '$(randomFilter)'."
                exit
            fi
        done

        if [ "$prepend" ]; then
            s="$s $(dbRead $file)"
        fi

        save $s
esac
