#!/usr/bin/env bash

# Almanak (4)

# Lufttemperatur (3)

# Vandtemperatur (1)
echo -n "Zugersee:  "
curl -s "https://www.badi-info.ch/_temp/ww/zugsee.htm" | ggrep -Poz '(?<=<b>).*?(?=</b>)'
echo " °C."

# Pollen (2)
echo $(pollen $@) # argumenterne ender i rendestenen.


# UV index (5)
