#!/usr/bin/env python
#
# concieggs sender indhold fra TV 2 Zulus online-stream direkte til IRC-kanalen.

import time, sys, subprocess, random

sandsynligheder = [1] * 2 + [2] * 5 + [3] * 3 + [4] * 1
def run_main(args):
    i = random.choice(sandsynligheder)
    while (i >= 0):
        subprocess.call(["runcmd hurtighumor"], shell=True)
        time.sleep(random.randint(1,3))
        i -= 1
        sys.stdout.flush()
    sys.exit(0)


if __name__ == "__main__":
    run_main(sys.argv)
