#!/bin/sh
#
# Udskriv en liste over de nuværende indkøbsønsker

wishes=$($EGGS_LIB_DIR/eggstool.py $EGGS_DIR/slashdotfrokost wishes | enumerate)

if [ "$wishes" ]; then
    echo "Indkøbsønsker: $wishes."
else
    echo "Bred ymer!  Der er ingen indkøbsønsker!"
fi
