#!/bin/sh
#
# Tilføj til listen over indkøbsønsker.  Kun katalogmuligheder tillades!


if [ $# -lt 1 ]; then
    echo "Brug: ønsk ønske..."
else
    what="$@"
    there="$(checkCatalogue "$what")"
    if ! [ "$there" ]; then
        echo "$EGGS_USER: '$@' er ikke i kataloget.  Prøv min 'katalog'-kommando for at se hvad der er af muligheder, eller brug 'kanoniser' til at tilføje en ny."
        exit
    fi
    $CONCIEGGS_DIR/cmds/unsafePerformRåønsk "$there"
fi
