#!/usr/bin/env bash
#
# Hør første vers af den nye sang fra østkyst hustlers

if [ $# = 0 ]; then
    echo "$EGGS_USER: Hør hvad en politiker mener om et emne (på Guds eget sprog)"
    exit
fi

songname=$@

prompt="Her er de første par linjer fra sangen \"Han får for lidt\":
Han spejler sig i spejlet
For hans spejl er hans ven
Han kender hud og kinder
Ud og ind og ud igen
Han holder ormegården nede
Sætter bumser under pres
Og med pincet er det let
At holde brynene på plads
Og skægget står totalt
Som var det målt med lineal

Her er de første par linjer fra sangen \"$songname\":
"

answer=$(gpt3 $((${#subject} + 100)) "$prompt")

if [ "$answer" ]; then
    echo "$EGGS_USER: Her er de første par linjer fra sangen \"$songname\":
$answer"
else
    echo "$EGGS_USER: Beklager, kunne ikke finde den efterspurgte sang"
fi
