#!/bin/sh

ircJoinChannel "$CONCIEGGS_ERROR_CHANNEL"
ircJoinChannel "$CONCIEGGS_DEFAULT_CHANNEL"

dbIterate "channels" | while read channel; do
                           ircJoinChannel "$channel"
                       done
