#!/bin/sh

ircJoinChannel "$CONCIEGGS_ERROR_CHANNEL"
ircJoinChannel "$CONCIEGGS_DEFAULT_CHANNEL"

dbIterate "channels" | while read channel; do
                           ircJoinChannel "$(echo "$channel" | cut -d '/' -f 2)"
                       done
