#!/usr/bin/env python
# vim: set fileencoding=utf-8 :
# Forklar en mening samt brødrenes holdning til denne.

import simplejson as json
from os import environ, path
from sys import exit
import sys


def main():
    if len(sys.argv) < 2:
        print "Du skal give et navn på en mening."
        exit(0)

    mening = sys.argv[1]
    meningl = mening.lower()

    datafile = path.join(environ['CONCIEGGS_DB_DIR'], 'meningstats')

    if not path.exists(datafile):
        f = open(datafile, 'w+')
        f.write('{}')
        f.close()

    dbfile = open(datafile, 'r')
    db = json.load(dbfile)
    dbfile.close()

    if not meningl in db:
        print "Jeg kender ikke til %s." % mening
        exit(0)

    print "%s (%.3f/10): %s" % (db[meningl]['kortNavn'],
                                db[meningl]['gennemsnit'],
                                db[meningl]['beskrivelse'])

if __name__ == '__main__':
    main()
