#!/usr/bin/env python
# vim: set fileencoding=utf-8 :
# En ny mening er spottet!

import simplejson as json
from os import environ, path
from sys import exit
import sys


def main():
    if len(sys.argv) < 2:
        print "Du skal give meningen et navn.  Ex: nymening redhead Hende den rødhårede"
        exit(0)

    mening = sys.argv[1]
    meningl = mening.lower()

    datafile = path.join(environ['CONCIEGGS_DB_DIR'], 'meningstats')

    if not path.exists(datafile):
        f = open(datafile, 'w+')
        f.write('{}')
        f.close()

    dbfile = open(datafile, 'r')
    db = json.load(dbfile)
    dbfile.close()

    if meningl in db:
        print "Vi har allerede den mening liggende!"
        exit(0)

    db[meningl] = {
        'kortNavn': mening,
        'fuldtNavn': mening,
        'beskrivelse': 'Ingen info.',
        'vurderinger': {},
        'gennemsnit': 0,
        'billeder': {}
    }

    dbfile = open(datafile, 'w')
    json.dump(db, dbfile)
    dbfile.close()
    print "$(ack)  %s er nu oprettet i logeprotokollen." % mening
    dbfile.close()

if __name__ == '__main__':
    main()
