#!/bin/sh
#
# Afvikl SML-kode i gudernes SML-fortolker

echo "$EGGS_USER: Desværre - denne kommando er et gerningssted, så den er afskærmet med polititape."
annoyedBy "$EGGS_USER"
exit

if [ $# -eq 0 ]; then
   echo "$EGGS_USER: Jeg er bange for at jeg har brug for mere information."
   exit
fi

runSML "$@"
