#!/bin/sh
#
# Gem at en person er gået ud.

ON_CHANNEL=$(dbRead "on_channel/$EGGS_WHERE")
for name in $ON_CHANNEL; do
  if [ "$name" != "$EGGS_USER" ]; then
    echo $name
  fi
done | dbWrite "on_channel/$EGGS_WHERE"
