#!/bin/sh

(notOnEggsChannel || shuttingUp) && exit
[ "$EGGS_USER" = "$CONCIEGGS_NAME" ] && exit

time=$(dbUserRead "$EGGS_USER" eggsactly)
if [ "$time" ]; then
    if [ "$(expr $(nowTime) - $time)" -lt $(expr 5 '*' 60) ]; then
        echo "$(randomName $EGGS_USER) har begået en Reenberg!"
        echo "$(nowTime)" | dbUserWrite "$EGGS_USER" reenberg/when
        echo "$(expr $(nowTime) - $time)" | dbUserWrite "$EGGS_USER" reenberg/loss
    fi
fi
