#!/bin/sh

set -e

onEggsChannel || exit

[ "$EGGS_USER" = "$CONCIEGGS_NAME" ] && exit

maybeGood .9 || exit


user=$EGGS_USER
lookupDebt $user | grep -vq '\-' || exit

penge=`randomLine <<EOF
penge
moneter
danske kroner
Danskens Valuta
gysser
mønter
kronesedler
EOF`

randomLine <<EOF
/me ved at $user er i negativ.
Hmm... Med alle de $penge $user skylder, får vi mon $user at se igen?
$user: Du skylder pengeeeeeee.  Så smutter $user bare.
$user bør snart betale sin gæld til samfundet.
$user er objektivt set en nasserøv, nasserøv, nasserøv.
$user giver mig ikke nok $penge.
Hvilken verden lever $user i?  Betal så de $penge, ellers bliver jeg mopset!
/me gider ikke være inkasso, men $user mangler altså at give nogle $penge.
$user: Fy!
EOF
