#!/bin/sh
#
# Find word relations.  Also do some filtering to keep them nice.
#
# Run once for each relation.  It's pretty slow (and stupid).
#
# Usage: ./find_relations RELATION
#
# Looks for instances of RELATION (e.g. 'hyponymOf'), and saves them
# into the file ../DanNet/RELATION with each line of the format 'X<Y',
# where X has the asked-for relation to Y.

cd "$(dirname "$0")"
db="../DanNet-2.2_csv"

relation="$1"
if ! [ "$relation" ]; then
   echo "error: missing relation argument" > /dev/stderr
   exit 1
fi

f() {
    grep -E "^$(grep -E "^[0-9]+@[0-9]+@$1@" "$db/wordsenses-utf-8.csv" | cut -d@ -f2)@" "$db/words-utf-8.csv" \
        | cut -d@ -f2
}

cat "$db/relations-utf-8.csv" | grep "$relation" | while read line; do
    x="$(echo $line | cut -d@ -f1)"
    y="$(echo $line | cut -d@ -f4)"
    f "$x" | while read xf; do
        f "$y" | while read yf; do
            if ! [ "$xf" ] || ! [ "$yf" ] || \
                    (echo "$xf" | grep -q ' ') || (echo "$yf" | grep -q ' ') || \
                    (echo "$xf" | grep -qE "$yf"'$'); then
                continue
            fi
            echo "$xf<$yf"
        done
    done
done > "../DanNet/$relation"
