#!/usr/bin/env python
# -*- coding: utf-8 -*-
import json
import os
import re
import sys
import urllib

ytvids = re.finditer(r'\b(?:youtube.com/watch.*?\bv=|youtu.be/)([A-Z0-9-_]{11})', os.getenv('EGGS_BODY'), re.IGNORECASE)

vids = []

for vid in ytvids:
    vidid = vid.group(1)
    url = "http://gdata.youtube.com/feeds/api/videos/%s?v=2&alt=json" % vidid

    try:
        result = json.load(urllib.urlopen(url))
        entry = result['entry']

        title = entry['title']['$t']
        rating = entry['gd$rating']['average']
        maxrating = entry['gd$rating']['max']
        numratings = entry['gd$rating']['numRaters']
        uploader = entry['author'][0]['name']['$t']
        views = int(entry['yt$statistics']['viewCount'])

        print (u"%s (%.2f/%d efter %d stemmer, %d visninger, uploadet af %s)" % (title, rating, maxrating, numratings, views, uploader)).encode("utf8")
    except (KeyError, IndexError):
        print u"Den dér YouTube-video er vist ikke helt i orden.".encode("utf8")
    except:
        print u"Jeg er slet ikke skrevet godt nok til at håndtere UTF-8-tegn der er mere end 8 bit!".encode("utf8")

