#!/bin/sh
# Post-remove script for ‘bsdgames’ package.
#
# Man page: ‘dh_installdeb(1)’

set -e

# Summary of ways this script can be called:
#   * <postrm> ‘remove’
#   * <postrm> ‘purge’
#   * <old-postrm> ‘upgrade’ <new-version>
#   * <disappearer's-postrm> ‘disappear’ <overwriter> <overwriter-version>
#   * <new-postrm> ‘failed-upgrade’ <old-version>
#   * <new-postrm> ‘abort-install’
#   * <new-postrm> ‘abort-install’ <old-version>
#   * <new-postrm> ‘abort-upgrade’ <old-version>
# For details, see <URL:http://www.debian.org/doc/debian-policy/> or
# the ‘debian-policy’ package.

action="$1"

SCOREFILES="
	/var/games/bsdgames/atc_score
	/var/games/bsdgames/battlestar.log
	/var/games/bsdgames/cfscores
	/var/games/bsdgames/criblog
	/var/games/bsdgames/robots_roll
	/var/games/bsdgames/saillog
	/var/games/bsdgames/snake.log
	/var/games/bsdgames/snakerawscores
	/var/games/bsdgames/tetris-bsd.scores
	/var/games/bsdgames/phantasia/characs
	/var/games/bsdgames/phantasia/gold
	/var/games/bsdgames/phantasia/lastdead
	/var/games/bsdgames/phantasia/mess
	/var/games/bsdgames/phantasia/motd
	/var/games/bsdgames/phantasia/scoreboard
	/var/games/bsdgames/phantasia/void
	/var/games/bsdgames/phantasia/monsters
	/var/games/bsdgames/hack/perm
	/var/games/bsdgames/hack/record"

# Remove high score files on purge.
if [ "$1" = "purge" ]; then
	rm -f $SCOREFILES
	rmdir /var/games/bsdgames/phantasia /var/games/bsdgames/sail \
	      /var/games/bsdgames /var/games 2>/dev/null || true 
	rm -f /var/games/bsdgames/hack/save/* 2>/dev/null || true
	rmdir -p /var/games/bsdgames/hack/save 2>/dev/null || true
fi

case "$action" in

    remove|purge|upgrade|disappear|failed-upgrade|abort-install|abort-upgrade)
        ;;

    *)
        printf "postrm called with unknown action ‘%s’\n" "$action" >&2
        exit 1
        ;;

esac

#DEBHELPER#

exit 0
