#!/usr/bin/env python3
import sys

user, user2, circle, board = sys.argv[1:5]

print(f"{user}: Det er din tur i kampen mod {user2}. Du er {circle}. Her er hvordan brættet ser ud:\n{board}")
print(f"{user}: Tag dit træk ved at skrive '4påstribe <søjle>'.")
