#!/bin/sh

(echo "ACK-ACK"
 echo "Javel"
 echo "OK"
 echo "Forstået"
 echo "Accepteret"
 echo "Det er i orden"
 echo "Roger"
 echo "10-4"
 echo "Den er fin"
 echo "Den er fino"
 echo "Den er fin-fin"
 echo "Den er fjong"
 echo "Jep, det siger vi"
 echo "Jep, det siger vi bare"
 echo "Ja, herre"
 echo "Det er dandy"
) | randomElement | xargs echo -n
(echo "!"; echo ".") | randomElement
