#!/bin/sh
#
# Actually run command.

set -f # No globbing

cmd="$1"
acmd="$2"
shift
shift

broke() {
    pleasedBy "$EGGS_USER" 1 "hjalp med at finde en fejl i '$cmd'"
    echo "Kommandoen fejlede!  Du kan prøve at spørge mig om 'udu', men det hjælper næsten helt sikkert ikke."
    exit 1
}

eggcheck() {
    if dbExists ægget; then
        egg=$(dbRead ægget)
        if [ "$egg" = "$cmd" ]; then
            echo "$EGGS_USER: Du fandt ægget!  Tillykke!  Du er den nye konge af IRC!"
            makeKing "$EGGS_USER"
            dbDelete ægget
        else
            last=$(dbRead last_cmd | cut -d' ' -f1)
            this_dist=$(echo "$cmd" | levenshtein "$egg" | cut -d' ' -f1)
            last_dist=$(echo "$last" | levenshtein "$egg" | cut -d' ' -f1)
            if [ "$last" != "$cmd" ]; then
                if [ $last_dist -eq $this_dist ]; then
                    echo "$EGGS_USER: $(egg_heat $this_dist)"
                elif [ $last_dist -gt $this_dist ]; then
                    echo "$EGGS_USER: Varmere..."
                else
                    echo "$EGGS_USER: Koldere..."
                fi
                if [ "$(random 1 10)" = 1 ]; then
                    firstc=$(echo - "$egg" | cut -c1)
                    lastc=$(echo -n "$egg" | rev | cut -c1)
                    num=$(echo -n "$egg" | wc -c)
                    ( echo "Et lille vink: Ægget er gemt i en kommando der starter med '$firstc'."
                      echo "Et lille vink: Ægget er gemt i en kommando der slutter med '$lastc'."
                      echo "Et lille vink: Ægget er gemt i en kommando på $num tegn.") | randomLine
                fi
            fi
        fi
    fi
}

dbRead cur_cmd | dbWrite last_cmd
echo "$cmd $@" | dbWrite cur_cmd
case "$cmd" in
er|hvem|hvad|hvor|hvorfor|hvornår|har*|kan|skal|hvilke*)
    timeout 30s "$acmd" $(echo "$@" | sed 's/\?*$//') || broke
    ;;
# If a command should be allowed more than 30s to run, include its name here
fluen|duen|flaske|benåd*)
    timeout 240s "$acmd" "$@" || broke
    ;;
*)
    timeout 30s "$acmd" "$@" || broke
    ;;
esac | gawk '{print; fflush()}' # Hack: use awk to newline-terminate.

eggcheck
