#!/bin/sh
#
# Actually run command.

set -f # No globbing

cmd="$1"
acmd="$2"
shift
shift

broke() {
    pleasedBy "$EGGS_USER" 1 "hjalp med at finde en fejl i '$cmd'"
    echo "Kommandoen fejlede!  Du kan prøve at spørge mig om 'udu', men det hjælper næsten helt sikkert ikke."
    exit 1
}

dbRead cur_cmd | dbWrite last_cmd
echo "$cmd $@" | dbWrite cur_cmd
case "$cmd" in
er|hvem|hvad|hvor|hvorfor|hvornår|har*|kan|skal|hvilke*)
    gtimeout 30s "$acmd" $(echo "$@" | sed 's/\?*$//') || broke
    ;;
# If a command should be allowed more than 30s to run, include its name here
fluen|duen|flaske|benåd*)
    gtimeout 240s "$acmd" "$@" || broke
    ;;
*)
    gtimeout 30s "$acmd" "$@" || broke
    ;;
esac | gawk '{print; fflush()}' # Hack: use awk to newline-terminate.
