#!/bin/sh

factor="$(eggsFactor $1 $2)"
if ! [ "$factor" ]; then
    num=0
fi

if [ "$num" != 0 ]; then
    rmFromEggs $1 "$cur"
fi

if [ $# -eq 3 ]; then
    new="$2, $(($num + $3))"
else
    new="$2, $(($num + 1))"
fi
echo "$new" >> $CONCIEGGS_DB_DIR/eggs/$1
updateSubTime "$2" "$(nowTime)"
