#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Modtag data fra Conservapedia.  Brug: antividen [emne]

import sys
import os
from functools import partial
import itertools
import random

from eggsthon.url_open import request
from eggsthon.wikipedia import get_page_urls, get_paragraphs, get_sentences

base_url = 'http://conservapedia.com/'
random_page_url = base_url + 'Special:Random'
pre_rules = [
    'eg',
    'e.g',
    'etc'
    'ie',
    'i.e',
    'bc',
    'ad',
    'dr',
    'mr',
    'mrs',
    'ms',
    'v'
    ]

def complain():
    print 'Jeg kan ikke finde antividen.'

def run_main(args):
    args = map(lambda a: a.decode('utf-8', 'ignore'), args)
    term = u' '.join(args[1:]).strip()
    urls = get_page_urls(term, base_url,
                         link_regex=u'<li><a href="(.+?)"',
                         search_url='Special:Search?%s') \
        if term else [random_page_url]
    pages = request(urls[:5])
    if not pages:
        return complain()
    paragraphs = itertools.chain(*map(get_paragraphs, pages))
    sentences = filter(lambda s: len(s) > 20 and term.lower() in s.lower(),
                       (itertools.chain(*map(partial(get_sentences, pre_rules=pre_rules),
                                             paragraphs))))
    try:
        s = random.choice(sentences).strip()
    except IndexError:
        return complain()
    if not (s.endswith(u'.') or s.endswith(u':')):
        s += u'.'
    print s.encode('utf-8')

if __name__ == '__main__':
    run_main(sys.argv)
