#!/bin/sh

cd $CONCIEGGS_IRC_DIR

echoToServer ":WHOIS $1"
for i in $(seq 1 2); do
    authed=$(tail -n 20 out | awk 'match($0,/([^ ]+)\): is logged in as$/,matches) { print matches[1]; exit(0); }')
    if [ "$authed" ]; then
        echo $authed
        exit
    fi
    sleep 1
done
