#!/usr/bin/env python3

import requests
import sys

def median(lst):
    sortedLst = sorted(lst)
    lstLen = len(lst)
    index = (lstLen - 1) // 2

    if (lstLen % 2):
        return sortedLst[index]
    else:
        return (sortedLst[index] + sortedLst[index + 1])/2.0

# Bitstamp
prices = [-1, -1, -1]
urlBS = "https://www.bitstamp.net/api/ticker/"
respBS = requests.get(url=urlBS)
dataBS = respBS.json()
prices[0] = float(dataBS["last"])

# Bitfinex
urlBF = "https://api-pub.bitfinex.com/v2/tickers?symbols=tBTCUSD"
respBF = requests.get(url=urlBF)
dataBF = respBF.json()
prices[1] = float(dataBF[0][1])

# Coinbase
urlCB = "https://api.coinbase.com/v2/prices/spot?currency=USD"
respCB = requests.get(url=urlCB)
dataCB = respCB.json()
prices[2] = float(dataCB["data"]["amount"])

if (len(sys.argv) > 1 and sys.argv[1] == "median"):
    print(str(round(median(prices))))
else:
    print("Bitstamp: " + str(round(prices[0])) + " usd, Bitfinex: " + str(round(prices[1])) + " usd, Coinbase: " + str(round(prices[2])) + " usd, median: " + str(round(median(prices))) + " usd.")
