#!/usr/bin/env node

var request = require('request');

request.post({
    url: 'https://www.borgerforslag.dk/api/proposals/search',
    json: { filter: 'all',
        sortOrder: 'latest',
        searchQuery: '',
        pageNumber: 1,
        pageSize: 100}},
    function (error, response, body) {
        if (!error && response.statusCode == 200) {
            var items = body.data
            for (var i in items) {
                console.log(items[i].title)
            }
        }
        else {
            throw("Noget gik galt")
        }
    }
);
