#!/bin/sh

set -e

cooldown=$1
cooldown_duration=$2
file=$(echo $1 | sed 's/\//_/g')
file="$CONCIEGGS_DB_DIR/cooldowns/$file"

if [ -f "$file" ]; then
    until=$(cat "$file")
    if [ "$until" ]; then
        if [ $(nowTime) -lt $until ]; then
            exit 1
        fi
    fi
fi

mkdir -p "$(dirname "$file")"
echo $(($(nowTime) + $cooldown_duration)) > "$file"
