#!/bin/sh

prog=$(cat <<"EOF"
function frobword_inner(s) {
  fst = substr(s,1,1)
  prefix = toupper(fst) == fst ? "Jule-" : "jule-"
  if (length(s) > 3 && !festive) {
    return prefix s
  } else if (length(s) > 3 && rand() > 0.1) {
    return frobword_inner(prefix s)
  } else {
    return s
  }
}
function frobword(s) {
  if (match(s, "[jJ]ul") != 1 && rand() > 0.75) {
    return frobword_inner(s)
  } else {
    return s
  }
}
function frob(s) {
  match(s, "[a-zA-ZæøåÆØÅ]+")
  if (RSTART == 0) {
    return s
  } else {
    pre=substr(s,1,RSTART-1)
    post=substr(s,RSTART+RLENGTH,length(s))
    return pre frobword(substr(s,RSTART,RLENGTH)) frob(post)
  }
}
{
festive=0
srand()
print frob($0)
fflush(); 
}
EOF
)

awk -- "$prog"

# while IFS='' read line; do
#     if echo "$line" | grep -qE 'http://[^.]+\.[^ ]+'; then
#         echo "$line"
#     else
#         echo "$line" | awk -- "$prog"
#     fi
# done
