#!/bin/sh

prog=$(cat <<"EOF"
function frobword(s) {
  fst = substr(s,1,1)
  prefix = toupper(fst) == fst ? "Jule-" : "jule-"
  if (length(s) > 3 && rand() > 0.75) {
    return prefix s
  } else {
    return s
  }
}
function frob(s) {
  match(s, "[a-zA-ZæøåÆØÅ]+")
  if (RSTART == 0) {
    return s
  } else {
    return substr(s,1,RSTART-1) frobword(substr(s,RSTART,RLENGTH)) frob(substr(s,RSTART+RLENGTH,length(s)))
  }
}
{
print frob($0)
fflush(); 
}
EOF
)

awk -- "$prog"
