#!/bin/sh

prog=$(cat <<"EOF"
function frobword(s) {
  fst = substr(s,1,1)
  prefix = toupper(fst) == fst ? "Jule-" : "jule-"
  if (match(s, "[jJ]ul") != 1 && length(s) > 3 && rand() > 0.75) {
    return prefix s
  } else {
    return s
  }
}
function frob(s) {
  match(s, "[a-zA-ZæøåÆØÅ]+")
  if (RSTART == 0) {
    return s
  } else {
    pre=substr(s,1,RSTART-1)
    post=substr(s,RSTART+RLENGTH,length(s))
    return pre frobword(substr(s,RSTART,RLENGTH)) frob(post)
  }
}
{
print frob($0)
fflush(); 
}
EOF
)

awk -- "$prog"
