#!/bin/sh
#
# Same as `cmpNames`, except it also looks at GitHub names if they exist.  Only
# compare first names.

firstname() {
    echo "$1" | cut -d' ' -f1
}

a="$1"
b="$2"

if ! [ "$a" ]; then
    exit 1
elif ! [ "$b" ]; then
    exit 1
fi

ag="$(dbUserRead "$a" githubname)"
bg="$(dbUserRead "$b" githubname)"

small_check() {
    a1="$(firstname "$a")"
    b1="$(firstname "$b")"
    ag1="$(firstname "$ag")"
    bg1="$(firstname "$bg")"
    test "$a1" = "$b1" || \
        test "$ag1" = "$b1" || \
        test "$a1" = "$bg1"
}

large_check() {
    cmpNames "$a" "$b" || \
        test "$a" = "$b" || \
        test "$ag" = "$b" || \
        test "$a" = "$bg"
}

if echo "$a" | grep -q ' '; then
    small_check
elif echo "$b" | grep -q ' '; then
    small_check
else
    large_check
fi
