#!/bin/sh
#
# Same as `cmpNames`, except it also looks at GitHub names if they exist.

a="$1"
b="$2"

if ! [ "$a" ]; then
    exit 1
elif ! [ "$b" ]; then
    exit 1
fi

ag="$(dbUserRead "$a" githubname)"
bg="$(dbUserRead "$b" githubname)"

small() {
    test "$a" = "$b" || \
        test "$ag" = "$b" || \
        test "$a" = "$bg"
}

large() {
    cmpNames "$a" "$b" || \
        test "$a" = "$b" || \
        test "$ag" = "$b" || \
        test "$a" = "$bg"
}

if echo "$a" | grep -q ' '; then
    small
elif echo "$b" | grep -q ' '; then
    small
else
    large
fi
