#!/bin/sh

cmddir=$CONCIEGGS_DIR/cmds

channel="$(ircChannel)"

find "$cmddir" "$cmddir/$channel" -maxdepth 1 2>/dev/null \
    | while read -r acmd; do
    if [ -x "$acmd" ] && [ -f "$acmd" ]; then
        basename "$acmd"
    fi
done
