#!/bin/sh

cmddir=$CONCIEGGS_DIR/cmds

if [ "$1" = -a ]; then
    check_all_places=-a
    shift
fi

{
    if [ "$check_all_places" ]; then
        echo 3 >&2
        find "$cmddir" -maxdepth 2
    else
        find "$cmddir" "$cmddir/$(ircChannel)" -maxdepth 1 1>&2
        find "$cmddir" "$cmddir/$(ircChannel)" -maxdepth 1 2>/dev/null
    fi
} | while read -r acmd; do
    if [ -x "$acmd" ] && [ -f "$acmd" ]; then
        basename "$acmd"
    fi
done
