#!/bin/sh

awk '{if (out && last) { out = out ", " last; last = $0 }\
else if (out) { last = $0 }\
else { out = $0 } }\
END{ if (last) { if (out) { out = out ", " last } else { out = last } };\
print out }'
