#!/bin/sh

set -e # Die on error

if [ $# -ne 1 ]; then
    echo "Usage: $0 <file>.go"
    exit 1
fi

origsrc=$1
shift
compiled=$CONCIEGGS_DB_DIR/compiled-cache/$(basename "$origsrc" | sed 's/\.go$//')

if [ "$compiled" -nt "$origsrc" ]; then
    "$compiled" "$@"
else
    if echo "$origsrc" | grep '\.go$'; then
        src=$CONCIEGGS_DB_DIR/compiled-cache/$(basename "$origsrc")
    else
        src=$CONCIEGGS_DB_DIR/compiled-cache/$(basename "$origsrc").go
    fi
    mkdir -p "$CONCIEGGS_DB_DIR/compiled-cache"
    grep -v '^#' "$origsrc" > "$src"
    (cd "$CONCIEGGS_DB_DIR/compiled-cache"
        go build "$src"
    )
    "$compiled" "$@"
fi
