#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Bedre program end google.

import subprocess
import sys
import os
from functools import partial
import itertools
import random
import urllib2
import re
import xml.etree.ElementTree as ET
from lxml import html

def run_main(args):
    (maengde, fraValuta, tilValuta) = float(args[1]), args[2].lower(), args[3].lower()
    if fraValuta == tilValuta:
        tilPrEenFra = 1.0
    else:
        tilPrEenFra = skafPris(fraValuta, tilValuta)
    beloeb = maengde * tilPrEenFra

    print "%.*f" %  (2,  beloeb)

def skafPris(fraValuta, tilValuta):
    opener = urllib2.build_opener()
    opener.addheaders = [('User-agent', 'Mozilla/5.0')]
    list = opener.open("http://finance.yahoo.com/q?s=" + fraValuta + tilValuta +  "=X")
    content = list.read()

    try:

        tilPrEenFra = content.split('<span id="yfs_l10_' + fraValuta + tilValuta + '=x">')[1].split('<')[0]
        tilPrEenFra = tilPrEenFra.replace(",",".")
        points = tilPrEenFra.count(".")
        if points > 1:
            tilPrEenFra = tilPrEenFra.replace(".","", 1)
        return float(tilPrEenFra)
    except:
        sys.exit(1)
if __name__ == '__main__':
    run_main(sys.argv)
