#!/bin/sh
#
# Count the amount of time a king has reigned in seconds.

king="$(mainAlias $1)"

dbRead eggskinglist | egrep '^[0-9]+ '"$king"'$' -A 1 | tr '\n' ' ' | tr -s '\-\-' '\n' | awk '{ s += $3 - $1 } END {print s}'
