#!/bin/sh
#
# Count the amount of times a king has reigned.

king=$1

count=$(dbRead eggskinglist | while read line; do
    kingname=$(echo $line | cut -d ' ' -f 2)
    if [ "$kingname" ] && cmpNames $king $kingname; then
        echo prut
    fi
done | wc -l)
echo $count
