#!/bin/sh
#
# Count the amount of times a king has reigned.

king=$1
count=0

dbRead eggskinglist | while read line; do
    kingname=$(cut -d ' ' -f 2)
    if [ "$kingname" ]; then
        if cmpNames $king $kingname; then
            count=$(expr "$count" + "1")
        fi
    fi
    #TODO: Tjek for mytiske konger.
done
echo $count
