#!/bin/sh
#
# Next date in YYYY-MM-DD format.

# If we're on OpenBSD and `date` points to BSD `date`.
if [ $(uname) = OpenBSD -a $(date --version 2>&1 1>/dev/null; echo $?) ]; then
    date -f %s -j $(expr $(date +%s) + 86400) +%F
else
    date -d tomorrow +%F
fi
