#!/bin/sh
#
# Previous date in YYYY-MM-DD format.

# We now support OpenBSD with and without GNU `date` as the standard `date`.
if [ $(uname) = OpenBSD -a $(date --version 1>/dev/null 2>/dev/null; echo $?) ]; then
    /bin/date -f %s -j $(expr $(date +%s) - 86400) +%F
else
    date -d yesterday +%F
fi
