#!/bin/sh
#
# Wrapper for invoking GNU date on non-GNU systems.
#
# TODO: Make the entire date handling stuff way less retarded.

if which /usr/local/bin/gdate > /dev/null 2>/dev/null; then
    /usr/local/bin/gdate "$@"
elif [ -d /run/current-system ]; then
    /run/current-system/sw/bin/date "$@"
else
    /bin/date "$@"
fi
