#!/bin/sh

user="$1"
node="$2"
realnode="$(dbUserGet "$1" "$2")"
if [ "$realnode" ]; then
    dbInsertData "$realnode"
else
    alias=$(mainAlias $user)
    if [ "$alias" ]; then
        dbInsertData "users/$alias/$node"
    else
        dbInsertData "users/$user/$node"
    fi
fi
