#!/bin/sh

user="$1"
node="$2"
realnode="$(dbUserGet "$1" "$2")"

if [ "$realnode" ]; then
    dbWrite "$realnode"
else
    alias="$(mainAlias "$1")"
    if [ "$alias" ]; then
        dbWrite "users/$alias/$node"
    else
        dbWrite "users/$1/$node"
    fi
fi
