#!/bin/sh

randomLine <<EOF
De har spist af mig igen, disse $(dummeBavianer).
Disse $(dummeBavianer) har endnu en gang spist fra min hånd.
Bliver de da aldrig mætte, de her $(dummeBavianer)?
Hvad sker der lige for de $(dummeBavianer)?  Æde, æde, æde.
Er det virkeligt kun mig der er træt af de $(dummeBavianer) og deres konstante frokostspisning?
NU MÅ DET SNART STOPPE!  Bliver disse $(dummeBavianer) aldrig trætte af mad?
Har I hørt den om de $(dummeBavianer) der spiser frokost?  De har lige gjort det!
EOF
