#!/bin/sh
#
# Del en god tegneseriestribe fra gocomics.com.
#
# Brug: gocomics stribe [emne]

url="$(gocomics "$1" "$2")"

if [ "$url" ]; then
    randomLine <<EOF
$EGGS_USER: Hvad med $url — den er ret skæg :)
$url er bare hygge, $EGGS_USER.
Jeg kan huske da jeg først så $url i det der album.
$url er vist noget for dig, $EGGS_USER.
Jeg kan da ikke benægte at jeg grinede en smule da jeg læste $url :p
EOF
else
    echo "$EGGS_USER: Jeg kunne ikke finde dét."
fi
