#!/bin/sh

awk 'BEGIN{}\
/^#!/{next}\
/^# ?$/{next}\
/^\/\/ ?$/{next}\
/^# .+$/{indoc_hash=1}\
/^\/\/ .+$/{indoc_slash=1}\
/^[^#/]/{indoc_hash=0; indoc_slash=0}\
/^$/{indoc_hash=0; indoc_slash=0}\
indoc_hash{out = out substr($0, 3, length($0)) " "}\
indoc_slash{out = out substr($0, 4, length($0)) " "}\
END{print out}' | sed 's/-\*- e\?n\?coding: utf-8 -\*- //'
