#!/bin/sh

dumme() {
    randomElement <<EOF
dumme
stupide
træge
fulde
ghettoskabende
trampolinfaldende
antimajestætiske
umuskuløse
slatne
politiske
upolitiske
glassmadrende
noobede
newbede
n00bede
skinkede
skinkende
tunge
beskidthårede
barbariske
åndsforsnoskede
flommefede
modbydelige
plottende
lavpraktiske
endelige
dårlige
grinagtige
kakkerlakkede
forlorne
shellede
pythonske
haskellske
cplusplussede
åndssvage
sandalbærende
barfodede
beskidte
syndige
sveddryppende
rutineprægede
yderligtgående
intetsigende
ECTS-slugende
ekstremistiske
kursusansvarlige
radikale
konservative
pseudovidenskabelige
makrel-lugtende
underforståede
web-udviklende
jQuery-fanatiske
Facebook-afhængige
light-mayonaisse-købende
halvhumoristiske
tidsrejsemaskinedestruerende
æggeslugende
døddovne
støvsamlende
intelligenstomme
trampolinfaldende
ikke-minimerede
VHS-piratkopierende
EOF
}

bavianer() {
    randomElement <<EOF
bavianer
kameler
øldrikkere
tennis suckers
bubbibjørne
kamæleoner
ågerkarle
burgøjsere
idioter
hackerz
gamere
newbs
noobs
n00bs
skinker
NOT-porte
slaver
dovenlarser
pivstilker
basilisker
dinosaurer
banditter
kaffejunkies
colaafhængige
GT-vrag
Leffe-luffer
mindstenævnere
overløbere
ildfluer
fluesmækkere
campingvogne
Ladaer
dogmemagere
fysiker wannabees
myg
biolog wannabees
kursusdumpere
vim-brugere
emacs-brugere
anti-dataloger
fæpander
republikanere
vaccinebenægtere
DFU-medlemmer
desillusionister
motorbøller
luskebukser
luksusdyr
proletarudnyttere
asfaltcowboys
sofarækkebesiddere
spegesild
shell script-idioter
tilstandsmaskiner
kantinebrugere
Caféen?-gængere
rus-sympatisører
ateister
eksaminanter
grænsetilfælde
socialdemokrater
mider
amøber
ådselædere
DDR-betonvrag
humorbenægtere
firserlævn
Lars von Trier-efterabere
Otto Leisner-fanboys
P3-lyttere
valnøddesnaps-hipstere
reklamesamlere
VGA-skærme
sørovsfændrikker
Tintin-nyoversættere
EOF
}

udenHumor() {
randomElement <<EOF
uden humor
fra kælderen
fra under sengen
med mere
(seriøst)
og deres "venner"
EOF
}

randomElement<<EOF
$(dumme) $(bavianer)
$(dumme), $(dumme) $(bavianer)
$(dumme) $(bavianer) $(udenHumor)
EOF
