#!/bin/sh

eggs=$1
all="$(listCleanEggsers $eggs)"

numbeneggters="$(echo "$all" | while read -r who; do
        if [ "$(dbUserGet $who beneggter)" ]; then
            echo $who
        fi
    done| wc -l)"

numeggs=$(($(echo "$all"|wc -l) - $numbeneggters))

prefs () {
    echo "$all" | while read -r who; do
        pref=$(preference $who)
        if [ "$pref" ]; then
            case "$(random 0 1)" in
                0)
                    echo "$(randomNameWithTitle $who)" vil gerne have "$pref"
                    ;;
                *)
                    echo "$(randomNameWithTitle $who)" foretrækker "$pref"
                    ;;
            esac
        fi
        if isKing "$who"; then
            if [ $(countEggsers $eggs) -eq 1 ]; then
                echo "Kongen spiser alene"
            else
                echo "Hans Majestæt er med til bords"
            fi
        fi
    done
}

prefs="$(prefs | enumerate)"

echo -n "Der er $(countEggsers $eggs) tilmeldt til $(titleEggs $eggs): $(describeEggs $eggs).  Der skal tilberedes $numeggs eggs."

if [ "$prefs" ]; then
    echo "Endvidere: $prefs."
else
    echo
fi
