#!/bin/sh
#
# Someone who can be elected.

randomLine <<EOF
Emmanuel Macron
Marine Le Pen
Poul Schlüter
Thorvald Stauning
Helle Thorning-Schmidt
Hillary Rodham Clinton
Angela Merkel
Theresa May
Jeremy Corbyn
Adolf Hitler
Lars Løkke Rasmussen
Poul Nyrup Rasmussen
Anders Fogh Rasmussen
EOF
