#!/bin/sh
#
# Free an arrested user by royal decree.

dbRemoveLines() {
    name="$1"
    should_remove_fun="$2"
    dbRead $name | while read some_user; do
        if ! $should_remove_fun $some_user; then
            echo $some_user
        fi
    done | dbWrite $name
}

user_to_free="$1"
dbRemoveLines underArrest "cmpNames $user_to_free"
