#!/bin/sh
#
# Free an arrested user by royal decree.

user="$1"
fire_alarm="$(mktemp)"
dbRead underArrest > "$fire_alarm"
dbDelete underArrest

while read alarmed_user; do
    if ! cmpNames "$alarmed_user" "$user"; then
        arrestUser "$user"
    fi
done < "$fire_alarm"
rm "$fire_alarm"
