#!/usr/bin/env python3
import sys
import subprocess
import re

if len(sys.argv) != 2:
    print("Brug: GetGdpPcOf <land>", file=sys.stderr)
    sys.exit(1)

wa_output = subprocess.run(['wa', 'gdp', 'per', 'capita', 'of', sys.argv[1]], 
                          capture_output=True, text=True).stdout

match = re.search(r'\s*(?:[Rr]esult:)\s+\$(\d+(?:\.\d+)?)', wa_output)

if not match:
    print(f"Unable to interpret population number. Got: {wa_output}", file=sys.stderr)
    sys.exit(1)

gdp_pc_string = match.group(1)
print(gdp_pc_string)
