#!/usr/bin/env perl
use utf8;
use 5.042;
use warnings;

die "Brug: GetGdpPcOf <land>" unless $#ARGV == 0;
my $waOutput = `wa gdp per capita of $ARGV[0]`;
$waOutput =~ /\s*(?:[Rr]esult:)\s+\$(\d+(?:\.\d+)?)/;

my $gdpPcString = $1;

die "Unable to interpret population number. Got: $waOutput" unless $gdpPcString ne '';

say $gdpPcString;
