#!/usr/bin/env perl
#
# Har du et problem, hva'?

use 5.020;
use warnings;
use Mojo::UserAgent;
use Mojo::Util qw/url_escape/;

my $q = join(' ', @ARGV);
my $eq = url_escape( $q );

my $url = qq{https://api.github.com/search/issues?q=$q+type:issue+state:open&sort=created&order=desc};

my $ua = Mojo::UserAgent->new;
my $res = $ua->get($url)->result;

die(q{Kunne ikke kontakte github-api'et.}) unless $res->is_success;

my $data = $res->json;
my @items = @{ $data->{items} };

unless (@items) {
    say "Jeg har intet problem med $q.";
    exit(0);
}

my $item = $items[rand @items];

my $issue_title = $item->{title};
my $issue_url = $item->{html_url};

say 'Mit problem' . ($q =~ m/^\s*$/ ? '' : " med $q") . "? $issue_title ($issue_url)";
