#!/bin/sh
#
# Use: gpt3 n text...

api_key="$(cat "$CONCIEGGS_HOME/credentials/openai")"
temperature=0.7
engine=gpt-3.5-turbo
max_tokens=$1
shift
prompt=$(echo "$@" | sed 's/"/\\"/g')

curl -s https://api.openai.com/v1/engines/$engine/completions \
     -H "Content-Type: application/json" \
     -H "Authorization: Bearer $api_key" \
     -d '{"prompt": "'"$prompt"'", "temperature": '$temperature', "max_tokens": '$max_tokens'}' \
     | jq -r '.choices[0].text'
