#!/bin/sh
#
# Use: gpt4o n text...

api_key="$(cat "$CONCIEGGS_HOME/credentials/openai")"
temperature=0.7
engine=gpt-5
max_tokens=$1
shift
prompt=$(echo "$@" | sed 's/"/\\"/g')

curl -s https://api.openai.com/v1/chat/completions \
     -H "Content-Type: application/json" \
     -H "Authorization: Bearer $api_key" \
     -d '{ "model": "'"$engine"'", "messages": [{"role": "user", "content": "'"$prompt"'"}], "temperature": '$temperature', "max_tokens": '$max_tokens'}' \
     | jq -r '.choices[0].message.content'
