#!/bin/sh
#
# Har en bruger meldt sig under kongen?

set -e

dbRead vilstøttekongen | {
    while read user; do
        if cmpNames "$1" "$user"; then
            exit 0
        fi
    done
    exit 1
}
