#!/bin/sh

biblen=`randomElement <<EOF
Gabriel
Michael
Raphael
Uriel
Chamuel
Jophiel
Zadkiel
Belial
Behemoth
Beelzebub
Asmodeus
Satanas
Lucifer
EOF`

omskrivning=`randomElement <<EOF
.., men det snakker vi ikke om.
 "noget"
 "dét"
 du ved nok ;)
 det "frække"
EOF`

hjulene=`randomElement <<EOF
hjulene
Illuminati
menneskeheden
dyret i os
dataloger
fysikere
biologer
"Dét"
Han
Electra
$biblen
EOF`

drejer=`randomElement <<EOF
drejer
styrer
fortsat ånder
leder verden
komplementerer bits
sover
spiser giftig kage
grinte ondt
taster
ingen grænser har
vader rundt
tilbad hedenske guder
gjorde$omskrivning
EOF`

echo $hjulene $drejer
