#!/usr/bin/env perl
#
# Slå noget op i Krak.

use 5.042;
use strict;
use warnings;
use utf8;

use URI;
use String::Util qw(trim);
use EggsML::EggsPI text => [qw(curl krakApiKey)];

my $uri = URI->new('https://api.eniro.com/cs/search/basic');
$uri->query_form(
    profile     => 'concieggs',
    key         => krakApiKey,
    country     => 'dk',
    version     => '1.1.3',
    geo_area    => 'København',
    search_word => join(' ', @ARGV),
);
print trim(curl('-s', $uri->as_string));
