#!/bin/sh
#
# Konverterer en $(eggspi/langcode) til sprognavn.

langcode="$1"

case "$langcode" in
    af) echo "afrikaans" ;;
    sq) echo "albansk" ;;
    ar) echo "arabisk" ;;
    az) echo "aserbajdsjansk" ;;
    eu) echo "baskisk" ;;
    bn) echo "bengalsk" ;;
    be) echo "hviderussisk" ;;
    bg) echo "bulgarsk" ;;
    ca) echo "katalansk" ;;
    zh-CN|zh-TW) echo "kinesisk" ;;
    hr) echo "kroatisk" ;;
    cs) echo "tjekkisk" ;;
    da) echo "dansk" ;;
    nl) echo "hollandsk" ;;
    en) echo "engelsk" ;;
    eo) echo "esperanto" ;;
    et) echo "estisk" ;;
    tl) echo "filipinsk" ;;
    fi) echo "finsk" ;;
    fr) echo "fransk" ;;
    gl) echo "galisisk" ;;
    ka) echo "georgisk" ;;
    de) echo "tysk" ;;
    el) echo "græsk" ;;
    gu) echo "gurajati" ;;
    ht) echo "haitisk" ;;
    iw) echo "hebraisk" ;;
    hi) echo "hindi" ;;
    hu) echo "hungarsk" ;;
    is) echo "islandsk" ;;
    id) echo "indonesisk" ;;
    ga) echo "irsk" ;;
    it) echo "italiensk" ;;
    ja) echo "japansk" ;;
    kn) echo "kannada" ;;
    ko) echo "koreansk" ;;
    la) echo "latinsk" ;;
    lv) echo "lettisk" ;;
    lt) echo "litausk" ;;
    mk) echo "makedonisk" ;;
    ms) echo "malajsisk" ;;
    mt) echo "maltesisk" ;;
    no) echo "norsk" ;;
    fa) echo "persisk" ;;
    pl) echo "polsk" ;;
    pt) echo "portugesisk" ;;
    ro) echo "romænsk" ;;
    ru) echo "russisk" ;;
    sr) echo "serbisk" ;;
    sk) echo "slovakisk" ;;
    sl) echo "slovensk" ;;
    es) echo "spansk" ;;
    sw) echo "swahili" ;;
    sv) echo "svensk" ;;
    ta) echo "tamilsk" ;;
    te) echo "telugu" ;;
    th) echo "thai" ;;
    tr) echo "tyrkisk" ;;
    uk) echo "ukrainsk" ;;
    ur) echo "urdu" ;;
    vi) echo "vietnamesisk" ;;
    cy) echo "walisisk" ;;
    yi) echo "jiddisch" ;;
    so) echo "somalisk" ;;
    *) exit 1 ;;
esac
