#!/usr/bin/env tclsh
#
# Producerer en ond, fnisende, bøvet eller julet latter.

# [rand i j] producerer et tilfældigt heltal i intervallet [min,max[.
proc rand {min max} {
    return [expr {$min + int(rand() * ($max-$min))}]
}

# [randindex {a b c ...}] producerer en tilfældig indgang i listen.
proc randindex xs {
    return [lindex $xs [rand 0 [llength $xs]]]
}

# Er det jul?
catch {exec isChristmas} {} options
set isntChristmas [dict get $options -code]

# Hvordan skal der grines?
if {$isntChristmas} {
    set has {
        {MU HA {"" "" RH AAAARGH}}
        {ti hi {"" "" " fniz"}}
        {tø hø {""}}
        {lol ol {"" "" "!!1" "!!1!one"}}
        {l o {"l"}}
        {tro lo {""}}
        {rofl "" {ade kopter saurus}}
        {wolol o {""}}
        {hydr " hydr" {""}}
    }
    foreach {prefix ha suffixes} [randindex $has] {}
    set suffix [randindex $suffixes]
} else {
    set prefix HO
    set ha HO

    catch {exec christmasLevel} christmasLevel options
    set suffix "[string repeat O [expr {int($christmasLevel / 10)}]]H"
}

# Grin!
set response "$prefix[string repeat $ha [rand 2 10]]$suffix"
puts $response
