#!/usr/bin/env tclsh

catch {exec isChristmas} {} options
set isntChristmas [dict get $options -code]
set ha [expr {$isntChristmas ? "HA" : "Ho"}]
puts [string repeat $ha [expr {2 + int(rand() * 10)}]]
