#!/bin/sh

l="$(listGods | wc -l | sed 's/ //g')"
ll=$(expr $l - 1)
i=0
listGods | while read who; do
  if [ "$i" = "$l" ]; then
    echo "og $who."
  elif [ "$i" = "$ll" ]; then
    echo -n "$who "
  else
    echo -n "$who, "
  fi
  i=$(expr $i + 1)
done
