#!/bin/sh

cat $CONCIEGGS_DB_DIR/eggs/$1 | while read who; do
    name=$(echo "$who" | sed 's/,.*//')
    fact=$(echo "$who" | grep "," | sed 's/.*, //')
    if [ "$fact" -a "$fact" != 1 ]; then
        echo "$(randomNameWithTitle "$name")(*$fact)"
    else
        echo $(randomNameWithTitle "$name")
    fi
done
