#!/bin/sh

who="$(aliases "$1")"
# ja, vi beregner alles gæld, selv om vi kun er interesseret i et
# enkelt af tallene
eggstool balances | while read -r line; do
    name="$(echo "$line" | cut -d' ' -f 2)"
    if echo "$who" | fgrep -x "$name" > /dev/null; then
        echo "$line" | cut -d' ' -f 1 | awk '{ print -1*$0 }'
        exit
    fi
done
