#!/bin/sh
#
# Generer en sætning til at blive gættet i lykkehjulet-programmet.

if echo "$EGGS_BODY" | egrep -iqv 'apl|revy|filsystem|udtryk|avis'; then
    # Vi vil have ord på mindst længde to, for ellers bliver nogle af
    # lykkehjul-kommandoerne tvetydige.
    cat $CONCIEGGS_DB_DIR/ordbog-dansk-navneord-gode \
        | egrep '^.{2,}$' \
        | randomLine
elif echo "$EGGS_BODY" | egrep -iqv 'apl|filsystem|udtryk|avis'; then
    cat $CONCIEGGS_DB_DIR/revue_titles | randomLine
elif echo "$EGGS_BODY" | egrep -iqv 'apl|udtryk|avis'; then
    locate '.' | randomLine
elif echo "$EGGS_BODY" | egrep -iqv 'apl|avis'; then
    cat $CONCIEGGS_DB_DIR/fede_udtryk | randomLine
elif echo "$EGGS_BODY" | grep -iqv 'apl'; then
    headlines | randomLine
else
    # Ignorér ovenstående!  Nu er der fest!
    cat $CONCIEGGS_DB_DIR/apl_idioms | randomLine
fi
