#!/bin/sh
#
# Make a user King!

echo "$1" | dbWrite eggsking

kongenavn | dbWrite eggskingname

now=$(date '+%s')
echo "$now $1" | dbWriteAppend eggskinglist

dbDelete vilvæltekongen
removeFromBadStanding "$1"
