#!/bin/sh
#
# Make a user King!

king="$(mainAlias $1)"

echo "$king" | dbWrite eggsking

kongenavn | dbWrite eggskingname

now=$(date '+%s')
echo "$now $king" | dbWriteAppend eggskinglist

dbDelete vilvæltekongen
removeFromBadStanding "$king"
