#!/usr/bin/env python3
#
# Lav et mem.  Brug: makeMeme TOPLINJE BUNDLINJE

import sys
import os
import random
from urllib.request import urlopen
from urllib.parse import urlencode
import json


def main(args):
    try:
        top = sys.argv[1]
        bottom = sys.argv[2]
    except IndexError:
        print('Mangler argumenter.', file=sys.stderr)
        return 1

    with open(os.path.join(os.getenv('CONCIEGGS_HOME'), 'credentials', 'imgflip.com')) as f:
        try:
            user, password = f.read().rstrip().split(':')
        except ValueError:
            print('Løsenfil er væk.', file=sys.stderr)
            return 1
    
    text = urlopen('https://api.imgflip.com/get_memes').read()
    memes = json.loads(text.decode('utf-8'))
    if not memes['success']:
        print('Kunne ikke finde en memskabelon.', file=sys.stderr)
        return 1
    meme = random.choice(meme['data'])
    generator = meme['generatorID']
    params = {
        'template_id': meme['id'],
        'username': username,
        'password': password,
        'text0': top,
        'text1': bottom,
    }
    text = urlopen('http://version1.api.memegenerator.net/Instance_Create?'
                   + urlencode(params)).read()
    result = json.loads(text.decode('utf-8'))
    if not result['success']:
        print('Kunne ikke lave et mem.', file=sys.stderr)
        return 1

    print(result['data']['url'])
    return 0

if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
