#!/usr/bin/env python3
#
# Lav et mem.  Brug: makeMeme TOPLINJE BUNDLINJE

import sys
import os
import random
from urllib.request import urlopen, Request
from urllib.parse import urlencode
import json

def urlread(url):
    req = Request(url, headers={'User-Agent': 'Mozilla/5.0 (X11; U; Linux i686) Gecko/20071127 Firefox/2.0.0.11'})
    return urlopen(req).read()


def main(args):
    try:
        top = sys.argv[1]
        bottom = sys.argv[2]
    except IndexError:
        print('Mangler argumenter.', file=sys.stderr)
        return 1

    with open(os.path.join(os.getenv('CONCIEGGS_HOME'), 'credentials', 'imgflip.com')) as f:
        try:
            user, password = f.read().rstrip().split(':')
        except ValueError:
            print('Løsenfil er væk.', file=sys.stderr)
            return 1

    text = urlread('https://api.imgflip.com/get_memes')
    memes = json.loads(text.decode('utf-8'))
    if not memes['success']:
        print('Kunne ikke finde en memskabelon.', file=sys.stderr)
        return 1
    meme = random.choice(memes['data']['memes'])
    params = {
        'template_id': meme['id'],
        'username': user,
        'password': password,
        'text0': top,
        'text1': bottom,
    }
    text = urlread('https://api.imgflip.com/caption_image?' + urlencode(params))
    result = json.loads(text.decode('utf-8'))
    if not result['success']:
        print('Kunne ikke lave et mem.', file=sys.stderr)
        return 1

    print(result['data']['url'])
    return 0

if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
