#!/bin/sh
#
# Return 0 if everything's okay, 1 if it's not.

charm=$( ( echo 2 k
           (checkCharmen || echo 10)
           echo "10 / $1 100 * * 0 k 1 /"
           echo p
         ) | dc)
[ "$charm" -gt $(random 0 99) ]
