#!/bin/sh
#
# Format a month as its Danish name.

nthLine() {
    n="$1"
    head -n "$n" | tail -n 1
}

nthLine $1 <<EOF
januar
februar
marts
april
maj
juni
juli
august
september
oktober
november
december
EOF
