#!/bin/sh
#
# This script is run on all non-command output from the IRC bot.

set -e

channel="$1"
destuser="$2" # empty if it's not a 'user: message' message.
line="$3"

apply_db_filter() {
    if [ "$destuser" != '' ]; then
        cmd=$(echo -n $(dbRead "outfilter_command_$destuser"))
    fi
    if ! [ "$cmd" ] && [ "$channel" != '' ]; then
        cmd=$(echo -n $(dbRead "outfilter_command_$channel"))
    fi
    if ! [ "$cmd" ]; then
        cmd=$(echo -n $(dbRead outfilter_command))
    fi
    if [ "$cmd" ]; then
        $cmd
    else
        cat
    fi
}

echo "$line" | apply_db_filter
