#!/bin/sh
# Parses a command given to concieggs.

regex='(?i)(^ *'"$(regexEscape $CONCIEGGS_NAME)"'[,:!] +(?<rawcmd>[^ ]+)(?<args>.*)$|(?<rawcmd>[^ ]+)(?<args>.*), '"$(regexEscape $CONCIEGGS_NAME)"'[!.? ]*)$'

echo "$EGGS_BODY" | parse "$regex"
