#!/usr/bin/env perl
use 5.01;
use warnings;

die("Call script with: $0 <regex>\n") unless $#ARGV == 0;

my $rawregex = $ARGV[0];
my $regex = qr/$rawregex/;
my $data = join("\n", <STDIN>);

if ($data =~ $regex) {
    my %matches = %+;
    for my $key (keys %matches) {
        my $val = $matches{$key};
        $val =~ s/(\\)/\\$1/g;
        print "$key=\"\$(cat <<\"EOF\"\n$val\nEOF\n)\"\n"
    }
}
