#!/bin/sh
# Parses a command given to concieggs.

regex="(?i)(^ *$CONCIEGGS_NAME[,:!] +(?<rawcmd>[^ ]+)(?<args>.*)$|(?<rawcmd>[^ ]+)(?<args>.*), $CONCIEGGS_NAME[!.? ]*)\$"

echo "$EGGS_BODY" | parse "$regex"
