#!/bin/sh
# Parses a command given to concieggs.

me=$(regexEscape $CONCIEGGS_NAME)

regex='(?i)(^((ja)?men)? *'"$me"'[,:!] +(?<rawcmd>[^ ]+)(?<args>.*)$|(?<rawcmd>[^ ]+)(?<args>.*), '"$me"'[!.? ]*$)'

echo "$EGGS_BODY" | parse "$regex"
