#!/usr/bin/env python3
import sys
import re

if len(sys.argv) != 2:
    print(f"Call script with: {sys.argv[0]} <regex>", file=sys.stderr)
    sys.exit(1)

rawregex = sys.argv[1]
data = sys.stdin.read()

match = re.search(rawregex, data, re.MULTILINE | re.DOTALL)

if match:
    for key, val in match.groupdict().items():
        if val is not None:
            # Escape backslashes for shell
            val = val.replace('\\', '\\\\')
            print(f'{key}=$(cat <<"EOF" | sed -E \'s/[[:space:]]+$//\'')
            print(val)
            print()
            print('EOF')
            print(')')
