#!/bin/sh

if [ $# -eq 2 ]; then
    ann=$2
else
    ann=1
fi

sebastiansKodeVarEnGodIde=""

if maybeGood 0.05; then
    annoyedBy "$1" $(echo "$ann * -2" | bc)
    if [ "$sebastiansKodeVarEnGodIde" ]; then
        victim="$(allAliases | randomLine)"
        annoyedBy "$victim" $ann "blev valgt som syndebuk for $1's gode opførsel"
    fi
    exit
fi

annoyedBy "$1" $(echo "$ann * -1" | bc)
