#!/bin/sh

if [ $# -eq 2 ]; then
    ann=$2
else
    ann=1
fi

if cmpNames $1 Sebbe; then
    annoyedBy "svip" $(echo "$ann * -2" | bc)
    annoyedBy "Sebbe" $ann
    exit
fi

annoyedBy "$1" $(echo "$ann * -1" | bc)
