#!/bin/sh

if [ $# -eq 2 ]; then
    ann=$2
else
    ann=1
fi

if maybeGood 0.05; then
    annoyedBy "$1" $(echo "$ann * -2" | bc)
    victim="$(allAliases | randomLine)"
    annoyedBy "$victim" $ann "blev valgt som syndebuk for $1's gode opførsel"
    exit
fi

annoyedBy "$1" $(echo "$ann * -1" | bc)
