#!/bin/sh

charm=$(getCharmen)
anticharm=`expr 10 - $charm`

start=\|
kasse=□

until [ $charm -lt 1 ]
do
  start=$start$kasse
  charm=`expr $charm - 1`
done

until [ $anticharm -lt 1 ]
do
  start=$start-
  anticharm=`expr $anticharm - 1`
done

echo $start\|
