#!/bin/sh

name=$(randomName "$1")
if isGod "$1"; then
    randomLine <<EOF
hans Hellighed
den Øverste
vor Frelser
vor Ophøjede Skaber
$1 Augustus
EOF
else
    randomLine <<EOF
Kong $name
Hans Majestæt $name
Hans Majestæt
$name Rex
Hans Majestæt $1
EOF
fi
