#!/bin/sh

set -e

public_key=$(cat $HOME/credentials/marvel/public-key)
private_key=$(cat $HOME/credentials/marvel/private-key)
timestamp=$(date +%s)
hash=$(echo -n $timestamp$private_key$public_key | md5)

curl -s -G \
     -d apikey=$public_key -d ts=$timestamp -d hash=$hash -d limit=1 -d offset=$(random 0 1490) \
     https://gateway.marvel.com/v1/public/characters \
    | egrep -o '"name":"[^"]+"' | head -n 1 | cut -d '"' -f 4
