#!/bin/sh

name=$(randomName "$1")
if isGod "$1"; then
    randomElement <<EOF
hans Hellighed
den Øverste
vor Frelser
vor Ophøjede Skaber
$1 Augustus
EOF
else
    randomElement <<EOF
kong $name
hans majestæt $name
hans majestæt
$name rex
hans kongelige højhed $1
EOF
fi
