#!/bin/sh
#
# Add an item to the list of indkøbsønsker.

count="$1"
what="$2"

if gitRefresh; then
    cd $EGGS_DIR
    for i in `seq 1 $count`; do
        ed slashdotfrokost > /dev/null <<EOF
/::INDKØBSØNSKER::/
+1
i
$(echo "$what")
.
w
EOF
    done
    if tryGitChange "ønsk $count af $what" slashdotfrokost; then
        echo "Det er noteret at $count $what er ønsket."
    else
        gitRepair slashdotfrokost
        echo "Katastrofe!  Noget gik galt med Git!"
        exit 1
    fi
else
    exit 1
fi
