#!/bin/sh
#
# Add an item to the list of indkøbsønsker.

count="$1"
what="$2"

if gitRefresh; then
    cd $EGGS_DIR
    ed slashdotfrokost > /dev/null <<EOF
/::INDKØBSØNSKER::/
+1
i
$(for i in `seq 1 $count`; do echo "$what"; done)
.
w
EOF
    if tryGitChange "ønsk $count af $what" slashdotfrokost; then
        if [ $count = 1 ]; then
            echo "Det er noteret at $what er ønsket."
        else
            echo "Det er noteret at $count $what er ønsket."
        fi
    else
        gitRepair slashdotfrokost
        echo "Katastrofe!  Noget gik galt med Git!"
        exit 1
    fi
else
    exit 1
fi
