#!/bin/sh

randomLine <<EOF
Du træder stolt ind i det monarkibevarende selskab og støtter Kongen.
Du skælder ud på et barn der synes godt om den anarkistiske karakter i eventyrsromanen.
Du barberer en mistænkt oprører dårligt.
Du giver din andenfødte søn kongens fornavn som mellemnavn.
Om aftenen før du skal sove beder du både til Gud *og* Kongen.
EOF
