#!/bin/sh
#
# Find de nyligt aktive.

lines=$1

if ! [ $lines ]; then
    lines=1000
fi

filterIsOnline() {
    while read user; do
        if isOnline $user; then
            echo $user
        fi
    done
}

recentChat $lines \
    | egrep -o '^#[a-z]+ +:[0-9 :\-]+<([^ >]+)' \
    | cut -d'<' -f2 \
    | grep -v "^$CONCIEGGS_NAME\$" \
    | grep -v '^guest_' \
    | grep -v '^infoskaerm' \
    | sort \
    | uniq \
    | randomise

#    | filterIsOnline \ # This is too inefficient, but at least it's there.
