#!/bin/sh
#
# Find de nyligt aktive.

tail -n 1000 out|egrep -o '^#[a-z]+ +:[0-9 :\-]+<([^ >]+)' | cut -d'<' -f2 | grep -v '^hej_fra_github$' | grep -v "^$CONCIEGGS_NAME$" | grep -v '^guest_' | sort -u
