#!/bin/sh
#
# The revolution is real!

dbDelete eggsking
now=$(date '+%s')
echo "$now" | dbWriteAppend eggskinglist
# Uden felt to (kongenavn), betyder det at kongen var blevet smidt af!
# Interregnum
