#!/bin/sh

broke() {
    echo "Kommandoen fejlede!  Du kan prøve at spørge mig om 'udu', men det hjælper næsten helt sikkert ikke."
}

run() {
    cmd="$1"
    acmd="$2"
    shift
    shift

    case "$cmd" in
        er|hvem|hvad|hvor|har*)
            "$acmd" $(echo "$@" | sed 's/\?*$//')
            ;;
        *)
            "$acmd" "$@"
            ;;
    esac || broke
}

if [ "$1" = -a ]; then
    check_all_places=-a
    shift
fi


rawcmd=$1
cmd="$(basename -- "$rawcmd")"
cmd="$(echo "$cmd" | sed 's/,$//')"
cmddir=$CONCIEGGS_DIR/cmds
shift

alias="$(cmdAlias "$cmd")"
if [ "$alias" ]; then
    cmd="$(echo $alias | cut -s -d' ' -f 1)"
    args="$(echo $alias | cut -s -d' ' -f 2-) $@"
else
    args="$@"
fi

if [ $check_all_places ]; then
    acmd="$(find "$CONCIEGGS_DIR/cmds" -name "$cmd" | head -n 1)"
else
    t="$cmddir/$cmd"
    if [ -x "$t" ] && [ -f "$t" ]; then
        acmd="$t"
    else
        t="$cmddir/$(ircChannel)/$cmd"
        if [ -x "$t" ] && [ -f "$t" ]; then
            acmd="$t"
        fi
    fi
fi

if [ "$cmd" ] && [ "$EGGS_USER" != "$CONCIEGGS_NAME" ]; then
    if [ "$acmd" ]; then
        run "$cmd" "$acmd" "$args"
    elif $(echo "$args" | grep '\?$' > /dev/null); then
        run 8ball "$cmddir/8ball" "$args"
    else
        othercmd="$(commands $check_all_places|levenshtein "$cmd"|sort -n|head -n 1|cut -d ' ' -f 2-)"
        if [ "$othercmd" ]; then
            echo "Jeg antager at du mente $othercmd!"
            otheracmd="$(find "$CONCIEGGS_DIR/cmds" -name "$othercmd" | head -n 1)"
            run "$othercmd" "$otheracmd" "$args"
        else
            echo "$EGGS_USER: Du bad mig om $cmd, men den kommando har jeg ikke!";
            echo "Skriv 'concieggs: kommandoer' for at få en liste over mulige kommandoer."
        fi
    fi
fi
