#!/bin/sh
#
# Run a simple shell command in the service of some channel or user.
# This will decorate the output with specifications of where it is
# supposed to go at the IRC-level.

sayTo() {
    destination=$1

    fmt -w 380 | gawk '{ print ":m", DEST, $0 }' "DEST=$destination"
}

filter_non_commands() {
    while read -r line; do
        (if say "$line" | egrep -q '^:'; then
             say "$line"
         else
             user="$(say "$line" | sed -r 's/: .+//')"
             if (say "$user" | grep -q ' '); then
                 user=''
             fi
             outfilter "$(basename "$PWD")" "$user" "$line"
         fi) || say "$line"
    done
}

where=$1
shift
((("$@" 2>&4 | filter_non_commands | sayTo "$where" >&3) 4>&1) | sayTo "$CONCIEGGS_ERROR_CHANNEL" >&3) 3>&1
