#!/bin/sh
#
# Run a simple shell command in the service of some channel or user.
# This will decorate the output with specifications of where it is
# supposed to go at the IRC-level.

sayTo() {
    destination=$1

    while read -r line; do
        if say "$line" | egrep -q '^:'; then
            # Is command - do not molest.
            say "$line"
        else
            # Is not command - do molest.
            say "$line" | \
                fmt -s -w 380 | \
                while read -r subline; do
                    say ":m $destination $subline"
                done
        fi
    done
}

where=$1
shift
((("$@" 2>&4 | sayTo "$where" >&3) 4>&1) | sayTo "$CONCIEGGS_ERROR_CHANNEL" >&3) 3>&1
