#!/bin/sh
#
# Run a simple shell command in the service of some channel or user.
# This will decorate the output with specifications of where it is
# supposed to go at the IRC-level.

sayTo() {
    destination=$1

    linefmt -w 380 | gawk '{ print ":m", DEST, $0; fflush(); }' "DEST=$destination"
}

filter_non_commands() {
    while IFS='' read -r line; do
        (if say "$line" | egrep -q '^:'; then
             say "$line"
         else
             user="$(say "$line" | sed -r 's/: .+//')"
             if (say "$user" | grep -q ' '); then
                 user=''
             fi
             outfilter "$(basename "$PWD")" "$user" "$line"
         fi) || say "$line"
    done
}

# Converts "/me does stuff" to "\x01ACTION does stuff"
ircify_actions() {
    perl -ne 's{^/me}{\x01ACTION}g; print'
}

where=$1
shift
((("$@" 2>&4 | filter_non_commands | ircify_actions | sayTo "$where" >&3) 4>&1) | sayTo "$CONCIEGGS_ERROR_CHANNEL" >&3) 3>&1
