#!/bin/sh
hooks=$1

onlyFirstHook=$(cat <<"EOF"
BEGIN { curhook = 0 }
{
match($0, "[^:]+: ");
hook=substr($0, RSTART, RLENGTH-2)
output=substr($0, RSTART+RLENGTH)

if (!curhook || hook == curhook) {
  curhook = hook
  print output
  fflush()
}
}
EOF
             )

doGentauto() {
    i=0;
    while read -r line; do
        if [ $i = 0 ]; then
            echo "$(date +%H:%M) <$EGGS_USER> $EGGS_BODY"
        fi
        i=$((i+1))
        echo "$line"
    done
}

ls "$CONCIEGGS_DIR/hooks/$hooks/" |
    while read -r f; do
        spoke=''
        hook=$CONCIEGGS_DIR/hooks/$hooks/$f
        if [ -x "$hook" ]; then
            decorateStdout "hooks/$f" decorateStderr "hooks/$f" runhook "$hook"
        fi
    done |
    if dbExists debugging; then
        cat
    else
        awk "$onlyFirstHook"
    fi |
    if usesFilter gentauro; then
        doGentauto
    else
        cat
    fi
