#!/bin/sh
hooks=$1
ls "$CONCIEGGS_DIR/hooks/$hooks/" |
    while read -r f; do
        hook=$CONCIEGGS_DIR/hooks/$hooks/$f
        if [ -x "$hook" ]; then
            runhook "$hook"
        fi
    done
