#!/usr/bin/env perl
#
# Konvertér fx "translate da sv" til "svensk" eller "translate da sv da" til "svensk-dansk".
use 5.020;
use strict;
use warnings;
use utf8::all;

use Env qw(EGGS_WHERE);
use EggsML::EggsPI text => [qw(dbRead langname)];

my $b = dbRead('outfilter_command_' . $EGGS_WHERE) || dbRead('outfilter_command');
$b =~ s/^translate da *//;

print join('-', map { langname($_) } (split / /, $b)) || 'dansk';
