#!/bin/sh

Output=$(curl -s -o /dev/null -w "%{http_code}" --connect-timeout 1 $1)
case $Output in 3*)
    sc_follow=$(curl -L -s -o /dev/null -w "%{http_code}" --connect-timeout 1 $1)
    Output="$Output -> $sc_follow"
esac
case $Output in
    5*) Output="$Output.  Pis mig i øret." ;;
    4*) Output="$Output.  Er du sikker på, den findes?" ;;
    2*) Output="$Output ^^"
esac
echo "$Output"
exit 0;
