#!/bin/sh

usle=`randomLine <<EOF
Usle
Gemene
Blødsødne
Latterlige
Dumme
Ubehøvlede
Perfide
EOF`

slambert=`randomLine <<EOF
slambert
IP-genganger
humanist
PHK-wannabe
kujon
krapyl
hundehandler
EOF`

randomLine <<EOF
$usle $slambert!
EOF
