#!/bin/sh
#
# How many seconds to the closest reminder?

here=$(ircChannel)
now=$(nowTime)

{
    for reminder in $(dbIterate reminders); do
        dbRead "$reminder" |
            ( read duration
              read when
              read who
              read where
              read command
              if [ "$now" -gt "$when" ]; then
                  echo 0
              else
                  echo $(($when - $now))
              fi
            )
    done
    echo 86400
} | sort -n | head -n 1
