#!/bin/sh

hour="$(dateSecs $1 +%H)"
minute="$(dateSecs $1 +%M)"

if [ $hour = 13 -a $minute = 0 ]; then
    minutes
    echo "gentleman Eggs $(timeToRelDay $1)"
elif [ $hour = 14 -a $minute = 0 ]; then
    minutes
    echo "Eggs royale $(timeToRelDay $1)"
else
    echo "Eggs $(timeToDate $1)"
fi
