#!/bin/sh
#
# Translate from any Google Translate-supported language to another through a
# chain.  Also handle built-in filters.

t() {
    filter="$CONCIEGGS_DIR/filters/$2"
    if test -x "$filter"; then
        "$filter"
    else
        $CONCIEGGS_HOME/bin/translate-shell/translate -brief "$(langcode $1):$(langcode $2)" - \
            | perl -ple 's!^/(?: me)? !/me !' # Google Translate breaks '/me' lines. Unbreak them.
    fi
}

eval $(python - "$@" <<EOF
import sys
print ' | '.join("t '%s' '%s'" % t for t in zip(sys.argv[1:], sys.argv[2:]))
EOF
)
