#!/bin/sh
#
# Translate from any Google Translate-supported language to another through a
# chain.

t() {
    filter="$CONCIEGGS_DIR/filters/$2"
    if test -x "$filter"; then
        "$filter"
    else
        from="$1"
        langcodes="$CONCIEGGS_DB_DIR/langcodes"
        if ! grep -q "$from" "$langcodes"; then
            from='' # Let Google guess.
        fi
        $CONCIEGGS_HOME/bin/translate-shell/translate -brief "$from:$2" -
    fi
}

eval $(python - "$@" <<EOF
import sys
print ' | '.join("t '%s' '%s'" % t for t in zip(sys.argv[1:], sys.argv[2:]))
EOF
)
