#!/bin/sh
#
# Translate from any Google Translate-supported language to another through a
# chain.

t() {
    while read -r line; do
        echo "$line" | gawk -f $HOME/bin/google-translate.awk "$1" -
    done
}

eval $(python - "$@" <<EOF
import sys
print ' | '.join("t '{%s=%s}'" % t for t in zip(sys.argv[1:], sys.argv[2:]))
EOF
)
