#!/bin/sh

ungerne=`randomElement <<EOF
ungerne
børnene
Java
NemID
HTML5
sammenhængskraften
fremtiden
CSS3
projektstyringen
SharePoint-installationen
loginportalerne
statens overvågning
kønsdelene
monader
forretningsmodeller
fri software
open source
Facebook
Instagram
JavaScript
EOF`

enHipster=`randomElement <<EOF
en hipster
en humanist
en fysiker
en radmager laban
en brillemager
en "it-professionel"
en idiot
et gadekryds
en frihedsevangelist
en business man
en popstjerne
en Peter
en Windows-bruger
en Mac-fanatiker
EOF`

styre=`randomElement <<EOF
styre
kontrollere
have kontrol over
håndtere
migrere
regulere
tvinge
EOF`

klikkeHer=`randomElement <<EOF
klikke her
trykke på _den_ knap
være en $hipster for at forstå det
afhænge af $ungerne
gøre dét
$styre mig selv
indtaste *den* kommando
EOF`

lort=`randomElement <<EOF
lort
søm
skruer
tis
klamhed
EOF`

egerntype=`randomElement <<EOF
jord
flyve
EOF`

nuttedeDyr=`randomElement <<EOF
${egerntype}egern
kaniner
katte
marsvin
hundehvalpe
delfiner
EOF`

menHvadMedUngerne=`randomElement <<EOF
Men hvad med $ungerne?
Kan du give et eksempel?
Jeg er ikke tryg ved fokus på $ungerne.
Jeg er ikke tryg ved mangel af fokus på $ungerne.
Stoler du da ikke på $ungerne?
Jeg har nu ret svært ved det.
Man er nok $enHipster der går op i $ungerne...
Fuck dig.  Tænk på $ungerne.
Hvorfor er du så begejstret for $ungerne?
For fanden, smid dem nu bare ud.
Hvorfor skal jeg $klikkeHer?
Så du siger at jeg skal $klikkeHer?
Ikke $ungerne igen...
EOF`

deSkalVelHaveMad=`randomElement <<EOF
De skal vel også spise!
Slår du dine venner?
Det er urealistisk.
Din hippie-optimist.
Ligner jeg måske $enHipster?
Jeg kan selv $styre mit liv.
Husk at gemme. ;-)
*Jeg* bruger ikke buzzwords!!!
Danmark har ikke brug for endnu $enHipster.
Det virker i Ubuntu.
Det virker på Windows.
Man kan sige at "Du styer får vilt!! XD"
Skal det da forstås sådan?
Spis $lort.
Det oversætter jo ikke.
Fuck dig!
Dræber du måske $nuttedeDyr?
Tag dig dog sammen.
Er du også sådan i morgen?
EOF`

erDuMaaskeDum=`randomElement <<EOF
Er du måske dum?
Spis tis.
Fucking latterligt.
Din mor.
Din mormor!
For fanden...
På pikken..
For helvede!
EOF`

randomElement <<EOF
$menHvadMedUngerne  $deSkalVelHaveMad  $erDuMaaskeDum
$menHvadMedUngerne  $erDuMaaskeDum  $deSkalVelHaveMad
$erDuMaaskeDum
EOF
