#!/usr/bin/env perl
#
# Udfør en forespørgsel til Wolfram|Alpha.

use strict;
use warnings;
#use lib "$ENV{HOME}/.perl/lib/perl/5.10.1/";
use WWW::WolframAlpha;

# https://developer.wolframalpha.com/portal/myapps/
# user: concieggs@coq.dk
# password: the usual
my $wa = WWW::WolframAlpha->new(
    appid => 'UE3A9Y-HT8WR4VVV7'
);

my $req = join " ", @ARGV;
my $query = $wa->query(
    input => $req
);

unless ($query->success) {
    print "Intet resultat.\n";
    exit(0);
}

foreach my $pod (@{$query->pods}[0 .. 5]) {
    next unless $pod;

    my $contents = join ", ", map { $_->plaintext // '' } @{$pod->subpods};

    next if $contents =~ /HASH\(0x[0-9a-f]+\)/;

    my $title = $pod->title;
    print "$title: $contents\n";
}
