#!/usr/bin/env python3
import sys
import random

n = int(sys.argv[1])
min_val = int(sys.argv[2])
max_val = int(sys.argv[3])
wiggle_factor = float(sys.argv[4])

last_change = 0
offset = 0
wiggle_back_space = 4

res = []

for i in range(1, n + 1):
    if (i - last_change) > wiggle_back_space:
        if n - i <= abs(offset) * wiggle_back_space:
            if offset > 0:
                offset -= 1
            if offset < 0:
                offset += 1
            last_change = i
        elif random.random() < wiggle_factor:
            offset += 1 if random.random() > 0.5 else -1
            if offset > max_val:
                offset = max_val
            if offset < min_val:
                offset = min_val
            last_change = i
    
    res.append(offset)

for val in res:
    print(val)
