#!/bin/sh
#
# This script is run on all non-command output from the IRC bot.

set -e

channel="$1"
destuser="$2" # empty if it's not a 'user: message' message.
line="$3"

# We would like to remove '/me ' from messages before passing them to filters.
# That way, filters can rewrite the message liberally without distorting the
# way it gets delivered as an action.
apply_db_filter() {
    if echo "$line" | egrep -q '^/me '; then
        sed 's/^\/me //' | apply_db_filter_inner | sed 's/^/\/me /'
    else
        apply_db_filter_inner
    fi
}

apply_db_filter_inner() {
    # Set 'filterchain'
    if [ "$destuser" != '' ]; then
        filterchain=$(echo -n $(dbRead "filterchain_$destuser"))
    fi
    if ! [ "$cmd" ] && [ "$channel" != '' ]; then
        filterchain=$(echo -n $(dbRead "filterchain_$channel"))
    fi
    if ! [ "$cmd" ]; then
        filterchain=$(echo -n $(dbRead filterchain))
    fi

    # Apply 'filterchain', or not.
    if [ "$filterchain" ]; then
        translate da $filterchain
    else
        cat
    fi
}

if [ "$(date +%H%M)" = 1337 ]; then
    echo "$line" | filter leet | apply_db_filter
elif isChristmas; then
    echo "$line" | christmasy | apply_db_filter
else
    echo "$line" | apply_db_filter
fi
