#!/bin/sh
#
# This script is run on all non-command output from the IRC bot.

set -e

channel="$1"
destuser="$2" # empty if it's not a 'user: message' message.
line="$3"

apply_db_filter() {
    if [ "$destuser" != '' ]; then
        filterchain=$(echo -n $(dbRead "filterchain_$destuser"))
    fi
    if ! [ "$cmd" ] && [ "$channel" != '' ]; then
        filterchain=$(echo -n $(dbRead "filterchain_$channel"))
    fi
    if ! [ "$cmd" ]; then
        filterchain=$(echo -n $(dbRead filterchain))
    fi
    if [ "$filterchain" ]; then
        translate da $filterchain
    else
        cat
    fi
}

if isChristmas; then
  echo "$line" | christmasy | apply_db_filter
else
  echo "$line" | apply_db_filter
fi
