#!/bin/sh

set -e
id="$(basename "$0")"

jeopardy() {
    # kun en test indtil videre
    echo Start
    read -r a
    echo "$a"
    read -r b
    echo "$b"
    echo "$a"
}

eval $(bgCmdRun "$id" jeopardy "$*")
