#!/bin/sh

(notOnEggsChannel || shuttingUp) && exit
[ "$EGGS_USER" = "$CONCIEGGS_NAME" ] && exit

aliases "$EGGS_USER" | while read -r alias; do
    when=$(dbUserRead "$EGGS_USER" reenberg/when)
    if [ "$when" ]; then
        loss=$(expr $(dbUserRead "$EGGS_USER" reenberg/loss) / 60 + 1)
        echo "$EGGS_USER: Skam dig!  Du begik en Reenberg $(timeToFullDate $when), da du forlod kanalen mindre end $loss minutter efter din frokosttilmelding!"
        dbUserDelete "$EGGS_USER" reenberg
        annoyedBy "$EGGS_USER" 10 "begik en Reenberg"
    fi
done
