#!/bin/sh

if ! checkCooldown "velkomstGlobal" 120; then
    exit 0
fi

if ! checkCooldown "Velkomst$EGGS_USER" $((60 * 60 * 96)); then
    exit 0
fi

if [ "$EGGS_USER" = "$CONCIEGGS_NAME" ]; then
    exit
fi

# Produce a random thought when someone enters the channel
# but wait a short while such that it seems more natural
sleep 6
rand=$(random 1 10)
case $rand in
    # Produce a random thought
    1|2|3)
        rt=`$CONCIEGGS_DIR/cmds/vejr Velkomstbesked`
        ;;
    4|5|6)
        rt=`$CONCIEGGS_DIR/cmds/forvikling Velkomstbesked`
        ;;
    7|8|9)
        rt=`$CONCIEGGS_DIR/cmds/betragtning`
        ;;
    10)
        rt=`$CONCIEGGS_DIR/cmds/drudge dyr Velkomstbesked`
esac

echo "Velkommen $EGGS_USER! $rt"
