#!/bin/sh

if ! checkCooldown "velkomstGlobal" 180; then
    exit 0
fi

if ! checkCooldown "Velkomst$EGGS_USER" $((60 * 60 * 120)); then
    exit 0
fi

if [ "$EGGS_USER" = "$CONCIEGGS_NAME" ]; then
    exit 0
fi

# Produce a random thought when someone enters the channel
# but wait a short while such that it seems more natural
sleep 6
rand=$(random 1 5)
case $rand in
    # Produce a random thought
    1)
        rt=`$CONCIEGGS_DIR/cmds/forvikling Velkomstbesked`
        ;;
    2)
        rt=`$CONCIEGGS_DIR/cmds/forvakling`
        ;;
    3)
        rt=`$CONCIEGGS_DIR/cmds/betragtning`
esac

echo "Velkommen $EGGS_USER! $rt"
