#!/bin/sh

if [ "$EGGS_USER" = "$CONCIEGGS_NAME" ]; then
    exit
fi

if [ 1 = 1 ]; then
    # Produce a random thought when someone enters the channel
    rand=1
    case $rand in
        # Produce a random thought
        1)
            rt=`$CONCIEGGS_DIR/cmds/vejr Velkomstbesked`
            ;;
        2)
            rt=`$CONCIEGGS_DIR/cmds/forvikling`
            ;;
        3)
            rt=`$CONCIEGGS_DIR/cmds/betragtning`
            ;;
    esac
fi

echo "Velkommen $EGGS_USER! $rt"
