#!/bin/sh

shuttingUp && exit

if christmas && maybeGood .7; then
    if isKing "$EGGS_USER"; then
        randomElement <<EOF
Deres Majestæt!  Det er jul!
Pøblen glæder sig over højtiden, Deres Majestæt.
Vi forventer mange gaver til Dem, Kong $EGGS_USER.
$EGGS_USER: Julen er den gladeste tid i riget.
EOF
    else
        randomElement <<EOF
$EGGS_USER: Hohoho!  Glædelig jul!
$EGGS_USER, det er jul!
$EGGS_USER, jul-jul-jul!
Husk nu at det er jul, $EGGS_USER!
DET ER LISSOM JUL $EGGS_USER!
JUUUUUUUUUUUUUUUUUUUUUUUUL!!!
$EGGS_USER, $EGGS_USER, $EGGS_USER!!!  DET ER JUUUUUUL!
Jeg kan ikke vente til juleaften, $EGGS_USER!
$EGGS_USER: Er $(du $EGGS_USER) ikke også spændt på julen?
$EGGS_USER, tænk på alle de gaver vi får til jul!
Jubii, $EGGS_USER!  Det er jul!
EOF
	fi
    pleasedBy "$EGGS_USER" 1
fi
