#!/bin/sh

shuttingUp && exit

if christmas && maybeGood .7; then
   randomElement <<EOF
$EGGS_USER: Hohoho!  Glædelig jul!
$EGGS_USER, det er jul!
$EGGS_USER, jul-jul-jul!
Husk nu at det er jul, $EGGS_USER!
DET ER LISSOM JUL $EGGS_USER!
EOF
fi
