#!/bin/sh
#
# Påmind om gæld ved join

. $CONCIEGGS_DIR/eggspi.lib

debt=$(lookupDebt $EGGS_USER)

if [ -n "$debt" ]; then
    if [ "$(echo "$debt > 50" | bc)" = 1 ]; then
        echo "Velkommen $EGGS_USER, du skylder $debt kr. til frokostkassen! Stram op!"
    fi
fi
