#!/bin/sh
#
# Påmind om gæld ved join

. $CONCIEGGS_DIR/eggspi.lib

debt=$(lookupDebt $EGGS_USER)

if [ -n "$debt" ]; then
    if  [ $(echo "0 $(echo $debt | sed s/\-/_/) [1p] sX >X" | dc) ]; then
        echo "Velkommen $EGGS_USER, du skylder $debt kr. til frokostkassen! Stram op!"
    fi
fi
