#!/bin/sh
#
# Påmind om gæld ved join

notOnEggsChannel && exit

debt=$(lookupDebt $EGGS_USER)

if [ -n "$debt" ]; then
    if [ "$(echo "$debt > 50" | bc)" = 1 ]; then
        echo -n "Velkommen $EGGS_USER, du skylder $debt kr. til frokostkassen! "
        if [ "$(echo "$debt > 150" | bc)" = 1]; then
            echo -n "Du skylder snart mere en Grækenland! "
        else
            echo -n "Stram op! "
        fi
        wish=$(eggstool wishes | sort -R | head -n 1)
        if [ "$wish" ]; then
            echo "Du kunne f.eks. købe $wish!"
        else
            echo
        fi
    fi
fi
