#!/bin/sh

(notOnEggsChannel || shuttingUp) && exit

aliases "$EGGS_USER" | while read -r alias; do
    when=$(dbRead "users/$alias/reenberg/when")
    if [ "$when" ]; then
        loss=$(expr $(dbRead "users/$alias/reenberg/loss") / 60 + 1)
        echo "$EGGS_USER: Skam dig!  Du begik en Reenberg $(timeToFullDate $when), da du forlod kanalen mindre end $loss minutter efter din frokosttilmelding!"
        dbDelete "users/$alias/reenberg"
    fi
    annoyedAt "$EGGS_USER" 1
done
