#!/bin/sh

# Spred glæde på #eggsml.

set -e

maybeGood .2 || exit # Men ikke *så* ofte.

rar=(randomElement <<EOF
rar
sød
behagelig
venlig
det modsatte af ond
unedern
den bedste ven en IRC-bot kan ønske sig
helt ok
slet ikke et svin
velduftende
EOF

echo $EGGS_USER: Jeg synes at du er $rar.
