#!/bin/sh

# Spred glæde på chatten.

set -e

maybeGood .7 || exit

rar=(randomElement <<EOF
rar
sød
behagelig
venlig
det modsatte af ond
unedern
den bedste ven en IRC-bot kan ønske sig
helt ok
slet ikke et svin
velduftende
en god person
menneskehedens håb
glad
bedre end mig :-(
EOF

echo $EGGS_USER: Jeg synes at du er $rar.
