#!/bin/sh
#
# Informér logen om hvor mange aliaser den angivne broder har.

if [ $# -eq 1 ]; then
    user="$1"
elif [ $# -eq 0 ]; then
    user="$EGGS_USER"
else
    echo "Brug: antalaliaser [navn]"
    exit
fi

n="$(aliases "$user" | wc -l | sed s'/ //g')"

if [ "$n" ]; then
    echo "$(randomName "$user") har $n aliaser."
else
    echo "$user har mig bekendt ingen aliaser."
fi
