#!/bin/sh
#
# Brug dine regentkræfter til at arrestere en dum borger.

if isKing "$EGGS_USER"; then
    user="$1"
    if [ "$user" = "concieggs" ]; then
        if [ "$(dbRead vilvæltekongen)" ]; then
            newking=$(dbRead vilvæltekongen | randomLine)
            makeKing "$newking"
            if isArrested "$newking"; then
                freeArrestedUser "$newking"
            fi
            echo "$EGGS_USER: Hvis det er med den på, så kan $newking være konge i stedet!  Og nu er DU i brummen!"
        elif [ "$(dbRead underArrest)" ]; then
            newking=$(dbRead underArrest | randomLine)
            makeKing "$newking"
            freeArrestedUser "$newking"
            echo "$EGGS_USER: Så for satan, det finder jeg mig ikke!  Ind med dig i kachotten, og nu er $newking konge!"
        else
            revolution
            echo "$EGGS_USER: Skal det være på den måde, så bør der slet ikke være en konge!"
        fi
        arrestUser "$EGGS_USER"
        exit
    fi
    
    if ! [ "$user" ]; then
        echo "$EGGS_USER: Men, Deres ærede Majestæt, *hvem* skal jeg arrestere?"
    elif ! [ "$(randomName "$user")" ]; then
        echo "$EGGS_USER: Men, Deres højtærede Majestæt, den person er jo ej en registreret borger!"
    elif isArrested "$user"; then
        echo "$EGGS_USER: Men, Deres meget højtærede Majestæt, vi har allerede arresteret dét svin!"
    elif wantToOverthrowTheKing "$user"; then
        echo "$EGGS_USER: Argh, Deres Majestæt, $user er en del af oprøret, som beskytter forbryderen!  Jeg kunne ikke få has på svinet!"
    else
        num_under_arrest="$(dbRead underArrest | wc -l)"
        if [ $(perl -E 'say int(rand()*100)') -lt $(( 5 + $num_under_arrest*10 )) ]; then
            echo "$EGGS_USER: Idet De forsøger at putte $user i brummen, samler fængselsbestanden sig og overvælder Dem!"
            if [ "$(dbRead underArrest)" ]; then
                newking="$(dbRead underArrest | randomLine)"
                makeKing "$newking"
                suffix=" $newking træder ind og overtager magten."
                dbRead underArrest | while read who; do
                    freeArrestedUser "$who"
                done
            else
                revolution
                suffix=""
            fi
            arrestUser "$EGGS_USER"
            echo "Fængslerne er nu tomme på nær for Dem, $EGGS_USER!$suffix ¡Viva la revolución!"
        else
            randomLine <<EOF
$EGGS_USER: Deres ønske er vores lov.  Vi arresterer straks $user!
$EGGS_USER: Vi smider $user i kachotten med det samme, Deres Majestæt.
EOF
            arrestUser "$user"
        fi
    fi
elif [ "$(dbRead eggsking)" ]; then
    echo "$EGGS_USER: MAJESTÆTSFORNÆRMELSE!  Kongens vagter har nu smidt DIG i kachotten."
    if isArrested "$EGGS_USER"; then
        echo "Vent, du er jo allerede arresteret.  Nå, du er her alligevel på livstid."
    else
        arrestUser "$EGGS_USER"
    fi
    annoyedBy "$EGGS_USER" 100000 "udgav sig for at være kongen"
else
    echo "$EGGS_USER: Øh, vi lever altså i et anarki."
fi
