#!/bin/sh
#
# Udøv kongelig autoritet til at benåde en logebroder.

remove() {
    removeFromBadStanding "$who"
    freeArrestedUser "$who"
    if cmpNames "$who" "$EGGS_USER"; then
        echo "$(ack) Nu De jo er konge, så bør jeg vel hellere behandle Dem med respekt..."
    else
        echo "$(ack) Jeg har atter taget $who til nåde."
    fi
}

if isKing $EGGS_USER; then
    if [ "$*" = "alle!" ]; then
        allAliases | while read who; do
            if isInBadStanding "$who" || isArrested "$who"; then
                remove "$who"
            fi
        done
        echo "Alle er benådet, min konge!"
    elif [ "$*" = "alle" ]; then
        echo "Deres Majestæt, en sådan handling er indenfor Deres beføjelser, men De skal virkelig mene det."
    elif [ $# -eq 1 ]; then
        who=$(randomName "$1")
        if [ "$who" ]; then
            if isInBadStanding "$who"; then
                remove "$who"
            else
                echo "$EGGS_USER: $who er allerede fri for sanktioner fra min side af."
            fi
        else
            echo "$EGGS_USER: Jeg er bange for, at jeg ikke ved hvem '$1' skulle være."
        fi
    fi
else
    punishNonKing "$EGGS_USER" 5 "bad mig om at benåde uden at være konge"
fi
