#!/bin/sh
#
# Få concieggs til at lave drive-by-kanal-hop.  Brug: 'hop på KANAL' eller 'hop
# af KANAL'.


if [ $# -lt 2 ]; then
    echo "$EGGS_USER: Jeg har aldeles ikke i sinde bare at hoppe og danse for $(dig $EGGS_USER)!  Du må udtrykke $(dig $EGGS_USER) forståeligt."
else
    if [ "$1" = "på" ]; then
        ircJoinChannel "$2"
    elif [ "$2" = "af" ]; then
        ircPartChannel "$2"
    fi
fi
