#!/bin/sh
#
# Husk et givent faktum til senere opslag via 'forklar'.

if [ "$1" = 'at' ]; then
    shift
fi

if [ $# -gt 0 ]; then
    say "$@" >> $CONCIEGGS_DB_DIR/fakta
    echo "Det er husket!"
else
    echo "Men hvad skal jeg huske?"
fi 
