#!/bin/sh
#
# Husk et givent faktum til senere opslag via 'forklar'.

if [ "$1" = 'at' ]; then
    say "$EGGS_USER: Hvis du begynder dit stykke fakta med 'at', så er det nok ikke en værdig sætning.  Skriv i stedet dit stykke fakta som en hel sætning."
    exit
fi

if [ $# -gt 0 ]; then
    say "$@" >> $CONCIEGGS_DB_DIR/fakta
    echo "Det er husket!"
else
    echo "Men hvad skal jeg huske?"
fi 
