#!/bin/sh
#
# Husk et givent faktum til senere opslag via 'forklar'.


if [ $# -gt 0 ]; then
    echo "$@" >> $CONCIEGGS_DB_DIR/fakta
    echo "Det er husket!"
else
    echo "Men hvad skal jeg huske?"
fi 
