#!/bin/sh
#
# Beskriv concieggs' opfattelse af en given brugers identitet.  Husk
# at benytte komplette sætninger!  Alternativt, spørg hvem der skal
# købe ind eller hvem der har en ting.

eval "$(echo "$@" | parse 'er (?<hveranden>hveranden)|'\
'(?<user>[^ ]+))$|'\
'(?<buy>(køber ind|skal købe ind|handler|skal handle ind))|'\
'(?<neggst>eggser)')"

if [ "$user" ]; then
    if [ $user = jeg ]; then
        user=$EGGS_USER
    fi

    if [ $user = concieggs -o $user = du ]; then
        echo 'Orv ja, det kunne være vildt sjovt hvis jeg skrev "JEG KENDER IKKE CONCIEGGS!"'
        sleep 2
        echo 'LOL!'
        sleep 1
        echo 'ROFL!'
        sleep 2
        echo "LAD OS GRINE AF TROELS' DUMME BOT!  LOLDONGS!"
        annoyedBy "$EGGS_USER" 10 "har stillet et dumsmart spørgsmål"
        exit
    fi

    if cmpNames $user reenberg; then
        echo "$user er nederen."
        exit
    fi

    if [ "$user" = Spartacus -o "$user" = spartacus ]; then
        alias=$(eggstool balances | cut -d' ' -f 2 | randomLine)
    else
        alias=$(randomName "$user")
        auth=$(authedName "$user")
    fi

    if cmpNames $user $EGGS_USER; then
        (echo "Ved du ikke hvem du selv er?"
         echo "ALLE SAMMEN!  $EGGS_USER har glemt hvem _"$EGGS_USER"_ er!"
         echo "Ej, gisp, jeg kan simpelthen ikke forestille mig hvem det kunne være."
         echo "..."
         echo "Tjek dit pas."
         echo "Kig i et spejl."
         echo "Den klammeste eggsling i kassen."
        ) | randomLine
        annoyedBy $EGGS_USER 1 "kender ikke sig selv"
        exit
    fi

    if [ "$swear" ] || [ "$swear2" ]; then
        fucking=" fucking"
    else
        fucking=""
    fi

    if [ ! "$alias" -a ! "$auth" -o "$alias" -a "$auth" ]; then
        conj="og"
    else
        conj="men"
    fi

    conj=$conj$fucking

    if [ "$alias" ]; then
        aliasMsg="$user er$fucking $alias, $conj"
    else
        aliasMsg="Jeg kender ikke$fucking $user, $conj vedkommende er$fucking"
    fi

    if [ "$auth" ]; then
        echo "$aliasMsg autenticeret som $auth ifølge$fucking Nickserv!"
    else
        echo "$aliasMsg ikke autenticeret ifølge$fucking Nickserv!"
    fi
elif [ "$buy" ]; then
    if [ "$buy" = "skal handle ind" ]; then
        echo "Lær dansk, jyde!"
        exit
    fi
    neggst=$(nextEggs | head -n 1)
    if [ "$neggst" ]; then
        echo "Vent venligst medens jeg overvejer dette fundamentale moralske dilemma..."
        listEggsers $neggst | while read -r eggser; do
            echo $(lookupDebt "$eggser") "$eggser"
        done | sort -n -r | cut -d' ' -f2- | head -n 1 | while read -r debtor; do
            echo "$(Du $debtor) bør købe ind!"
            if isKing "$debtor"; then
                if cmpNames "$debtor" "$EGGS_USER"; then
                    debtor="$EGGS_USER"
                fi
                randomLine <<EOF
$debtor: Vi er vel ikke på vej mod et nyt statsbankerot, Deres Majestæt?
Har De overvejet at hæve skatterne, $debtor?
$debtor: Hvad med en krig som distraktion for Deres tomme kiste?
$debtor: Har De overvejet en koloni i den Nye Verden?  Der skulle efter sigende være mange værdier.
$debtor, Deres højtærede Majestæt, pøblen klager over at de ikke har brød.  Måske De bør motivere dem.
EOF
            fi
        done
    else
        echo "Der er ingen tilmeldt Eggs, så jeg går ud fra at ingen køber ind."
    fi
elif [ "$neggst" ]; then
    runcmd neggst
    exit
elif [ "$hveranden" ]; then
    echo "$EGGS_USER: De vil ikke livet!"
else
    echo "Brug: hvem <er (navn|jeg)|skal købe ind|køber ind>"
    exit
fi
