#!/bin/sh
#
# Spørg om essentielle datoer.

eval "$(echo "$@" | parse '(?<birthday>har (?<birthday_kid>[^ ]+) fødselsdag)')"

who=$(randomName $EGGS_USER)
if ! [ "$who" ]; then
    echo "$EGGS_USER: Jeg kender dig slet, slet, slet ikke.  Hvad laver du her?"
    exit
fi

if [ "$birthday" ]; then
    if [ "$birthday_kid" != jeg ]; then
        who=$(randomName "$birthday_kid")
        if ! [ "$who" ]; then
            echo "$EGGS_USER: Hvem i alverden er denne '$birthday_kid'???"
            exit
        fi
        recp="$who"
    else
        recp="Du"
    fi
    date=$(dbUserRead $who birthday)
    if ! [ "$date" ]; then
        echo "$EGGS_USER: $recp har aldrig fødselsdag!"
    elif [ "$date" == $(dateToday | sed 's/^....//') ]; then
        echo "$EGGS_USER: $recp HAR FØDSELSDAG I DAG!  HURRRAAAAA!"
    else
        echo "$EGGS_USER: $recp har fødselsdag d. $date!"
    fi
else
    echo "Brug: hvornår har (jeg|<bruger>) fødselsdag?"
fi
