#!/bin/sh
#
# Indvi en lægmand i frokostens mysterier.


if [ $# -lt 1 ]; then
    echo 'Brug: indvi <person>'
    exit 0
fi

auth="$(isTrusted "$EGGS_USER")"
if ! [ "$auth" ]; then
    echo "$EGGS_USER: Det har $(du $EGGS_USER) på ingen måde bemyndigelse til."
    exit
fi

who=$(randomName $1)

if [ "$who" ]; then
    echo "$EGGS_USER: $1 er allerede en af vore brødre."
    exit
fi

if ! (echo "$1" | egrep '^[^, ]+$' > /dev/null); then
    echo "$EGGS_USER: Føj!  Den slags fæle navne kan vi ikke lide."
    exit
fi

if gitRefresh; then
    cd $EGGS_DIR
    ed slashdotfrokost > /dev/null <<EOF
/::ALIAS::/
/^$/
i
$(echo $1)
.
w
EOF
    if tryGitChange "Indvielse af $1: Godkendt af $auth" slashdotfrokost; then
        echo "$(ack)  $1 tælles nu blandt vore brødre.  Lad indvielsesfrokosten begynde!"
    else
        gitRepair slashdotfrokost
        echo "Katastrofe!  Noget gik galt under opdatering!"
        exit 1
    fi
else
    exit 1
fi
