#!/bin/sh
#
# Nedfæld essentielle personlige fakta og præferencer i logeprotokollen.


eval "$(echo "$@" | parse 'er ((?<beneggter>beneggter)|(?<eggsalteret>eggsalteret))|foretrækker ((?<nothing>intet)|(?<pref>.+))|(?<birthday>har fødselsdag i dag)|er (?<king>konge)|er(?:<also> også)(?:<truegod> den (?: eneste) (sande|rigtige)) (?<god>gud)')"

who=$(randomName $EGGS_USER)
if ! [ "$who" ]; then
    echo "$EGGS_USER: Jeg kender dig slet ikke.  Dine præferencer er uden betydning for denne frokostloge."
    exit
fi

if [ "$beneggter" ]; then
    if [ "$(dbUserGet $who beneggter)" ]; then
        echo "Jeg er allerede bekendt med $(dine $EGGS_USER) afvigelser, $EGGS_USER."
    else
        dbUserWrite $who beneggter < /dev/null
        echo "$(ack)  Meget vel, $EGGS_USER, under antagelse af at logebrødrene gør deres forarbejde, vil der ikke længere tilberedes æg til $(dig $EGGS_USER)."
    fi
elif [ "$eggsalteret" ]; then
    if [ "$(dbUserGet $who beneggter)" ]; then
        echo "$(ack)  Velkommen tilbage i folden, $EGGS_USER!  Under antagelse af at logebrødrene gør deres forarbejde, vil der igen være æg at finde til $(dig $EGGS_USER)."
        dbUserDelete $who beneggter
    else
        echo "Jovist, $EGGS_USER, det ved jeg skam allerede.  Er der et formål med denne udmelding?"
    fi
elif [ "$nothing" ]; then
    if ! [ "$(dbUserGet $who pref)" ]; then
        echo "Jeg er allerede ikke bekendt med nogen særlige præferencer fra $(din $EGGS_USER) side af, broder $EGGS_USER."
    else
        dbUserDelete $who pref
        echo "$(ack)  Der vil ikke for fremtiden ikke tages usædvanlige hensyn til $(dig $EGGS_USER), $EGGS_USER."
    fi
elif [ "$pref" ]; then
    echo "$pref" | dbUserWrite $who pref
    echo "$(ack)  For fremtiden vil jeg minde logebrødrene om, at $(du $who) foretrækker $(preference1 $who)."
elif [ "$birthday" ]; then
    date=$(dateToday | sed 's/^....-//')
    echo $date | dbUserWrite $who birthday
    echo "$(ack)  Nu ved jeg at du har fødselsdag i dag, d. $date."
elif [ "$king" ]; then
    kingname="$(dbRead eggsking)"
    if [ -z "$kingname" ]; then
        echo "OK."
        makeKing "$EGGS_USER"
        echo "Længe leve $(randomKingName $EGGS_USER)!"
    else
        if cmpNames "$kingname" "$EGGS_USER"; then
            echo "Det er korrekt."
        else
            echo "Nej haj!"
        fi
    fi
elif [ "$god" ]; then
    v="$(dbRead eggsgod | wc -l | sed 's/ //g')"
    if isGod "$god"; then
        if [ v = 1 ]; then
            echo "Men De er jo allerede vor Herre!"
        else
            echo "De er jo allerede en af vor guder!"
        fi
    elif isThereAGod; then
        if [ "$also" ]; then
            if [ v = 1 ]; then
                echo "Moderne monotenitiske religioner er forkerte!  Flere guder er vejen!"
            else
                echo "Vores mytologi vokser!  Jo flere guder jo bedre!"
            fi
            makeGod "$EGGS_USER"
        elif [ "$truegod" ]; then
            echo "Ud med de hedenske guder!  Hil vor Herre $EGGS_USER!"
            removePaganGods
            makeGod "$EGGS_USER"
        else
            if [ v = 1 ]; then
                echo "Men der er allerede en gud!"
            else
                echo "Måske du skal spørge de andre guder først?"
            fi
        fi
    else
        echo "Vor Herre $EGGS_USER!  Lad os alle bede."
        makeGod "$EGGS_USER"
    fi
else
    echo "Brug: jeg <er <beneggter|eggsalteret>>|<foretrækker <præference>>|<har fødselsdag i dag>"
fi
