#!/bin/sh
#
# Find ud af hvem der er blevet arresteret.

forbryderiske() {
    randomLine <<EOF
forbryderiske
usle
svinske
samfundsnedbrydende
hårdkogte
bidske
farlige
socialdemokratiske
landsforræderiske
EOF
}

if ! [ "$(dbRead underArrest)" ]; then
    echo "$EGGS_USER: Kachotten er tom!  Styrets modstandere går frit omkring!"
else
    echo -n "$EGGS_USER: Følgende $(forbryderiske) svin er buret inde under slottet: "
    dbRead underArrest | while read user; do
        (echo "den $(forbryderiske) $(randomName "$user")"
         echo "den $(forbryderiske) $(randomName "$user")"
         echo "den $(forbryderiske) $(randomName "$user")"
         echo "den såkaldte \"$(randomName "$user")\" (CPR-navn: $(randomName "$user"))" ) \
            | randomLine
    done | enumerate
fi
