#!/bin/sh
#
# Find ud af hvem der er blevet arresteret.

forbryderiske() {
    randomLine <<EOF
forbryderiske
usle
svinske
samfundsnedbrydende
hårdkogte
bidske
farlige
EOF
}

if ! [ "$(dbRead underArrest)" ]; then
    echo "$EGGS_USER: Kachotten er tom!  Det virker altså urealistisk."
else
    echo -e "$EGGS_USER: Følgende $(forbryderiske) svin er buret inde under slottet:"
    dbRead underArrest | while read user; do
        echo "den $(forbryderiske) $(randomName "$user")"
    done | enumerate
fi
