#!/bin/sh
#
# Knus oprøret!

if [ "$#" = 0 ]; then
    if isKing "$EGGS_USER"; then
        echo "Det er ikke passende, Deres Majestæt."
    else
        echo "Skal du allerede have en krammer?"
    fi
    exit
elif [ "$1" != "oprøret" ]; then
    echo "Jeg har knust $@."
    exit
fi

v="$(dbRead vilvæltekongen | wc -l | sed 's/ //g')"

if [ v = 0 ]; then
    echo "Der er intet oprør."
    exit
fi

vilVaelte() {
    dbRead vilvæltekongen | {
        while read user; do
            if cmpNames $rebel $user; then
                exit 0
            fi
        done
        exit 1
    }
}

knusOproeret() {
    dbRead vilvæltekongen | {
        while read user; do
            if ! isArrested "$user"; then
                arrestUser "$user"
            fi
        done
    }
    dbDelete vilvæltekongen
}

if ! isKing "$EGGS_USER"; then
    kingname="$(dbRead eggsking)"
    if vilVaelte; then
        echo "Man var alligevel ikke helt loyal over for oprøret, hva'?"
        echo "Bare rolig, jeg skal nok gøre det så de andre ikke fatter mistanke."
        sleep 3
    else
        echo "Jeg vil straks fortælle kongen at der er et oprør imod ham!"
    fi
    echo "$(randomKingName $kingname)!  Der er nogle rebeller der prøver at fratage Dem Deres retmæssig magt!"
else
    if ! checkCooldown knusOproeret $((3600 * 2)); then
        echo "Jeg kan ikke knuse oprøret hele tiden, Deres Majestæt!"
        exit
    fi
    echo "Jeg vil gøre mit bedste, Deres Majestæt!"
    if [ $(random 1 4) = 4 ]; then
        echo "De fik mig, Deres Majestæt, oprøret lever videre..."
    else
        knusOproeret
        echo "Oprøret er knust og uromagerne smidt i brummen, Deres Majestæt."
    fi
fi

