#!/bin/sh
#
# Kongen kan vha. kron give sin magt videre til en anden eggser. Også Gud
# Vorherre kan krone en konge. Staver du forkert, kan det dog få voldsomme
# konsekvenser.

if isKing "$EGGS_USER"; then
    echo "$EGGS_USER har valgt at træde i Edward VIII's fodspor ..."
    dbDelete eggsking
    if isTrusted "$1"; then
        makeKing "$1"
        removeFromBadStanding "$1"
        echo "Kongen er abdiceret! Længe leve kongen!"
    echo "Hil Kong $1!"
    else
        echo "Kongen er abdiceret, men magtede ikke at finde en værdig efterfølger. Der blæser en kold vind fra nord. Kun den stærke vil overleve i dette anarki ..."
    fi
else
    echo "$EGGS_USER: Du ikke er konge, men undersåt. Kun kongen kan krone. Tror du det her er anarki!?"
fi
