#!/bin/sh
#
# Levér fantastisk Apina-link med en snedig og ustyrligt komisk
# kommentar!

kommentar=$(cat $CONCIEGGS_DB_DIR/fakta | sed 's/[.:!?].*//' | fgrep -i "$*" | grep -v http | randomElement)

linkid() {
    if [ $1 -ne 0 ]; then
        link="http://apina.biz/"$(random 10000 80000)
        if wget --load-cookies $CONCIEGGS_DB_DIR/concieggs_cookies.txt -O /dev/stdout --quiet $link | grep 'Entry not found' > /dev/null; then
            linkid $(($1-1))
        else
            echo $link
        fi
    fi
}

# id=$(linkid 10)
link=$(cat $CONCIEGGS_DB_DIR/fakta | egrep -o 'http://apina\.biz/[0-9]+' | randomElement)

if ! [ "$kommentar" ]; then
    echo "Næh, det ved jeg ikke noget om."
    exit 0
fi

if ! [ "$link" ]; then
    echo "Næh, ingen Apina til dig."
    exit 0
fi

echo $kommentar: $link


