#!/bin/sh
#
# Foretag en monetær transaktion til en anden logebroder gennem EggsML
# bankcentralen.  Denne facilitet er dog kun for logemestre.

eval "$(echo "$@"| parse '(?<amount>-?[0-9]+(\.[0-9][0-9]?)?) ?(?<currency>[^ ]+) til (?<maybeto>[^ ]+)')"

if ! [ "$amount" ]; then
    echo 'Brug: overfør <beløb> <valuta> til <modtager>'
    exit
fi

currency=${currency-DKK}

from=$(randomName $EGGS_USER)
if ! [ "$from" ]; then
    echo "Dig kender jeg ikke.  Hvem skulle du forestille at være?"
    exit
fi

auth="$(isTrusted "$EGGS_USER")"
if ! [ "$auth" ]; then
    echo "Jeg stoler ikke på folk som $(dig $EGGS_USER), $EGGS_USER."
    exit
fi

if [ "$maybeto" = concieggs ]; then
    echo "Tak, men jeg er hævet over behovet for ussel mammon."
    exit
fi

to=$(randomName "$maybeto")
if ! [ "$to" ]; then
    echo "Jeg kender ikke $maybeto!  Prøv med 'Athas' i stedet for."
    exit
fi

if [ $(echo "$amount == 0" | bc) = 1 ]; then
    echo "Undlad venligst at spilde bankvæsenets tid på pjat."
    exit 0
elif [ $(echo "$amount < 0" | bc) = 1 ]; then
    amount="$(echo $amount '*' -1|bc)"
    tmp=$from
    from=$to
    to=$tmp
fi

if cmpNames $from $to; then
    echo "Hold venligst den slags onanistiske gris ude af logen."
    exit
fi

when=$(date '+%Y-%m-%d')
finalamount=$(convertCurrency "$amount" "$currency" "DKK")

if ! [ "$finalamount" ]; then
    echo "$EGGS_USER: Jeg er ikke bekendt med valutaen '${currency-DKK}'."
    exit
fi

if gitRefresh; then
    transfer "$when" "$finalamount" "$from" "$to"
    if tryGitChange "Overførsel fra $from til $to, godkendt af $auth" slashdotfrokost; then
        echo "Lad det runge og gjalde i DIKUs sale at $from har overført ${amount}${currency} til $to, som betaling for indtil videre ukendte ydelser!"
    else
        gitRepair slashdotfrokost
        echo "Katastrofe!  Noget gik galt under opdatering!"
        exit 1
    fi
else
    exit 1
fi
