#!/bin/sh

eval "$(echo "$@" | parse '^ *(?<budskab>(nu |dog |roligt |bare )*(budskabet|det (gode|glade) (budskab|nyt)|rygtet)) *$')"

if [ "$budskab" ]; then
    eggses=$(prevEggs; nextEggs)

    if ! [ "$eggses" ]; then
        echo "$EGGS_USER: Men der er jo ingen frokost at sprede noget budskab om!"
        exit
    fi

    eggs="$(echo "$eggses" | randomLine)"

    if [ $(random 1 3) = 1 ]; then
        echo "Internetbruger: Kan du lokkes med til $(titleEggs "$eggs")?" | kvidr
    else
        recentlyActive | head -n 2 | while read user; do
            echo "$user: Kan du lokkes med til $(titleEggs "$eggs")?"
        done
    fi
else
    echo "$EGGS_USER: Spred hvad?  Jeg kan sprede det gode budskab."
fi
