#!/bin/sh
#
# Tilføj til listen over indkøbsønsker.


if [ $# -lt 1 ]; then
    echo "Brug: unsafePerformRåønsk [antal] ønske..."
else
    eval "$(echo "$@" | parse '(?<count>[0-9]+) (?<what>.*)|(?<what>.*)')"
    if ! [ "$count" ]; then
        count=1
    fi
    rawWish "$count" "$what"
fi
