#!/bin/sh
#
# Vær mere kongelig end 'jeg'.

if isKing $EGGS_USER; then
    if [ "$1" = "ses" ]; then
        randomElement <<EOF
Hav det godt, Deres Majestæt!
Jeg ønsker Dem al lykke i verden!
Deres tilstedeværelse har været en ære!
Lad solen skinne på din skygge, herre.
EOF
    else
        eval "$(echo "$@" | parse 'spiser med (kl.|klokken) (?<tid>[0-9][0-9]?(:[0-9][0-9]?)?)')"
        if [ "$tid" ]; then
            runcmd eggsml "$tid"
        else
            runcmd jeg $@
        fi
    fi
else
    echo -n "$EGGS_USER: "
    randomElement <<EOF
DU ER SGU DA IKKE EN TAND ROYAL!
Hvad har du gang i, din UNDERSÅT!
Kig dig bag skulderen.  Ja, det er mine politibetjente der fjerner dig!
Du er ikke altså ikke kongen!
EOF
    putInBadStanding $EGGS_USER
fi
