#!/bin/sh
#
# Vær mere kongelig end 'jeg'.

do_as_king_says() {
    eval "$(echo "$@" | parse 'spiser med (kl.|klokken) (?<tid>[0-9][0-9]?(:[0-9][0-9]?)?)')"
    if [ "$tid" ]; then
        runcmd eggsml "$tid"
    else
        runcmd jeg $@
    fi
}

if isKing $EGGS_USER; then
    do_as_king_says
else
    echo -n "$EGGS_USER: "
    randomElement <<EOF
DU ER SGU DA IKKE EN TAND ROYAL!
Hvad har du gang i, din UNDERSÅT!
Kig dig bag skulderen.  Ja, det er mine politibetjente der fjerner dig!
Du er ikke altså ikke kongen!
EOF
    putInBadStanding $EGGS_USER
fi
