#!/bin/sh
#
# Vælt kongen hvis I er nok!

if [ "$#" = 0 ]; then
    echo "$EGGS_USER: Vælt hvad?  Et glas vand?  Læsset?  På dansegulvet?  Richard Stallman?  ...Kongen?"
    exit
elif [ "$1" != "kongen" ]; then
    echo "$EGGS_USER: $(ack)  Vi siger bare at $@ er væltet."
    exit
fi

kingname="$(dbRead eggsking)"
if [ -z "$kingname" ]; then
    echo "$EGGS_USER: Uagtet dit ønske om at gøre oprør mod 'manden', så er tronen allerede ganske tom."
    exit
fi

rebel="$(randomName "$EGGS_USER")"

if ! [ "$rebel" ]; then
    echo "$EGGS_USER: Ingen udefrakommende indblanding i intern logepolitik, tak."
    exit
fi

if isKing "$rebel"; then
    echo "Ærede majestæt, det ville være upassende hvis De skulle begå attentat mod eget embede.  Hvad vil folket ikke tænke?"
    exit
fi

harVaeltet() {
    dbRead vilvæltekongen | {
        while read user; do
            if cmpNames $rebel $user; then
                exit 0
            fi
        done
        exit 1
    }
}

if harVaeltet; then
    echo "$EGGS_USER: Du har allerede meldt dig under tricoloren.  Det kan anbefales at dirigere al denne energi mod at hverve medsammensvorne."
    exit
fi
echo "$rebel" | dbWriteAppend vilvæltekongen

v="$(dbRead vilvæltekongen | wc -l | sed 's/ //g')"

if [ "$v" -gt $(random 3 5) ]; then

    newKing=$(dbRead vilvæltekongen | randomLine)

    dbDelete eggsking
    dbDelete vilvæltekongen

    randomLine <<EOF
KONGEN ER VÆLTET!
Kongen er død!  Længe leve anarkiet!
Kongen er smidt på porten!  Knap en bajer op!  Knap to bajere op!
¡Viva la revolución!
"Manden" er nu på SPANDEN!  Byd anarkiet velkomment!
EOF

    if [ "$newking" -a $(random 1 4) = 4 -a "$(isTrusted $newking)" ]; then
        sleep 2
        echo "Men hvad er nu dette?  $newking griber magten!  Længe leve den nye konge!"
        makeKing "$newking"
    fi
else
    navn="$(randomLine <<EOF
Frederik
Knud
Niels
EOF
)"

    attribut_god="$(randomLine <<EOF
Gode
Barmhjertige
Glædelige
EOF
)"

    randomLine <<EOF
Du ser en gammel film.
Du bagtaler Kongen på en bar.
Du planlægger en retningsbestemt slotseksplosion.
Du lægger dit hovede i blød.
Du drømmer dig langt væk.
Du tager dit sværd ud af kisten.
Du læser en bog skrevet af en gut i fængsel.
Du skriver et langt digt.
Du går rundt og råber bandeord i en hel time.
Du putter rottegift i slotsvinen.
Du sender et brev om hjælp til en nærliggende republiks præsident.
Du øver dig i at ride på hest.
Du bestiller en guillotine fra et postordrekatalog.
Du tænker søde tanker om din familie i den frie naborepublik.
Du griner ad regentens nytårstale.
Du lytter til kontra-revolutionær musik på den lokale smugkro.
Du lyver i din selvangivelse.
Du tegner overskæg på et portræt af kongen.
Du hvisker »det svin« om Kongen til dig selv, mens Hans parade går forbi.
Du dukker ikke op til Kongens fødselsdagsparade.
Du tisser op ad slotsmuren.
Du polerer dine støvler.
Du prutter i retning ad slotsbygningen.
Du hænger et billede op af Kongen på dit toilet.
Du vender hjem fra et studieophold i en fjern republik.
Du spytter dristigt på skiltet af en hofleverandør af hvidtøl.
Ved Hendes Majestæts dronningens officielle helligdag prutter du højlydt på et offentligt toilet.
Du spiser en af prinsessens kælekaniner til aftensmad.
På dit arbejde hos den lokale smed imprægnerer du en tissemand på prinsens nye sværd.
Ved pudsning af en royals lædersko smører du med friskt snot i stedet for skosværte.
Du lytter til din farfars gamle historier om kong ${navn} den ${god_attribut}.
EOF
    echo "Kun $v har meldt sig under den revolutionære fane!  I skal være flere!"
fi
