#!/bin/sh
#
# Vælt kongen hvis I er nok!

kingname="$(dbRead eggsking)"
if [ -z "$kingname" ]; then
    echo "$EGGS_USER: Uagtet dit ønske om at gøre oprør mod 'manden', så er tronen allerede ganske tom."
    exit
fi

rebel="$(randomName "$EGGS_USER")"

if ! [ "$rebel" ]; then
    echo "$EGGS_USER: Ingen udefrakommende indblanding i intern logepolitik, tak."
    exit
fi

harVaeltet() {
    dbRead vilvæltekongen | {
        while read user; do
            if cmpNames $rebel $user; then
                exit 0
            fi
        done
        exit 1
    }
}

if harVaeltet; then
    echo "$EGGS_USER: Du har allerede meldt dig under tricoloren.  Det kan anbefales at dirigere al denne energi mod at hverve medsammensvorne."
    exit
fi
echo "$rebel" | dbWriteAppend vilvæltekongen

v="$(dbRead vilvæltekongen | wc -l | sed 's/ //g')"

if [ "$v" -gt 4 ]; then
    dbDelete eggsking
    dbDelete vilvæltekongen
    randomElement <<EOF
KONGEN ER VÆLTET!
Kongen er død!  Længe leve anarkiet!
EOF
else
    randomElement <<EOF
Du forsøger dristigt at hugge hovedet af majestæten.
Du bagtaler kongen på en bar.
Du planlægger en retningsbestemt slotseksplosion.
Du lægger dit hovede i blød.
Du tager dit sværd ud af kisten.
EOF
    echo "Kun $v har meldt sig under den revolutionære fane!  I skal være flere!"
fi
