#!/bin/sh
#
# Vælt kongen hvis I er nok!

if [ "$#" = 0 ]; then
    echo "$EGGS_USER: Vælt hvad?  Et glas vand?  Læsset?  På dansegulvet?  ...Kongen?"
    exit
elif [ "$1" != "kongen" ]; then
    echo "$EGGS_USER: $(ack)  Vi siger bare at $@ er væltet."
    exit
fi

kingname="$(dbRead eggsking)"
if [ -z "$kingname" ]; then
    echo "$EGGS_USER: Uagtet dit ønske om at gøre oprør mod 'manden', så er tronen allerede ganske tom."
    exit
fi

rebel="$(randomName "$EGGS_USER")"

if ! [ "$rebel" ]; then
    echo "$EGGS_USER: Ingen udefrakommende indblanding i intern logepolitik, tak."
    exit
fi

harVaeltet() {
    dbRead vilvæltekongen | {
        while read user; do
            if cmpNames $rebel $user; then
                exit 0
            fi
        done
        exit 1
    }
}

if harVaeltet; then
    echo "$EGGS_USER: Du har allerede meldt dig under tricoloren.  Det kan anbefales at dirigere al denne energi mod at hverve medsammensvorne."
    exit
fi
echo "$rebel" | dbWriteAppend vilvæltekongen

v="$(dbRead vilvæltekongen | wc -l | sed 's/ //g')"

if [ "$v" -gt 4 ]; then

    newKing=$(dbRead vilvæltekongen | randomElement)

    dbDelete eggsking
    dbDelete vilvæltekongen

    randomElement <<EOF
KONGEN ER VÆLTET!
Kongen er død!  Længe leve anarkiet!
EOF

    if [ "$newking" -a $(random 4) = 4 -a "$(isTrusted $newking)" ]; then
        sleep 2
        echo "Men hvad er nu dette?  $newking griber magten!  Længe leve den nye konge!"
        makeKing "$newking"
    fi
else
    randomElement <<EOF
Du forsøger dristigt at hugge hovedet af majestæten.
Du bagtaler kongen på en bar.
Du planlægger en retningsbestemt slotseksplosion.
Du lægger dit hovede i blød.
Du tager dit sværd ud af kisten.
EOF
    echo "Kun $v har meldt sig under den revolutionære fane!  I skal være flere!"
fi
