#!/bin/sh
#
# Udskriv en liste over de nuværende indkøbsønsker.

dugodeste=$(randomElement <<EOF
Du godeste!
Mein Gott!
Bred ymer!
Sacre bleu !
Mon Dieu !
Dios mio!
Ach du lieber!
Sikke noget!
Hillemænd!
Ryd forsiden!
EOF
)

wishes=$(eggstool wishes \
    | sort \
    | uniq -c \
    | sed -e 's/ *1 //' -e 's/ *//' \
    | enumerate)

if [ "$wishes" ]; then
    echo "Indkøbsønsker: $wishes."
else
    echo "$dugodeste  Der er ingen indkøbsønsker!"
fi
