#!/usr/bin/env bash
#
# Spørg den netværkskyndige, concieggs, om et domænenavn er ledig.

if [ "$1" = det -a "$2" = "jul" ]; then
    isChristmas && echo "Ja!!!" || echo "Nej!!!"
    exit
fi

eval "$(echo "$@" | parse 'sol(en)? (?<sol>stået op|oppe)')"

if [ "$sol" ]; then
    default_location="København"
    if [ "$EGGS_USER" == "sword_smith" ] || [ "$EGGS_USER" == "trobjo" ]; then
        default_location="Zug,CH"
    fi
    location="$default_location"
    if isSunUp "$location"; then
        echo "Solen er oppe i $location!"
    else
        echo "Solen er ikke oppe i $location :((("
    fi
    exit 0
fi

if [[ ( "$2" == "ledig" ) || ( "$2" == "ledig?" ) ]]; then
    runcmd whois "$1" "ledighed"
elif [ $# -gt 1 ]; then
    runcmd 8ball "$@"
else
    echo "Brug: er <domænenavn> ledig?"
fi
