#!/usr/bin/env bash
#
# Spørg den netværkskyndige, concieggs, om et domænenavn er ledigt, om det er
# jul, eller om solen er oppe.

if [ "$1" = det -a "$2" = "jul" ]; then
    if isChristmas; then
        if ! checkCooldown "julenysgerrig$EGGS_USER" 24; then
            echo "$EGGS_USER: Hohoho, du har seriøst lige spurgt."
        else
            echo "$EGGS_USER: Ja!!!"
        fi
    else
        echo "$EGGS_USER: Nej!!!"
    fi
    exit
fi

eval "$(echo "$@" | parse 'sol(en)? (?<sol>stået op|oppe)( (i|på) (?<place>[^\?]+))?')"

if [ "$sol" ]; then
    default_location="København"
    if [ "$EGGS_USER" == "sword_smith" ]; then
        default_location="Zug"
    fi
    location="$default_location"
    if [ "$place" ]; then
        location="$place"
    fi

    if isSunUp "$location"; then
        echo "Solen er oppe i $location!"
    else
        echo "Solen er ikke oppe i $location :((("
    fi
    exit 0
fi

if [[ ( "$2" == "ledig" ) || ( "$2" == "ledig?" ) ]]; then
    runcmd whois "$1" "ledighed"
elif [ $# -gt 1 ]; then
    runcmd 8ball "$@"
else
    echo "Brug: er <domænenavn> ledig?"
fi
