#!/usr/bin/env perl
use 5.012;
use warnings;
use utf8::all;

while (my $text = <>) {
    $text =~ s/hans/hendes/ig;
    $text =~ s/han/hun/ig;
    $text =~ s/ham/hende/ig;
    $text =~ s/mand/kvinde/ig;
    $text =~ s/far/mor/ig;
    $text =~ s/fader/moder/ig;
    $text =~ s/penis/vagina/ig;
    $text =~ s/pik/kusse/ig;
    $text =~ s/diller/fjams/ig;
    $text =~ s/skæg\b/bryst/ig;
    $text =~ s/den[ts]\b/hendes/ig;
    $text =~ s/den\b/hun/ig;

    print $text;
}
