#!/bin/sh
#
# Hotfix imod at concieggs er for høflig.


besked="$(cat)"

fra_haven() {
    randomElement <<EOF
gulerod
rødbede
kartoffel
kål
jordskok
jordbær
stikkelsbær
vintegækker
hyacinth
EOF
}

fjern_gen() {
    echo -n 'sed'
    while read bandeord; do
        echo -n ' -e' "'s/ $bandeord / $(fra_haven) /g'"
    done
    # AT GØRE: Det er ikke case insensitive, for det er besværligt på OpenBSD.
}

fjern() {
    eval "echo $besked | $(fjern_gen)"
}

fjern <<EOF
dovenlars
fuck
lort
tis
pis
satan
Gud
Scheiße
slacker
idiot
EOF
