#!/usr/bin/env perl
use 5.012;
use warnings;
use utf8::all;

while (<>) {
    s/(?<=\w)er\b/0r/;
    s/cks?/x/;
    s/eggs?/x/;
    s/ow/pw/;
    s/[æÆ]/ae/;
    s/[øØ]/oe/;
    s/[åÅ]/aa/;
    tr/aAeEiIoOsS/44331100$$/;
    print
}
