#!/usr/bin/env perl
use 5.012;
use warnings;
use utf8::all;

while (<>) {
    s/(?<=\w)er\b/0r/g;
    s/cks?/x/g;
    s/eggs?/x/g;
    s/ow/pw/g;
    s/[æÆ]/ae/g;
    s/[øØ]/oe/g;
    s/[åÅ]/aa/g;
    tr/aAeEiIoOsS/44331100$$/;
    print
}
