#!/usr/bin/env perl
use 5.012;
use warnings;
use utf8::all;

my @smilies = qw/ :i <3 /; 

while (<>) {
    s/^(.*)$/\L$1/;
    s/ det / d /g;
    s/t\b/th/g;
    s/e\b/øh/g;
    s/sgu /sq /g;
    s/g/q/g;
    s/ikke/ik/g;
    s/en hamster/et hamster/g;
    s/q(?:nne|')//g;
    s/iq/iiq/g;
    s/u\b/uuh/g;
    s/(?<=q)u(?!u)//g;
    s/\?/???/g;
    s/!/ !/g;
    s/(\W*)\s*$/ lizzom$1/;
    s/\bh(?=v)//g;
    s/\.(?= |$)/" " . $smilies[rand @smilies] x (int(rand(2)) + 1)/ge;
    print
}

