#!/usr/bin/env perl
use 5.012;
use warnings;
use utf8::all;

while (<>) {
    lc;
    tr/skg/zq/;
    s/q(?:nne|')//g;
    s/iq/iiq/g;
    s/(?<=q)u//g;
    s/\?/???/g;
    s/(\W*)\S$/ lizzom\1/;
    s/\bh//g;
    print
}

