#!/usr/bin/env perl
use 5.012;
use warnings;
use utf8::all;
use Env qw/CONCIEGGS_LIB_DIR/;

my %aliases = map { (lc($_) => 1) } split("\n", `allAliases`);

sub preben {
    my $name = shift;

    return $name unless $aliases{lc($name)};

    return navn();
}

while (my $line = <>) {
    $line =~ s/\b(\S*)\b/preben($1)/ge;

    print $line;
}

sub navn {
    @array   = ("Preben", "Snefred", "Sigurd", "Musse");
    $index   = rand @array;
    $element = $array[$index];
    return $element
    }
