#!/usr/bin/env perl
use 5.012;
use warnings;
use utf8::all;
use POSIX;
use List::MoreUtils qw/zip/;

my @rainbow = map { "\cC$_\cB\cB" } qw(04 07 08 09 11 06 13);

while (my $line = <>) {
    chomp $line;
    my $n = ceil(length($line) / @rainbow);
    my @msg = unpack("(a$n)*", $line);

    print join("", zip(@rainbow, @msg)) . "\cO";
}


