#!/usr/bin/env python3

import random, sys, subprocess


def run_main(args):
    result = []
    for words in args.split():
        if (random.randint(0,3) == 0):
            word = subprocess.check_output(("oversæt " + word + " fra dansk til engelsk").split(), shell=False).decode()
        result.append(word)
    print(result.join(" "))


if __name__ == "__main__":
    run_main(sys.argv)





















