#!/usr/bin/env python3

import random, sys, subprocess


def run_main(args):
    result = []
    for word in args:
        if (random.randint(0,3) == 0):
            word = subprocess.check_output(("runcmd oversæt " + word + " fra dansk til engelsk").split(), shell=True).decode()
        result.append(word)
    print(" ".join(result))


if __name__ == "__main__":
    run_main(sys.argv)





















