#!/usr/bin/env perl
use 5.012;
use warnings;
use utf8::all;

# baseret på http://www.classy.dk/download/styrelizer.asp

while (my $text = <>) {
    $text =~ s/ kræver / vil have /g;
    $text =~ s/ jeg / mig /g;
    $text =~ s/ De / du /g;
    $text =~ s/ deres / dem sine /g;
    $text =~ s/ skærm / computer /g;
    $text =~ s/ datamat / kasse /g;
    $text =~ s/ datamaten / kassen /g;
    $text =~ s/ datamater / kasser /g;
    $text =~ s/ datamaterne / kasserne /g;
    $text =~ s/, /, og så  /g;
    $text =~ s/\. /, ikke også? /g;
    $text =~ s/siger /siger /g;
    $text =~ s/sagde /sigede /g;
    $text =~ s/ stor / mere /g;
    $text =~ s/ lille / mindre /g;
    $text =~ s/ mindre / meget mindre /g;
    $text =~ s/ godt / god /g;
    $text =~ s/tilfredse /glad med /g;
    $text =~ s/tilfreds /glad med /g;
    $text =~ s/ tøj/ flyverdragt/g;
    $text =~ s/kommunes/område/g;
    $text =~ s/Kommune/område/g;
    $text =~ s/kommune/område/g;
    $text =~ s/kommuners/områder/g;
    $text =~ s/Flygtninges /folk som flygter /g;
    $text =~ s/Flygtningenes /de folk som flygter ses's/g;
    $text =~ s/flygtninge /folk som stikker af fra noget /g;
    $text =~ s/flygtning /en som er flygtet fra noget /g;
    $text =~ s/ god / dejlig /g;
    $text =~ s/ større / mere stor/g;
    $text =~ s/regeringen /kongen /g;
    $text =~ s/Regeringen /Kongen /g;
    $text =~ s/ statsministeren / Kongen /g;
    $text =~ s/ livstid / for evig og altid /g;
    $text =~ s/statsminister / Konge /g;
    $text =~ s/ dreng / drengebarn /g;
    $text =~ s/ pige / pigebarn /g;
    $text =~ s/statsminister / konge /g;
    $text =~ s/ er godt / gør mig glad /g;
    $text =~ s/ cigaret / lille cigar /g;
    $text =~ s/ dropper / aflyser /g;
    $text =~ s/minister/medister/g;
    $text =~ s/debat /diskussion /g;
    $text =~ s/ tilskud/ gave/g;
    $text =~ s/debatten /diskussionen /g;
    $text =~ s/ Danmark/ Danmark :-) /g;
    $text =~ s/ uheld / svipser /g;
    $text =~ s/ulykke/avs'er/g;
    $text =~ s/ børn/ småfolk/g;
    $text =~ s/ at miste / at ikke længere have /g;
    $text =~ s/ mister / at tabe /g;
    $text =~ s/ bedre / mere god end før/g;
    $text =~ s/ dræbt / forsvundet /g;
    $text =~ s/ dræbte / forsvandt /g;
    $text =~ s/ computerspil/ bip-bip-spil/g;
    $text =~ s/ blev / blivede /g;
    $text =~ s/ hej / god dag /g;
    $text =~ s/Hej /Halløjsa /g;
    $text =~ s/ flyttende / bevægende /g;
    $text =~ s/ flyttede / bevægede /g;
    $text =~ s/ flytte / bevæge /g;
    $text =~ s/ flyt / rumstér /g;
    $text =~ s/ irriterende/ drilsk/g;
    $text =~ s/ irriterer/ driller/g;
    $text =~ s/ irriteret/ drillet/g;
    $text =~ s/ irriter/ dril/g;
    $text =~ s/ foreslår/ synes at/g;
    $text =~ s/kritik /mobning /g;
    $text =~ s/ kritiserer / mobber /g;
    $text =~ s/kritikken /mobningen /g;
    $text =~ s/ kritikken/ mobningen/g;
    $text =~ s/ de / dem /g;
    $text =~ s/ ligner / ser ud ligesom /g;
    $text =~ s/ påvirke / gøre noget ved /g;
    $text =~ s/ cd / Compact Disc /g;
    $text =~ s/ nummer / sang /g;
    $text =~ s/ personer/ folk/g;
    $text =~ s/ regulært / almindeligt /g;
    $text =~ s/ samfund/ land/g;
    $text =~ s/ million / hel million /g;
    $text =~ s/ hurtig / travl /g;
    $text =~ s/ hurtigt / travlt /g;
    $text =~ s/ formentlig / nok /g;
    $text =~ s/ konsekvenser / ballade /g;
    $text =~ s/ kriminelle / slyngler /g;
    $text =~ s/ byrådsmedlem / borgmester(?) /g;
    $text =~ s/ musik / disko-dasko-musik /g;
    $text =~ s/ det / den /g;
    $text =~ s/ indtægt / løn /g;
    $text =~ s/Foto:/Billedet er taget af:/g;
    $text =~ s/Arkivfoto:/Avisbilled:/g;
    $text =~ s/ forældre/ forellerne :-p/g;
    $text =~ s/ orienteret / fået fortalt /g;
    $text =~ s/beslutning/valg/g;
    $text =~ s/ forlader / går /g;
    $text =~ s/ forlade / gå /g;
    $text =~ s/ forlad / gå fra /g;
    $text =~ s/ forlod / gik fra /g;
    $text =~ s/ om / om det med /g;
    $text =~ s/direktør/mester/g;
    $text =~ s/støtte/hjælpe/g;
    $text =~ s/udpege /vælge /g;
    $text =~ s/ underholdende / sjovt /g;
    $text =~ s/stoffer/narko/g;
    $text =~ s/stoffet/narkoet/g;
    $text =~ s/stof/narko/g;
    $text =~ s/Det /Den dersens /g;
    $text =~ s/ den / den dersens /g;
    $text =~ s/Den /Den dersens /g;
    $text =~ s/Heste-Nettet/Krikke-Nettet/g;
    $text =~ s/ hest / krikke /g;
    $text =~ s/ heste-/ krikke-/g;
    $text =~ s/ heste / krikker /g;
    $text =~ s/hesten/krikken/g;
    $text =~ s/ tager / snupper /g;
    $text =~ s/ tage / snuppe /g;
    $text =~ s/ fordi / fordi at /g;

    $text =~ s/Arla /Mælkemonopolet Arla /g;

    $text =~ s/Arla, /Mælkemonopolet Arla, /g;
    $text =~ s/Arlas, /Mælkemonopolet Arlas, /g;
    $text =~ s/Arlas /Mælkemonopolet Arlas /g;

    $text =~ s/ bøde / straf /g;
    $text =~ s/ kroner/ penge/g;
    $text =~ s/fjernsyn/fjerner/g;
    $text =~ s/ TV / colortossen /g;

    # ede til et
    $text =~ s/ede /et /g;

    # nutids-r
    $text =~ s/rer /\@e\@ /g;
    $text =~ s/re /rer /g;
    $text =~ s/\@e\@ /re /g;
    $text =~ s/rer\./\@e\@\./g;
    $text =~ s/re\./rer\./g;
    $text =~ s/\@e\@\./re\./g;
    $text =~ s/rer,/\@e\@,/g;
    $text =~ s/re,/rer,/g;
    $text =~ s/\@e\@,/re,/g;

    print $text;
}


