#!/usr/bin/env perl
use 5.012;
use warnings;
use utf8::all;
use Env qw/CONCIEGGS_LIB_DIR/;

sub nuserfy {
    my $name = shift;

    my $rn = `randomName "$name"`;
    return $name unless $rn;

    my @options = (
        map { "$name$_" } qw(
            -musen
            -snut
            kins
            pus
        ),
        qw(
            pullernuller
            nullergøj
            skattebasse
        ),
    );

    return $options[rand @options];
}

while (my $line = <>) {
    $line =~ s/\b(\S*)\b/nuserfy($1)/ge;

    print $line;
}

