#!/usr/bin/env python3

import sys

def run_main(args):
    output = "<root><status>Success</status><response>"
    output += args.strip()
    output += "</response></root>"
    print(output)


if __name__ == "__main__":
    run_main(sys.stdin.readline())
