#!/usr/bin/env python3

import sys
from string import punctuation

def run_main(args):
    output = "<?xml version="1.0"?><root><status>Success</status><response><sentence>"
    for word in args:
        word = word.strip()
        if word[0] in punctuation:
            output += "<punctuation>" + word[0] + "</punctuation>"
            word = word[1:]
        if word[-1] in punctuation:
            output += "<word>" + word[:-1] + "</word>"
            output += "<punctuation>" + word[-1] + "</punctuation>"
        else:
            output += "<word>" + word + "</word>"
    output += "</sentence></response></root>"
    print(output)


if __name__ == "__main__":
    run_main(sys.stdin.readline().split())
