#!/usr/bin/env python3

import sys, cgi

def run_main(args):
    output = "<root><status>Success</status><response><sentence>"
    for word in args:
        output += "<word>" + cgi.escape(word) + "</word>"
    output += "</sentence></response></root>"
    print(output)


if __name__ == "__main__":
    run_main(sys.stdin.readline().split())
